domains = [{'description': '(opt18) Nurikabe:\n\nThis is a version of the Floortile domain where a robot must paint a certain pattern in a\ngrid and cannot move into locations that have already been painted. The pattern is not\ndecided in advance, but instead it must fulfill the constraints of a simplified Nurikabe\npuzzle. The grid has some positions marked with a number. When the robot is on top of a\ncell with a number N on it, it can start the paint action so that the next N cells\n(including the current position) will be painted. There is an additional constraint that\ntwo adjacent cells cannot belong to cells of different groups.',
 'ipc': '2018',
 'name': 'nurikabe',
 'problems': [('nurikabe-opt18/domain.pddl', 'nurikabe-opt18/p11.pddl'),
              ('nurikabe-opt18/domain.pddl', 'nurikabe-opt18/p07.pddl'),
              ('nurikabe-opt18/domain.pddl', 'nurikabe-opt18/p06.pddl'),
              ('nurikabe-opt18/domain.pddl', 'nurikabe-opt18/p10.pddl'),
              ('nurikabe-opt18/domain.pddl', 'nurikabe-opt18/p17.pddl'),
              ('nurikabe-opt18/domain.pddl', 'nurikabe-opt18/p01.pddl'),
              ('nurikabe-opt18/domain.pddl', 'nurikabe-opt18/p16.pddl'),
              ('nurikabe-opt18/domain.pddl', 'nurikabe-opt18/p20.pddl'),
              ('nurikabe-opt18/domain.pddl', 'nurikabe-opt18/p19.pddl'),
              ('nurikabe-opt18/domain.pddl', 'nurikabe-opt18/p03.pddl'),
              ('nurikabe-opt18/domain.pddl', 'nurikabe-opt18/p15.pddl'),
              ('nurikabe-opt18/domain.pddl', 'nurikabe-opt18/p14.pddl'),
              ('nurikabe-opt18/domain.pddl', 'nurikabe-opt18/p02.pddl'),
              ('nurikabe-opt18/domain.pddl', 'nurikabe-opt18/p18.pddl'),
              ('nurikabe-opt18/domain.pddl', 'nurikabe-opt18/p05.pddl'),
              ('nurikabe-opt18/domain.pddl', 'nurikabe-opt18/p13.pddl'),
              ('nurikabe-opt18/domain.pddl', 'nurikabe-opt18/p09.pddl'),
              ('nurikabe-opt18/domain.pddl', 'nurikabe-opt18/p08.pddl'),
              ('nurikabe-opt18/domain.pddl', 'nurikabe-opt18/p12.pddl'),
              ('nurikabe-opt18/domain.pddl', 'nurikabe-opt18/p04.pddl')]}]
