domains = [
{'description': '',
 'ipc': '2014',
 'name': 'cavediving',
 'problems': [('cavediving/domain.pddl', 'cavediving/testing01.pddl'),
              ('cavediving/domain.pddl', 'cavediving/testing01_easy.pddl'),
              ('cavediving/domain.pddl', 'cavediving/testing02_easy.pddl'),
              ('cavediving/domain.pddl', 'cavediving/testing03_easy.pddl'),
              ('cavediving/domain.pddl', 'cavediving/testing04_easy.pddl'),
              ('cavediving/domain.pddl', 'cavediving/testing05A_easy.pddl'),
              ('cavediving/domain.pddl', 'cavediving/testing06A_easy.pddl'),
              ('cavediving/domain.pddl', 'cavediving/testing07_easy.pddl'),
              ('cavediving/domain.pddl', 'cavediving/testing08_easy.pddl'),
              ('cavediving/domain.pddl', 'cavediving/testing09_easy.pddl'),
              ('cavediving/domain.pddl', 'cavediving/testing10_easy.pddl'),
              ('cavediving/domain.pddl', 'cavediving/testing11_easy.pddl'),
              ('cavediving/domain.pddl', 'cavediving/testing12_easy.pddl'),
              ('cavediving/domain.pddl', 'cavediving/testing13_easy.pddl'),
              ('cavediving/domain.pddl', 'cavediving/testing14_easy.pddl'),
              ('cavediving/domain.pddl', 'cavediving/testing15_easy.pddl'),
              ('cavediving/domain.pddl', 'cavediving/testing16_easy.pddl'),
              ('cavediving/domain.pddl', 'cavediving/testing18A_easy.pddl'),
              ('cavediving/domain.pddl', 'cavediving/testing18_easy.pddl'),
              ('cavediving/domain.pddl', 'cavediving/testing20A_easy.pddl')]}
]