domains = [
{'description': '',
 'ipc': '2014',
 'name': 'tetris',
 'problems': [('tetris-sat14-strips/domain.pddl',
               'tetris-sat14-strips/p020.pddl'),
              ('tetris-sat14-strips/domain.pddl',
               'tetris-sat14-strips/p021.pddl'),
              ('tetris-sat14-strips/domain.pddl',
               'tetris-sat14-strips/p022.pddl'),
              ('tetris-sat14-strips/domain.pddl',
               'tetris-sat14-strips/p023.pddl'),
              ('tetris-sat14-strips/domain.pddl',
               'tetris-sat14-strips/p024.pddl'),
              ('tetris-sat14-strips/domain.pddl',
               'tetris-sat14-strips/p025.pddl'),
              ('tetris-sat14-strips/domain.pddl',
               'tetris-sat14-strips/p026.pddl'),
              ('tetris-sat14-strips/domain.pddl',
               'tetris-sat14-strips/p027.pddl'),
              ('tetris-sat14-strips/domain.pddl',
               'tetris-sat14-strips/p028.pddl'),
              ('tetris-sat14-strips/domain.pddl',
               'tetris-sat14-strips/p029.pddl'),
              ('tetris-sat14-strips/domain.pddl',
               'tetris-sat14-strips/p031.pddl'),
              ('tetris-sat14-strips/domain.pddl',
               'tetris-sat14-strips/p032.pddl'),
              ('tetris-sat14-strips/domain.pddl',
               'tetris-sat14-strips/p033.pddl'),
              ('tetris-sat14-strips/domain.pddl',
               'tetris-sat14-strips/p034.pddl'),
              ('tetris-sat14-strips/domain.pddl',
               'tetris-sat14-strips/p035.pddl'),
              ('tetris-sat14-strips/domain.pddl',
               'tetris-sat14-strips/p036.pddl'),
              ('tetris-sat14-strips/domain.pddl',
               'tetris-sat14-strips/p037.pddl'),
              ('tetris-sat14-strips/domain.pddl',
               'tetris-sat14-strips/p038.pddl'),
              ('tetris-sat14-strips/domain.pddl',
               'tetris-sat14-strips/p039.pddl'),
              ('tetris-sat14-strips/domain.pddl',
               'tetris-sat14-strips/p040.pddl')]}
]