domains = [
{'description': 'This domain is original from the learning part of IPC2008. The domain involves parking cars on a street with N curb locations, and where cars can be double-parked but not triple-parked. The goal is to find a plan to move from one configuration of parked cars to another configuration, by driving cars from one curb location to another. The problems in the competition contain 2*(N-1) cars, which allows one free curb space and guarantees solvability.',
 'ipc': '2014',
 'name': 'parking',
 'problems': [('parking-sat14-strips/domain.pddl',
               'parking-sat14-strips/p_28_2.pddl'),
              ('parking-sat14-strips/domain.pddl',
               'parking-sat14-strips/p_28_3.pddl'),
              ('parking-sat14-strips/domain.pddl',
               'parking-sat14-strips/p_30_1.pddl'),
              ('parking-sat14-strips/domain.pddl',
               'parking-sat14-strips/p_30_2.pddl'),
              ('parking-sat14-strips/domain.pddl',
               'parking-sat14-strips/p_30_3.pddl'),
              ('parking-sat14-strips/domain.pddl',
               'parking-sat14-strips/p_32_1.pddl'),
              ('parking-sat14-strips/domain.pddl',
               'parking-sat14-strips/p_32_2.pddl'),
              ('parking-sat14-strips/domain.pddl',
               'parking-sat14-strips/p_32_3.pddl'),
              ('parking-sat14-strips/domain.pddl',
               'parking-sat14-strips/p_34_1.pddl'),
              ('parking-sat14-strips/domain.pddl',
               'parking-sat14-strips/p_34_2.pddl'),
              ('parking-sat14-strips/domain.pddl',
               'parking-sat14-strips/p_34_3.pddl'),
              ('parking-sat14-strips/domain.pddl',
               'parking-sat14-strips/p_36_1.pddl'),
              ('parking-sat14-strips/domain.pddl',
               'parking-sat14-strips/p_36_2.pddl'),
              ('parking-sat14-strips/domain.pddl',
               'parking-sat14-strips/p_36_3.pddl'),
              ('parking-sat14-strips/domain.pddl',
               'parking-sat14-strips/p_38_1.pddl'),
              ('parking-sat14-strips/domain.pddl',
               'parking-sat14-strips/p_38_2.pddl'),
              ('parking-sat14-strips/domain.pddl',
               'parking-sat14-strips/p_38_3.pddl'),
              ('parking-sat14-strips/domain.pddl',
               'parking-sat14-strips/p_40_1.pddl'),
              ('parking-sat14-strips/domain.pddl',
               'parking-sat14-strips/p_40_2.pddl'),
              ('parking-sat14-strips/domain.pddl',
               'parking-sat14-strips/p_40_3.pddl')]}
]