domains = [
{'description': 'Typed classical ADL domain, using conditional effects. Transport a number of objects from their start- to their goal-locations, using a briefcase. Each location is accessible from each other location, objects can be put into the briefcase or taken out of the briefcase. When a move is made between locations, then all objects inside the briefcase are also moved, which is encoded by a conditional effect.',
 'ipc': None,
 'name': 'briefcaseworld',
 'problems': [('briefcaseworld/domain.pddl', 'briefcaseworld/pfile1.pddl'),
              ('briefcaseworld/domain.pddl', 'briefcaseworld/pfile10.pddl'),
              ('briefcaseworld/domain.pddl', 'briefcaseworld/pfile11.pddl'),
              ('briefcaseworld/domain.pddl', 'briefcaseworld/pfile12.pddl'),
              ('briefcaseworld/domain.pddl', 'briefcaseworld/pfile13.pddl'),
              ('briefcaseworld/domain.pddl', 'briefcaseworld/pfile14.pddl'),
              ('briefcaseworld/domain.pddl', 'briefcaseworld/pfile15.pddl'),
              ('briefcaseworld/domain.pddl', 'briefcaseworld/pfile16.pddl'),
              ('briefcaseworld/domain.pddl', 'briefcaseworld/pfile17.pddl'),
              ('briefcaseworld/domain.pddl', 'briefcaseworld/pfile18.pddl'),
              ('briefcaseworld/domain.pddl', 'briefcaseworld/pfile19.pddl'),
              ('briefcaseworld/domain.pddl', 'briefcaseworld/pfile2.pddl'),
              ('briefcaseworld/domain.pddl', 'briefcaseworld/pfile20.pddl'),
              ('briefcaseworld/domain.pddl', 'briefcaseworld/pfile21.pddl'),
              ('briefcaseworld/domain.pddl', 'briefcaseworld/pfile22.pddl'),
              ('briefcaseworld/domain.pddl', 'briefcaseworld/pfile23.pddl'),
              ('briefcaseworld/domain.pddl', 'briefcaseworld/pfile24.pddl'),
              ('briefcaseworld/domain.pddl', 'briefcaseworld/pfile25.pddl'),
              ('briefcaseworld/domain.pddl', 'briefcaseworld/pfile26.pddl'),
              ('briefcaseworld/domain.pddl', 'briefcaseworld/pfile27.pddl'),
              ('briefcaseworld/domain.pddl', 'briefcaseworld/pfile28.pddl'),
              ('briefcaseworld/domain.pddl', 'briefcaseworld/pfile29.pddl'),
              ('briefcaseworld/domain.pddl', 'briefcaseworld/pfile3.pddl'),
              ('briefcaseworld/domain.pddl', 'briefcaseworld/pfile30.pddl'),
              ('briefcaseworld/domain.pddl', 'briefcaseworld/pfile4.pddl'),
              ('briefcaseworld/domain.pddl', 'briefcaseworld/pfile5.pddl'),
              ('briefcaseworld/domain.pddl', 'briefcaseworld/pfile6.pddl'),
              ('briefcaseworld/domain.pddl', 'briefcaseworld/pfile7.pddl'),
              ('briefcaseworld/domain.pddl', 'briefcaseworld/pfile8.pddl'),
              ('briefcaseworld/domain.pddl', 'briefcaseworld/pfile9.pddl')]}
]