domains = [
{'description': 'Classical untyped STRIPS domain, where stackable blocks need to be re-assembled on a table with unlimited space. Representation uses 3 operators, moving a block from the table to another block, a block from another block to the table, or a block from a block to another block. Semantically, the representation does not use a robot arm, in difference to the 4 operator representation. The initial state specifies a complete state, the goal state specifies only the on relations required between any two blocks.',
 'ipc': None,
 'name': 'blocks-3op',
 'problems': [('blocks-3op/domain.pddl', 'blocks-3op/pfile1.pddl'),
              ('blocks-3op/domain.pddl', 'blocks-3op/pfile10.pddl'),
              ('blocks-3op/domain.pddl', 'blocks-3op/pfile11.pddl'),
              ('blocks-3op/domain.pddl', 'blocks-3op/pfile12.pddl'),
              ('blocks-3op/domain.pddl', 'blocks-3op/pfile13.pddl'),
              ('blocks-3op/domain.pddl', 'blocks-3op/pfile14.pddl'),
              ('blocks-3op/domain.pddl', 'blocks-3op/pfile15.pddl'),
              ('blocks-3op/domain.pddl', 'blocks-3op/pfile16.pddl'),
              ('blocks-3op/domain.pddl', 'blocks-3op/pfile17.pddl'),
              ('blocks-3op/domain.pddl', 'blocks-3op/pfile18.pddl'),
              ('blocks-3op/domain.pddl', 'blocks-3op/pfile19.pddl'),
              ('blocks-3op/domain.pddl', 'blocks-3op/pfile2.pddl'),
              ('blocks-3op/domain.pddl', 'blocks-3op/pfile20.pddl'),
              ('blocks-3op/domain.pddl', 'blocks-3op/pfile21.pddl'),
              ('blocks-3op/domain.pddl', 'blocks-3op/pfile22.pddl'),
              ('blocks-3op/domain.pddl', 'blocks-3op/pfile23.pddl'),
              ('blocks-3op/domain.pddl', 'blocks-3op/pfile24.pddl'),
              ('blocks-3op/domain.pddl', 'blocks-3op/pfile25.pddl'),
              ('blocks-3op/domain.pddl', 'blocks-3op/pfile26.pddl'),
              ('blocks-3op/domain.pddl', 'blocks-3op/pfile27.pddl'),
              ('blocks-3op/domain.pddl', 'blocks-3op/pfile28.pddl'),
              ('blocks-3op/domain.pddl', 'blocks-3op/pfile29.pddl'),
              ('blocks-3op/domain.pddl', 'blocks-3op/pfile3.pddl'),
              ('blocks-3op/domain.pddl', 'blocks-3op/pfile30.pddl'),
              ('blocks-3op/domain.pddl', 'blocks-3op/pfile4.pddl'),
              ('blocks-3op/domain.pddl', 'blocks-3op/pfile5.pddl'),
              ('blocks-3op/domain.pddl', 'blocks-3op/pfile6.pddl'),
              ('blocks-3op/domain.pddl', 'blocks-3op/pfile7.pddl'),
              ('blocks-3op/domain.pddl', 'blocks-3op/pfile8.pddl'),
              ('blocks-3op/domain.pddl', 'blocks-3op/pfile9.pddl')]}
]