domains = [{'description': '(opt18) Termes:\nsubmitted by Sven Koenig and Satish Kumar\n\nThis domain models the Harvard TERMES robots, based on termites. They cannot only carry\nblocks but also climb on them so that they can build complex structures. This domain, in\nits full generality, is a multi-agent planning benchmark, but here we model only a single\nrobot.\n\n\nPublication: S. Koenig and S. Kumar. A Case for Collaborative Construction as Testbed for Cooperative\nMulti-Agent Planning. In Proceedings of the ICAPS-17 Scheduling and Planning Applications\nWorkshop (SPARK), 2017.',
 'ipc': '2018',
 'name': 'termes',
 'problems': [('termes-opt18/domain.pddl', 'termes-opt18/p11.pddl'),
              ('termes-opt18/domain.pddl', 'termes-opt18/p07.pddl'),
              ('termes-opt18/domain.pddl', 'termes-opt18/p06.pddl'),
              ('termes-opt18/domain.pddl', 'termes-opt18/p10.pddl'),
              ('termes-opt18/domain.pddl', 'termes-opt18/p17.pddl'),
              ('termes-opt18/domain.pddl', 'termes-opt18/p01.pddl'),
              ('termes-opt18/domain.pddl', 'termes-opt18/p16.pddl'),
              ('termes-opt18/domain.pddl', 'termes-opt18/p20.pddl'),
              ('termes-opt18/domain.pddl', 'termes-opt18/p19.pddl'),
              ('termes-opt18/domain.pddl', 'termes-opt18/p03.pddl'),
              ('termes-opt18/domain.pddl', 'termes-opt18/p15.pddl'),
              ('termes-opt18/domain.pddl', 'termes-opt18/p14.pddl'),
              ('termes-opt18/domain.pddl', 'termes-opt18/p02.pddl'),
              ('termes-opt18/domain.pddl', 'termes-opt18/p18.pddl'),
              ('termes-opt18/domain.pddl', 'termes-opt18/p05.pddl'),
              ('termes-opt18/domain.pddl', 'termes-opt18/p13.pddl'),
              ('termes-opt18/domain.pddl', 'termes-opt18/p09.pddl'),
              ('termes-opt18/domain.pddl', 'termes-opt18/p08.pddl'),
              ('termes-opt18/domain.pddl', 'termes-opt18/p12.pddl'),
              ('termes-opt18/domain.pddl', 'termes-opt18/p04.pddl')]}]
