domains = [
{'description': 'An agent in the middle of a square grid nxn must visit all the cells in the grid. Solving optimally the delete relaxation h+ gives the exact goal distance as long as there exists a hamiltonian path visiting every cell. Recall that in a 1xn grid, no hamiltonian path exists.',
 'ipc': '2014',
 'name': 'visitall',
 'problems': [('visitall-opt14-strips/domain.pddl',
               'visitall-opt14-strips/p-05-10.pddl'),
              ('visitall-opt14-strips/domain.pddl',
               'visitall-opt14-strips/p-05-5.pddl'),
              ('visitall-opt14-strips/domain.pddl',
               'visitall-opt14-strips/p-05-6.pddl'),
              ('visitall-opt14-strips/domain.pddl',
               'visitall-opt14-strips/p-05-7.pddl'),
              ('visitall-opt14-strips/domain.pddl',
               'visitall-opt14-strips/p-05-8.pddl'),
              ('visitall-opt14-strips/domain.pddl',
               'visitall-opt14-strips/p-05-9.pddl'),
              ('visitall-opt14-strips/domain.pddl',
               'visitall-opt14-strips/p-1-10.pddl'),
              ('visitall-opt14-strips/domain.pddl',
               'visitall-opt14-strips/p-1-11.pddl'),
              ('visitall-opt14-strips/domain.pddl',
               'visitall-opt14-strips/p-1-12.pddl'),
              ('visitall-opt14-strips/domain.pddl',
               'visitall-opt14-strips/p-1-13.pddl'),
              ('visitall-opt14-strips/domain.pddl',
               'visitall-opt14-strips/p-1-14.pddl'),
              ('visitall-opt14-strips/domain.pddl',
               'visitall-opt14-strips/p-1-15.pddl'),
              ('visitall-opt14-strips/domain.pddl',
               'visitall-opt14-strips/p-1-16.pddl'),
              ('visitall-opt14-strips/domain.pddl',
               'visitall-opt14-strips/p-1-17.pddl'),
              ('visitall-opt14-strips/domain.pddl',
               'visitall-opt14-strips/p-1-18.pddl'),
              ('visitall-opt14-strips/domain.pddl',
               'visitall-opt14-strips/p-1-5.pddl'),
              ('visitall-opt14-strips/domain.pddl',
               'visitall-opt14-strips/p-1-6.pddl'),
              ('visitall-opt14-strips/domain.pddl',
               'visitall-opt14-strips/p-1-7.pddl'),
              ('visitall-opt14-strips/domain.pddl',
               'visitall-opt14-strips/p-1-8.pddl'),
              ('visitall-opt14-strips/domain.pddl',
               'visitall-opt14-strips/p-1-9.pddl')]}
]