domains = [
{'description': 'Nomystery is a transportation domain designed to study resource constrained planning. In this domain, a truck moves in a weighted graph; a set of packages must be transported between nodes; actions move along edges, and load/unload packages; each move consumes the edge weight in fuel. In brief, Nomystery is a straightforward problem similar to the ones contained in many IPC benchmarks. Its key feature is that it comes with a domain-specific optimal solver allowing to control the constrainedness of the resources. The generator first creates a random connected undirected graph with n nodes, and it adds k packages with random origins and destinations. The edge weights are uniformly drawn between 1 and an integer W. The optimal solver computes the minimum required amount of fuel M, and the initial fuel supply is set to [C xM], where C >=1 is a (float) input parameter of the generator. The parameter C denotes the ratio between the available fuel vs. the minimum amount required. The problem becomes more constrained when C approaches 1.',
 'ipc': None,
 'name': 'no-mystery',
 'problems': [('no-mystery/domain.pddl', 'no-mystery/prob01.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob02.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob03.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob04.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob05.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob06.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob07.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob08.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob09.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob10.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob11.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob12.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob13.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob14.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob15.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob16.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob17.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob18.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob19.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob20.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob21.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob22.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob23.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob24.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob25.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob26.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob27.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob28.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob29.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob30.pddl')]}
]