domains = [
{'description': '',
 'ipc': None,
 'name': 'no-mystery',
 'problems': [('no-mystery/domain.pddl', 'no-mystery/prob01.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob02.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob03.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob04.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob05.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob06.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob07.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob08.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob09.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob10.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob11.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob12.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob13.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob14.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob15.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob16.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob17.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob18.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob19.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob20.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob21.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob22.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob23.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob24.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob25.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob26.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob27.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob28.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob29.pddl'),
              ('no-mystery/domain.pddl', 'no-mystery/prob30.pddl')]}
]