domains = [
{'description': 'Moving packages between locations by trucks under certain spatial constraints and delivering deadlines.',
 'ipc': None,
 'name': 'trucks',
 'problems': [('trucks-strips/domain_p01.pddl', 'trucks-strips/p01.pddl'),
              ('trucks-strips/domain_p02.pddl', 'trucks-strips/p02.pddl'),
              ('trucks-strips/domain_p03.pddl', 'trucks-strips/p03.pddl'),
              ('trucks-strips/domain_p04.pddl', 'trucks-strips/p04.pddl'),
              ('trucks-strips/domain_p05.pddl', 'trucks-strips/p05.pddl'),
              ('trucks-strips/domain_p06.pddl', 'trucks-strips/p06.pddl'),
              ('trucks-strips/domain_p07.pddl', 'trucks-strips/p07.pddl'),
              ('trucks-strips/domain_p08.pddl', 'trucks-strips/p08.pddl'),
              ('trucks-strips/domain_p09.pddl', 'trucks-strips/p09.pddl'),
              ('trucks-strips/domain_p10.pddl', 'trucks-strips/p10.pddl'),
              ('trucks-strips/domain_p11.pddl', 'trucks-strips/p11.pddl'),
              ('trucks-strips/domain_p12.pddl', 'trucks-strips/p12.pddl'),
              ('trucks-strips/domain_p13.pddl', 'trucks-strips/p13.pddl'),
              ('trucks-strips/domain_p14.pddl', 'trucks-strips/p14.pddl'),
              ('trucks-strips/domain_p15.pddl', 'trucks-strips/p15.pddl'),
              ('trucks-strips/domain_p16.pddl', 'trucks-strips/p16.pddl'),
              ('trucks-strips/domain_p17.pddl', 'trucks-strips/p17.pddl'),
              ('trucks-strips/domain_p18.pddl', 'trucks-strips/p18.pddl'),
              ('trucks-strips/domain_p19.pddl', 'trucks-strips/p19.pddl'),
              ('trucks-strips/domain_p20.pddl', 'trucks-strips/p20.pddl'),
              ('trucks-strips/domain_p21.pddl', 'trucks-strips/p21.pddl'),
              ('trucks-strips/domain_p22.pddl', 'trucks-strips/p22.pddl'),
              ('trucks-strips/domain_p23.pddl', 'trucks-strips/p23.pddl'),
              ('trucks-strips/domain_p24.pddl', 'trucks-strips/p24.pddl'),
              ('trucks-strips/domain_p25.pddl', 'trucks-strips/p25.pddl'),
              ('trucks-strips/domain_p26.pddl', 'trucks-strips/p26.pddl'),
              ('trucks-strips/domain_p27.pddl', 'trucks-strips/p27.pddl'),
              ('trucks-strips/domain_p28.pddl', 'trucks-strips/p28.pddl'),
              ('trucks-strips/domain_p29.pddl', 'trucks-strips/p29.pddl'),
              ('trucks-strips/domain_p30.pddl', 'trucks-strips/p30.pddl')]}
]