domains = [
{'description': 'Each vehicle can transport some packages depending on its capacity and moving has a cost depending on the length of the road. Picking up or dropping a package costs 1.',
 'ipc': '2011',
 'name': 'transport',
 'problems': [('transport-opt11-strips/domain.pddl',
               'transport-opt11-strips/p01.pddl'),
              ('transport-opt11-strips/domain.pddl',
               'transport-opt11-strips/p02.pddl'),
              ('transport-opt11-strips/domain.pddl',
               'transport-opt11-strips/p03.pddl'),
              ('transport-opt11-strips/domain.pddl',
               'transport-opt11-strips/p04.pddl'),
              ('transport-opt11-strips/domain.pddl',
               'transport-opt11-strips/p05.pddl'),
              ('transport-opt11-strips/domain.pddl',
               'transport-opt11-strips/p06.pddl'),
              ('transport-opt11-strips/domain.pddl',
               'transport-opt11-strips/p07.pddl'),
              ('transport-opt11-strips/domain.pddl',
               'transport-opt11-strips/p08.pddl'),
              ('transport-opt11-strips/domain.pddl',
               'transport-opt11-strips/p09.pddl'),
              ('transport-opt11-strips/domain.pddl',
               'transport-opt11-strips/p10.pddl'),
              ('transport-opt11-strips/domain.pddl',
               'transport-opt11-strips/p11.pddl'),
              ('transport-opt11-strips/domain.pddl',
               'transport-opt11-strips/p12.pddl'),
              ('transport-opt11-strips/domain.pddl',
               'transport-opt11-strips/p13.pddl'),
              ('transport-opt11-strips/domain.pddl',
               'transport-opt11-strips/p14.pddl'),
              ('transport-opt11-strips/domain.pddl',
               'transport-opt11-strips/p15.pddl'),
              ('transport-opt11-strips/domain.pddl',
               'transport-opt11-strips/p16.pddl'),
              ('transport-opt11-strips/domain.pddl',
               'transport-opt11-strips/p17.pddl'),
              ('transport-opt11-strips/domain.pddl',
               'transport-opt11-strips/p18.pddl'),
              ('transport-opt11-strips/domain.pddl',
               'transport-opt11-strips/p19.pddl'),
              ('transport-opt11-strips/domain.pddl',
               'transport-opt11-strips/p20.pddl')]}
]