domains = [
{'description': 'Traveling and buying goods at selected markets minimizing costs (from OR with variants, NP-hard).',
 'ipc': '2011',
 'name': 'tpp',
 'problems': [('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p01.pddl'),
('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p02.pddl'),
('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p03.pddl'),
('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p04.pddl'),
('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p05.pddl'),
('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p06.pddl'),
('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p07.pddl'),
('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p08.pddl'),
('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p09.pddl'),
('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p10.pddl'),
('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p11.pddl'),
('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p12.pddl'),
('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p13.pddl'),
('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p14.pddl'),
('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p15.pddl'),
('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p16.pddl'),
('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p17.pddl'),
('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p18.pddl'),
('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p19.pddl'),
('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p20.pddl'),
('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p21.pddl'),
('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p22.pddl'),
('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p23.pddl'),
('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p24.pddl'),
('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p25.pddl'),
('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p26.pddl'),
('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p27.pddl'),
('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p28.pddl'),
('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p29.pddl'),
('tpp-ipc11-learning-test/domain.pddl', 'tpp-ipc11-learning-test/p30.pddl')]}
]
