domains = [
{'description': 'Traveling and buying goods at selected markets minimizing costs (from OR with variants, NP-hard).',
 'ipc': '2006',
 'name': 'tpp',
 'problems': [('tpp/domain.pddl', 'tpp/p01.pddl'),
              ('tpp/domain.pddl', 'tpp/p02.pddl'),
              ('tpp/domain.pddl', 'tpp/p03.pddl'),
              ('tpp/domain.pddl', 'tpp/p04.pddl'),
              ('tpp/domain.pddl', 'tpp/p05.pddl'),
              ('tpp/domain.pddl', 'tpp/p06.pddl'),
              ('tpp/domain.pddl', 'tpp/p07.pddl'),
              ('tpp/domain.pddl', 'tpp/p08.pddl'),
              ('tpp/domain.pddl', 'tpp/p09.pddl'),
              ('tpp/domain.pddl', 'tpp/p10.pddl'),
              ('tpp/domain.pddl', 'tpp/p11.pddl'),
              ('tpp/domain.pddl', 'tpp/p12.pddl'),
              ('tpp/domain.pddl', 'tpp/p13.pddl'),
              ('tpp/domain.pddl', 'tpp/p14.pddl'),
              ('tpp/domain.pddl', 'tpp/p15.pddl'),
              ('tpp/domain.pddl', 'tpp/p16.pddl'),
              ('tpp/domain.pddl', 'tpp/p17.pddl'),
              ('tpp/domain.pddl', 'tpp/p18.pddl'),
              ('tpp/domain.pddl', 'tpp/p19.pddl'),
              ('tpp/domain.pddl', 'tpp/p20.pddl'),
              ('tpp/domain.pddl', 'tpp/p21.pddl'),
              ('tpp/domain.pddl', 'tpp/p22.pddl'),
              ('tpp/domain.pddl', 'tpp/p23.pddl'),
              ('tpp/domain.pddl', 'tpp/p24.pddl'),
              ('tpp/domain.pddl', 'tpp/p25.pddl'),
              ('tpp/domain.pddl', 'tpp/p26.pddl'),
              ('tpp/domain.pddl', 'tpp/p27.pddl'),
              ('tpp/domain.pddl', 'tpp/p28.pddl'),
              ('tpp/domain.pddl', 'tpp/p29.pddl'),
              ('tpp/domain.pddl', 'tpp/p30.pddl')]}
]