domains = [
{'description': '',
 'ipc': '2014',
 'name': 'floortile',
 'problems': [('floortile-opt14-strips/domain.pddl',
               'floortile-opt14-strips/p01-4-3-2.pddl'),
              ('floortile-opt14-strips/domain.pddl',
               'floortile-opt14-strips/p01-4-4-2.pddl'),
              ('floortile-opt14-strips/domain.pddl',
               'floortile-opt14-strips/p01-5-3-2.pddl'),
              ('floortile-opt14-strips/domain.pddl',
               'floortile-opt14-strips/p01-5-4-2.pddl'),
              ('floortile-opt14-strips/domain.pddl',
               'floortile-opt14-strips/p01-5-5-2.pddl'),
              ('floortile-opt14-strips/domain.pddl',
               'floortile-opt14-strips/p01-6-4-2.pddl'),
              ('floortile-opt14-strips/domain.pddl',
               'floortile-opt14-strips/p01-6-5-2.pddl'),
              ('floortile-opt14-strips/domain.pddl',
               'floortile-opt14-strips/p02-4-4-2.pddl'),
              ('floortile-opt14-strips/domain.pddl',
               'floortile-opt14-strips/p02-5-3-2.pddl'),
              ('floortile-opt14-strips/domain.pddl',
               'floortile-opt14-strips/p02-5-4-2.pddl'),
              ('floortile-opt14-strips/domain.pddl',
               'floortile-opt14-strips/p02-5-5-2.pddl'),
              ('floortile-opt14-strips/domain.pddl',
               'floortile-opt14-strips/p02-6-4-2.pddl'),
              ('floortile-opt14-strips/domain.pddl',
               'floortile-opt14-strips/p02-6-5-2.pddl'),
              ('floortile-opt14-strips/domain.pddl',
               'floortile-opt14-strips/p03-4-3-2.pddl'),
              ('floortile-opt14-strips/domain.pddl',
               'floortile-opt14-strips/p03-4-4-2.pddl'),
              ('floortile-opt14-strips/domain.pddl',
               'floortile-opt14-strips/p03-5-3-2.pddl'),
              ('floortile-opt14-strips/domain.pddl',
               'floortile-opt14-strips/p03-5-4-2.pddl'),
              ('floortile-opt14-strips/domain.pddl',
               'floortile-opt14-strips/p03-5-5-2.pddl'),
              ('floortile-opt14-strips/domain.pddl',
               'floortile-opt14-strips/p03-6-4-2.pddl'),
              ('floortile-opt14-strips/domain.pddl',
               'floortile-opt14-strips/p03-6-5-2.pddl')]}
]