domains = [
{'description': 'This domain is original from the learning part of IPC2008. The domain involves parking cars on a street with N curb locations, and where cars can be double-parked but not triple-parked. The goal is to find a plan to move from one configuration of parked cars to another configuration, by driving cars from one curb location to another. The problems in the competition contain 2*(N-1) cars, which allows one free curb space and guarantees solvability.',
 'ipc': '2011',
 'name': 'parking',
 'problems': [('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p01.pddl'),
('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p02.pddl'),
('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p03.pddl'),
('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p04.pddl'),
('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p05.pddl'),
('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p06.pddl'),
('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p07.pddl'),
('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p08.pddl'),
('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p09.pddl'),
('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p10.pddl'),
('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p11.pddl'),
('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p12.pddl'),
('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p13.pddl'),
('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p14.pddl'),
('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p15.pddl'),
('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p16.pddl'),
('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p17.pddl'),
('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p18.pddl'),
('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p19.pddl'),
('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p20.pddl'),
('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p21.pddl'),
('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p22.pddl'),
('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p23.pddl'),
('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p24.pddl'),
('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p25.pddl'),
('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p26.pddl'),
('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p27.pddl'),
('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p28.pddl'),
('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p29.pddl'),
('parking-ipc11-learning-target/domain.pddl', 'parking-ipc11-learning-target/p30.pddl')]}
]
