domains = [
{'description': "In this domain there is a robot barman that manipulates drink dispensers, glasses and a shaker. The goal is to find a plan of the robot's actions that serves a desired set of drinks. In this domain deletes of actions encode relevant knowledge given that robot hands can only grasp one object at a time and given that glasses need to be empty and clean to be filled.",
 'ipc': '2011',
 'name': 'barman',
 'problems': [('barman-ipc11-learning-target/domain.pddl',
               'barman-ipc11-learning-target/p01.pddl'),
              ('barman-ipc11-learning-target/domain.pddl',
               'barman-ipc11-learning-target/p02.pddl'),
              ('barman-ipc11-learning-target/domain.pddl',
               'barman-ipc11-learning-target/p03.pddl'),
              ('barman-ipc11-learning-target/domain.pddl',
               'barman-ipc11-learning-target/p04.pddl'),
              ('barman-ipc11-learning-target/domain.pddl',
               'barman-ipc11-learning-target/p05.pddl'),
              ('barman-ipc11-learning-target/domain.pddl',
               'barman-ipc11-learning-target/p06.pddl'),
              ('barman-ipc11-learning-target/domain.pddl',
               'barman-ipc11-learning-target/p07.pddl'),
              ('barman-ipc11-learning-target/domain.pddl',
               'barman-ipc11-learning-target/p08.pddl'),
              ('barman-ipc11-learning-target/domain.pddl',
               'barman-ipc11-learning-target/p09.pddl'),
              ('barman-ipc11-learning-target/domain.pddl',
               'barman-ipc11-learning-target/p10.pddl'),
              ('barman-ipc11-learning-target/domain.pddl',
               'barman-ipc11-learning-target/p11.pddl'),
              ('barman-ipc11-learning-target/domain.pddl',
               'barman-ipc11-learning-target/p12.pddl'),
              ('barman-ipc11-learning-target/domain.pddl',
               'barman-ipc11-learning-target/p13.pddl'),
              ('barman-ipc11-learning-target/domain.pddl',
               'barman-ipc11-learning-target/p14.pddl'),
              ('barman-ipc11-learning-target/domain.pddl',
               'barman-ipc11-learning-target/p15.pddl'),
              ('barman-ipc11-learning-target/domain.pddl',
               'barman-ipc11-learning-target/p16.pddl'),
              ('barman-ipc11-learning-target/domain.pddl',
               'barman-ipc11-learning-target/p17.pddl'),
              ('barman-ipc11-learning-target/domain.pddl',
               'barman-ipc11-learning-target/p18.pddl'),
              ('barman-ipc11-learning-target/domain.pddl',
               'barman-ipc11-learning-target/p19.pddl'),
              ('barman-ipc11-learning-target/domain.pddl',
               'barman-ipc11-learning-target/p20.pddl')]}
]
