domains = [
{'description': 'A domain that models the cyber security model of vulnerability analysis for cyber defense.',
 'ipc': '2008',
 'name': 'cybersec',
 'problems': [('cybersec/p01-domain.pddl', 'cybersec/p01.pddl'),
              ('cybersec/p02-domain.pddl', 'cybersec/p02.pddl'),
              ('cybersec/p03-domain.pddl', 'cybersec/p03.pddl'),
              ('cybersec/p04-domain.pddl', 'cybersec/p04.pddl'),
              ('cybersec/p05-domain.pddl', 'cybersec/p05.pddl'),
              ('cybersec/p06-domain.pddl', 'cybersec/p06.pddl'),
              ('cybersec/p07-domain.pddl', 'cybersec/p07.pddl'),
              ('cybersec/p08-domain.pddl', 'cybersec/p08.pddl'),
              ('cybersec/p09-domain.pddl', 'cybersec/p09.pddl'),
              ('cybersec/p10-domain.pddl', 'cybersec/p10.pddl'),
              ('cybersec/p11-domain.pddl', 'cybersec/p11.pddl'),
              ('cybersec/p12-domain.pddl', 'cybersec/p12.pddl'),
              ('cybersec/p13-domain.pddl', 'cybersec/p13.pddl'),
              ('cybersec/p14-domain.pddl', 'cybersec/p14.pddl'),
              ('cybersec/p15-domain.pddl', 'cybersec/p15.pddl'),
              ('cybersec/p16-domain.pddl', 'cybersec/p16.pddl'),
              ('cybersec/p17-domain.pddl', 'cybersec/p17.pddl'),
              ('cybersec/p18-domain.pddl', 'cybersec/p18.pddl'),
              ('cybersec/p19-domain.pddl', 'cybersec/p19.pddl'),
              ('cybersec/p20-domain.pddl', 'cybersec/p20.pddl'),
              ('cybersec/p21-domain.pddl', 'cybersec/p21.pddl'),
              ('cybersec/p22-domain.pddl', 'cybersec/p22.pddl'),
              ('cybersec/p23-domain.pddl', 'cybersec/p23.pddl'),
              ('cybersec/p24-domain.pddl', 'cybersec/p24.pddl'),
              ('cybersec/p25-domain.pddl', 'cybersec/p25.pddl'),
              ('cybersec/p26-domain.pddl', 'cybersec/p26.pddl'),
              ('cybersec/p27-domain.pddl', 'cybersec/p27.pddl'),
              ('cybersec/p28-domain.pddl', 'cybersec/p28.pddl'),
              ('cybersec/p29-domain.pddl', 'cybersec/p29.pddl'),
              ('cybersec/p30-domain.pddl', 'cybersec/p30.pddl')]}
]