domains = [
{'description': 'This domain is original from the learning part of IPC2008. The domain involves parking cars on a street with N curb locations, and where cars can be double-parked but not triple-parked. The goal is to find a plan to move from one configuration of parked cars to another configuration, by driving cars from one curb location to another. The problems in the competition contain 2*(N-1) cars, which allows one free curb space and guarantees solvability.',
 'ipc': '2011',
 'name': 'parking',
 'problems': [('parking-opt11-strips/domain.pddl',
               'parking-opt11-strips/pfile03-011.pddl'),
              ('parking-opt11-strips/domain.pddl',
               'parking-opt11-strips/pfile03-012.pddl'),
              ('parking-opt11-strips/domain.pddl',
               'parking-opt11-strips/pfile04-013.pddl'),
              ('parking-opt11-strips/domain.pddl',
               'parking-opt11-strips/pfile04-014.pddl'),
              ('parking-opt11-strips/domain.pddl',
               'parking-opt11-strips/pfile04-015.pddl'),
              ('parking-opt11-strips/domain.pddl',
               'parking-opt11-strips/pfile04-016.pddl'),
              ('parking-opt11-strips/domain.pddl',
               'parking-opt11-strips/pfile05-017.pddl'),
              ('parking-opt11-strips/domain.pddl',
               'parking-opt11-strips/pfile05-018.pddl'),
              ('parking-opt11-strips/domain.pddl',
               'parking-opt11-strips/pfile05-019.pddl'),
              ('parking-opt11-strips/domain.pddl',
               'parking-opt11-strips/pfile05-020.pddl'),
              ('parking-opt11-strips/domain.pddl',
               'parking-opt11-strips/pfile06-021.pddl'),
              ('parking-opt11-strips/domain.pddl',
               'parking-opt11-strips/pfile06-022.pddl'),
              ('parking-opt11-strips/domain.pddl',
               'parking-opt11-strips/pfile06-023.pddl'),
              ('parking-opt11-strips/domain.pddl',
               'parking-opt11-strips/pfile06-024.pddl'),
              ('parking-opt11-strips/domain.pddl',
               'parking-opt11-strips/pfile07-025.pddl'),
              ('parking-opt11-strips/domain.pddl',
               'parking-opt11-strips/pfile07-026.pddl'),
              ('parking-opt11-strips/domain.pddl',
               'parking-opt11-strips/pfile07-027.pddl'),
              ('parking-opt11-strips/domain.pddl',
               'parking-opt11-strips/pfile07-028.pddl'),
              ('parking-opt11-strips/domain.pddl',
               'parking-opt11-strips/pfile08-029.pddl'),
              ('parking-opt11-strips/domain.pddl',
               'parking-opt11-strips/pfile08-030.pddl')]}
]