domains = [
{'description': '',
 'ipc': '1998',
 'name': 'mystery',
 'problems': [('mystery/domain.pddl', 'mystery/prob01.pddl'),
              ('mystery/domain.pddl', 'mystery/prob02.pddl'),
              ('mystery/domain.pddl', 'mystery/prob03.pddl'),
              ('mystery/domain.pddl', 'mystery/prob04.pddl'),
              ('mystery/domain.pddl', 'mystery/prob05.pddl'),
              ('mystery/domain.pddl', 'mystery/prob06.pddl'),
              ('mystery/domain.pddl', 'mystery/prob07.pddl'),
              ('mystery/domain.pddl', 'mystery/prob08.pddl'),
              ('mystery/domain.pddl', 'mystery/prob09.pddl'),
              ('mystery/domain.pddl', 'mystery/prob10.pddl'),
              ('mystery/domain.pddl', 'mystery/prob11.pddl'),
              ('mystery/domain.pddl', 'mystery/prob12.pddl'),
              ('mystery/domain.pddl', 'mystery/prob13.pddl'),
              ('mystery/domain.pddl', 'mystery/prob14.pddl'),
              ('mystery/domain.pddl', 'mystery/prob15.pddl'),
              ('mystery/domain.pddl', 'mystery/prob16.pddl'),
              ('mystery/domain.pddl', 'mystery/prob17.pddl'),
              ('mystery/domain.pddl', 'mystery/prob18.pddl'),
              ('mystery/domain.pddl', 'mystery/prob19.pddl'),
              ('mystery/domain.pddl', 'mystery/prob20.pddl'),
              ('mystery/domain.pddl', 'mystery/prob21.pddl'),
              ('mystery/domain.pddl', 'mystery/prob22.pddl'),
              ('mystery/domain.pddl', 'mystery/prob23.pddl'),
              ('mystery/domain.pddl', 'mystery/prob24.pddl'),
              ('mystery/domain.pddl', 'mystery/prob25.pddl'),
              ('mystery/domain.pddl', 'mystery/prob26.pddl'),
              ('mystery/domain.pddl', 'mystery/prob27.pddl'),
              ('mystery/domain.pddl', 'mystery/prob28.pddl'),
              ('mystery/domain.pddl', 'mystery/prob29.pddl'),
              ('mystery/domain.pddl', 'mystery/prob30.pddl')]}
]