domains = [
{'description': 'There is a planar graph of nodes. At each node are vehicles, cargo items, and some amount of fuel. Objects can be loaded onto vehicles (up to their capacity), and the vehicles can move between nodes; but a vehicle can leave a node only if there is a nonzero amount of fuel there, and the amount decreases by one unit. The goal is to get cargo items from various nodes to various new nodes. To disguise the domain, the nodes were called emotions, the cargo items were pains, the vehicles were pleasures, and fuel and capacity numbers were encoded as geographical entities. This domain was created by Drew McDermott.',
 'ipc': '1998',
 'name': 'mystery',
 'problems': [('mystery/domain.pddl', 'mystery/prob01.pddl'),
              ('mystery/domain.pddl', 'mystery/prob02.pddl'),
              ('mystery/domain.pddl', 'mystery/prob03.pddl'),
              ('mystery/domain.pddl', 'mystery/prob04.pddl'),
              ('mystery/domain.pddl', 'mystery/prob05.pddl'),
              ('mystery/domain.pddl', 'mystery/prob06.pddl'),
              ('mystery/domain.pddl', 'mystery/prob07.pddl'),
              ('mystery/domain.pddl', 'mystery/prob08.pddl'),
              ('mystery/domain.pddl', 'mystery/prob09.pddl'),
              ('mystery/domain.pddl', 'mystery/prob10.pddl'),
              ('mystery/domain.pddl', 'mystery/prob11.pddl'),
              ('mystery/domain.pddl', 'mystery/prob12.pddl'),
              ('mystery/domain.pddl', 'mystery/prob13.pddl'),
              ('mystery/domain.pddl', 'mystery/prob14.pddl'),
              ('mystery/domain.pddl', 'mystery/prob15.pddl'),
              ('mystery/domain.pddl', 'mystery/prob16.pddl'),
              ('mystery/domain.pddl', 'mystery/prob17.pddl'),
              ('mystery/domain.pddl', 'mystery/prob18.pddl'),
              ('mystery/domain.pddl', 'mystery/prob19.pddl'),
              ('mystery/domain.pddl', 'mystery/prob20.pddl'),
              ('mystery/domain.pddl', 'mystery/prob21.pddl'),
              ('mystery/domain.pddl', 'mystery/prob22.pddl'),
              ('mystery/domain.pddl', 'mystery/prob23.pddl'),
              ('mystery/domain.pddl', 'mystery/prob24.pddl'),
              ('mystery/domain.pddl', 'mystery/prob25.pddl'),
              ('mystery/domain.pddl', 'mystery/prob26.pddl'),
              ('mystery/domain.pddl', 'mystery/prob27.pddl'),
              ('mystery/domain.pddl', 'mystery/prob28.pddl'),
              ('mystery/domain.pddl', 'mystery/prob29.pddl'),
              ('mystery/domain.pddl', 'mystery/prob30.pddl')]}
]