domains = [
{'description': 'Freecell is the familiar solitaire game found on many computers, involving moving cards from an initial tableau, constrained by tight restrictions, to achieve a final suit-sorted collection of stacks.',
 'ipc': '2011',
 'name': 'freecell',
 'problems':
 [('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p01.pddl'),
  ('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p02.pddl'),
  ('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p03.pddl'),
  ('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p04.pddl'),
  ('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p05.pddl'),
  ('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p06.pddl'),
  ('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p07.pddl'),
  ('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p08.pddl'),
  ('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p09.pddl'),
  ('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p10.pddl'),
  ('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p11.pddl'),
  ('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p12.pddl'),
  ('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p13.pddl'),
  ('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p14.pddl'),
  ('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p15.pddl'),
  ('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p16.pddl'),
  ('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p17.pddl'),
  ('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p18.pddl'),
  ('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p19.pddl'),
  ('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p20.pddl'),
  ('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p21.pddl'),
  ('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p22.pddl'),
  ('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p23.pddl'),
  ('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p24.pddl'),
  ('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p25.pddl'),
  ('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p26.pddl'),
  ('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p27.pddl'),
  ('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p28.pddl'),
  ('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p29.pddl'),
  ('freecell-ipc11-learning-target/domain.pddl', 'freecell-ipc11-learning-target/p30.pddl')]}
]
