domains = [
{'description': '',
 'ipc': '2014',
 'name': 'openstacks',
 'problems': [('openstacks-opt14-strips/domain_p20_1.pddl',
               'openstacks-opt14-strips/p20_1.pddl'),
              ('openstacks-opt14-strips/domain_p20_2.pddl',
               'openstacks-opt14-strips/p20_2.pddl'),
              ('openstacks-opt14-strips/domain_p20_3.pddl',
               'openstacks-opt14-strips/p20_3.pddl'),
              ('openstacks-opt14-strips/domain_p25_1.pddl',
               'openstacks-opt14-strips/p25_1.pddl'),
              ('openstacks-opt14-strips/domain_p25_3.pddl',
               'openstacks-opt14-strips/p25_3.pddl'),
              ('openstacks-opt14-strips/domain_p30_1.pddl',
               'openstacks-opt14-strips/p30_1.pddl'),
              ('openstacks-opt14-strips/domain_p30_2.pddl',
               'openstacks-opt14-strips/p30_2.pddl'),
              ('openstacks-opt14-strips/domain_p30_3.pddl',
               'openstacks-opt14-strips/p30_3.pddl'),
              ('openstacks-opt14-strips/domain_p35_1.pddl',
               'openstacks-opt14-strips/p35_1.pddl'),
              ('openstacks-opt14-strips/domain_p35_2.pddl',
               'openstacks-opt14-strips/p35_2.pddl'),
              ('openstacks-opt14-strips/domain_p35_3.pddl',
               'openstacks-opt14-strips/p35_3.pddl'),
              ('openstacks-opt14-strips/domain_p40_1.pddl',
               'openstacks-opt14-strips/p40_1.pddl'),
              ('openstacks-opt14-strips/domain_p40_2.pddl',
               'openstacks-opt14-strips/p40_2.pddl'),
              ('openstacks-opt14-strips/domain_p40_3.pddl',
               'openstacks-opt14-strips/p40_3.pddl'),
              ('openstacks-opt14-strips/domain_p45_1.pddl',
               'openstacks-opt14-strips/p45_1.pddl'),
              ('openstacks-opt14-strips/domain_p45_2.pddl',
               'openstacks-opt14-strips/p45_2.pddl'),
              ('openstacks-opt14-strips/domain_p45_3.pddl',
               'openstacks-opt14-strips/p45_3.pddl'),
              ('openstacks-opt14-strips/domain_p50_1.pddl',
               'openstacks-opt14-strips/p50_1.pddl'),
              ('openstacks-opt14-strips/domain_p50_2.pddl',
               'openstacks-opt14-strips/p50_2.pddl'),
              ('openstacks-opt14-strips/domain_p50_3.pddl',
               'openstacks-opt14-strips/p50_3.pddl')]}
]