domains = [
{'description': 'There is a square grid of locations. A robot can move one grid square at a time horizontally and vertically. If a square is locked, the robot can move to it only by unlocking it, which requires having a key of the same shape as the lock. The goal is to get keys from various locations to various new locations. This domain was created by Jana Koehler, based on an earlier domain by Drew McDermott.',
 'ipc': '2011',
 'name': 'grid',
 'problems': [('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p01.pddl'),
('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p02.pddl'),
('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p03.pddl'),
('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p04.pddl'),
('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p05.pddl'),
('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p06.pddl'),
('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p07.pddl'),
('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p08.pddl'),
('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p09.pddl'),
('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p10.pddl'),
('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p11.pddl'),
('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p12.pddl'),
('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p13.pddl'),
('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p14.pddl'),
('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p15.pddl'),
('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p16.pddl'),
('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p17.pddl'),
('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p18.pddl'),
('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p19.pddl'),
('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p20.pddl'),
('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p21.pddl'),
('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p22.pddl'),
('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p23.pddl'),
('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p24.pddl'),
('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p25.pddl'),
('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p26.pddl'),
('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p27.pddl'),
('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p28.pddl'),
('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p29.pddl'),
('grid-ipc11-learning-target/domain.pddl', 'grid-ipc11-learning-target/p30.pddl')]}
]
