domains = [
{'description': "In this domain there is a robot barman that manipulates drink dispensers, glasses and a shaker. The goal is to find a plan of the robot's actions that serves a desired set of drinks. In this domain deletes of actions encode relevant knowledge given that robot hands can only grasp one object at a time and given that glasses need to be empty and clean to be filled.",
 'ipc': '2011',
 'name': 'barman',
 'problems': [('barman-sat11-strips/domain.pddl',
               'barman-sat11-strips/pfile06-021.pddl'),
              ('barman-sat11-strips/domain.pddl',
               'barman-sat11-strips/pfile06-022.pddl'),
              ('barman-sat11-strips/domain.pddl',
               'barman-sat11-strips/pfile06-023.pddl'),
              ('barman-sat11-strips/domain.pddl',
               'barman-sat11-strips/pfile06-024.pddl'),
              ('barman-sat11-strips/domain.pddl',
               'barman-sat11-strips/pfile07-025.pddl'),
              ('barman-sat11-strips/domain.pddl',
               'barman-sat11-strips/pfile07-026.pddl'),
              ('barman-sat11-strips/domain.pddl',
               'barman-sat11-strips/pfile07-027.pddl'),
              ('barman-sat11-strips/domain.pddl',
               'barman-sat11-strips/pfile07-028.pddl'),
              ('barman-sat11-strips/domain.pddl',
               'barman-sat11-strips/pfile08-029.pddl'),
              ('barman-sat11-strips/domain.pddl',
               'barman-sat11-strips/pfile08-030.pddl'),
              ('barman-sat11-strips/domain.pddl',
               'barman-sat11-strips/pfile08-031.pddl'),
              ('barman-sat11-strips/domain.pddl',
               'barman-sat11-strips/pfile08-032.pddl'),
              ('barman-sat11-strips/domain.pddl',
               'barman-sat11-strips/pfile09-033.pddl'),
              ('barman-sat11-strips/domain.pddl',
               'barman-sat11-strips/pfile09-034.pddl'),
              ('barman-sat11-strips/domain.pddl',
               'barman-sat11-strips/pfile09-035.pddl'),
              ('barman-sat11-strips/domain.pddl',
               'barman-sat11-strips/pfile09-036.pddl'),
              ('barman-sat11-strips/domain.pddl',
               'barman-sat11-strips/pfile10-037.pddl'),
              ('barman-sat11-strips/domain.pddl',
               'barman-sat11-strips/pfile10-038.pddl'),
              ('barman-sat11-strips/domain.pddl',
               'barman-sat11-strips/pfile10-039.pddl'),
              ('barman-sat11-strips/domain.pddl',
               'barman-sat11-strips/pfile10-040.pddl')]}
]