domains = [
{'description': 'There is a robot with two grippers. It can carry a ball in each. The goal is to take N balls from one room to another; N rises with problem number. Some planners treat the two grippers asymmetrically, giving rise to an unnecessary combinatorial explosion. This domain was created by Jana Koehler.',
 'ipc': '2011',
 'name': 'gripper',
 'problems': [('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p01.pddl'),
('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p02.pddl'),
('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p03.pddl'),
('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p04.pddl'),
('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p05.pddl'),
('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p06.pddl'),
('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p07.pddl'),
('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p08.pddl'),
('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p09.pddl'),
('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p10.pddl'),
('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p11.pddl'),
('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p12.pddl'),
('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p13.pddl'),
('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p14.pddl'),
('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p15.pddl'),
('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p16.pddl'),
('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p17.pddl'),
('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p18.pddl'),
('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p19.pddl'),
('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p20.pddl'),
('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p21.pddl'),
('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p22.pddl'),
('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p23.pddl'),
('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p24.pddl'),
('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p25.pddl'),
('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p26.pddl'),
('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p27.pddl'),
('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p28.pddl'),
('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p29.pddl'),
('gripper-ipc11-learning-target/domain.pddl', 'gripper-ipc11-learning-target/p30.pddl'),
]}
]
