domains = [
{'description': '',
 'ipc': '2014',
 'name': 'hiking',
 'problems': [('hiking-sat14-strips/domain.pddl',
               'hiking-sat14-strips/ptesting-1-2-7.pddl'),
              ('hiking-sat14-strips/domain.pddl',
               'hiking-sat14-strips/ptesting-1-2-8.pddl'),
              ('hiking-sat14-strips/domain.pddl',
               'hiking-sat14-strips/ptesting-2-2-6.pddl'),
              ('hiking-sat14-strips/domain.pddl',
               'hiking-sat14-strips/ptesting-2-2-7.pddl'),
              ('hiking-sat14-strips/domain.pddl',
               'hiking-sat14-strips/ptesting-2-2-8.pddl'),
              ('hiking-sat14-strips/domain.pddl',
               'hiking-sat14-strips/ptesting-2-3-6.pddl'),
              ('hiking-sat14-strips/domain.pddl',
               'hiking-sat14-strips/ptesting-2-3-7.pddl'),
              ('hiking-sat14-strips/domain.pddl',
               'hiking-sat14-strips/ptesting-2-3-8.pddl'),
              ('hiking-sat14-strips/domain.pddl',
               'hiking-sat14-strips/ptesting-2-4-5.pddl'),
              ('hiking-sat14-strips/domain.pddl',
               'hiking-sat14-strips/ptesting-2-4-6.pddl'),
              ('hiking-sat14-strips/domain.pddl',
               'hiking-sat14-strips/ptesting-2-4-7.pddl'),
              ('hiking-sat14-strips/domain.pddl',
               'hiking-sat14-strips/ptesting-2-4-8.pddl'),
              ('hiking-sat14-strips/domain.pddl',
               'hiking-sat14-strips/ptesting-3-3-5.pddl'),
              ('hiking-sat14-strips/domain.pddl',
               'hiking-sat14-strips/ptesting-3-3-6.pddl'),
              ('hiking-sat14-strips/domain.pddl',
               'hiking-sat14-strips/ptesting-3-3-7.pddl'),
              ('hiking-sat14-strips/domain.pddl',
               'hiking-sat14-strips/ptesting-3-3-8.pddl'),
              ('hiking-sat14-strips/domain.pddl',
               'hiking-sat14-strips/ptesting-3-4-5.pddl'),
              ('hiking-sat14-strips/domain.pddl',
               'hiking-sat14-strips/ptesting-3-4-6.pddl'),
              ('hiking-sat14-strips/domain.pddl',
               'hiking-sat14-strips/ptesting-3-4-7.pddl'),
              ('hiking-sat14-strips/domain.pddl',
               'hiking-sat14-strips/ptesting-3-4-8.pddl')]}
]