domains = [
{'description': '',
 'ipc': '2006',
 'name': 'openstacks',
 'problems': [('openstacks/domain.pddl', 'openstacks/p01.pddl'),
              ('openstacks/domain.pddl', 'openstacks/p02.pddl'),
              ('openstacks/domain.pddl', 'openstacks/p03.pddl'),
              ('openstacks/domain.pddl', 'openstacks/p04.pddl'),
              ('openstacks/domain.pddl', 'openstacks/p05.pddl'),
              ('openstacks/domain.pddl', 'openstacks/p06.pddl'),
              ('openstacks/domain.pddl', 'openstacks/p07.pddl'),
              ('openstacks/domain.pddl', 'openstacks/p08.pddl'),
              ('openstacks/domain.pddl', 'openstacks/p09.pddl'),
              ('openstacks/domain.pddl', 'openstacks/p10.pddl'),
              ('openstacks/domain.pddl', 'openstacks/p11.pddl'),
              ('openstacks/domain.pddl', 'openstacks/p12.pddl'),
              ('openstacks/domain.pddl', 'openstacks/p13.pddl'),
              ('openstacks/domain.pddl', 'openstacks/p14.pddl'),
              ('openstacks/domain.pddl', 'openstacks/p15.pddl'),
              ('openstacks/domain.pddl', 'openstacks/p16.pddl'),
              ('openstacks/domain.pddl', 'openstacks/p17.pddl'),
              ('openstacks/domain.pddl', 'openstacks/p18.pddl'),
              ('openstacks/domain.pddl', 'openstacks/p19.pddl'),
              ('openstacks/domain.pddl', 'openstacks/p20.pddl'),
              ('openstacks/domain.pddl', 'openstacks/p21.pddl'),
              ('openstacks/domain.pddl', 'openstacks/p22.pddl'),
              ('openstacks/domain.pddl', 'openstacks/p23.pddl'),
              ('openstacks/domain.pddl', 'openstacks/p24.pddl'),
              ('openstacks/domain.pddl', 'openstacks/p25.pddl'),
              ('openstacks/domain.pddl', 'openstacks/p26.pddl'),
              ('openstacks/domain.pddl', 'openstacks/p27.pddl'),
              ('openstacks/domain.pddl', 'openstacks/p28.pddl'),
              ('openstacks/domain.pddl', 'openstacks/p29.pddl'),
              ('openstacks/domain.pddl', 'openstacks/p30.pddl')]}
]