domains = [
{'description': 'A worker is in a shed, containing a number of spanners, and at a gate some distance away there are a number of nuts that must be tightened. Crucially, once the worker has left the shed they cannot return. Also, the spanners are fragile, so once used to tighten a nut they break, and then cannot be used to tighten another. The goal is planning to pick-up the spanners and tighten the nuts. This is an interesting domain for learning, as it has a directed search space, and is challenging for planners employing an ignore delete lists relaxation.',
 'ipc': '2011',
 'name': 'spanner',
 'problems': [('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p01.pddl'),
('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p02.pddl'),
('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p03.pddl'),
('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p04.pddl'),
('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p05.pddl'),
('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p06.pddl'),
('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p07.pddl'),
('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p08.pddl'),
('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p09.pddl'),
('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p10.pddl'),
('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p11.pddl'),
('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p12.pddl'),
('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p13.pddl'),
('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p14.pddl'),
('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p15.pddl'),
('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p16.pddl'),
('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p17.pddl'),
('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p18.pddl'),
('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p19.pddl'),
('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p20.pddl'),
('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p21.pddl'),
('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p22.pddl'),
('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p23.pddl'),
('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p24.pddl'),
('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p25.pddl'),
('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p26.pddl'),
('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p27.pddl'),
('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p28.pddl'),
('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p29.pddl'),
('spanner-ipc11-learning-test/domain.pddl', 'spanner-ipc11-learning-test/p30.pddl')]}
]
