domains = [
{'description': '',
 'ipc': '2014',
 'name': 'visitall',
 'problems': [('visitall-sat14-strips/domain.pddl',
               'visitall-sat14-strips/pfile30.pddl'),
              ('visitall-sat14-strips/domain.pddl',
               'visitall-sat14-strips/pfile31.pddl'),
              ('visitall-sat14-strips/domain.pddl',
               'visitall-sat14-strips/pfile32.pddl'),
              ('visitall-sat14-strips/domain.pddl',
               'visitall-sat14-strips/pfile33.pddl'),
              ('visitall-sat14-strips/domain.pddl',
               'visitall-sat14-strips/pfile50.pddl'),
              ('visitall-sat14-strips/domain.pddl',
               'visitall-sat14-strips/pfile51.pddl'),
              ('visitall-sat14-strips/domain.pddl',
               'visitall-sat14-strips/pfile52.pddl'),
              ('visitall-sat14-strips/domain.pddl',
               'visitall-sat14-strips/pfile53.pddl'),
              ('visitall-sat14-strips/domain.pddl',
               'visitall-sat14-strips/pfile54.pddl'),
              ('visitall-sat14-strips/domain.pddl',
               'visitall-sat14-strips/pfile55.pddl'),
              ('visitall-sat14-strips/domain.pddl',
               'visitall-sat14-strips/pfile56.pddl'),
              ('visitall-sat14-strips/domain.pddl',
               'visitall-sat14-strips/pfile57.pddl'),
              ('visitall-sat14-strips/domain.pddl',
               'visitall-sat14-strips/pfile58.pddl'),
              ('visitall-sat14-strips/domain.pddl',
               'visitall-sat14-strips/pfile59.pddl'),
              ('visitall-sat14-strips/domain.pddl',
               'visitall-sat14-strips/pfile60.pddl'),
              ('visitall-sat14-strips/domain.pddl',
               'visitall-sat14-strips/pfile61.pddl'),
              ('visitall-sat14-strips/domain.pddl',
               'visitall-sat14-strips/pfile62.pddl'),
              ('visitall-sat14-strips/domain.pddl',
               'visitall-sat14-strips/pfile63.pddl'),
              ('visitall-sat14-strips/domain.pddl',
               'visitall-sat14-strips/pfile64.pddl'),
              ('visitall-sat14-strips/domain.pddl',
               'visitall-sat14-strips/pfile65.pddl')]}
]