domains = [
{'description': 'The GED problem is to find a min-cost sequence of operations that transforms one genome (signed permutation of genes) into another. The purpose of this is to use this cost as a measure of the distance between the two genomes, which is used to construct hypotheses about the evolutionary relationship between the organisms.',
 'ipc': '2014',
 'name': 'ged',
 'problems': [('ged-sat14-strips/domain.pddl',
               'ged-sat14-strips/d-10-1.pddl'),
              ('ged-sat14-strips/domain.pddl',
               'ged-sat14-strips/d-10-2.pddl'),
              ('ged-sat14-strips/domain.pddl',
               'ged-sat14-strips/d-10-3.pddl'),
              ('ged-sat14-strips/domain.pddl',
               'ged-sat14-strips/d-10-4.pddl'),
              ('ged-sat14-strips/domain.pddl',
               'ged-sat14-strips/d-10-5.pddl'),
              ('ged-sat14-strips/domain.pddl',
               'ged-sat14-strips/d-10-6.pddl'),
              ('ged-sat14-strips/domain.pddl',
               'ged-sat14-strips/d-11-1.pddl'),
              ('ged-sat14-strips/domain.pddl',
               'ged-sat14-strips/d-11-3.pddl'),
              ('ged-sat14-strips/domain.pddl',
               'ged-sat14-strips/d-11-5.pddl'),
              ('ged-sat14-strips/domain.pddl',
               'ged-sat14-strips/d-11-6.pddl'),
              ('ged-sat14-strips/domain.pddl',
               'ged-sat14-strips/d-12-11.pddl'),
              ('ged-sat14-strips/domain.pddl',
               'ged-sat14-strips/d-12-2.pddl'),
              ('ged-sat14-strips/domain.pddl',
               'ged-sat14-strips/d-12-3.pddl'),
              ('ged-sat14-strips/domain.pddl',
               'ged-sat14-strips/d-12-5.pddl'),
              ('ged-sat14-strips/domain.pddl',
               'ged-sat14-strips/d-12-6.pddl'),
              ('ged-sat14-strips/domain.pddl',
               'ged-sat14-strips/d-12-7.pddl'),
              ('ged-sat14-strips/domain.pddl',
               'ged-sat14-strips/d-12-8.pddl'),
              ('ged-sat14-strips/domain.pddl',
               'ged-sat14-strips/d-12-9.pddl'),
              ('ged-sat14-strips/domain.pddl', 'ged-sat14-strips/d-3-6.pddl'),
              ('ged-sat14-strips/domain.pddl', 'ged-sat14-strips/d-9-5.pddl')]}
]