domains = [
{'description': 'Developed by Sylvie Thiebaux and Jorg Hoffmann. Planners must resupply a number of lines in a faulty electricity network. The flow of electricity through the network, at any point in time, is given by a transitive closure over the network connections, subject to the states of the switches and electricity supply devices. The domain is therefore a good example of the usefulness of derived predicates in real-world applications.',
 'ipc': '2004',
 'name': 'psr-middle',
 'problems': [('psr-middle/domain.pddl', 'psr-middle/p01-s17-n2-l2-f30.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p02-s23-n2-l3-f70.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p03-s28-n2-l5-f10.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p04-s31-n2-l5-f70.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p05-s34-n3-l2-f50.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p06-s37-n3-l3-f30.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p07-s38-n3-l3-f50.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p08-s40-n3-l4-f10.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p09-s42-n3-l4-f50.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p10-s45-n3-l5-f30.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p11-s46-n3-l5-f50.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p12-s50-n4-l2-f50.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p13-s53-n4-l3-f30.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p14-s55-n4-l3-f70.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p15-s56-n4-l4-f10.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p16-s60-n4-l5-f10.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p17-s61-n4-l5-f30.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p18-s62-n4-l5-f50.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p19-s66-n5-l2-f50.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p20-s69-n5-l3-f30.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p21-s72-n5-l4-f10.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p22-s74-n5-l4-f50.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p23-s76-n5-l5-f10.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p24-s77-n5-l5-f30.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p25-s81-n6-l2-f30.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p26-s85-n6-l3-f30.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p27-s86-n6-l3-f50.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p28-s88-n6-l4-f10.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p29-s89-n6-l4-f30.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p30-s90-n6-l4-f50.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p31-s92-n6-l5-f10.pddl'),
              ('psr-middle/domain.pddl', 'psr-middle/p32-s93-n6-l5-f30.pddl'),
              ('psr-middle/domain.pddl',
               'psr-middle/p33-s100-n7-l3-f10.pddl'),
              ('psr-middle/domain.pddl',
               'psr-middle/p34-s102-n7-l3-f50.pddl'),
              ('psr-middle/domain.pddl',
               'psr-middle/p35-s103-n7-l3-f70.pddl'),
              ('psr-middle/domain.pddl',
               'psr-middle/p36-s106-n7-l4-f50.pddl'),
              ('psr-middle/domain.pddl',
               'psr-middle/p37-s108-n7-l5-f10.pddl'),
              ('psr-middle/domain.pddl',
               'psr-middle/p38-s109-n7-l5-f30.pddl'),
              ('psr-middle/domain.pddl',
               'psr-middle/p39-s112-n8-l2-f10.pddl'),
              ('psr-middle/domain.pddl',
               'psr-middle/p40-s114-n8-l2-f50.pddl'),
              ('psr-middle/domain.pddl',
               'psr-middle/p41-s116-n8-l3-f10.pddl'),
              ('psr-middle/domain.pddl',
               'psr-middle/p42-s120-n8-l4-f10.pddl'),
              ('psr-middle/domain.pddl',
               'psr-middle/p43-s123-n8-l4-f70.pddl'),
              ('psr-middle/domain.pddl',
               'psr-middle/p44-s131-n9-l2-f70.pddl'),
              ('psr-middle/domain.pddl',
               'psr-middle/p45-s132-n9-l3-f10.pddl'),
              ('psr-middle/domain.pddl',
               'psr-middle/p46-s135-n9-l3-f70.pddl'),
              ('psr-middle/domain.pddl',
               'psr-middle/p47-s139-n9-l4-f70.pddl'),
              ('psr-middle/domain.pddl',
               'psr-middle/p48-s144-n10-l2-f10.pddl'),
              ('psr-middle/domain.pddl',
               'psr-middle/p49-s149-n10-l3-f30.pddl'),
              ('psr-middle/domain.pddl',
               'psr-middle/p50-s153-n10-l4-f30.pddl')]}
]