domains = [
{'description': '',
 'ipc': '2011',
 'name': 'floortile',
 'problems': [('floortile-opt11-strips/domain.pddl',
               'floortile-opt11-strips/opt-p01-001.pddl'),
              ('floortile-opt11-strips/domain.pddl',
               'floortile-opt11-strips/opt-p01-002.pddl'),
              ('floortile-opt11-strips/domain.pddl',
               'floortile-opt11-strips/opt-p02-003.pddl'),
              ('floortile-opt11-strips/domain.pddl',
               'floortile-opt11-strips/opt-p02-004.pddl'),
              ('floortile-opt11-strips/domain.pddl',
               'floortile-opt11-strips/opt-p03-005.pddl'),
              ('floortile-opt11-strips/domain.pddl',
               'floortile-opt11-strips/opt-p03-006.pddl'),
              ('floortile-opt11-strips/domain.pddl',
               'floortile-opt11-strips/opt-p04-007.pddl'),
              ('floortile-opt11-strips/domain.pddl',
               'floortile-opt11-strips/opt-p04-008.pddl'),
              ('floortile-opt11-strips/domain.pddl',
               'floortile-opt11-strips/opt-p05-009.pddl'),
              ('floortile-opt11-strips/domain.pddl',
               'floortile-opt11-strips/opt-p05-010.pddl'),
              ('floortile-opt11-strips/domain.pddl',
               'floortile-opt11-strips/opt-p06-011.pddl'),
              ('floortile-opt11-strips/domain.pddl',
               'floortile-opt11-strips/opt-p06-012.pddl'),
              ('floortile-opt11-strips/domain.pddl',
               'floortile-opt11-strips/opt-p07-013.pddl'),
              ('floortile-opt11-strips/domain.pddl',
               'floortile-opt11-strips/opt-p07-014.pddl'),
              ('floortile-opt11-strips/domain.pddl',
               'floortile-opt11-strips/opt-p08-015.pddl'),
              ('floortile-opt11-strips/domain.pddl',
               'floortile-opt11-strips/opt-p08-016.pddl'),
              ('floortile-opt11-strips/domain.pddl',
               'floortile-opt11-strips/opt-p09-017.pddl'),
              ('floortile-opt11-strips/domain.pddl',
               'floortile-opt11-strips/opt-p09-018.pddl'),
              ('floortile-opt11-strips/domain.pddl',
               'floortile-opt11-strips/opt-p10-019.pddl'),
              ('floortile-opt11-strips/domain.pddl',
               'floortile-opt11-strips/opt-p10-020.pddl')]}
]