domains = [
{'description': 'This domain was devised in order to see what would happen if two previously well-researched domains were joined together. These were the logistics and blocks domains. They are combined to form a domain in which trucks can transport crates around and then the crates must be stacked onto pallets at their destinations. The stacking is achieved using hoists, so the stacking problem is like a blocks-world problem with hands. Trucks can behave like "tables", since the pallets on which crates are stacked are limited.',
 'ipc': '2011',
 'name': 'depot',
 'problems': 
 [('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p01.pddl'),
  ('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p02.pddl'),
  ('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p03.pddl'),
  ('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p04.pddl'),
  ('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p05.pddl'),
  ('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p06.pddl'),
  ('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p07.pddl'),
  ('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p08.pddl'),
  ('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p09.pddl'),
  ('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p10.pddl'),
  ('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p11.pddl'),
  ('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p12.pddl'),
  ('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p13.pddl'),
  ('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p14.pddl'),
  ('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p15.pddl'),
  ('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p16.pddl'),
  ('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p17.pddl'),
  ('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p18.pddl'),
  ('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p19.pddl'),
  ('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p20.pddl'),
  ('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p21.pddl'),
  ('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p22.pddl'),
  ('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p23.pddl'),
  ('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p24.pddl'),
  ('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p25.pddl'),
  ('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p26.pddl'),
  ('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p27.pddl'),
  ('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p28.pddl'),
  ('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p29.pddl'),
  ('depots-ipc11-learning-target/domain.pddl', 'depots-ipc11-learning-target/p30.pddl')]}]
