domains = [
{'description': 'This is the mystery domain with one extra action, the ability to squirt a unit of fuel from any node to a neighboring node, provided the originating node has at least two units. Created by Drew McDermott',
 'ipc': '1998',
 'name': 'mprime',
 'problems': [('mprime/domain.pddl', 'mprime/prob01.pddl'),
              ('mprime/domain.pddl', 'mprime/prob02.pddl'),
              ('mprime/domain.pddl', 'mprime/prob03.pddl'),
              ('mprime/domain.pddl', 'mprime/prob04.pddl'),
              ('mprime/domain.pddl', 'mprime/prob05.pddl'),
              ('mprime/domain.pddl', 'mprime/prob06.pddl'),
              ('mprime/domain.pddl', 'mprime/prob07.pddl'),
              ('mprime/domain.pddl', 'mprime/prob08.pddl'),
              ('mprime/domain.pddl', 'mprime/prob09.pddl'),
              ('mprime/domain.pddl', 'mprime/prob10.pddl'),
              ('mprime/domain.pddl', 'mprime/prob11.pddl'),
              ('mprime/domain.pddl', 'mprime/prob12.pddl'),
              ('mprime/domain.pddl', 'mprime/prob13.pddl'),
              ('mprime/domain.pddl', 'mprime/prob14.pddl'),
              ('mprime/domain.pddl', 'mprime/prob15.pddl'),
              ('mprime/domain.pddl', 'mprime/prob16.pddl'),
              ('mprime/domain.pddl', 'mprime/prob17.pddl'),
              ('mprime/domain.pddl', 'mprime/prob18.pddl'),
              ('mprime/domain.pddl', 'mprime/prob19.pddl'),
              ('mprime/domain.pddl', 'mprime/prob20.pddl'),
              ('mprime/domain.pddl', 'mprime/prob21.pddl'),
              ('mprime/domain.pddl', 'mprime/prob22.pddl'),
              ('mprime/domain.pddl', 'mprime/prob23.pddl'),
              ('mprime/domain.pddl', 'mprime/prob24.pddl'),
              ('mprime/domain.pddl', 'mprime/prob25.pddl'),
              ('mprime/domain.pddl', 'mprime/prob26.pddl'),
              ('mprime/domain.pddl', 'mprime/prob27.pddl'),
              ('mprime/domain.pddl', 'mprime/prob28.pddl'),
              ('mprime/domain.pddl', 'mprime/prob29.pddl'),
              ('mprime/domain.pddl', 'mprime/prob30.pddl'),
              ('mprime/domain.pddl', 'mprime/prob31.pddl'),
              ('mprime/domain.pddl', 'mprime/prob32.pddl'),
              ('mprime/domain.pddl', 'mprime/prob33.pddl'),
              ('mprime/domain.pddl', 'mprime/prob34.pddl'),
              ('mprime/domain.pddl', 'mprime/prob35.pddl')]}
]