domains = [{'description': '(opt18) Data Network:\nsubmitted by: Manuel Heusner\n\nIn a given network of servers, each server can produce data by processing\nexisting data and send the data to connected servers. Each server has a disk\nand random access memory (RAM). Data that is saved on the disk of a server\nmust be loaded into RAM of the server in order to be processed or sent to the\nRAM of another server.\n\nThe ability to process and distribute the data in the network is constrained by\n    - the connections between servers,\n    - the capacity of RAM on a server,\n    - the availability of scripts on servers, and\n    - the cost of\n        - loading and saving data, which depends on the data size and the (disk io performance of a) server,\n        - sending data, which depends on the data size and (bandwidth of a) connection, and\n        - processing data, which depends on the script and (clock rate and numbers of processors of a) server.',
 'ipc': '2018',
 'name': 'data-network',
 'problems': [('data-network-opt18/domain.pddl',
               'data-network-opt18/p11.pddl'),
              ('data-network-opt18/domain.pddl',
               'data-network-opt18/p07.pddl'),
              ('data-network-opt18/domain.pddl',
               'data-network-opt18/p06.pddl'),
              ('data-network-opt18/domain.pddl',
               'data-network-opt18/p10.pddl'),
              ('data-network-opt18/domain.pddl',
               'data-network-opt18/p17.pddl'),
              ('data-network-opt18/domain.pddl',
               'data-network-opt18/p01.pddl'),
              ('data-network-opt18/domain.pddl',
               'data-network-opt18/p16.pddl'),
              ('data-network-opt18/domain.pddl',
               'data-network-opt18/p20.pddl'),
              ('data-network-opt18/domain.pddl',
               'data-network-opt18/p19.pddl'),
              ('data-network-opt18/domain.pddl',
               'data-network-opt18/p03.pddl'),
              ('data-network-opt18/domain.pddl',
               'data-network-opt18/p15.pddl'),
              ('data-network-opt18/domain.pddl',
               'data-network-opt18/p14.pddl'),
              ('data-network-opt18/domain.pddl',
               'data-network-opt18/p02.pddl'),
              ('data-network-opt18/domain.pddl',
               'data-network-opt18/p18.pddl'),
              ('data-network-opt18/domain.pddl',
               'data-network-opt18/p05.pddl'),
              ('data-network-opt18/domain.pddl',
               'data-network-opt18/p13.pddl'),
              ('data-network-opt18/domain.pddl',
               'data-network-opt18/p09.pddl'),
              ('data-network-opt18/domain.pddl',
               'data-network-opt18/p08.pddl'),
              ('data-network-opt18/domain.pddl',
               'data-network-opt18/p12.pddl'),
              ('data-network-opt18/domain.pddl',
               'data-network-opt18/p04.pddl')]}]
