domains = [
{'description': 'The first of the domains inspired by space-applications is a first step towards the "Ambitious Spacecraft" described by David Smith at AIPS-2000. It involves planning and scheduling a collection of observation tasks between multiple satellites, each equipped in slightly different ways.',
 'ipc': '2011',
 'name': 'satellite',
 'problems': [('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p01.pddl'),
('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p02.pddl'),
('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p03.pddl'),
('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p04.pddl'),
('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p05.pddl'),
('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p06.pddl'),
('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p07.pddl'),
('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p08.pddl'),
('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p09.pddl'),
('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p10.pddl'),
('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p11.pddl'),
('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p12.pddl'),
('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p13.pddl'),
('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p14.pddl'),
('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p15.pddl'),
('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p16.pddl'),
('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p17.pddl'),
('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p18.pddl'),
('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p19.pddl'),
('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p20.pddl'),
('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p21.pddl'),
('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p22.pddl'),
('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p23.pddl'),
('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p24.pddl'),
('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p25.pddl'),
('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p26.pddl'),
('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p27.pddl'),
('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p28.pddl'),
('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p29.pddl'),
('satellite-ipc11-learning-target/domain.pddl', 'satellite-ipc11-learning-target/p30.pddl')]}
]
