(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	satellite2 - satellite
	instrument3 - instrument
	satellite3 - satellite
	instrument4 - instrument
	instrument5 - instrument
	satellite4 - satellite
	instrument6 - instrument
	instrument7 - instrument
	satellite5 - satellite
	instrument8 - instrument
	instrument9 - instrument
	satellite6 - satellite
	instrument10 - instrument
	satellite7 - satellite
	instrument11 - instrument
	satellite8 - satellite
	instrument12 - instrument
	satellite9 - satellite
	instrument13 - instrument
	thermograph1 - mode
	spectrograph2 - mode
	thermograph14 - mode
	image4 - mode
	thermograph6 - mode
	image11 - mode
	image0 - mode
	infrared10 - mode
	infrared13 - mode
	image7 - mode
	thermograph8 - mode
	infrared9 - mode
	spectrograph12 - mode
	thermograph3 - mode
	image5 - mode
	GroundStation0 - direction
	GroundStation1 - direction
	Phenomenon2 - direction
	Phenomenon3 - direction
	Star4 - direction
	Star5 - direction
	Planet6 - direction
	Phenomenon7 - direction
	Star8 - direction
	Planet9 - direction
	Phenomenon10 - direction
	Star11 - direction
	Planet12 - direction
	Star13 - direction
	Planet14 - direction
	Planet15 - direction
	Phenomenon16 - direction
	Star17 - direction
	Phenomenon18 - direction
	Star19 - direction
	Phenomenon20 - direction
	Planet21 - direction
	Phenomenon22 - direction
	Phenomenon23 - direction
	Star24 - direction
	Star25 - direction
	Phenomenon26 - direction
	Planet27 - direction
	Planet28 - direction
	Star29 - direction
	Star30 - direction
	Planet31 - direction
	Phenomenon32 - direction
	Phenomenon33 - direction
	Star34 - direction
	Star35 - direction
	Star36 - direction
	Phenomenon37 - direction
	Phenomenon38 - direction
	Phenomenon39 - direction
	Star40 - direction
	Phenomenon41 - direction
	Star42 - direction
	Star43 - direction
	Star44 - direction
	Phenomenon45 - direction
	Phenomenon46 - direction
	Planet47 - direction
	Phenomenon48 - direction
	Planet49 - direction
	Planet50 - direction
	Phenomenon51 - direction
	Star52 - direction
	Star53 - direction
	Planet54 - direction
	Star55 - direction
	Planet56 - direction
	Phenomenon57 - direction
	Star58 - direction
	Star59 - direction
	Phenomenon60 - direction
	Star61 - direction
	Star62 - direction
	Planet63 - direction
	Planet64 - direction
	Planet65 - direction
	Phenomenon66 - direction
	Planet67 - direction
	Star68 - direction
	Planet69 - direction
	Planet70 - direction
	Phenomenon71 - direction
	Phenomenon72 - direction
	Planet73 - direction
	Star74 - direction
	Star75 - direction
	Planet76 - direction
	Star77 - direction
	Phenomenon78 - direction
	Phenomenon79 - direction
	Planet80 - direction
	Star81 - direction
	Planet82 - direction
	Star83 - direction
	Star84 - direction
	Phenomenon85 - direction
	Phenomenon86 - direction
	Phenomenon87 - direction
	Star88 - direction
	Star89 - direction
	Phenomenon90 - direction
	Planet91 - direction
	Planet92 - direction
	Star93 - direction
	Planet94 - direction
	Star95 - direction
	Star96 - direction
	Planet97 - direction
	Planet98 - direction
	Planet99 - direction
	Planet100 - direction
	Phenomenon101 - direction
	Star102 - direction
	Phenomenon103 - direction
	Phenomenon104 - direction
	Phenomenon105 - direction
	Planet106 - direction
	Phenomenon107 - direction
	Planet108 - direction
	Star109 - direction
	Phenomenon110 - direction
	Star111 - direction
	Planet112 - direction
	Planet113 - direction
	Phenomenon114 - direction
	Star115 - direction
	Star116 - direction
	Star117 - direction
	Star118 - direction
	Star119 - direction
	Planet120 - direction
	Planet121 - direction
	Star122 - direction
	Planet123 - direction
	Planet124 - direction
	Planet125 - direction
	Planet126 - direction
	Planet127 - direction
	Planet128 - direction
	Planet129 - direction
	Planet130 - direction
	Planet131 - direction
)
(:init
	(supports instrument0 image5)
	(supports instrument0 thermograph3)
	(calibration_target instrument0 GroundStation1)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon90)
	(supports instrument1 spectrograph2)
	(supports instrument1 spectrograph12)
	(supports instrument1 thermograph14)
	(calibration_target instrument1 GroundStation1)
	(supports instrument2 image4)
	(supports instrument2 thermograph14)
	(calibration_target instrument2 GroundStation1)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star77)
	(supports instrument3 infrared10)
	(calibration_target instrument3 GroundStation0)
	(on_board instrument3 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star30)
	(supports instrument4 image11)
	(calibration_target instrument4 GroundStation1)
	(supports instrument5 image11)
	(supports instrument5 thermograph6)
	(supports instrument5 image5)
	(calibration_target instrument5 GroundStation0)
	(on_board instrument4 satellite3)
	(on_board instrument5 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet125)
	(supports instrument6 image7)
	(supports instrument6 image5)
	(supports instrument6 image0)
	(calibration_target instrument6 GroundStation1)
	(supports instrument7 image7)
	(supports instrument7 infrared13)
	(supports instrument7 infrared10)
	(calibration_target instrument7 GroundStation0)
	(on_board instrument6 satellite4)
	(on_board instrument7 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon51)
	(supports instrument8 thermograph3)
	(supports instrument8 image5)
	(calibration_target instrument8 GroundStation0)
	(supports instrument9 spectrograph12)
	(supports instrument9 thermograph3)
	(calibration_target instrument9 GroundStation0)
	(on_board instrument8 satellite5)
	(on_board instrument9 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Planet126)
	(supports instrument10 image5)
	(supports instrument10 thermograph8)
	(calibration_target instrument10 GroundStation0)
	(on_board instrument10 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Phenomenon20)
	(supports instrument11 infrared9)
	(supports instrument11 thermograph3)
	(calibration_target instrument11 GroundStation1)
	(on_board instrument11 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Planet28)
	(supports instrument12 thermograph3)
	(supports instrument12 spectrograph12)
	(supports instrument12 image5)
	(calibration_target instrument12 GroundStation0)
	(on_board instrument12 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Phenomenon10)
	(supports instrument13 image5)
	(calibration_target instrument13 GroundStation1)
	(on_board instrument13 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star40)
)
(:goal (and
	(pointing satellite1 Planet76)
	(pointing satellite2 Phenomenon105)
	(pointing satellite3 Star93)
	(pointing satellite6 Planet50)
	(pointing satellite7 Star118)
	(pointing satellite9 Planet99)
	(have_image Phenomenon2 thermograph3)
	(have_image Phenomenon2 infrared10)
	(have_image Phenomenon2 thermograph8)
	(have_image Phenomenon2 spectrograph12)
	(have_image Phenomenon3 thermograph3)
	(have_image Phenomenon3 image5)
	(have_image Star4 image7)
	(have_image Star4 image5)
	(have_image Star4 thermograph8)
	(have_image Star4 image11)
	(have_image Star5 spectrograph2)
	(have_image Planet6 spectrograph2)
	(have_image Planet6 thermograph3)
	(have_image Planet6 infrared9)
	(have_image Planet6 image4)
	(have_image Phenomenon7 infrared10)
	(have_image Phenomenon7 image7)
	(have_image Planet9 thermograph3)
	(have_image Planet9 image11)
	(have_image Planet9 image7)
	(have_image Planet9 thermograph6)
	(have_image Planet9 image4)
	(have_image Phenomenon10 thermograph6)
	(have_image Phenomenon10 infrared10)
	(have_image Phenomenon10 image11)
	(have_image Star11 thermograph3)
	(have_image Star11 infrared13)
	(have_image Star11 thermograph14)
	(have_image Star11 image7)
	(have_image Star11 spectrograph12)
	(have_image Planet12 infrared10)
	(have_image Star13 thermograph14)
	(have_image Star13 thermograph6)
	(have_image Planet14 spectrograph2)
	(have_image Planet14 spectrograph12)
	(have_image Planet15 image7)
	(have_image Planet15 thermograph6)
	(have_image Planet15 spectrograph12)
	(have_image Planet15 image0)
	(have_image Phenomenon16 image4)
	(have_image Phenomenon16 image5)
	(have_image Phenomenon16 spectrograph2)
	(have_image Phenomenon18 thermograph14)
	(have_image Phenomenon18 thermograph8)
	(have_image Phenomenon18 image0)
	(have_image Phenomenon18 image7)
	(have_image Star19 image5)
	(have_image Star19 spectrograph2)
	(have_image Star19 infrared13)
	(have_image Star19 thermograph8)
	(have_image Star19 image11)
	(have_image Phenomenon20 image5)
	(have_image Phenomenon20 image0)
	(have_image Planet21 thermograph3)
	(have_image Phenomenon22 infrared13)
	(have_image Phenomenon23 thermograph3)
	(have_image Phenomenon23 thermograph14)
	(have_image Phenomenon23 spectrograph2)
	(have_image Phenomenon23 infrared10)
	(have_image Phenomenon23 spectrograph12)
	(have_image Star24 spectrograph2)
	(have_image Star24 infrared13)
	(have_image Star24 image4)
	(have_image Phenomenon26 image0)
	(have_image Phenomenon26 spectrograph12)
	(have_image Phenomenon26 thermograph14)
	(have_image Planet27 thermograph8)
	(have_image Planet27 infrared10)
	(have_image Planet27 image5)
	(have_image Planet27 image4)
	(have_image Planet27 infrared9)
	(have_image Planet28 spectrograph12)
	(have_image Planet28 infrared10)
	(have_image Planet28 image11)
	(have_image Star29 infrared13)
	(have_image Star29 thermograph6)
	(have_image Star30 spectrograph2)
	(have_image Star30 image7)
	(have_image Star30 infrared10)
	(have_image Star30 image4)
	(have_image Planet31 spectrograph2)
	(have_image Planet31 infrared9)
	(have_image Planet31 infrared13)
	(have_image Phenomenon32 image5)
	(have_image Phenomenon32 image4)
	(have_image Phenomenon32 image0)
	(have_image Phenomenon32 spectrograph2)
	(have_image Phenomenon32 infrared9)
	(have_image Phenomenon33 thermograph6)
	(have_image Phenomenon33 image7)
	(have_image Phenomenon33 image5)
	(have_image Star34 thermograph3)
	(have_image Star34 thermograph8)
	(have_image Star34 infrared9)
	(have_image Star34 thermograph14)
	(have_image Star35 thermograph3)
	(have_image Star36 thermograph8)
	(have_image Star36 infrared9)
	(have_image Star36 infrared13)
	(have_image Phenomenon37 image7)
	(have_image Phenomenon37 thermograph6)
	(have_image Phenomenon38 thermograph3)
	(have_image Phenomenon38 image0)
	(have_image Phenomenon39 infrared10)
	(have_image Star40 thermograph8)
	(have_image Star40 image11)
	(have_image Star40 image5)
	(have_image Phenomenon41 infrared10)
	(have_image Phenomenon41 thermograph6)
	(have_image Phenomenon41 image7)
	(have_image Star42 thermograph6)
	(have_image Star42 image11)
	(have_image Star43 thermograph14)
	(have_image Star43 spectrograph12)
	(have_image Star43 image4)
	(have_image Phenomenon45 image7)
	(have_image Phenomenon45 infrared9)
	(have_image Phenomenon45 image11)
	(have_image Phenomenon45 infrared13)
	(have_image Phenomenon45 thermograph3)
	(have_image Phenomenon46 image7)
	(have_image Phenomenon46 infrared10)
	(have_image Phenomenon46 image5)
	(have_image Phenomenon46 thermograph3)
	(have_image Planet47 image11)
	(have_image Phenomenon48 image4)
	(have_image Planet49 image5)
	(have_image Planet49 thermograph8)
	(have_image Planet49 thermograph6)
	(have_image Planet49 image7)
	(have_image Planet50 infrared9)
	(have_image Planet50 infrared10)
	(have_image Phenomenon51 thermograph14)
	(have_image Phenomenon51 infrared10)
	(have_image Phenomenon51 image11)
	(have_image Star52 image11)
	(have_image Star53 spectrograph2)
	(have_image Star53 image5)
	(have_image Star53 image0)
	(have_image Star53 thermograph6)
	(have_image Star53 thermograph8)
	(have_image Planet54 image5)
	(have_image Planet54 spectrograph2)
	(have_image Planet54 image7)
	(have_image Planet54 thermograph6)
	(have_image Star55 infrared9)
	(have_image Star55 thermograph8)
	(have_image Star55 infrared13)
	(have_image Planet56 image0)
	(have_image Planet56 spectrograph12)
	(have_image Planet56 infrared10)
	(have_image Planet56 thermograph8)
	(have_image Phenomenon57 thermograph8)
	(have_image Phenomenon57 spectrograph12)
	(have_image Star58 thermograph3)
	(have_image Star58 thermograph8)
	(have_image Star58 image4)
	(have_image Star58 image0)
	(have_image Star59 thermograph14)
	(have_image Phenomenon60 image4)
	(have_image Phenomenon60 thermograph8)
	(have_image Star61 infrared9)
	(have_image Star61 image11)
	(have_image Star61 thermograph14)
	(have_image Star61 infrared13)
	(have_image Star62 infrared9)
	(have_image Star62 image5)
	(have_image Star62 image7)
	(have_image Star62 thermograph8)
	(have_image Star62 spectrograph12)
	(have_image Planet63 thermograph6)
	(have_image Planet63 infrared10)
	(have_image Planet64 image0)
	(have_image Planet64 spectrograph2)
	(have_image Planet65 infrared13)
	(have_image Planet65 image11)
	(have_image Planet65 thermograph8)
	(have_image Phenomenon66 spectrograph2)
	(have_image Phenomenon66 infrared9)
	(have_image Phenomenon66 image11)
	(have_image Planet67 thermograph14)
	(have_image Planet67 image11)
	(have_image Planet67 spectrograph2)
	(have_image Star68 image7)
	(have_image Planet69 infrared9)
	(have_image Planet69 spectrograph12)
	(have_image Planet70 infrared10)
	(have_image Planet70 thermograph3)
	(have_image Phenomenon71 thermograph6)
	(have_image Phenomenon71 spectrograph12)
	(have_image Phenomenon71 image11)
	(have_image Phenomenon71 image0)
	(have_image Phenomenon72 spectrograph12)
	(have_image Planet73 image0)
	(have_image Planet73 image11)
	(have_image Planet73 thermograph3)
	(have_image Star74 image11)
	(have_image Star74 thermograph14)
	(have_image Star74 image7)
	(have_image Star74 image0)
	(have_image Planet76 image11)
	(have_image Planet76 image7)
	(have_image Star77 spectrograph2)
	(have_image Star77 infrared9)
	(have_image Star77 thermograph6)
	(have_image Phenomenon78 image11)
	(have_image Phenomenon79 infrared10)
	(have_image Phenomenon79 thermograph8)
	(have_image Phenomenon79 thermograph14)
	(have_image Phenomenon79 image7)
	(have_image Phenomenon79 spectrograph12)
	(have_image Planet80 thermograph8)
	(have_image Planet80 infrared13)
	(have_image Star81 thermograph3)
	(have_image Planet82 image4)
	(have_image Planet82 image7)
	(have_image Star83 infrared10)
	(have_image Star83 image7)
	(have_image Star84 thermograph6)
	(have_image Star84 thermograph14)
	(have_image Star84 spectrograph12)
	(have_image Phenomenon85 spectrograph12)
	(have_image Phenomenon85 infrared10)
	(have_image Phenomenon86 image4)
	(have_image Phenomenon86 thermograph3)
	(have_image Phenomenon86 infrared9)
	(have_image Phenomenon87 spectrograph12)
	(have_image Star88 thermograph6)
	(have_image Star88 infrared13)
	(have_image Star88 infrared10)
	(have_image Star88 spectrograph12)
	(have_image Star89 thermograph8)
	(have_image Star89 infrared13)
	(have_image Star89 image5)
	(have_image Star89 thermograph14)
	(have_image Phenomenon90 thermograph8)
	(have_image Planet92 thermograph14)
	(have_image Planet92 image7)
	(have_image Planet92 image5)
	(have_image Planet94 spectrograph2)
	(have_image Planet94 infrared10)
	(have_image Planet94 thermograph8)
	(have_image Star95 image0)
	(have_image Star95 thermograph8)
	(have_image Star96 thermograph3)
	(have_image Planet97 infrared9)
	(have_image Planet99 thermograph3)
	(have_image Star102 image5)
	(have_image Star102 image4)
	(have_image Star102 image0)
	(have_image Star102 infrared13)
	(have_image Phenomenon104 spectrograph2)
	(have_image Phenomenon104 infrared10)
	(have_image Phenomenon104 infrared9)
	(have_image Phenomenon104 image0)
	(have_image Phenomenon104 thermograph14)
	(have_image Phenomenon105 infrared9)
	(have_image Phenomenon105 spectrograph12)
	(have_image Phenomenon105 thermograph14)
	(have_image Phenomenon107 image4)
	(have_image Phenomenon107 thermograph6)
	(have_image Phenomenon107 thermograph3)
	(have_image Planet108 infrared13)
	(have_image Planet108 image7)
	(have_image Planet108 thermograph6)
	(have_image Star109 infrared13)
	(have_image Star109 thermograph6)
	(have_image Star109 spectrograph12)
	(have_image Phenomenon110 thermograph6)
	(have_image Phenomenon110 image11)
	(have_image Phenomenon110 thermograph3)
	(have_image Star111 thermograph6)
	(have_image Star111 thermograph8)
	(have_image Planet112 spectrograph2)
	(have_image Planet112 image0)
	(have_image Planet113 spectrograph2)
	(have_image Planet113 image11)
	(have_image Planet113 spectrograph12)
	(have_image Planet113 thermograph3)
	(have_image Phenomenon114 infrared9)
	(have_image Phenomenon114 spectrograph12)
	(have_image Phenomenon114 thermograph6)
	(have_image Phenomenon114 thermograph3)
	(have_image Star115 image0)
	(have_image Star115 thermograph6)
	(have_image Star115 image5)
	(have_image Star115 spectrograph12)
	(have_image Star116 infrared10)
	(have_image Star116 spectrograph2)
	(have_image Star117 spectrograph12)
	(have_image Star117 image11)
	(have_image Star117 infrared9)
	(have_image Star117 thermograph3)
	(have_image Star119 thermograph14)
	(have_image Star119 infrared9)
	(have_image Planet121 spectrograph12)
	(have_image Star122 thermograph8)
	(have_image Star122 thermograph6)
	(have_image Star122 infrared13)
	(have_image Planet123 image0)
	(have_image Planet123 spectrograph2)
	(have_image Planet124 image11)
	(have_image Planet124 image5)
	(have_image Planet124 spectrograph12)
	(have_image Planet124 thermograph8)
	(have_image Planet125 image11)
	(have_image Planet125 infrared9)
	(have_image Planet125 image7)
	(have_image Planet125 infrared10)
	(have_image Planet126 spectrograph12)
	(have_image Planet126 image4)
	(have_image Planet126 image7)
	(have_image Planet126 infrared9)
	(have_image Planet126 image0)
	(have_image Planet128 infrared10)
	(have_image Planet129 spectrograph12)
	(have_image Planet130 image7)
	(have_image Planet130 infrared13)
	(have_image Planet131 image4)
	(have_image Planet131 thermograph6)
	(have_image Planet131 infrared10)
	(have_image Planet131 thermograph3)
))

)
