(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	satellite2 - satellite
	instrument2 - instrument
	satellite3 - satellite
	instrument3 - instrument
	satellite4 - satellite
	instrument4 - instrument
	satellite5 - satellite
	instrument5 - instrument
	satellite6 - satellite
	instrument6 - instrument
	satellite7 - satellite
	instrument7 - instrument
	instrument8 - instrument
	satellite8 - satellite
	instrument9 - instrument
	satellite9 - satellite
	instrument10 - instrument
	thermograph4 - mode
	image6 - mode
	infrared14 - mode
	infrared9 - mode
	infrared11 - mode
	infrared13 - mode
	spectrograph1 - mode
	image10 - mode
	infrared7 - mode
	thermograph2 - mode
	thermograph3 - mode
	spectrograph0 - mode
	spectrograph5 - mode
	infrared12 - mode
	image8 - mode
	GroundStation1 - direction
	Star0 - direction
	Planet2 - direction
	Star3 - direction
	Star4 - direction
	Phenomenon5 - direction
	Phenomenon6 - direction
	Phenomenon7 - direction
	Planet8 - direction
	Phenomenon9 - direction
	Star10 - direction
	Planet11 - direction
	Phenomenon12 - direction
	Phenomenon13 - direction
	Phenomenon14 - direction
	Star15 - direction
	Planet16 - direction
	Phenomenon17 - direction
	Star18 - direction
	Phenomenon19 - direction
	Phenomenon20 - direction
	Star21 - direction
	Star22 - direction
	Phenomenon23 - direction
	Star24 - direction
	Phenomenon25 - direction
	Star26 - direction
	Planet27 - direction
	Planet28 - direction
	Star29 - direction
	Planet30 - direction
	Planet31 - direction
	Planet32 - direction
	Star33 - direction
	Star34 - direction
	Phenomenon35 - direction
	Star36 - direction
	Planet37 - direction
	Star38 - direction
	Star39 - direction
	Star40 - direction
	Planet41 - direction
	Phenomenon42 - direction
	Planet43 - direction
	Star44 - direction
	Planet45 - direction
	Planet46 - direction
	Star47 - direction
	Star48 - direction
	Phenomenon49 - direction
	Planet50 - direction
	Star51 - direction
	Planet52 - direction
	Planet53 - direction
	Planet54 - direction
	Star55 - direction
	Planet56 - direction
	Planet57 - direction
	Phenomenon58 - direction
	Phenomenon59 - direction
	Planet60 - direction
	Phenomenon61 - direction
	Star62 - direction
	Star63 - direction
	Star64 - direction
	Star65 - direction
	Planet66 - direction
	Planet67 - direction
	Planet68 - direction
	Planet69 - direction
	Phenomenon70 - direction
	Planet71 - direction
	Phenomenon72 - direction
	Star73 - direction
	Star74 - direction
	Phenomenon75 - direction
	Phenomenon76 - direction
	Phenomenon77 - direction
	Planet78 - direction
	Phenomenon79 - direction
	Phenomenon80 - direction
	Planet81 - direction
	Phenomenon82 - direction
	Star83 - direction
	Planet84 - direction
	Phenomenon85 - direction
	Phenomenon86 - direction
	Planet87 - direction
	Planet88 - direction
	Phenomenon89 - direction
	Star90 - direction
	Planet91 - direction
	Planet92 - direction
	Phenomenon93 - direction
	Star94 - direction
	Phenomenon95 - direction
	Planet96 - direction
	Star97 - direction
	Phenomenon98 - direction
	Star99 - direction
	Phenomenon100 - direction
	Star101 - direction
	Phenomenon102 - direction
	Planet103 - direction
	Phenomenon104 - direction
	Phenomenon105 - direction
	Planet106 - direction
	Star107 - direction
	Star108 - direction
	Planet109 - direction
	Phenomenon110 - direction
	Star111 - direction
	Phenomenon112 - direction
	Phenomenon113 - direction
	Planet114 - direction
	Planet115 - direction
	Star116 - direction
	Planet117 - direction
	Planet118 - direction
	Phenomenon119 - direction
	Star120 - direction
	Star121 - direction
	Planet122 - direction
	Planet123 - direction
	Star124 - direction
	Phenomenon125 - direction
	Star126 - direction
	Star127 - direction
	Star128 - direction
	Star129 - direction
	Planet130 - direction
	Star131 - direction
)
(:init
	(supports instrument0 spectrograph5)
	(calibration_target instrument0 Star0)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet30)
	(supports instrument1 image8)
	(supports instrument1 image10)
	(calibration_target instrument1 GroundStation1)
	(on_board instrument1 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star121)
	(supports instrument2 infrared13)
	(supports instrument2 image8)
	(supports instrument2 spectrograph0)
	(calibration_target instrument2 Star0)
	(on_board instrument2 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon119)
	(supports instrument3 spectrograph1)
	(supports instrument3 thermograph3)
	(calibration_target instrument3 Star0)
	(on_board instrument3 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet115)
	(supports instrument4 spectrograph5)
	(calibration_target instrument4 Star0)
	(on_board instrument4 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet130)
	(supports instrument5 image10)
	(supports instrument5 infrared7)
	(calibration_target instrument5 Star0)
	(on_board instrument5 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Planet78)
	(supports instrument6 infrared12)
	(calibration_target instrument6 Star0)
	(on_board instrument6 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet41)
	(supports instrument7 thermograph2)
	(supports instrument7 infrared7)
	(calibration_target instrument7 GroundStation1)
	(supports instrument8 spectrograph5)
	(supports instrument8 spectrograph0)
	(supports instrument8 thermograph3)
	(calibration_target instrument8 Star0)
	(on_board instrument7 satellite7)
	(on_board instrument8 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation1)
	(supports instrument9 infrared12)
	(calibration_target instrument9 GroundStation1)
	(on_board instrument9 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Phenomenon13)
	(supports instrument10 image8)
	(calibration_target instrument10 Star0)
	(on_board instrument10 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Planet28)
)
(:goal (and
	(pointing satellite0 Planet81)
	(pointing satellite6 Star111)
	(pointing satellite8 Star29)
	(pointing satellite9 Star73)
	(have_image Planet2 thermograph3)
	(have_image Planet2 image8)
	(have_image Planet2 image10)
	(have_image Star3 thermograph3)
	(have_image Star3 spectrograph5)
	(have_image Star3 infrared13)
	(have_image Star3 thermograph2)
	(have_image Phenomenon6 infrared7)
	(have_image Phenomenon6 infrared13)
	(have_image Phenomenon6 spectrograph1)
	(have_image Phenomenon7 spectrograph5)
	(have_image Phenomenon7 spectrograph1)
	(have_image Phenomenon7 spectrograph0)
	(have_image Planet8 thermograph2)
	(have_image Planet8 spectrograph0)
	(have_image Phenomenon9 infrared12)
	(have_image Phenomenon9 infrared7)
	(have_image Phenomenon9 infrared13)
	(have_image Phenomenon9 spectrograph5)
	(have_image Star10 spectrograph0)
	(have_image Star10 thermograph2)
	(have_image Star10 image10)
	(have_image Star10 thermograph3)
	(have_image Star10 infrared13)
	(have_image Planet11 infrared13)
	(have_image Planet11 spectrograph0)
	(have_image Planet11 image8)
	(have_image Phenomenon12 infrared13)
	(have_image Phenomenon12 spectrograph0)
	(have_image Phenomenon12 spectrograph1)
	(have_image Phenomenon13 image8)
	(have_image Phenomenon13 image10)
	(have_image Phenomenon14 image8)
	(have_image Star15 image10)
	(have_image Star15 spectrograph0)
	(have_image Planet16 thermograph3)
	(have_image Planet16 spectrograph1)
	(have_image Planet16 thermograph2)
	(have_image Phenomenon17 thermograph2)
	(have_image Phenomenon17 infrared13)
	(have_image Phenomenon17 thermograph3)
	(have_image Star18 spectrograph1)
	(have_image Star18 thermograph3)
	(have_image Phenomenon19 spectrograph1)
	(have_image Phenomenon19 image8)
	(have_image Star21 infrared12)
	(have_image Star22 spectrograph0)
	(have_image Star22 infrared12)
	(have_image Phenomenon23 infrared12)
	(have_image Phenomenon23 infrared13)
	(have_image Star24 infrared7)
	(have_image Phenomenon25 infrared7)
	(have_image Star26 thermograph3)
	(have_image Planet27 spectrograph0)
	(have_image Planet27 spectrograph5)
	(have_image Planet28 thermograph3)
	(have_image Planet28 image8)
	(have_image Star29 infrared12)
	(have_image Star29 infrared13)
	(have_image Planet30 image10)
	(have_image Planet30 thermograph2)
	(have_image Planet31 thermograph2)
	(have_image Planet31 spectrograph5)
	(have_image Planet31 spectrograph1)
	(have_image Planet32 image10)
	(have_image Planet32 spectrograph1)
	(have_image Planet32 spectrograph5)
	(have_image Star33 infrared13)
	(have_image Star33 infrared12)
	(have_image Star34 spectrograph0)
	(have_image Star34 infrared12)
	(have_image Star38 infrared13)
	(have_image Star38 spectrograph0)
	(have_image Star39 spectrograph0)
	(have_image Star40 spectrograph1)
	(have_image Star40 image10)
	(have_image Star40 spectrograph0)
	(have_image Phenomenon42 spectrograph5)
	(have_image Phenomenon42 infrared12)
	(have_image Phenomenon42 image8)
	(have_image Planet43 spectrograph1)
	(have_image Planet43 infrared7)
	(have_image Planet43 thermograph3)
	(have_image Planet43 thermograph2)
	(have_image Planet46 infrared7)
	(have_image Planet46 image8)
	(have_image Planet46 thermograph2)
	(have_image Star47 spectrograph1)
	(have_image Star47 image10)
	(have_image Star47 infrared13)
	(have_image Star47 infrared7)
	(have_image Planet50 spectrograph0)
	(have_image Star51 image10)
	(have_image Planet52 image10)
	(have_image Planet52 thermograph2)
	(have_image Planet53 infrared13)
	(have_image Planet53 infrared7)
	(have_image Planet53 thermograph2)
	(have_image Planet54 infrared12)
	(have_image Planet54 image8)
	(have_image Planet56 infrared13)
	(have_image Planet57 image10)
	(have_image Phenomenon58 image10)
	(have_image Phenomenon59 thermograph2)
	(have_image Phenomenon59 infrared12)
	(have_image Phenomenon59 spectrograph0)
	(have_image Phenomenon59 infrared7)
	(have_image Planet60 spectrograph5)
	(have_image Phenomenon61 infrared7)
	(have_image Phenomenon61 image8)
	(have_image Phenomenon61 spectrograph1)
	(have_image Star63 image10)
	(have_image Star63 infrared13)
	(have_image Star64 thermograph3)
	(have_image Star64 infrared12)
	(have_image Star65 spectrograph1)
	(have_image Star65 infrared13)
	(have_image Star65 thermograph2)
	(have_image Planet66 spectrograph0)
	(have_image Planet66 thermograph3)
	(have_image Planet67 spectrograph0)
	(have_image Planet67 image8)
	(have_image Planet67 infrared12)
	(have_image Planet68 thermograph2)
	(have_image Planet69 image8)
	(have_image Planet69 thermograph3)
	(have_image Planet69 thermograph2)
	(have_image Planet71 infrared7)
	(have_image Planet71 image8)
	(have_image Phenomenon72 image10)
	(have_image Phenomenon72 thermograph3)
	(have_image Star73 spectrograph0)
	(have_image Phenomenon75 image8)
	(have_image Phenomenon75 spectrograph5)
	(have_image Phenomenon77 infrared13)
	(have_image Phenomenon77 thermograph3)
	(have_image Planet78 spectrograph1)
	(have_image Planet78 image8)
	(have_image Phenomenon79 image10)
	(have_image Phenomenon80 thermograph3)
	(have_image Phenomenon80 image10)
	(have_image Phenomenon80 spectrograph5)
	(have_image Planet81 spectrograph1)
	(have_image Phenomenon82 spectrograph1)
	(have_image Phenomenon82 infrared7)
	(have_image Phenomenon82 thermograph3)
	(have_image Star83 thermograph2)
	(have_image Planet84 infrared7)
	(have_image Planet84 infrared13)
	(have_image Phenomenon85 thermograph3)
	(have_image Phenomenon85 thermograph2)
	(have_image Phenomenon86 image8)
	(have_image Phenomenon86 infrared12)
	(have_image Planet87 infrared13)
	(have_image Planet87 thermograph3)
	(have_image Phenomenon89 infrared12)
	(have_image Phenomenon89 spectrograph0)
	(have_image Planet91 infrared7)
	(have_image Planet91 spectrograph5)
	(have_image Phenomenon93 infrared7)
	(have_image Star94 infrared13)
	(have_image Star94 thermograph3)
	(have_image Planet96 thermograph3)
	(have_image Planet96 infrared7)
	(have_image Planet96 spectrograph5)
	(have_image Star97 thermograph3)
	(have_image Star97 image10)
	(have_image Star97 image8)
	(have_image Star99 image10)
	(have_image Star99 spectrograph5)
	(have_image Star99 spectrograph1)
	(have_image Phenomenon100 infrared13)
	(have_image Star101 spectrograph1)
	(have_image Phenomenon102 infrared12)
	(have_image Planet103 image10)
	(have_image Planet103 spectrograph5)
	(have_image Planet103 thermograph2)
	(have_image Planet103 image8)
	(have_image Phenomenon104 thermograph3)
	(have_image Phenomenon105 thermograph2)
	(have_image Phenomenon105 image8)
	(have_image Phenomenon105 spectrograph0)
	(have_image Planet106 infrared13)
	(have_image Planet106 thermograph2)
	(have_image Star108 spectrograph1)
	(have_image Star108 thermograph3)
	(have_image Star108 infrared7)
	(have_image Phenomenon110 spectrograph1)
	(have_image Star111 spectrograph5)
	(have_image Phenomenon112 infrared7)
	(have_image Phenomenon112 thermograph2)
	(have_image Phenomenon112 thermograph3)
	(have_image Phenomenon112 spectrograph0)
	(have_image Phenomenon113 image10)
	(have_image Phenomenon113 infrared12)
	(have_image Planet114 image8)
	(have_image Planet114 spectrograph1)
	(have_image Planet115 spectrograph5)
	(have_image Planet115 infrared13)
	(have_image Star116 image8)
	(have_image Planet117 infrared13)
	(have_image Planet117 image10)
	(have_image Planet118 infrared7)
	(have_image Planet118 infrared12)
	(have_image Planet118 image10)
	(have_image Phenomenon119 thermograph2)
	(have_image Star120 thermograph3)
	(have_image Star121 infrared7)
	(have_image Star121 thermograph2)
	(have_image Star121 infrared13)
	(have_image Planet122 spectrograph1)
	(have_image Phenomenon125 thermograph3)
	(have_image Star126 infrared13)
	(have_image Star126 image8)
	(have_image Star126 thermograph3)
	(have_image Star126 infrared12)
	(have_image Star127 image8)
	(have_image Star128 image10)
	(have_image Star128 image8)
	(have_image Star128 spectrograph1)
	(have_image Star128 spectrograph0)
	(have_image Star129 image10)
	(have_image Star129 thermograph3)
	(have_image Star129 spectrograph5)
	(have_image Planet130 image8)
	(have_image Star131 spectrograph0)
	(have_image Star131 infrared7)
))

)
