(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	satellite2 - satellite
	instrument3 - instrument
	instrument4 - instrument
	satellite3 - satellite
	instrument5 - instrument
	satellite4 - satellite
	instrument6 - instrument
	instrument7 - instrument
	satellite5 - satellite
	instrument8 - instrument
	instrument9 - instrument
	satellite6 - satellite
	instrument10 - instrument
	satellite7 - satellite
	instrument11 - instrument
	satellite8 - satellite
	instrument12 - instrument
	instrument13 - instrument
	satellite9 - satellite
	instrument14 - instrument
	instrument15 - instrument
	infrared12 - mode
	spectrograph7 - mode
	thermograph4 - mode
	infrared5 - mode
	spectrograph8 - mode
	infrared6 - mode
	image14 - mode
	image2 - mode
	infrared13 - mode
	infrared3 - mode
	infrared10 - mode
	infrared9 - mode
	image0 - mode
	image1 - mode
	image11 - mode
	GroundStation1 - direction
	Star0 - direction
	Phenomenon2 - direction
	Phenomenon3 - direction
	Star4 - direction
	Planet5 - direction
	Phenomenon6 - direction
	Phenomenon7 - direction
	Planet8 - direction
	Planet9 - direction
	Planet10 - direction
	Phenomenon11 - direction
	Planet12 - direction
	Phenomenon13 - direction
	Star14 - direction
	Star15 - direction
	Star16 - direction
	Planet17 - direction
	Phenomenon18 - direction
	Planet19 - direction
	Planet20 - direction
	Planet21 - direction
	Planet22 - direction
	Star23 - direction
	Planet24 - direction
	Star25 - direction
	Star26 - direction
	Star27 - direction
	Phenomenon28 - direction
	Planet29 - direction
	Star30 - direction
	Phenomenon31 - direction
	Star32 - direction
	Star33 - direction
	Star34 - direction
	Star35 - direction
	Planet36 - direction
	Phenomenon37 - direction
	Planet38 - direction
	Star39 - direction
	Planet40 - direction
	Star41 - direction
	Planet42 - direction
	Star43 - direction
	Planet44 - direction
	Star45 - direction
	Phenomenon46 - direction
	Phenomenon47 - direction
	Planet48 - direction
	Star49 - direction
	Star50 - direction
	Planet51 - direction
	Planet52 - direction
	Planet53 - direction
	Star54 - direction
	Planet55 - direction
	Star56 - direction
	Planet57 - direction
	Star58 - direction
	Phenomenon59 - direction
	Phenomenon60 - direction
	Star61 - direction
	Phenomenon62 - direction
	Star63 - direction
	Planet64 - direction
	Planet65 - direction
	Planet66 - direction
	Star67 - direction
	Planet68 - direction
	Planet69 - direction
	Star70 - direction
	Phenomenon71 - direction
	Star72 - direction
	Phenomenon73 - direction
	Planet74 - direction
	Phenomenon75 - direction
	Star76 - direction
	Planet77 - direction
	Phenomenon78 - direction
	Planet79 - direction
	Phenomenon80 - direction
	Star81 - direction
	Star82 - direction
	Planet83 - direction
	Phenomenon84 - direction
	Phenomenon85 - direction
	Planet86 - direction
	Star87 - direction
	Star88 - direction
	Planet89 - direction
	Star90 - direction
	Planet91 - direction
	Phenomenon92 - direction
	Planet93 - direction
	Planet94 - direction
	Phenomenon95 - direction
	Phenomenon96 - direction
	Phenomenon97 - direction
	Phenomenon98 - direction
	Star99 - direction
	Planet100 - direction
	Phenomenon101 - direction
	Planet102 - direction
	Star103 - direction
	Star104 - direction
	Phenomenon105 - direction
	Star106 - direction
	Planet107 - direction
	Star108 - direction
	Phenomenon109 - direction
	Phenomenon110 - direction
	Planet111 - direction
	Planet112 - direction
	Planet113 - direction
	Planet114 - direction
	Phenomenon115 - direction
	Star116 - direction
	Phenomenon117 - direction
	Star118 - direction
	Phenomenon119 - direction
	Planet120 - direction
	Star121 - direction
	Star122 - direction
	Planet123 - direction
	Phenomenon124 - direction
	Star125 - direction
	Planet126 - direction
	Phenomenon127 - direction
	Phenomenon128 - direction
	Phenomenon129 - direction
	Planet130 - direction
	Phenomenon131 - direction
)
(:init
	(supports instrument0 infrared13)
	(supports instrument0 image11)
	(calibration_target instrument0 GroundStation1)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet86)
	(supports instrument1 image2)
	(supports instrument1 infrared13)
	(supports instrument1 spectrograph8)
	(calibration_target instrument1 Star0)
	(supports instrument2 infrared6)
	(supports instrument2 infrared10)
	(supports instrument2 thermograph4)
	(calibration_target instrument2 GroundStation1)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Planet83)
	(supports instrument3 thermograph4)
	(calibration_target instrument3 Star0)
	(supports instrument4 infrared10)
	(supports instrument4 infrared5)
	(supports instrument4 image14)
	(calibration_target instrument4 Star0)
	(on_board instrument3 satellite2)
	(on_board instrument4 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star0)
	(supports instrument5 image14)
	(supports instrument5 image0)
	(supports instrument5 image1)
	(calibration_target instrument5 GroundStation1)
	(on_board instrument5 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star87)
	(supports instrument6 infrared9)
	(calibration_target instrument6 GroundStation1)
	(supports instrument7 infrared13)
	(calibration_target instrument7 Star0)
	(on_board instrument6 satellite4)
	(on_board instrument7 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star61)
	(supports instrument8 infrared5)
	(calibration_target instrument8 GroundStation1)
	(supports instrument9 infrared6)
	(supports instrument9 spectrograph8)
	(calibration_target instrument9 Star0)
	(on_board instrument8 satellite5)
	(on_board instrument9 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star104)
	(supports instrument10 image2)
	(supports instrument10 image14)
	(calibration_target instrument10 GroundStation1)
	(on_board instrument10 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star34)
	(supports instrument11 infrared9)
	(supports instrument11 infrared13)
	(calibration_target instrument11 Star0)
	(on_board instrument11 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star30)
	(supports instrument12 image0)
	(supports instrument12 infrared3)
	(calibration_target instrument12 Star0)
	(supports instrument13 infrared10)
	(supports instrument13 infrared9)
	(supports instrument13 image1)
	(calibration_target instrument13 Star0)
	(on_board instrument12 satellite8)
	(on_board instrument13 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Planet44)
	(supports instrument14 image0)
	(supports instrument14 infrared9)
	(calibration_target instrument14 Star0)
	(supports instrument15 image11)
	(supports instrument15 image1)
	(calibration_target instrument15 Star0)
	(on_board instrument14 satellite9)
	(on_board instrument15 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Planet57)
)
(:goal (and
	(pointing satellite3 Star81)
	(pointing satellite4 Planet120)
	(pointing satellite5 Star70)
	(pointing satellite7 Planet74)
	(have_image Phenomenon2 infrared9)
	(have_image Phenomenon2 image11)
	(have_image Phenomenon2 image1)
	(have_image Phenomenon2 infrared3)
	(have_image Star4 infrared6)
	(have_image Star4 image14)
	(have_image Planet5 infrared10)
	(have_image Planet5 infrared9)
	(have_image Planet5 image2)
	(have_image Planet5 infrared6)
	(have_image Phenomenon7 image2)
	(have_image Phenomenon7 thermograph4)
	(have_image Phenomenon7 image11)
	(have_image Phenomenon7 image0)
	(have_image Phenomenon7 image1)
	(have_image Planet9 infrared10)
	(have_image Planet10 infrared3)
	(have_image Planet10 image0)
	(have_image Phenomenon11 image11)
	(have_image Phenomenon11 infrared9)
	(have_image Phenomenon11 image0)
	(have_image Phenomenon11 infrared5)
	(have_image Planet12 image1)
	(have_image Planet12 infrared6)
	(have_image Planet12 infrared3)
	(have_image Phenomenon13 infrared9)
	(have_image Phenomenon13 thermograph4)
	(have_image Phenomenon13 spectrograph8)
	(have_image Star14 image0)
	(have_image Star15 infrared5)
	(have_image Star16 image1)
	(have_image Star16 infrared13)
	(have_image Star16 infrared3)
	(have_image Planet17 infrared5)
	(have_image Planet17 infrared9)
	(have_image Planet17 image2)
	(have_image Phenomenon18 image2)
	(have_image Phenomenon18 image1)
	(have_image Phenomenon18 infrared5)
	(have_image Planet19 infrared10)
	(have_image Planet20 thermograph4)
	(have_image Planet20 infrared3)
	(have_image Planet20 spectrograph8)
	(have_image Planet20 infrared5)
	(have_image Planet20 infrared9)
	(have_image Planet21 image14)
	(have_image Planet21 image11)
	(have_image Planet21 thermograph4)
	(have_image Planet21 infrared5)
	(have_image Star23 infrared10)
	(have_image Star23 image14)
	(have_image Planet24 image2)
	(have_image Planet24 infrared9)
	(have_image Planet24 infrared10)
	(have_image Planet24 image14)
	(have_image Star25 infrared13)
	(have_image Star25 image0)
	(have_image Star25 spectrograph8)
	(have_image Star25 infrared10)
	(have_image Star26 image1)
	(have_image Phenomenon28 infrared13)
	(have_image Planet29 image11)
	(have_image Star30 infrared13)
	(have_image Star30 image0)
	(have_image Phenomenon31 image2)
	(have_image Star32 thermograph4)
	(have_image Star32 image11)
	(have_image Star32 infrared6)
	(have_image Star34 image1)
	(have_image Star34 spectrograph8)
	(have_image Star35 infrared3)
	(have_image Star35 image1)
	(have_image Planet36 infrared13)
	(have_image Phenomenon37 spectrograph8)
	(have_image Phenomenon37 image11)
	(have_image Phenomenon37 infrared6)
	(have_image Planet38 image2)
	(have_image Planet38 infrared5)
	(have_image Star39 image2)
	(have_image Star39 thermograph4)
	(have_image Planet40 infrared9)
	(have_image Planet40 infrared3)
	(have_image Star41 image0)
	(have_image Planet42 image1)
	(have_image Star43 infrared10)
	(have_image Star43 infrared5)
	(have_image Planet44 spectrograph8)
	(have_image Planet44 infrared5)
	(have_image Planet44 infrared3)
	(have_image Planet44 infrared6)
	(have_image Planet44 image1)
	(have_image Star45 image11)
	(have_image Star45 image2)
	(have_image Star45 infrared10)
	(have_image Phenomenon47 image2)
	(have_image Phenomenon47 infrared3)
	(have_image Phenomenon47 infrared9)
	(have_image Planet48 image2)
	(have_image Star49 infrared3)
	(have_image Star49 image2)
	(have_image Star50 infrared10)
	(have_image Star50 image0)
	(have_image Star50 infrared9)
	(have_image Planet52 infrared10)
	(have_image Planet52 infrared13)
	(have_image Planet52 infrared3)
	(have_image Planet53 image14)
	(have_image Planet53 image0)
	(have_image Star56 infrared5)
	(have_image Star56 image1)
	(have_image Star56 infrared13)
	(have_image Star56 thermograph4)
	(have_image Star56 image0)
	(have_image Planet57 infrared9)
	(have_image Planet57 image2)
	(have_image Planet57 image11)
	(have_image Star58 infrared6)
	(have_image Star58 image11)
	(have_image Star58 image14)
	(have_image Phenomenon59 image11)
	(have_image Phenomenon59 infrared13)
	(have_image Phenomenon59 spectrograph8)
	(have_image Phenomenon59 image1)
	(have_image Phenomenon60 image14)
	(have_image Phenomenon60 infrared5)
	(have_image Phenomenon60 image1)
	(have_image Star61 infrared6)
	(have_image Star61 image0)
	(have_image Star61 infrared9)
	(have_image Phenomenon62 image11)
	(have_image Star63 image14)
	(have_image Star63 infrared10)
	(have_image Star63 spectrograph8)
	(have_image Star63 image1)
	(have_image Planet64 infrared5)
	(have_image Planet64 infrared13)
	(have_image Planet65 image1)
	(have_image Planet65 infrared9)
	(have_image Planet66 infrared10)
	(have_image Planet69 image1)
	(have_image Planet69 infrared5)
	(have_image Planet69 image14)
	(have_image Planet69 spectrograph8)
	(have_image Planet69 image11)
	(have_image Star70 infrared3)
	(have_image Star70 infrared5)
	(have_image Star70 infrared13)
	(have_image Phenomenon71 infrared3)
	(have_image Phenomenon71 image0)
	(have_image Phenomenon71 image11)
	(have_image Star72 infrared13)
	(have_image Star72 image2)
	(have_image Star72 infrared6)
	(have_image Star72 infrared5)
	(have_image Phenomenon73 infrared5)
	(have_image Star76 infrared5)
	(have_image Star76 spectrograph8)
	(have_image Star76 infrared6)
	(have_image Planet77 image1)
	(have_image Planet77 image14)
	(have_image Phenomenon78 infrared3)
	(have_image Phenomenon78 image11)
	(have_image Phenomenon78 image1)
	(have_image Phenomenon78 infrared6)
	(have_image Planet79 infrared3)
	(have_image Planet79 image2)
	(have_image Planet79 image1)
	(have_image Planet79 infrared6)
	(have_image Phenomenon80 thermograph4)
	(have_image Star81 infrared13)
	(have_image Star81 infrared6)
	(have_image Star81 image11)
	(have_image Star81 image2)
	(have_image Star82 image1)
	(have_image Star82 image14)
	(have_image Star82 thermograph4)
	(have_image Planet83 infrared9)
	(have_image Phenomenon84 infrared10)
	(have_image Phenomenon84 spectrograph8)
	(have_image Phenomenon84 image2)
	(have_image Phenomenon84 thermograph4)
	(have_image Phenomenon84 infrared13)
	(have_image Planet86 image0)
	(have_image Planet86 infrared10)
	(have_image Planet86 image2)
	(have_image Planet86 infrared6)
	(have_image Star87 infrared6)
	(have_image Star88 image2)
	(have_image Star88 infrared6)
	(have_image Star88 thermograph4)
	(have_image Star88 image1)
	(have_image Planet89 image11)
	(have_image Planet89 infrared3)
	(have_image Planet89 image1)
	(have_image Star90 thermograph4)
	(have_image Star90 infrared3)
	(have_image Star90 image1)
	(have_image Star90 infrared9)
	(have_image Planet91 infrared3)
	(have_image Planet91 infrared5)
	(have_image Planet91 infrared10)
	(have_image Phenomenon92 infrared10)
	(have_image Phenomenon92 infrared13)
	(have_image Phenomenon92 thermograph4)
	(have_image Planet93 infrared9)
	(have_image Planet93 infrared5)
	(have_image Planet93 spectrograph8)
	(have_image Planet94 image2)
	(have_image Planet94 image14)
	(have_image Planet94 infrared9)
	(have_image Planet94 spectrograph8)
	(have_image Phenomenon95 infrared5)
	(have_image Phenomenon96 thermograph4)
	(have_image Phenomenon96 infrared3)
	(have_image Phenomenon96 image1)
	(have_image Phenomenon97 image11)
	(have_image Phenomenon97 infrared13)
	(have_image Phenomenon97 image1)
	(have_image Phenomenon97 image14)
	(have_image Phenomenon97 infrared5)
	(have_image Phenomenon98 infrared10)
	(have_image Star99 image0)
	(have_image Star99 infrared10)
	(have_image Planet100 image14)
	(have_image Planet100 spectrograph8)
	(have_image Phenomenon101 infrared13)
	(have_image Phenomenon101 infrared9)
	(have_image Phenomenon101 image11)
	(have_image Phenomenon101 spectrograph8)
	(have_image Planet102 infrared6)
	(have_image Planet102 infrared5)
	(have_image Planet102 image14)
	(have_image Star103 infrared10)
	(have_image Star103 image2)
	(have_image Star103 infrared5)
	(have_image Star104 image1)
	(have_image Star104 spectrograph8)
	(have_image Star104 infrared3)
	(have_image Star104 image0)
	(have_image Phenomenon105 image11)
	(have_image Star106 infrared3)
	(have_image Planet107 infrared5)
	(have_image Planet107 image0)
	(have_image Planet107 image11)
	(have_image Planet107 infrared3)
	(have_image Star108 image0)
	(have_image Star108 infrared5)
	(have_image Star108 spectrograph8)
	(have_image Star108 image11)
	(have_image Phenomenon109 infrared5)
	(have_image Phenomenon109 spectrograph8)
	(have_image Phenomenon109 infrared9)
	(have_image Phenomenon109 infrared10)
	(have_image Phenomenon109 image11)
	(have_image Phenomenon110 infrared13)
	(have_image Phenomenon110 spectrograph8)
	(have_image Phenomenon110 infrared6)
	(have_image Phenomenon110 image1)
	(have_image Planet111 image14)
	(have_image Planet111 image2)
	(have_image Planet112 infrared5)
	(have_image Planet112 image14)
	(have_image Planet112 infrared3)
	(have_image Planet113 image14)
	(have_image Planet113 infrared9)
	(have_image Planet113 image0)
	(have_image Planet113 infrared3)
	(have_image Planet114 infrared5)
	(have_image Planet114 image1)
	(have_image Planet114 image11)
	(have_image Planet114 thermograph4)
	(have_image Phenomenon115 infrared3)
	(have_image Phenomenon115 infrared5)
	(have_image Phenomenon115 infrared10)
	(have_image Star116 infrared10)
	(have_image Phenomenon117 image11)
	(have_image Planet120 image1)
	(have_image Star121 infrared3)
	(have_image Star121 infrared6)
	(have_image Star121 spectrograph8)
	(have_image Star121 infrared9)
	(have_image Star121 infrared10)
	(have_image Star122 infrared3)
	(have_image Star122 infrared10)
	(have_image Planet123 image11)
	(have_image Planet123 infrared6)
	(have_image Phenomenon124 image2)
	(have_image Phenomenon124 infrared3)
	(have_image Phenomenon124 infrared6)
	(have_image Star125 image11)
	(have_image Star125 image14)
	(have_image Star125 image2)
	(have_image Planet126 image1)
	(have_image Phenomenon127 image0)
	(have_image Phenomenon127 infrared6)
	(have_image Phenomenon128 infrared10)
	(have_image Phenomenon128 spectrograph8)
	(have_image Phenomenon128 thermograph4)
	(have_image Phenomenon128 infrared9)
	(have_image Phenomenon128 image14)
	(have_image Phenomenon129 image14)
	(have_image Planet130 thermograph4)
	(have_image Planet130 image11)
	(have_image Planet130 spectrograph8)
	(have_image Phenomenon131 infrared6)
	(have_image Phenomenon131 thermograph4)
	(have_image Phenomenon131 spectrograph8)
	(have_image Phenomenon131 infrared10)
))

)
