(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	satellite2 - satellite
	instrument3 - instrument
	satellite3 - satellite
	instrument4 - instrument
	satellite4 - satellite
	instrument5 - instrument
	instrument6 - instrument
	satellite5 - satellite
	instrument7 - instrument
	instrument8 - instrument
	satellite6 - satellite
	instrument9 - instrument
	satellite7 - satellite
	instrument10 - instrument
	instrument11 - instrument
	satellite8 - satellite
	instrument12 - instrument
	satellite9 - satellite
	instrument13 - instrument
	instrument14 - instrument
	image14 - mode
	spectrograph12 - mode
	infrared2 - mode
	image1 - mode
	thermograph13 - mode
	infrared4 - mode
	image6 - mode
	spectrograph10 - mode
	spectrograph0 - mode
	infrared3 - mode
	infrared9 - mode
	image11 - mode
	thermograph7 - mode
	infrared5 - mode
	thermograph8 - mode
	GroundStation1 - direction
	GroundStation0 - direction
	Planet2 - direction
	Star3 - direction
	Star4 - direction
	Star5 - direction
	Phenomenon6 - direction
	Phenomenon7 - direction
	Planet8 - direction
	Phenomenon9 - direction
	Planet10 - direction
	Star11 - direction
	Star12 - direction
	Phenomenon13 - direction
	Planet14 - direction
	Phenomenon15 - direction
	Phenomenon16 - direction
	Planet17 - direction
	Phenomenon18 - direction
	Star19 - direction
	Star20 - direction
	Star21 - direction
	Star22 - direction
	Phenomenon23 - direction
	Star24 - direction
	Phenomenon25 - direction
	Star26 - direction
	Phenomenon27 - direction
	Phenomenon28 - direction
	Star29 - direction
	Phenomenon30 - direction
	Phenomenon31 - direction
	Star32 - direction
	Phenomenon33 - direction
	Star34 - direction
	Star35 - direction
	Phenomenon36 - direction
	Planet37 - direction
	Planet38 - direction
	Planet39 - direction
	Planet40 - direction
	Star41 - direction
	Star42 - direction
	Phenomenon43 - direction
	Star44 - direction
	Phenomenon45 - direction
	Planet46 - direction
	Planet47 - direction
	Phenomenon48 - direction
	Star49 - direction
	Star50 - direction
	Star51 - direction
	Phenomenon52 - direction
	Star53 - direction
	Phenomenon54 - direction
	Planet55 - direction
	Planet56 - direction
	Star57 - direction
	Planet58 - direction
	Star59 - direction
	Phenomenon60 - direction
	Star61 - direction
	Phenomenon62 - direction
	Star63 - direction
	Phenomenon64 - direction
	Planet65 - direction
	Star66 - direction
	Star67 - direction
	Phenomenon68 - direction
	Phenomenon69 - direction
	Phenomenon70 - direction
	Star71 - direction
	Star72 - direction
	Phenomenon73 - direction
	Phenomenon74 - direction
	Star75 - direction
	Star76 - direction
	Star77 - direction
	Star78 - direction
	Phenomenon79 - direction
	Planet80 - direction
	Phenomenon81 - direction
	Star82 - direction
	Phenomenon83 - direction
	Planet84 - direction
	Phenomenon85 - direction
	Star86 - direction
	Star87 - direction
	Star88 - direction
	Star89 - direction
	Planet90 - direction
	Phenomenon91 - direction
	Phenomenon92 - direction
	Phenomenon93 - direction
	Phenomenon94 - direction
	Star95 - direction
	Star96 - direction
	Star97 - direction
	Star98 - direction
	Phenomenon99 - direction
	Star100 - direction
	Planet101 - direction
	Star102 - direction
	Planet103 - direction
	Phenomenon104 - direction
	Star105 - direction
	Planet106 - direction
	Planet107 - direction
	Star108 - direction
	Star109 - direction
	Star110 - direction
	Planet111 - direction
	Phenomenon112 - direction
	Phenomenon113 - direction
	Planet114 - direction
	Phenomenon115 - direction
	Planet116 - direction
	Phenomenon117 - direction
	Phenomenon118 - direction
	Phenomenon119 - direction
	Planet120 - direction
	Phenomenon121 - direction
	Star122 - direction
	Phenomenon123 - direction
	Planet124 - direction
	Star125 - direction
	Phenomenon126 - direction
	Phenomenon127 - direction
	Planet128 - direction
	Phenomenon129 - direction
	Planet130 - direction
	Planet131 - direction
)
(:init
	(supports instrument0 infrared3)
	(calibration_target instrument0 GroundStation0)
	(supports instrument1 infrared9)
	(supports instrument1 image6)
	(supports instrument1 image11)
	(calibration_target instrument1 GroundStation0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star22)
	(supports instrument2 image14)
	(calibration_target instrument2 GroundStation0)
	(on_board instrument2 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Phenomenon119)
	(supports instrument3 spectrograph12)
	(supports instrument3 spectrograph0)
	(calibration_target instrument3 GroundStation0)
	(on_board instrument3 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Planet128)
	(supports instrument4 infrared2)
	(calibration_target instrument4 GroundStation0)
	(on_board instrument4 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet107)
	(supports instrument5 image11)
	(supports instrument5 infrared5)
	(calibration_target instrument5 GroundStation1)
	(supports instrument6 infrared9)
	(supports instrument6 image1)
	(calibration_target instrument6 GroundStation0)
	(on_board instrument5 satellite4)
	(on_board instrument6 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star87)
	(supports instrument7 infrared3)
	(supports instrument7 thermograph13)
	(supports instrument7 image6)
	(calibration_target instrument7 GroundStation0)
	(supports instrument8 infrared4)
	(calibration_target instrument8 GroundStation0)
	(on_board instrument7 satellite5)
	(on_board instrument8 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star11)
	(supports instrument9 spectrograph10)
	(calibration_target instrument9 GroundStation0)
	(on_board instrument9 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet65)
	(supports instrument10 infrared3)
	(supports instrument10 infrared9)
	(supports instrument10 spectrograph0)
	(calibration_target instrument10 GroundStation1)
	(supports instrument11 image11)
	(supports instrument11 spectrograph10)
	(supports instrument11 image6)
	(calibration_target instrument11 GroundStation1)
	(on_board instrument10 satellite7)
	(on_board instrument11 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Phenomenon83)
	(supports instrument12 infrared9)
	(supports instrument12 infrared3)
	(supports instrument12 spectrograph0)
	(calibration_target instrument12 GroundStation1)
	(on_board instrument12 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star76)
	(supports instrument13 thermograph7)
	(supports instrument13 image11)
	(calibration_target instrument13 GroundStation0)
	(supports instrument14 thermograph8)
	(supports instrument14 infrared5)
	(supports instrument14 thermograph7)
	(calibration_target instrument14 GroundStation0)
	(on_board instrument13 satellite9)
	(on_board instrument14 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Planet37)
)
(:goal (and
	(pointing satellite1 Star4)
	(pointing satellite3 Phenomenon74)
	(pointing satellite7 Planet101)
	(pointing satellite9 Planet37)
	(have_image Planet2 image11)
	(have_image Planet2 image14)
	(have_image Planet2 image6)
	(have_image Star3 image11)
	(have_image Star3 infrared4)
	(have_image Star4 thermograph8)
	(have_image Star4 thermograph13)
	(have_image Star5 spectrograph12)
	(have_image Phenomenon6 image1)
	(have_image Phenomenon7 image14)
	(have_image Phenomenon7 infrared9)
	(have_image Phenomenon7 spectrograph10)
	(have_image Phenomenon7 thermograph7)
	(have_image Planet8 infrared2)
	(have_image Planet8 infrared4)
	(have_image Planet8 thermograph13)
	(have_image Planet8 infrared3)
	(have_image Planet8 image14)
	(have_image Phenomenon9 spectrograph10)
	(have_image Phenomenon9 infrared2)
	(have_image Phenomenon9 infrared4)
	(have_image Phenomenon9 spectrograph0)
	(have_image Planet10 spectrograph10)
	(have_image Planet10 infrared2)
	(have_image Star11 infrared3)
	(have_image Star11 thermograph8)
	(have_image Star11 spectrograph0)
	(have_image Star11 image6)
	(have_image Star11 infrared9)
	(have_image Star12 thermograph8)
	(have_image Star12 infrared9)
	(have_image Star12 image1)
	(have_image Phenomenon13 thermograph8)
	(have_image Phenomenon13 image6)
	(have_image Phenomenon13 infrared9)
	(have_image Phenomenon13 infrared5)
	(have_image Phenomenon13 infrared2)
	(have_image Planet14 infrared2)
	(have_image Planet14 infrared4)
	(have_image Phenomenon15 infrared2)
	(have_image Planet17 infrared9)
	(have_image Phenomenon18 infrared4)
	(have_image Star19 spectrograph12)
	(have_image Star19 thermograph13)
	(have_image Star19 image14)
	(have_image Star19 image1)
	(have_image Star20 image14)
	(have_image Star21 spectrograph10)
	(have_image Star21 infrared9)
	(have_image Star21 thermograph13)
	(have_image Star21 thermograph7)
	(have_image Star22 thermograph8)
	(have_image Phenomenon23 image14)
	(have_image Phenomenon23 spectrograph0)
	(have_image Star24 image11)
	(have_image Star24 spectrograph0)
	(have_image Star24 infrared5)
	(have_image Star24 image14)
	(have_image Phenomenon25 infrared2)
	(have_image Phenomenon25 thermograph7)
	(have_image Phenomenon25 infrared5)
	(have_image Phenomenon25 thermograph13)
	(have_image Star26 infrared9)
	(have_image Star26 image11)
	(have_image Star26 infrared5)
	(have_image Star26 image1)
	(have_image Phenomenon27 spectrograph10)
	(have_image Phenomenon28 image14)
	(have_image Phenomenon28 infrared4)
	(have_image Phenomenon28 thermograph8)
	(have_image Phenomenon28 infrared9)
	(have_image Star29 spectrograph12)
	(have_image Star29 thermograph7)
	(have_image Star29 spectrograph0)
	(have_image Star29 infrared5)
	(have_image Phenomenon30 infrared3)
	(have_image Phenomenon30 infrared2)
	(have_image Phenomenon30 thermograph7)
	(have_image Phenomenon30 image6)
	(have_image Phenomenon31 thermograph8)
	(have_image Phenomenon31 image11)
	(have_image Phenomenon31 thermograph7)
	(have_image Star32 infrared4)
	(have_image Star32 thermograph8)
	(have_image Phenomenon33 spectrograph0)
	(have_image Phenomenon33 spectrograph12)
	(have_image Phenomenon33 thermograph7)
	(have_image Star34 infrared2)
	(have_image Star34 image6)
	(have_image Star34 infrared9)
	(have_image Star34 thermograph7)
	(have_image Star34 thermograph8)
	(have_image Star35 spectrograph10)
	(have_image Star35 infrared9)
	(have_image Star35 image14)
	(have_image Phenomenon36 thermograph7)
	(have_image Phenomenon36 thermograph8)
	(have_image Planet37 infrared9)
	(have_image Planet38 infrared9)
	(have_image Planet39 infrared4)
	(have_image Planet39 infrared9)
	(have_image Planet40 spectrograph10)
	(have_image Planet40 image6)
	(have_image Planet40 image14)
	(have_image Planet40 infrared3)
	(have_image Planet40 infrared4)
	(have_image Star41 image1)
	(have_image Star41 image14)
	(have_image Star42 thermograph8)
	(have_image Star42 spectrograph10)
	(have_image Star42 infrared4)
	(have_image Star42 image1)
	(have_image Star42 infrared5)
	(have_image Phenomenon43 spectrograph12)
	(have_image Phenomenon43 image6)
	(have_image Phenomenon45 thermograph7)
	(have_image Phenomenon45 spectrograph10)
	(have_image Phenomenon45 image6)
	(have_image Phenomenon45 spectrograph0)
	(have_image Planet46 infrared2)
	(have_image Planet47 thermograph7)
	(have_image Phenomenon48 thermograph7)
	(have_image Phenomenon48 thermograph8)
	(have_image Star50 infrared3)
	(have_image Phenomenon52 image1)
	(have_image Phenomenon52 image6)
	(have_image Phenomenon52 thermograph8)
	(have_image Phenomenon52 thermograph13)
	(have_image Phenomenon52 image11)
	(have_image Star53 image14)
	(have_image Star53 infrared2)
	(have_image Star53 infrared3)
	(have_image Star53 image1)
	(have_image Star53 thermograph8)
	(have_image Phenomenon54 infrared2)
	(have_image Phenomenon54 thermograph13)
	(have_image Phenomenon54 image14)
	(have_image Phenomenon54 infrared9)
	(have_image Phenomenon54 image1)
	(have_image Planet56 spectrograph10)
	(have_image Planet56 infrared4)
	(have_image Planet56 image11)
	(have_image Planet56 image14)
	(have_image Star57 image11)
	(have_image Star57 thermograph7)
	(have_image Star57 infrared5)
	(have_image Star57 image1)
	(have_image Star57 thermograph13)
	(have_image Planet58 infrared4)
	(have_image Planet58 thermograph7)
	(have_image Planet58 image1)
	(have_image Star59 infrared5)
	(have_image Star59 image6)
	(have_image Phenomenon60 infrared2)
	(have_image Phenomenon60 image14)
	(have_image Phenomenon60 infrared3)
	(have_image Phenomenon60 infrared9)
	(have_image Star61 image11)
	(have_image Star61 thermograph8)
	(have_image Star61 image14)
	(have_image Phenomenon62 spectrograph0)
	(have_image Phenomenon62 thermograph7)
	(have_image Phenomenon62 image11)
	(have_image Phenomenon62 thermograph8)
	(have_image Star63 infrared9)
	(have_image Phenomenon64 infrared3)
	(have_image Planet65 image1)
	(have_image Planet65 spectrograph0)
	(have_image Planet65 image11)
	(have_image Star66 infrared4)
	(have_image Phenomenon68 infrared4)
	(have_image Phenomenon68 infrared3)
	(have_image Phenomenon68 infrared2)
	(have_image Phenomenon68 spectrograph0)
	(have_image Phenomenon69 infrared3)
	(have_image Phenomenon69 image1)
	(have_image Phenomenon69 thermograph13)
	(have_image Phenomenon69 infrared9)
	(have_image Phenomenon69 infrared2)
	(have_image Phenomenon70 thermograph8)
	(have_image Phenomenon70 spectrograph0)
	(have_image Phenomenon70 thermograph13)
	(have_image Phenomenon70 image1)
	(have_image Star72 infrared4)
	(have_image Star72 thermograph13)
	(have_image Star72 spectrograph10)
	(have_image Star72 thermograph7)
	(have_image Star72 image6)
	(have_image Phenomenon73 image11)
	(have_image Phenomenon73 infrared9)
	(have_image Phenomenon74 image11)
	(have_image Phenomenon74 thermograph7)
	(have_image Phenomenon74 spectrograph0)
	(have_image Star75 infrared5)
	(have_image Star75 infrared2)
	(have_image Star76 thermograph8)
	(have_image Star76 thermograph7)
	(have_image Star76 infrared5)
	(have_image Star76 spectrograph0)
	(have_image Star76 image6)
	(have_image Star77 spectrograph12)
	(have_image Star77 infrared3)
	(have_image Star77 infrared2)
	(have_image Star77 spectrograph0)
	(have_image Star77 thermograph13)
	(have_image Phenomenon79 infrared4)
	(have_image Phenomenon81 infrared4)
	(have_image Phenomenon81 image1)
	(have_image Star82 image14)
	(have_image Phenomenon83 image11)
	(have_image Phenomenon83 infrared9)
	(have_image Phenomenon83 image6)
	(have_image Planet84 infrared4)
	(have_image Star86 image14)
	(have_image Star86 thermograph13)
	(have_image Star86 spectrograph0)
	(have_image Star87 spectrograph0)
	(have_image Star87 infrared3)
	(have_image Star88 image6)
	(have_image Star88 spectrograph12)
	(have_image Star89 infrared5)
	(have_image Star89 spectrograph0)
	(have_image Star89 image1)
	(have_image Star89 thermograph8)
	(have_image Planet90 infrared5)
	(have_image Planet90 thermograph8)
	(have_image Planet90 thermograph7)
	(have_image Phenomenon91 image14)
	(have_image Phenomenon91 image11)
	(have_image Phenomenon92 infrared4)
	(have_image Phenomenon93 image11)
	(have_image Phenomenon93 spectrograph0)
	(have_image Phenomenon93 spectrograph12)
	(have_image Phenomenon93 infrared9)
	(have_image Phenomenon94 spectrograph0)
	(have_image Phenomenon94 infrared5)
	(have_image Phenomenon94 image6)
	(have_image Phenomenon94 infrared2)
	(have_image Phenomenon94 image14)
	(have_image Star95 thermograph8)
	(have_image Star95 thermograph13)
	(have_image Star95 image6)
	(have_image Star95 infrared2)
	(have_image Star95 thermograph7)
	(have_image Star96 thermograph8)
	(have_image Star96 infrared5)
	(have_image Star97 thermograph13)
	(have_image Star97 thermograph8)
	(have_image Star98 thermograph13)
	(have_image Star98 image6)
	(have_image Star98 thermograph7)
	(have_image Phenomenon99 spectrograph10)
	(have_image Phenomenon99 image6)
	(have_image Phenomenon99 infrared3)
	(have_image Star100 thermograph13)
	(have_image Star100 thermograph7)
	(have_image Planet101 thermograph13)
	(have_image Planet101 infrared9)
	(have_image Planet101 spectrograph10)
	(have_image Star102 image1)
	(have_image Planet103 spectrograph10)
	(have_image Phenomenon104 image6)
	(have_image Phenomenon104 image11)
	(have_image Phenomenon104 image14)
	(have_image Star105 thermograph8)
	(have_image Star105 thermograph13)
	(have_image Star105 spectrograph10)
	(have_image Planet106 image11)
	(have_image Planet107 thermograph7)
	(have_image Planet107 image1)
	(have_image Planet107 infrared3)
	(have_image Planet107 infrared9)
	(have_image Star108 spectrograph12)
	(have_image Star108 image11)
	(have_image Star108 infrared2)
	(have_image Star109 infrared5)
	(have_image Star109 infrared4)
	(have_image Star109 spectrograph10)
	(have_image Star109 thermograph7)
	(have_image Star109 thermograph8)
	(have_image Star110 thermograph13)
	(have_image Star110 infrared5)
	(have_image Star110 thermograph7)
	(have_image Star110 spectrograph0)
	(have_image Star110 spectrograph12)
	(have_image Planet111 infrared5)
	(have_image Planet111 infrared2)
	(have_image Planet111 spectrograph10)
	(have_image Planet111 infrared3)
	(have_image Phenomenon112 infrared5)
	(have_image Phenomenon112 spectrograph12)
	(have_image Phenomenon112 image6)
	(have_image Phenomenon112 thermograph7)
	(have_image Phenomenon113 thermograph7)
	(have_image Phenomenon113 infrared4)
	(have_image Phenomenon113 thermograph13)
	(have_image Phenomenon113 infrared2)
	(have_image Planet114 image1)
	(have_image Planet114 spectrograph0)
	(have_image Planet114 image11)
	(have_image Phenomenon115 spectrograph12)
	(have_image Phenomenon115 spectrograph0)
	(have_image Phenomenon115 image14)
	(have_image Phenomenon115 image11)
	(have_image Planet116 thermograph7)
	(have_image Planet116 spectrograph10)
	(have_image Planet116 infrared3)
	(have_image Planet116 thermograph13)
	(have_image Planet116 image6)
	(have_image Phenomenon117 thermograph13)
	(have_image Phenomenon117 infrared5)
	(have_image Phenomenon117 spectrograph10)
	(have_image Phenomenon117 thermograph8)
	(have_image Phenomenon117 image6)
	(have_image Phenomenon118 image6)
	(have_image Phenomenon118 spectrograph0)
	(have_image Phenomenon118 infrared9)
	(have_image Phenomenon118 infrared5)
	(have_image Phenomenon118 infrared2)
	(have_image Phenomenon119 infrared5)
	(have_image Phenomenon119 spectrograph12)
	(have_image Phenomenon121 image1)
	(have_image Star122 thermograph7)
	(have_image Star122 spectrograph10)
	(have_image Star122 image6)
	(have_image Phenomenon123 thermograph7)
	(have_image Phenomenon123 image6)
	(have_image Phenomenon123 spectrograph10)
	(have_image Phenomenon123 infrared9)
	(have_image Phenomenon123 spectrograph12)
	(have_image Star125 thermograph7)
	(have_image Star125 thermograph13)
	(have_image Star125 infrared4)
	(have_image Phenomenon126 spectrograph0)
	(have_image Phenomenon126 thermograph7)
	(have_image Phenomenon126 image1)
	(have_image Phenomenon127 spectrograph10)
	(have_image Phenomenon127 spectrograph12)
	(have_image Phenomenon127 spectrograph0)
	(have_image Phenomenon127 infrared4)
	(have_image Planet128 thermograph8)
	(have_image Phenomenon129 spectrograph12)
	(have_image Phenomenon129 infrared4)
	(have_image Planet130 image14)
	(have_image Planet130 thermograph7)
	(have_image Planet130 infrared3)
	(have_image Planet130 thermograph8)
	(have_image Planet131 spectrograph0)
	(have_image Planet131 thermograph7)
	(have_image Planet131 infrared4)
	(have_image Planet131 infrared5)
))

)
