(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	satellite2 - satellite
	instrument4 - instrument
	instrument5 - instrument
	satellite3 - satellite
	instrument6 - instrument
	instrument7 - instrument
	satellite4 - satellite
	instrument8 - instrument
	satellite5 - satellite
	instrument9 - instrument
	instrument10 - instrument
	satellite6 - satellite
	instrument11 - instrument
	instrument12 - instrument
	satellite7 - satellite
	instrument13 - instrument
	satellite8 - satellite
	instrument14 - instrument
	satellite9 - satellite
	instrument15 - instrument
	instrument16 - instrument
	infrared9 - mode
	image10 - mode
	image0 - mode
	image2 - mode
	infrared3 - mode
	infrared12 - mode
	thermograph13 - mode
	spectrograph11 - mode
	spectrograph8 - mode
	spectrograph6 - mode
	thermograph4 - mode
	spectrograph5 - mode
	thermograph14 - mode
	spectrograph7 - mode
	spectrograph1 - mode
	Star0 - direction
	GroundStation1 - direction
	Star2 - direction
	Star3 - direction
	Star4 - direction
	Phenomenon5 - direction
	Phenomenon6 - direction
	Planet7 - direction
	Phenomenon8 - direction
	Planet9 - direction
	Phenomenon10 - direction
	Star11 - direction
	Star12 - direction
	Phenomenon13 - direction
	Phenomenon14 - direction
	Star15 - direction
	Planet16 - direction
	Planet17 - direction
	Phenomenon18 - direction
	Star19 - direction
	Phenomenon20 - direction
	Star21 - direction
	Planet22 - direction
	Planet23 - direction
	Star24 - direction
	Planet25 - direction
	Phenomenon26 - direction
	Phenomenon27 - direction
	Planet28 - direction
	Planet29 - direction
	Phenomenon30 - direction
	Star31 - direction
	Planet32 - direction
	Phenomenon33 - direction
	Star34 - direction
	Phenomenon35 - direction
	Phenomenon36 - direction
	Phenomenon37 - direction
	Phenomenon38 - direction
	Star39 - direction
	Star40 - direction
	Star41 - direction
	Star42 - direction
	Phenomenon43 - direction
	Star44 - direction
	Planet45 - direction
	Star46 - direction
	Planet47 - direction
	Planet48 - direction
	Phenomenon49 - direction
	Star50 - direction
	Phenomenon51 - direction
	Star52 - direction
	Planet53 - direction
	Planet54 - direction
	Phenomenon55 - direction
	Star56 - direction
	Planet57 - direction
	Phenomenon58 - direction
	Phenomenon59 - direction
	Planet60 - direction
	Phenomenon61 - direction
	Phenomenon62 - direction
	Phenomenon63 - direction
	Phenomenon64 - direction
	Planet65 - direction
	Planet66 - direction
	Star67 - direction
	Phenomenon68 - direction
	Star69 - direction
	Phenomenon70 - direction
	Planet71 - direction
	Star72 - direction
	Phenomenon73 - direction
	Phenomenon74 - direction
	Star75 - direction
	Star76 - direction
	Planet77 - direction
	Planet78 - direction
	Planet79 - direction
	Phenomenon80 - direction
	Phenomenon81 - direction
	Planet82 - direction
	Star83 - direction
	Planet84 - direction
	Star85 - direction
	Phenomenon86 - direction
	Phenomenon87 - direction
	Star88 - direction
	Star89 - direction
	Phenomenon90 - direction
	Phenomenon91 - direction
	Star92 - direction
	Star93 - direction
	Star94 - direction
	Phenomenon95 - direction
	Star96 - direction
	Phenomenon97 - direction
	Phenomenon98 - direction
	Star99 - direction
	Star100 - direction
	Phenomenon101 - direction
	Planet102 - direction
	Planet103 - direction
	Planet104 - direction
	Planet105 - direction
	Planet106 - direction
	Phenomenon107 - direction
	Planet108 - direction
	Phenomenon109 - direction
	Star110 - direction
	Planet111 - direction
	Planet112 - direction
	Planet113 - direction
	Planet114 - direction
	Phenomenon115 - direction
	Star116 - direction
	Planet117 - direction
	Planet118 - direction
	Phenomenon119 - direction
	Star120 - direction
	Star121 - direction
	Star122 - direction
	Planet123 - direction
	Phenomenon124 - direction
	Phenomenon125 - direction
	Phenomenon126 - direction
	Planet127 - direction
	Phenomenon128 - direction
	Phenomenon129 - direction
	Star130 - direction
	Star131 - direction
	Phenomenon132 - direction
	Planet133 - direction
	Phenomenon134 - direction
	Planet135 - direction
	Planet136 - direction
	Planet137 - direction
	Star138 - direction
	Planet139 - direction
	Star140 - direction
	Phenomenon141 - direction
)
(:init
	(supports instrument0 spectrograph8)
	(calibration_target instrument0 Star0)
	(supports instrument1 spectrograph5)
	(calibration_target instrument1 Star0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon14)
	(supports instrument2 spectrograph6)
	(supports instrument2 thermograph14)
	(supports instrument2 image0)
	(calibration_target instrument2 Star0)
	(supports instrument3 infrared12)
	(supports instrument3 spectrograph11)
	(calibration_target instrument3 Star0)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Planet66)
	(supports instrument4 spectrograph11)
	(supports instrument4 spectrograph8)
	(supports instrument4 infrared12)
	(calibration_target instrument4 GroundStation1)
	(supports instrument5 spectrograph6)
	(supports instrument5 spectrograph8)
	(supports instrument5 spectrograph7)
	(calibration_target instrument5 GroundStation1)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation1)
	(supports instrument6 thermograph4)
	(supports instrument6 image2)
	(supports instrument6 spectrograph8)
	(calibration_target instrument6 Star0)
	(supports instrument7 infrared3)
	(supports instrument7 thermograph4)
	(calibration_target instrument7 GroundStation1)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet47)
	(supports instrument8 spectrograph1)
	(supports instrument8 spectrograph8)
	(supports instrument8 thermograph13)
	(calibration_target instrument8 Star0)
	(on_board instrument8 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star2)
	(supports instrument9 infrared12)
	(supports instrument9 spectrograph11)
	(calibration_target instrument9 Star0)
	(supports instrument10 spectrograph7)
	(supports instrument10 thermograph13)
	(supports instrument10 spectrograph6)
	(calibration_target instrument10 Star0)
	(on_board instrument9 satellite5)
	(on_board instrument10 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Planet112)
	(supports instrument11 spectrograph11)
	(supports instrument11 spectrograph6)
	(calibration_target instrument11 Star0)
	(supports instrument12 spectrograph6)
	(calibration_target instrument12 GroundStation1)
	(on_board instrument11 satellite6)
	(on_board instrument12 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Phenomenon49)
	(supports instrument13 thermograph4)
	(supports instrument13 spectrograph6)
	(supports instrument13 spectrograph8)
	(calibration_target instrument13 Star0)
	(on_board instrument13 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Planet71)
	(supports instrument14 spectrograph5)
	(supports instrument14 spectrograph7)
	(calibration_target instrument14 Star0)
	(on_board instrument14 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Phenomenon63)
	(supports instrument15 spectrograph5)
	(supports instrument15 thermograph14)
	(calibration_target instrument15 Star0)
	(supports instrument16 spectrograph1)
	(supports instrument16 spectrograph7)
	(supports instrument16 thermograph14)
	(calibration_target instrument16 GroundStation1)
	(on_board instrument15 satellite9)
	(on_board instrument16 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Phenomenon5)
)
(:goal (and
	(pointing satellite0 Planet104)
	(pointing satellite2 Phenomenon70)
	(pointing satellite6 Phenomenon6)
	(have_image Star2 infrared3)
	(have_image Star2 spectrograph8)
	(have_image Star3 image0)
	(have_image Star3 infrared3)
	(have_image Star3 image2)
	(have_image Star3 thermograph4)
	(have_image Star3 spectrograph7)
	(have_image Star4 spectrograph1)
	(have_image Star4 spectrograph8)
	(have_image Phenomenon5 spectrograph5)
	(have_image Phenomenon5 image2)
	(have_image Phenomenon5 spectrograph6)
	(have_image Phenomenon6 spectrograph7)
	(have_image Phenomenon6 thermograph4)
	(have_image Phenomenon6 infrared3)
	(have_image Phenomenon6 thermograph13)
	(have_image Planet7 thermograph14)
	(have_image Planet7 thermograph13)
	(have_image Phenomenon8 spectrograph7)
	(have_image Phenomenon8 thermograph14)
	(have_image Phenomenon8 spectrograph6)
	(have_image Phenomenon8 image0)
	(have_image Planet9 spectrograph7)
	(have_image Planet9 infrared12)
	(have_image Planet9 spectrograph11)
	(have_image Planet9 spectrograph8)
	(have_image Phenomenon10 thermograph4)
	(have_image Star11 image0)
	(have_image Star11 thermograph4)
	(have_image Star11 spectrograph5)
	(have_image Star12 thermograph4)
	(have_image Star12 image0)
	(have_image Star12 spectrograph1)
	(have_image Star12 spectrograph6)
	(have_image Star12 spectrograph8)
	(have_image Phenomenon14 thermograph14)
	(have_image Phenomenon14 spectrograph8)
	(have_image Phenomenon14 spectrograph1)
	(have_image Star15 spectrograph11)
	(have_image Planet16 image2)
	(have_image Planet16 spectrograph5)
	(have_image Planet16 thermograph14)
	(have_image Planet17 spectrograph5)
	(have_image Planet17 infrared12)
	(have_image Star19 thermograph14)
	(have_image Star19 spectrograph11)
	(have_image Star21 spectrograph7)
	(have_image Star21 infrared12)
	(have_image Star21 thermograph4)
	(have_image Star21 image2)
	(have_image Planet23 infrared12)
	(have_image Planet23 spectrograph6)
	(have_image Planet23 thermograph14)
	(have_image Star24 thermograph4)
	(have_image Star24 infrared12)
	(have_image Star24 spectrograph7)
	(have_image Star24 spectrograph1)
	(have_image Planet25 image2)
	(have_image Planet25 thermograph4)
	(have_image Planet25 spectrograph5)
	(have_image Phenomenon26 infrared3)
	(have_image Phenomenon27 infrared12)
	(have_image Phenomenon27 thermograph14)
	(have_image Phenomenon27 thermograph13)
	(have_image Phenomenon27 spectrograph1)
	(have_image Planet28 infrared12)
	(have_image Planet29 thermograph4)
	(have_image Phenomenon30 image0)
	(have_image Phenomenon30 thermograph4)
	(have_image Phenomenon30 spectrograph8)
	(have_image Star31 spectrograph7)
	(have_image Star31 thermograph14)
	(have_image Star31 spectrograph6)
	(have_image Phenomenon33 spectrograph8)
	(have_image Phenomenon33 infrared3)
	(have_image Phenomenon33 infrared12)
	(have_image Star34 spectrograph7)
	(have_image Star34 thermograph14)
	(have_image Star34 spectrograph5)
	(have_image Phenomenon35 image0)
	(have_image Phenomenon35 infrared12)
	(have_image Phenomenon35 spectrograph6)
	(have_image Phenomenon36 thermograph4)
	(have_image Phenomenon36 spectrograph1)
	(have_image Phenomenon37 spectrograph11)
	(have_image Phenomenon38 image0)
	(have_image Phenomenon38 spectrograph5)
	(have_image Phenomenon38 thermograph13)
	(have_image Phenomenon38 infrared12)
	(have_image Phenomenon38 image2)
	(have_image Star39 spectrograph11)
	(have_image Star39 thermograph4)
	(have_image Star39 image2)
	(have_image Star39 thermograph14)
	(have_image Star40 infrared12)
	(have_image Star40 infrared3)
	(have_image Star40 spectrograph11)
	(have_image Star40 thermograph13)
	(have_image Phenomenon43 thermograph4)
	(have_image Phenomenon43 image0)
	(have_image Planet45 spectrograph6)
	(have_image Planet45 spectrograph11)
	(have_image Star46 spectrograph6)
	(have_image Star46 image2)
	(have_image Star46 spectrograph8)
	(have_image Star46 infrared3)
	(have_image Star46 spectrograph7)
	(have_image Planet47 image2)
	(have_image Planet47 thermograph14)
	(have_image Planet47 thermograph13)
	(have_image Planet47 thermograph4)
	(have_image Planet48 spectrograph1)
	(have_image Planet48 spectrograph8)
	(have_image Planet48 image2)
	(have_image Phenomenon49 spectrograph8)
	(have_image Phenomenon49 spectrograph5)
	(have_image Star50 spectrograph5)
	(have_image Star50 spectrograph6)
	(have_image Phenomenon51 spectrograph1)
	(have_image Phenomenon51 spectrograph7)
	(have_image Phenomenon51 spectrograph5)
	(have_image Phenomenon51 infrared12)
	(have_image Phenomenon51 spectrograph8)
	(have_image Star52 thermograph14)
	(have_image Planet53 thermograph14)
	(have_image Planet53 thermograph4)
	(have_image Planet54 spectrograph1)
	(have_image Planet54 image2)
	(have_image Planet54 image0)
	(have_image Star56 image0)
	(have_image Star56 spectrograph11)
	(have_image Star56 thermograph14)
	(have_image Star56 thermograph4)
	(have_image Planet57 thermograph4)
	(have_image Planet57 spectrograph11)
	(have_image Phenomenon58 spectrograph5)
	(have_image Phenomenon58 infrared12)
	(have_image Phenomenon59 infrared3)
	(have_image Phenomenon59 spectrograph8)
	(have_image Phenomenon59 thermograph13)
	(have_image Phenomenon59 spectrograph1)
	(have_image Planet60 image0)
	(have_image Planet60 infrared3)
	(have_image Planet60 infrared12)
	(have_image Phenomenon61 spectrograph1)
	(have_image Phenomenon61 spectrograph5)
	(have_image Phenomenon61 spectrograph7)
	(have_image Phenomenon63 spectrograph11)
	(have_image Phenomenon63 spectrograph8)
	(have_image Phenomenon64 spectrograph1)
	(have_image Planet65 spectrograph6)
	(have_image Planet65 thermograph13)
	(have_image Planet65 spectrograph11)
	(have_image Planet65 spectrograph8)
	(have_image Planet65 infrared3)
	(have_image Planet66 spectrograph6)
	(have_image Planet66 infrared12)
	(have_image Planet66 spectrograph7)
	(have_image Planet66 spectrograph11)
	(have_image Planet66 thermograph13)
	(have_image Star67 infrared3)
	(have_image Star67 image2)
	(have_image Star67 thermograph13)
	(have_image Phenomenon68 thermograph14)
	(have_image Phenomenon68 thermograph13)
	(have_image Phenomenon68 spectrograph1)
	(have_image Phenomenon68 spectrograph5)
	(have_image Star69 image0)
	(have_image Phenomenon70 thermograph13)
	(have_image Phenomenon70 image2)
	(have_image Phenomenon70 infrared12)
	(have_image Phenomenon70 spectrograph7)
	(have_image Planet71 spectrograph7)
	(have_image Planet71 thermograph13)
	(have_image Planet71 spectrograph1)
	(have_image Star72 thermograph4)
	(have_image Star72 thermograph13)
	(have_image Star72 thermograph14)
	(have_image Star72 spectrograph11)
	(have_image Phenomenon73 thermograph13)
	(have_image Phenomenon74 spectrograph5)
	(have_image Phenomenon74 thermograph13)
	(have_image Phenomenon74 image2)
	(have_image Star76 thermograph14)
	(have_image Star76 image2)
	(have_image Star76 infrared3)
	(have_image Planet77 spectrograph5)
	(have_image Planet77 spectrograph8)
	(have_image Planet78 spectrograph7)
	(have_image Planet78 spectrograph5)
	(have_image Planet78 thermograph14)
	(have_image Planet79 thermograph14)
	(have_image Planet79 thermograph13)
	(have_image Planet79 spectrograph11)
	(have_image Planet79 spectrograph7)
	(have_image Phenomenon80 image0)
	(have_image Phenomenon80 spectrograph6)
	(have_image Phenomenon81 spectrograph1)
	(have_image Phenomenon81 spectrograph5)
	(have_image Phenomenon81 image0)
	(have_image Phenomenon81 thermograph14)
	(have_image Planet82 spectrograph1)
	(have_image Planet82 spectrograph5)
	(have_image Planet82 spectrograph6)
	(have_image Star83 thermograph13)
	(have_image Star83 infrared3)
	(have_image Star83 spectrograph1)
	(have_image Star83 spectrograph5)
	(have_image Planet84 spectrograph1)
	(have_image Planet84 image2)
	(have_image Planet84 spectrograph5)
	(have_image Star85 thermograph4)
	(have_image Star85 spectrograph5)
	(have_image Star85 spectrograph7)
	(have_image Phenomenon86 thermograph14)
	(have_image Phenomenon87 image0)
	(have_image Phenomenon87 spectrograph5)
	(have_image Phenomenon87 spectrograph6)
	(have_image Star88 image0)
	(have_image Star89 spectrograph7)
	(have_image Phenomenon90 spectrograph11)
	(have_image Phenomenon90 image0)
	(have_image Phenomenon90 thermograph13)
	(have_image Phenomenon91 infrared3)
	(have_image Star94 image2)
	(have_image Star94 thermograph14)
	(have_image Star94 thermograph4)
	(have_image Phenomenon95 spectrograph11)
	(have_image Phenomenon95 image2)
	(have_image Phenomenon95 thermograph14)
	(have_image Star96 spectrograph11)
	(have_image Star96 thermograph13)
	(have_image Star96 spectrograph6)
	(have_image Phenomenon97 spectrograph8)
	(have_image Phenomenon97 spectrograph6)
	(have_image Phenomenon97 thermograph14)
	(have_image Phenomenon97 spectrograph11)
	(have_image Phenomenon98 thermograph14)
	(have_image Phenomenon98 spectrograph1)
	(have_image Phenomenon98 spectrograph7)
	(have_image Star99 spectrograph1)
	(have_image Star100 thermograph13)
	(have_image Phenomenon101 spectrograph5)
	(have_image Phenomenon101 infrared3)
	(have_image Planet102 thermograph13)
	(have_image Planet104 thermograph14)
	(have_image Planet105 spectrograph5)
	(have_image Planet105 spectrograph7)
	(have_image Planet105 thermograph14)
	(have_image Planet105 spectrograph1)
	(have_image Planet105 spectrograph11)
	(have_image Planet106 spectrograph8)
	(have_image Planet106 spectrograph1)
	(have_image Planet106 infrared12)
	(have_image Planet106 thermograph14)
	(have_image Phenomenon107 spectrograph7)
	(have_image Phenomenon107 image0)
	(have_image Phenomenon107 image2)
	(have_image Planet108 infrared3)
	(have_image Planet108 thermograph13)
	(have_image Phenomenon109 image2)
	(have_image Phenomenon109 spectrograph8)
	(have_image Star110 thermograph13)
	(have_image Star110 spectrograph11)
	(have_image Planet112 thermograph13)
	(have_image Planet112 spectrograph5)
	(have_image Planet112 spectrograph8)
	(have_image Planet113 infrared12)
	(have_image Planet113 image0)
	(have_image Planet113 spectrograph1)
	(have_image Planet114 spectrograph7)
	(have_image Planet114 thermograph14)
	(have_image Planet114 spectrograph6)
	(have_image Phenomenon115 spectrograph8)
	(have_image Phenomenon115 infrared12)
	(have_image Phenomenon115 image0)
	(have_image Star116 spectrograph7)
	(have_image Planet117 spectrograph11)
	(have_image Planet117 image2)
	(have_image Planet117 spectrograph6)
	(have_image Planet117 infrared3)
	(have_image Planet117 thermograph13)
	(have_image Planet118 infrared12)
	(have_image Phenomenon119 spectrograph7)
	(have_image Phenomenon119 spectrograph8)
	(have_image Phenomenon119 spectrograph1)
	(have_image Phenomenon119 spectrograph6)
	(have_image Star120 spectrograph5)
	(have_image Star120 thermograph4)
	(have_image Star121 image2)
	(have_image Star121 thermograph4)
	(have_image Star122 spectrograph6)
	(have_image Star122 spectrograph5)
	(have_image Star122 thermograph4)
	(have_image Star122 thermograph14)
	(have_image Planet123 thermograph4)
	(have_image Phenomenon124 thermograph14)
	(have_image Phenomenon124 infrared3)
	(have_image Phenomenon124 spectrograph5)
	(have_image Phenomenon124 image0)
	(have_image Planet127 spectrograph1)
	(have_image Planet127 spectrograph6)
	(have_image Planet127 image0)
	(have_image Planet127 infrared12)
	(have_image Phenomenon128 spectrograph1)
	(have_image Phenomenon128 image2)
	(have_image Phenomenon129 spectrograph1)
	(have_image Star130 infrared3)
	(have_image Star130 spectrograph8)
	(have_image Star130 spectrograph6)
	(have_image Star130 image2)
	(have_image Star131 spectrograph6)
	(have_image Phenomenon132 infrared3)
	(have_image Phenomenon132 image0)
	(have_image Phenomenon134 thermograph14)
	(have_image Phenomenon134 image0)
	(have_image Phenomenon134 spectrograph6)
	(have_image Phenomenon134 thermograph4)
	(have_image Phenomenon134 spectrograph1)
	(have_image Planet135 thermograph13)
	(have_image Planet135 infrared12)
	(have_image Planet135 infrared3)
	(have_image Planet136 infrared3)
	(have_image Planet136 spectrograph7)
	(have_image Planet137 spectrograph7)
	(have_image Planet137 thermograph13)
	(have_image Star140 spectrograph6)
	(have_image Star140 spectrograph11)
	(have_image Star140 spectrograph8)
	(have_image Star140 infrared12)
	(have_image Star140 thermograph13)
	(have_image Phenomenon141 spectrograph8)
	(have_image Phenomenon141 infrared12)
))

)
