(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	satellite2 - satellite
	instrument3 - instrument
	satellite3 - satellite
	instrument4 - instrument
	satellite4 - satellite
	instrument5 - instrument
	satellite5 - satellite
	instrument6 - instrument
	instrument7 - instrument
	satellite6 - satellite
	instrument8 - instrument
	satellite7 - satellite
	instrument9 - instrument
	instrument10 - instrument
	satellite8 - satellite
	instrument11 - instrument
	instrument12 - instrument
	satellite9 - satellite
	instrument13 - instrument
	image0 - mode
	infrared11 - mode
	infrared3 - mode
	thermograph10 - mode
	thermograph14 - mode
	spectrograph9 - mode
	image1 - mode
	thermograph12 - mode
	spectrograph4 - mode
	image13 - mode
	spectrograph7 - mode
	thermograph2 - mode
	thermograph5 - mode
	image6 - mode
	spectrograph8 - mode
	Star1 - direction
	Star0 - direction
	Planet2 - direction
	Star3 - direction
	Star4 - direction
	Planet5 - direction
	Planet6 - direction
	Star7 - direction
	Star8 - direction
	Planet9 - direction
	Planet10 - direction
	Star11 - direction
	Star12 - direction
	Star13 - direction
	Planet14 - direction
	Planet15 - direction
	Phenomenon16 - direction
	Planet17 - direction
	Planet18 - direction
	Star19 - direction
	Planet20 - direction
	Phenomenon21 - direction
	Phenomenon22 - direction
	Planet23 - direction
	Planet24 - direction
	Star25 - direction
	Phenomenon26 - direction
	Planet27 - direction
	Planet28 - direction
	Planet29 - direction
	Star30 - direction
	Planet31 - direction
	Phenomenon32 - direction
	Star33 - direction
	Planet34 - direction
	Planet35 - direction
	Phenomenon36 - direction
	Star37 - direction
	Phenomenon38 - direction
	Star39 - direction
	Star40 - direction
	Star41 - direction
	Star42 - direction
	Planet43 - direction
	Planet44 - direction
	Phenomenon45 - direction
	Planet46 - direction
	Star47 - direction
	Planet48 - direction
	Planet49 - direction
	Phenomenon50 - direction
	Star51 - direction
	Phenomenon52 - direction
	Planet53 - direction
	Phenomenon54 - direction
	Star55 - direction
	Star56 - direction
	Planet57 - direction
	Planet58 - direction
	Star59 - direction
	Planet60 - direction
	Phenomenon61 - direction
	Planet62 - direction
	Planet63 - direction
	Planet64 - direction
	Star65 - direction
	Planet66 - direction
	Planet67 - direction
	Star68 - direction
	Star69 - direction
	Star70 - direction
	Planet71 - direction
	Planet72 - direction
	Star73 - direction
	Phenomenon74 - direction
	Phenomenon75 - direction
	Planet76 - direction
	Star77 - direction
	Star78 - direction
	Star79 - direction
	Star80 - direction
	Star81 - direction
	Star82 - direction
	Star83 - direction
	Planet84 - direction
	Planet85 - direction
	Planet86 - direction
	Phenomenon87 - direction
	Planet88 - direction
	Planet89 - direction
	Planet90 - direction
	Planet91 - direction
	Star92 - direction
	Planet93 - direction
	Planet94 - direction
	Star95 - direction
	Star96 - direction
	Planet97 - direction
	Star98 - direction
	Phenomenon99 - direction
	Planet100 - direction
	Phenomenon101 - direction
	Star102 - direction
	Phenomenon103 - direction
	Phenomenon104 - direction
	Phenomenon105 - direction
	Planet106 - direction
	Phenomenon107 - direction
	Planet108 - direction
	Star109 - direction
	Planet110 - direction
	Phenomenon111 - direction
	Phenomenon112 - direction
	Star113 - direction
	Star114 - direction
	Star115 - direction
	Star116 - direction
	Phenomenon117 - direction
	Star118 - direction
	Star119 - direction
	Planet120 - direction
	Planet121 - direction
	Planet122 - direction
	Star123 - direction
	Phenomenon124 - direction
	Phenomenon125 - direction
	Phenomenon126 - direction
	Star127 - direction
	Planet128 - direction
	Phenomenon129 - direction
	Star130 - direction
	Phenomenon131 - direction
	Planet132 - direction
	Planet133 - direction
	Star134 - direction
	Star135 - direction
	Phenomenon136 - direction
	Phenomenon137 - direction
	Planet138 - direction
	Planet139 - direction
	Star140 - direction
	Star141 - direction
)
(:init
	(supports instrument0 thermograph12)
	(calibration_target instrument0 Star1)
	(supports instrument1 spectrograph8)
	(calibration_target instrument1 Star0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet63)
	(supports instrument2 infrared11)
	(calibration_target instrument2 Star0)
	(on_board instrument2 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star11)
	(supports instrument3 thermograph12)
	(supports instrument3 thermograph14)
	(supports instrument3 infrared11)
	(calibration_target instrument3 Star1)
	(on_board instrument3 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon45)
	(supports instrument4 spectrograph8)
	(supports instrument4 image1)
	(calibration_target instrument4 Star1)
	(on_board instrument4 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet24)
	(supports instrument5 thermograph14)
	(calibration_target instrument5 Star1)
	(on_board instrument5 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star81)
	(supports instrument6 image13)
	(supports instrument6 thermograph12)
	(supports instrument6 infrared3)
	(calibration_target instrument6 Star1)
	(supports instrument7 spectrograph9)
	(supports instrument7 thermograph10)
	(calibration_target instrument7 Star1)
	(on_board instrument6 satellite5)
	(on_board instrument7 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Phenomenon45)
	(supports instrument8 spectrograph8)
	(supports instrument8 image13)
	(supports instrument8 thermograph14)
	(calibration_target instrument8 Star0)
	(on_board instrument8 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Phenomenon111)
	(supports instrument9 spectrograph7)
	(supports instrument9 spectrograph9)
	(calibration_target instrument9 Star0)
	(supports instrument10 spectrograph8)
	(supports instrument10 thermograph12)
	(supports instrument10 image1)
	(calibration_target instrument10 Star1)
	(on_board instrument9 satellite7)
	(on_board instrument10 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Planet128)
	(supports instrument11 spectrograph4)
	(calibration_target instrument11 Star1)
	(supports instrument12 thermograph2)
	(supports instrument12 spectrograph7)
	(supports instrument12 image13)
	(calibration_target instrument12 Star0)
	(on_board instrument11 satellite8)
	(on_board instrument12 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star82)
	(supports instrument13 spectrograph8)
	(supports instrument13 image6)
	(supports instrument13 thermograph5)
	(calibration_target instrument13 Star0)
	(on_board instrument13 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Planet29)
)
(:goal (and
	(pointing satellite0 Star1)
	(pointing satellite1 Planet35)
	(pointing satellite2 Planet6)
	(pointing satellite4 Star51)
	(pointing satellite6 Star3)
	(pointing satellite9 Planet84)
	(have_image Planet2 infrared3)
	(have_image Planet2 thermograph12)
	(have_image Star3 thermograph12)
	(have_image Star3 thermograph14)
	(have_image Star3 spectrograph9)
	(have_image Star3 spectrograph7)
	(have_image Star3 image1)
	(have_image Star4 thermograph5)
	(have_image Star4 infrared3)
	(have_image Star4 spectrograph4)
	(have_image Planet5 infrared3)
	(have_image Planet5 thermograph10)
	(have_image Planet5 spectrograph7)
	(have_image Star7 image13)
	(have_image Star7 image1)
	(have_image Star7 image6)
	(have_image Star7 spectrograph9)
	(have_image Star8 thermograph12)
	(have_image Star8 infrared3)
	(have_image Star8 image6)
	(have_image Planet9 image13)
	(have_image Planet10 image13)
	(have_image Planet10 thermograph12)
	(have_image Planet10 spectrograph9)
	(have_image Planet10 infrared3)
	(have_image Star11 spectrograph4)
	(have_image Star12 spectrograph7)
	(have_image Star13 thermograph2)
	(have_image Star13 spectrograph4)
	(have_image Star13 spectrograph7)
	(have_image Star13 image13)
	(have_image Planet14 infrared3)
	(have_image Planet14 image1)
	(have_image Planet14 thermograph10)
	(have_image Planet15 thermograph5)
	(have_image Planet15 image13)
	(have_image Phenomenon16 thermograph5)
	(have_image Phenomenon16 infrared11)
	(have_image Phenomenon16 spectrograph7)
	(have_image Planet17 spectrograph4)
	(have_image Planet18 spectrograph8)
	(have_image Planet18 thermograph10)
	(have_image Star19 infrared11)
	(have_image Planet20 image6)
	(have_image Planet20 thermograph14)
	(have_image Planet20 thermograph10)
	(have_image Phenomenon21 spectrograph9)
	(have_image Phenomenon21 thermograph12)
	(have_image Phenomenon22 spectrograph4)
	(have_image Phenomenon22 thermograph2)
	(have_image Planet23 thermograph2)
	(have_image Planet23 infrared11)
	(have_image Planet23 thermograph10)
	(have_image Planet23 image6)
	(have_image Planet24 image13)
	(have_image Planet24 spectrograph9)
	(have_image Star25 thermograph14)
	(have_image Star25 thermograph5)
	(have_image Phenomenon26 image1)
	(have_image Phenomenon26 infrared3)
	(have_image Phenomenon26 spectrograph7)
	(have_image Planet27 infrared3)
	(have_image Planet28 thermograph5)
	(have_image Planet28 image13)
	(have_image Planet28 spectrograph9)
	(have_image Planet29 spectrograph4)
	(have_image Planet29 spectrograph9)
	(have_image Star30 thermograph10)
	(have_image Star30 infrared3)
	(have_image Star30 infrared11)
	(have_image Planet31 spectrograph9)
	(have_image Planet31 thermograph14)
	(have_image Planet31 thermograph2)
	(have_image Phenomenon32 thermograph5)
	(have_image Phenomenon32 thermograph14)
	(have_image Star33 spectrograph4)
	(have_image Star33 spectrograph7)
	(have_image Star33 thermograph5)
	(have_image Star33 image1)
	(have_image Planet34 spectrograph7)
	(have_image Planet34 thermograph10)
	(have_image Planet34 spectrograph4)
	(have_image Planet34 thermograph12)
	(have_image Planet34 image1)
	(have_image Planet35 thermograph10)
	(have_image Planet35 thermograph2)
	(have_image Planet35 infrared3)
	(have_image Planet35 thermograph12)
	(have_image Phenomenon36 infrared3)
	(have_image Phenomenon36 spectrograph4)
	(have_image Phenomenon36 image1)
	(have_image Phenomenon36 image6)
	(have_image Star37 image6)
	(have_image Star37 thermograph10)
	(have_image Star37 infrared3)
	(have_image Star37 image1)
	(have_image Phenomenon38 spectrograph8)
	(have_image Phenomenon38 infrared3)
	(have_image Phenomenon38 thermograph5)
	(have_image Phenomenon38 image1)
	(have_image Phenomenon38 image6)
	(have_image Star39 spectrograph8)
	(have_image Star39 infrared3)
	(have_image Star40 image6)
	(have_image Star40 image1)
	(have_image Star40 image13)
	(have_image Star40 spectrograph8)
	(have_image Star40 spectrograph7)
	(have_image Star41 thermograph10)
	(have_image Star41 image13)
	(have_image Star42 thermograph14)
	(have_image Star42 spectrograph7)
	(have_image Planet43 spectrograph4)
	(have_image Planet44 thermograph10)
	(have_image Planet44 infrared3)
	(have_image Phenomenon45 image13)
	(have_image Phenomenon45 image6)
	(have_image Star47 spectrograph8)
	(have_image Star47 spectrograph4)
	(have_image Star47 image1)
	(have_image Star47 thermograph10)
	(have_image Star47 spectrograph9)
	(have_image Planet48 image13)
	(have_image Planet49 infrared11)
	(have_image Planet49 spectrograph8)
	(have_image Phenomenon50 spectrograph8)
	(have_image Phenomenon50 image1)
	(have_image Phenomenon50 infrared3)
	(have_image Phenomenon50 image6)
	(have_image Star51 thermograph12)
	(have_image Star51 spectrograph8)
	(have_image Star51 spectrograph7)
	(have_image Star51 image13)
	(have_image Phenomenon52 thermograph10)
	(have_image Phenomenon52 infrared3)
	(have_image Phenomenon52 image1)
	(have_image Planet53 spectrograph4)
	(have_image Planet53 image1)
	(have_image Planet53 thermograph5)
	(have_image Phenomenon54 spectrograph4)
	(have_image Phenomenon54 infrared11)
	(have_image Star55 spectrograph4)
	(have_image Star55 image6)
	(have_image Star55 spectrograph8)
	(have_image Star55 thermograph10)
	(have_image Star55 infrared3)
	(have_image Star56 image1)
	(have_image Star56 spectrograph7)
	(have_image Star56 thermograph12)
	(have_image Star56 spectrograph9)
	(have_image Planet57 image1)
	(have_image Planet57 thermograph2)
	(have_image Planet57 thermograph10)
	(have_image Planet57 infrared3)
	(have_image Planet58 spectrograph8)
	(have_image Planet58 thermograph12)
	(have_image Planet60 image13)
	(have_image Phenomenon61 thermograph10)
	(have_image Phenomenon61 image6)
	(have_image Phenomenon61 thermograph5)
	(have_image Phenomenon61 infrared3)
	(have_image Phenomenon61 spectrograph4)
	(have_image Planet62 spectrograph8)
	(have_image Planet63 infrared3)
	(have_image Planet63 spectrograph9)
	(have_image Planet64 thermograph2)
	(have_image Planet64 image1)
	(have_image Star65 spectrograph4)
	(have_image Star65 spectrograph7)
	(have_image Star65 thermograph2)
	(have_image Planet66 thermograph5)
	(have_image Planet66 thermograph12)
	(have_image Planet66 image13)
	(have_image Planet66 image1)
	(have_image Planet66 infrared11)
	(have_image Star68 spectrograph8)
	(have_image Star68 spectrograph4)
	(have_image Star68 infrared11)
	(have_image Star68 thermograph2)
	(have_image Star69 thermograph10)
	(have_image Star69 spectrograph8)
	(have_image Star69 image6)
	(have_image Star69 spectrograph4)
	(have_image Star69 spectrograph9)
	(have_image Star70 image6)
	(have_image Star70 infrared11)
	(have_image Planet71 infrared11)
	(have_image Planet71 thermograph12)
	(have_image Planet72 image13)
	(have_image Planet72 infrared11)
	(have_image Planet72 infrared3)
	(have_image Star73 image6)
	(have_image Phenomenon74 infrared3)
	(have_image Phenomenon74 thermograph10)
	(have_image Phenomenon74 image6)
	(have_image Phenomenon74 thermograph2)
	(have_image Star77 image13)
	(have_image Star77 thermograph2)
	(have_image Star78 spectrograph7)
	(have_image Star78 infrared11)
	(have_image Star80 infrared3)
	(have_image Star81 spectrograph9)
	(have_image Star82 spectrograph7)
	(have_image Star82 spectrograph4)
	(have_image Star83 thermograph2)
	(have_image Star83 image6)
	(have_image Planet84 thermograph12)
	(have_image Planet85 infrared3)
	(have_image Planet85 image1)
	(have_image Planet85 infrared11)
	(have_image Planet85 spectrograph9)
	(have_image Planet86 image1)
	(have_image Planet86 image6)
	(have_image Planet86 spectrograph9)
	(have_image Phenomenon87 image13)
	(have_image Planet88 image13)
	(have_image Planet88 spectrograph4)
	(have_image Planet90 thermograph5)
	(have_image Planet90 spectrograph9)
	(have_image Planet90 image1)
	(have_image Planet90 thermograph14)
	(have_image Planet91 image13)
	(have_image Planet91 thermograph12)
	(have_image Planet91 thermograph2)
	(have_image Star92 spectrograph9)
	(have_image Star92 image1)
	(have_image Star92 thermograph12)
	(have_image Star92 thermograph10)
	(have_image Star92 thermograph2)
	(have_image Planet94 thermograph12)
	(have_image Planet94 image1)
	(have_image Planet94 spectrograph9)
	(have_image Planet94 thermograph5)
	(have_image Planet94 spectrograph4)
	(have_image Star95 infrared3)
	(have_image Star95 image6)
	(have_image Star95 image1)
	(have_image Star95 spectrograph4)
	(have_image Star95 thermograph12)
	(have_image Star96 thermograph2)
	(have_image Star96 image6)
	(have_image Star96 spectrograph8)
	(have_image Star96 thermograph14)
	(have_image Star96 thermograph5)
	(have_image Planet97 thermograph12)
	(have_image Planet97 image1)
	(have_image Planet97 thermograph14)
	(have_image Star98 image1)
	(have_image Phenomenon99 thermograph5)
	(have_image Phenomenon99 thermograph10)
	(have_image Phenomenon99 infrared11)
	(have_image Phenomenon99 image1)
	(have_image Planet100 image1)
	(have_image Planet100 spectrograph4)
	(have_image Phenomenon101 thermograph14)
	(have_image Phenomenon101 spectrograph8)
	(have_image Phenomenon101 image6)
	(have_image Star102 thermograph5)
	(have_image Star102 spectrograph4)
	(have_image Phenomenon103 spectrograph9)
	(have_image Phenomenon103 spectrograph8)
	(have_image Phenomenon103 thermograph12)
	(have_image Phenomenon103 image6)
	(have_image Phenomenon103 thermograph10)
	(have_image Phenomenon105 thermograph5)
	(have_image Phenomenon105 thermograph10)
	(have_image Phenomenon105 spectrograph4)
	(have_image Phenomenon105 infrared11)
	(have_image Planet106 thermograph10)
	(have_image Planet106 spectrograph8)
	(have_image Planet106 spectrograph9)
	(have_image Planet106 thermograph12)
	(have_image Planet106 thermograph2)
	(have_image Phenomenon107 thermograph5)
	(have_image Planet108 thermograph10)
	(have_image Planet108 spectrograph8)
	(have_image Planet108 image6)
	(have_image Star109 spectrograph8)
	(have_image Star109 thermograph2)
	(have_image Star109 spectrograph4)
	(have_image Planet110 infrared11)
	(have_image Planet110 image1)
	(have_image Planet110 thermograph10)
	(have_image Planet110 infrared3)
	(have_image Planet110 image13)
	(have_image Phenomenon112 image1)
	(have_image Phenomenon112 spectrograph7)
	(have_image Phenomenon112 spectrograph4)
	(have_image Star113 image6)
	(have_image Star113 thermograph2)
	(have_image Star113 thermograph5)
	(have_image Star113 thermograph12)
	(have_image Star114 spectrograph7)
	(have_image Star114 thermograph2)
	(have_image Star114 thermograph5)
	(have_image Star115 infrared11)
	(have_image Star115 spectrograph4)
	(have_image Star115 infrared3)
	(have_image Star116 spectrograph9)
	(have_image Star116 image1)
	(have_image Star116 thermograph10)
	(have_image Star116 spectrograph4)
	(have_image Phenomenon117 image1)
	(have_image Phenomenon117 thermograph14)
	(have_image Phenomenon117 infrared3)
	(have_image Star118 spectrograph4)
	(have_image Star118 thermograph10)
	(have_image Star119 infrared3)
	(have_image Planet120 spectrograph8)
	(have_image Planet120 thermograph2)
	(have_image Planet120 infrared3)
	(have_image Planet121 spectrograph8)
	(have_image Planet121 thermograph5)
	(have_image Planet121 infrared3)
	(have_image Planet121 spectrograph4)
	(have_image Planet122 infrared3)
	(have_image Planet122 thermograph10)
	(have_image Star123 thermograph2)
	(have_image Star123 infrared3)
	(have_image Star123 image13)
	(have_image Star123 spectrograph4)
	(have_image Star123 infrared11)
	(have_image Phenomenon125 thermograph12)
	(have_image Phenomenon125 image6)
	(have_image Phenomenon126 thermograph10)
	(have_image Phenomenon126 infrared3)
	(have_image Phenomenon126 thermograph14)
	(have_image Phenomenon126 thermograph5)
	(have_image Phenomenon126 thermograph12)
	(have_image Star127 thermograph12)
	(have_image Star127 thermograph10)
	(have_image Star127 infrared3)
	(have_image Star127 thermograph2)
	(have_image Star127 spectrograph8)
	(have_image Planet128 thermograph5)
	(have_image Planet128 spectrograph8)
	(have_image Planet128 image13)
	(have_image Planet128 image6)
	(have_image Planet128 infrared11)
	(have_image Phenomenon129 thermograph12)
	(have_image Phenomenon129 thermograph10)
	(have_image Phenomenon129 thermograph5)
	(have_image Star130 thermograph10)
	(have_image Star130 infrared3)
	(have_image Star130 thermograph14)
	(have_image Star130 thermograph5)
	(have_image Phenomenon131 image1)
	(have_image Phenomenon131 spectrograph9)
	(have_image Phenomenon131 spectrograph4)
	(have_image Phenomenon131 thermograph2)
	(have_image Phenomenon131 thermograph12)
	(have_image Planet132 thermograph12)
	(have_image Planet132 infrared3)
	(have_image Planet133 thermograph2)
	(have_image Planet133 infrared11)
	(have_image Star134 thermograph12)
	(have_image Star134 image6)
	(have_image Star134 thermograph5)
	(have_image Star134 thermograph10)
	(have_image Star135 spectrograph9)
	(have_image Star135 image6)
	(have_image Star135 infrared3)
	(have_image Phenomenon136 thermograph14)
	(have_image Phenomenon136 spectrograph7)
	(have_image Phenomenon136 spectrograph8)
	(have_image Phenomenon137 thermograph5)
	(have_image Planet139 image6)
	(have_image Planet139 spectrograph8)
	(have_image Planet139 thermograph12)
	(have_image Star140 thermograph14)
	(have_image Star140 thermograph2)
	(have_image Star140 spectrograph8)
	(have_image Star140 thermograph5)
	(have_image Star141 thermograph12)
	(have_image Star141 thermograph2)
	(have_image Star141 infrared3)
	(have_image Star141 thermograph14)
))

)
