(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	satellite2 - satellite
	instrument3 - instrument
	satellite3 - satellite
	instrument4 - instrument
	satellite4 - satellite
	instrument5 - instrument
	instrument6 - instrument
	satellite5 - satellite
	instrument7 - instrument
	satellite6 - satellite
	instrument8 - instrument
	satellite7 - satellite
	instrument9 - instrument
	instrument10 - instrument
	satellite8 - satellite
	instrument11 - instrument
	satellite9 - satellite
	instrument12 - instrument
	satellite10 - satellite
	instrument13 - instrument
	instrument14 - instrument
	image18 - mode
	image8 - mode
	image12 - mode
	spectrograph0 - mode
	infrared6 - mode
	image4 - mode
	spectrograph11 - mode
	thermograph9 - mode
	spectrograph1 - mode
	thermograph19 - mode
	image5 - mode
	thermograph15 - mode
	spectrograph3 - mode
	infrared10 - mode
	spectrograph2 - mode
	thermograph14 - mode
	spectrograph16 - mode
	spectrograph17 - mode
	infrared7 - mode
	spectrograph13 - mode
	GroundStation1 - direction
	Star0 - direction
	Planet2 - direction
	Star3 - direction
	Phenomenon4 - direction
	Phenomenon5 - direction
	Planet6 - direction
	Star7 - direction
	Phenomenon8 - direction
	Phenomenon9 - direction
	Star10 - direction
	Phenomenon11 - direction
	Star12 - direction
	Planet13 - direction
	Planet14 - direction
	Planet15 - direction
	Planet16 - direction
	Planet17 - direction
	Planet18 - direction
	Planet19 - direction
	Phenomenon20 - direction
	Planet21 - direction
	Star22 - direction
	Phenomenon23 - direction
	Star24 - direction
	Planet25 - direction
	Planet26 - direction
	Star27 - direction
	Planet28 - direction
	Star29 - direction
	Planet30 - direction
	Phenomenon31 - direction
	Phenomenon32 - direction
	Phenomenon33 - direction
	Star34 - direction
	Phenomenon35 - direction
	Star36 - direction
	Star37 - direction
	Planet38 - direction
	Phenomenon39 - direction
	Planet40 - direction
	Phenomenon41 - direction
	Phenomenon42 - direction
	Planet43 - direction
	Phenomenon44 - direction
	Star45 - direction
	Planet46 - direction
	Phenomenon47 - direction
	Star48 - direction
	Phenomenon49 - direction
	Planet50 - direction
	Planet51 - direction
	Planet52 - direction
	Planet53 - direction
	Phenomenon54 - direction
	Phenomenon55 - direction
	Planet56 - direction
	Star57 - direction
	Planet58 - direction
	Phenomenon59 - direction
	Phenomenon60 - direction
	Star61 - direction
	Planet62 - direction
	Star63 - direction
	Star64 - direction
	Planet65 - direction
	Phenomenon66 - direction
	Phenomenon67 - direction
	Star68 - direction
	Planet69 - direction
	Phenomenon70 - direction
	Planet71 - direction
	Phenomenon72 - direction
	Phenomenon73 - direction
	Planet74 - direction
	Phenomenon75 - direction
	Phenomenon76 - direction
	Phenomenon77 - direction
	Planet78 - direction
	Phenomenon79 - direction
	Phenomenon80 - direction
	Planet81 - direction
	Planet82 - direction
	Phenomenon83 - direction
	Star84 - direction
	Planet85 - direction
	Planet86 - direction
	Planet87 - direction
	Planet88 - direction
	Planet89 - direction
	Star90 - direction
	Planet91 - direction
	Phenomenon92 - direction
	Phenomenon93 - direction
	Star94 - direction
	Phenomenon95 - direction
	Star96 - direction
	Planet97 - direction
	Phenomenon98 - direction
	Phenomenon99 - direction
	Planet100 - direction
	Phenomenon101 - direction
	Phenomenon102 - direction
	Planet103 - direction
	Phenomenon104 - direction
	Star105 - direction
	Planet106 - direction
	Planet107 - direction
	Star108 - direction
	Planet109 - direction
	Phenomenon110 - direction
	Star111 - direction
	Star112 - direction
	Planet113 - direction
	Star114 - direction
	Planet115 - direction
	Planet116 - direction
	Phenomenon117 - direction
	Phenomenon118 - direction
	Star119 - direction
	Planet120 - direction
	Star121 - direction
	Planet122 - direction
	Phenomenon123 - direction
	Star124 - direction
	Planet125 - direction
	Star126 - direction
	Phenomenon127 - direction
	Phenomenon128 - direction
	Planet129 - direction
	Phenomenon130 - direction
	Phenomenon131 - direction
	Phenomenon132 - direction
	Planet133 - direction
	Star134 - direction
	Planet135 - direction
	Star136 - direction
	Star137 - direction
	Planet138 - direction
	Star139 - direction
	Phenomenon140 - direction
	Phenomenon141 - direction
	Phenomenon142 - direction
	Phenomenon143 - direction
	Star144 - direction
	Phenomenon145 - direction
	Star146 - direction
	Star147 - direction
	Star148 - direction
	Planet149 - direction
	Planet150 - direction
	Planet151 - direction
	Planet152 - direction
	Phenomenon153 - direction
	Star154 - direction
	Star155 - direction
	Star156 - direction
	Phenomenon157 - direction
	Planet158 - direction
	Phenomenon159 - direction
	Planet160 - direction
	Planet161 - direction
)
(:init
	(supports instrument0 spectrograph17)
	(supports instrument0 spectrograph16)
	(calibration_target instrument0 Star0)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet158)
	(supports instrument1 spectrograph2)
	(supports instrument1 infrared7)
	(supports instrument1 thermograph9)
	(calibration_target instrument1 GroundStation1)
	(supports instrument2 image5)
	(supports instrument2 infrared6)
	(supports instrument2 thermograph15)
	(calibration_target instrument2 GroundStation1)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Phenomenon131)
	(supports instrument3 spectrograph13)
	(supports instrument3 image4)
	(supports instrument3 spectrograph3)
	(calibration_target instrument3 Star0)
	(on_board instrument3 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Planet71)
	(supports instrument4 thermograph9)
	(supports instrument4 spectrograph11)
	(calibration_target instrument4 Star0)
	(on_board instrument4 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon123)
	(supports instrument5 infrared10)
	(supports instrument5 spectrograph1)
	(supports instrument5 thermograph9)
	(calibration_target instrument5 Star0)
	(supports instrument6 thermograph19)
	(calibration_target instrument6 GroundStation1)
	(on_board instrument5 satellite4)
	(on_board instrument6 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet86)
	(supports instrument7 thermograph15)
	(supports instrument7 image5)
	(supports instrument7 infrared7)
	(calibration_target instrument7 Star0)
	(on_board instrument7 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star154)
	(supports instrument8 spectrograph13)
	(calibration_target instrument8 Star0)
	(on_board instrument8 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Phenomenon9)
	(supports instrument9 spectrograph2)
	(calibration_target instrument9 GroundStation1)
	(supports instrument10 infrared10)
	(supports instrument10 spectrograph16)
	(supports instrument10 spectrograph3)
	(calibration_target instrument10 Star0)
	(on_board instrument9 satellite7)
	(on_board instrument10 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Planet161)
	(supports instrument11 thermograph14)
	(supports instrument11 spectrograph2)
	(calibration_target instrument11 GroundStation1)
	(on_board instrument11 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star61)
	(supports instrument12 spectrograph16)
	(calibration_target instrument12 GroundStation1)
	(on_board instrument12 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Phenomenon39)
	(supports instrument13 infrared7)
	(supports instrument13 spectrograph13)
	(supports instrument13 spectrograph17)
	(calibration_target instrument13 Star0)
	(supports instrument14 spectrograph13)
	(calibration_target instrument14 Star0)
	(on_board instrument13 satellite10)
	(on_board instrument14 satellite10)
	(power_avail satellite10)
	(pointing satellite10 Star29)
)
(:goal (and
	(pointing satellite1 Planet109)
	(pointing satellite3 Planet38)
	(pointing satellite5 Star134)
	(pointing satellite8 Phenomenon143)
	(have_image Planet2 infrared6)
	(have_image Star3 spectrograph2)
	(have_image Phenomenon4 infrared7)
	(have_image Phenomenon5 spectrograph13)
	(have_image Planet6 infrared10)
	(have_image Planet6 image5)
	(have_image Planet6 thermograph19)
	(have_image Star7 infrared7)
	(have_image Star7 thermograph19)
	(have_image Star7 spectrograph11)
	(have_image Star7 thermograph15)
	(have_image Star7 spectrograph1)
	(have_image Star7 image4)
	(have_image Phenomenon8 spectrograph17)
	(have_image Phenomenon9 spectrograph13)
	(have_image Phenomenon9 infrared6)
	(have_image Phenomenon9 image5)
	(have_image Phenomenon9 spectrograph1)
	(have_image Star10 spectrograph3)
	(have_image Star10 spectrograph11)
	(have_image Star10 spectrograph17)
	(have_image Star10 spectrograph16)
	(have_image Phenomenon11 image4)
	(have_image Phenomenon11 infrared6)
	(have_image Phenomenon11 image5)
	(have_image Star12 infrared10)
	(have_image Star12 thermograph19)
	(have_image Star12 infrared7)
	(have_image Star12 spectrograph2)
	(have_image Planet13 image5)
	(have_image Planet13 spectrograph3)
	(have_image Planet14 spectrograph16)
	(have_image Planet16 infrared10)
	(have_image Planet16 spectrograph13)
	(have_image Planet17 thermograph19)
	(have_image Planet18 infrared10)
	(have_image Planet18 image4)
	(have_image Planet18 spectrograph17)
	(have_image Planet19 infrared6)
	(have_image Planet19 spectrograph11)
	(have_image Planet19 image5)
	(have_image Planet19 spectrograph3)
	(have_image Planet19 spectrograph13)
	(have_image Planet19 spectrograph2)
	(have_image Phenomenon20 spectrograph13)
	(have_image Phenomenon20 thermograph19)
	(have_image Phenomenon20 spectrograph16)
	(have_image Planet21 thermograph14)
	(have_image Planet21 infrared6)
	(have_image Planet21 image5)
	(have_image Star22 infrared10)
	(have_image Star22 thermograph15)
	(have_image Star22 spectrograph2)
	(have_image Phenomenon23 spectrograph17)
	(have_image Star24 image4)
	(have_image Star24 spectrograph1)
	(have_image Star24 infrared7)
	(have_image Star24 thermograph19)
	(have_image Star24 thermograph14)
	(have_image Planet25 spectrograph17)
	(have_image Planet25 spectrograph11)
	(have_image Planet25 spectrograph13)
	(have_image Planet25 image5)
	(have_image Planet26 thermograph9)
	(have_image Star27 image4)
	(have_image Star27 spectrograph16)
	(have_image Star29 thermograph14)
	(have_image Star29 spectrograph3)
	(have_image Star29 thermograph9)
	(have_image Planet30 thermograph19)
	(have_image Phenomenon31 image5)
	(have_image Phenomenon31 thermograph9)
	(have_image Phenomenon31 thermograph15)
	(have_image Phenomenon31 spectrograph3)
	(have_image Phenomenon32 thermograph9)
	(have_image Phenomenon32 thermograph15)
	(have_image Phenomenon33 thermograph15)
	(have_image Star34 infrared6)
	(have_image Star34 thermograph9)
	(have_image Star34 spectrograph13)
	(have_image Star36 thermograph15)
	(have_image Star36 spectrograph17)
	(have_image Star36 spectrograph16)
	(have_image Star36 thermograph19)
	(have_image Star36 infrared6)
	(have_image Star37 image4)
	(have_image Star37 thermograph19)
	(have_image Planet38 thermograph9)
	(have_image Planet38 infrared6)
	(have_image Planet38 spectrograph3)
	(have_image Planet38 spectrograph11)
	(have_image Phenomenon39 thermograph9)
	(have_image Phenomenon39 image5)
	(have_image Planet40 thermograph9)
	(have_image Planet40 spectrograph11)
	(have_image Planet40 infrared7)
	(have_image Phenomenon41 thermograph19)
	(have_image Phenomenon41 spectrograph2)
	(have_image Phenomenon41 thermograph14)
	(have_image Phenomenon41 infrared10)
	(have_image Phenomenon41 spectrograph11)
	(have_image Phenomenon42 spectrograph1)
	(have_image Phenomenon42 thermograph19)
	(have_image Planet43 thermograph15)
	(have_image Planet43 spectrograph3)
	(have_image Planet43 image5)
	(have_image Planet43 spectrograph13)
	(have_image Planet43 infrared10)
	(have_image Star45 spectrograph1)
	(have_image Star45 spectrograph3)
	(have_image Star45 thermograph14)
	(have_image Planet46 spectrograph11)
	(have_image Planet46 infrared10)
	(have_image Star48 spectrograph2)
	(have_image Star48 thermograph9)
	(have_image Star48 spectrograph1)
	(have_image Star48 spectrograph17)
	(have_image Phenomenon49 infrared6)
	(have_image Phenomenon49 spectrograph2)
	(have_image Phenomenon49 infrared7)
	(have_image Planet50 infrared10)
	(have_image Planet50 image5)
	(have_image Planet50 thermograph9)
	(have_image Planet50 infrared6)
	(have_image Planet51 thermograph19)
	(have_image Planet51 spectrograph16)
	(have_image Planet51 spectrograph1)
	(have_image Planet52 thermograph14)
	(have_image Planet52 spectrograph3)
	(have_image Planet52 spectrograph17)
	(have_image Planet52 thermograph19)
	(have_image Phenomenon55 spectrograph13)
	(have_image Planet56 thermograph9)
	(have_image Star57 spectrograph13)
	(have_image Star57 infrared10)
	(have_image Star57 spectrograph11)
	(have_image Star57 image5)
	(have_image Phenomenon59 spectrograph13)
	(have_image Phenomenon59 spectrograph2)
	(have_image Phenomenon59 thermograph19)
	(have_image Phenomenon59 thermograph14)
	(have_image Phenomenon59 spectrograph11)
	(have_image Phenomenon60 infrared10)
	(have_image Phenomenon60 spectrograph11)
	(have_image Phenomenon60 image4)
	(have_image Star61 spectrograph3)
	(have_image Planet62 spectrograph11)
	(have_image Planet62 spectrograph13)
	(have_image Planet62 thermograph19)
	(have_image Star63 thermograph15)
	(have_image Star63 image5)
	(have_image Star63 spectrograph11)
	(have_image Star63 spectrograph2)
	(have_image Star63 thermograph14)
	(have_image Star64 spectrograph16)
	(have_image Star64 spectrograph1)
	(have_image Star64 spectrograph17)
	(have_image Planet65 spectrograph3)
	(have_image Planet65 spectrograph11)
	(have_image Planet65 spectrograph13)
	(have_image Planet65 infrared7)
	(have_image Phenomenon66 thermograph15)
	(have_image Phenomenon67 spectrograph2)
	(have_image Phenomenon67 thermograph15)
	(have_image Phenomenon67 image4)
	(have_image Star68 image5)
	(have_image Planet69 thermograph19)
	(have_image Planet69 spectrograph3)
	(have_image Phenomenon70 spectrograph16)
	(have_image Phenomenon70 image4)
	(have_image Phenomenon70 thermograph14)
	(have_image Phenomenon70 thermograph9)
	(have_image Planet71 thermograph9)
	(have_image Planet71 spectrograph16)
	(have_image Planet71 infrared10)
	(have_image Planet71 thermograph15)
	(have_image Phenomenon72 infrared10)
	(have_image Phenomenon73 image5)
	(have_image Phenomenon73 infrared7)
	(have_image Planet74 thermograph14)
	(have_image Planet74 image4)
	(have_image Phenomenon75 thermograph14)
	(have_image Phenomenon76 spectrograph3)
	(have_image Phenomenon76 image4)
	(have_image Planet78 infrared6)
	(have_image Planet78 spectrograph3)
	(have_image Planet78 image5)
	(have_image Planet78 thermograph9)
	(have_image Phenomenon79 infrared7)
	(have_image Phenomenon79 infrared6)
	(have_image Phenomenon79 spectrograph1)
	(have_image Phenomenon79 spectrograph3)
	(have_image Phenomenon80 spectrograph11)
	(have_image Phenomenon80 image5)
	(have_image Phenomenon80 spectrograph1)
	(have_image Phenomenon80 thermograph9)
	(have_image Planet81 thermograph14)
	(have_image Phenomenon83 spectrograph11)
	(have_image Phenomenon83 spectrograph17)
	(have_image Star84 thermograph9)
	(have_image Star84 infrared10)
	(have_image Star84 spectrograph17)
	(have_image Star84 spectrograph11)
	(have_image Planet86 spectrograph11)
	(have_image Planet87 infrared10)
	(have_image Planet88 spectrograph13)
	(have_image Planet88 spectrograph17)
	(have_image Planet88 image5)
	(have_image Planet88 spectrograph2)
	(have_image Planet88 thermograph15)
	(have_image Planet89 spectrograph2)
	(have_image Planet89 thermograph19)
	(have_image Planet89 infrared7)
	(have_image Planet89 spectrograph17)
	(have_image Planet91 infrared10)
	(have_image Planet91 spectrograph3)
	(have_image Planet91 spectrograph13)
	(have_image Planet91 infrared6)
	(have_image Planet91 spectrograph2)
	(have_image Phenomenon92 infrared6)
	(have_image Phenomenon93 infrared7)
	(have_image Phenomenon93 thermograph9)
	(have_image Star94 image5)
	(have_image Star94 spectrograph3)
	(have_image Star94 thermograph19)
	(have_image Star94 thermograph9)
	(have_image Star94 spectrograph13)
	(have_image Star96 spectrograph11)
	(have_image Star96 spectrograph3)
	(have_image Star96 spectrograph17)
	(have_image Planet97 infrared7)
	(have_image Planet97 spectrograph1)
	(have_image Planet97 spectrograph13)
	(have_image Planet100 spectrograph16)
	(have_image Planet100 image4)
	(have_image Phenomenon102 thermograph19)
	(have_image Phenomenon102 spectrograph11)
	(have_image Phenomenon102 thermograph15)
	(have_image Phenomenon102 infrared6)
	(have_image Planet103 thermograph19)
	(have_image Star105 spectrograph16)
	(have_image Star105 thermograph15)
	(have_image Star105 image4)
	(have_image Planet106 spectrograph11)
	(have_image Planet106 thermograph15)
	(have_image Planet107 thermograph14)
	(have_image Planet107 spectrograph13)
	(have_image Planet107 infrared6)
	(have_image Planet107 spectrograph17)
	(have_image Star108 thermograph14)
	(have_image Star108 spectrograph16)
	(have_image Star108 spectrograph2)
	(have_image Star108 spectrograph13)
	(have_image Phenomenon110 spectrograph3)
	(have_image Phenomenon110 thermograph19)
	(have_image Star111 spectrograph13)
	(have_image Star112 thermograph14)
	(have_image Star112 spectrograph3)
	(have_image Planet113 thermograph15)
	(have_image Star114 image4)
	(have_image Star114 thermograph14)
	(have_image Star114 spectrograph11)
	(have_image Planet115 spectrograph16)
	(have_image Planet115 image5)
	(have_image Planet115 thermograph15)
	(have_image Planet116 spectrograph2)
	(have_image Planet116 spectrograph3)
	(have_image Phenomenon117 spectrograph13)
	(have_image Phenomenon117 spectrograph16)
	(have_image Phenomenon117 thermograph9)
	(have_image Phenomenon117 spectrograph3)
	(have_image Phenomenon118 thermograph9)
	(have_image Star119 spectrograph3)
	(have_image Planet120 thermograph15)
	(have_image Star121 infrared10)
	(have_image Planet122 infrared10)
	(have_image Star124 spectrograph17)
	(have_image Star124 infrared6)
	(have_image Star124 spectrograph1)
	(have_image Star124 thermograph19)
	(have_image Star124 thermograph14)
	(have_image Planet125 image4)
	(have_image Star126 thermograph19)
	(have_image Phenomenon127 thermograph19)
	(have_image Phenomenon127 infrared7)
	(have_image Phenomenon128 thermograph14)
	(have_image Phenomenon128 thermograph15)
	(have_image Phenomenon128 spectrograph17)
	(have_image Phenomenon128 spectrograph16)
	(have_image Planet129 thermograph14)
	(have_image Planet129 thermograph9)
	(have_image Phenomenon130 spectrograph16)
	(have_image Phenomenon130 spectrograph2)
	(have_image Phenomenon130 infrared7)
	(have_image Phenomenon130 spectrograph17)
	(have_image Phenomenon130 infrared6)
	(have_image Phenomenon131 infrared7)
	(have_image Phenomenon131 thermograph14)
	(have_image Phenomenon131 spectrograph1)
	(have_image Phenomenon131 thermograph19)
	(have_image Phenomenon132 thermograph14)
	(have_image Phenomenon132 infrared6)
	(have_image Planet133 spectrograph16)
	(have_image Planet133 infrared6)
	(have_image Star134 spectrograph3)
	(have_image Star134 spectrograph16)
	(have_image Star136 spectrograph17)
	(have_image Star136 spectrograph1)
	(have_image Star136 thermograph15)
	(have_image Star137 image4)
	(have_image Planet138 spectrograph3)
	(have_image Planet138 image5)
	(have_image Planet138 thermograph19)
	(have_image Planet138 thermograph14)
	(have_image Star139 spectrograph13)
	(have_image Star139 infrared6)
	(have_image Star139 spectrograph2)
	(have_image Star139 spectrograph17)
	(have_image Phenomenon140 spectrograph3)
	(have_image Phenomenon140 infrared7)
	(have_image Phenomenon141 thermograph9)
	(have_image Phenomenon141 spectrograph13)
	(have_image Phenomenon142 spectrograph2)
	(have_image Phenomenon142 spectrograph3)
	(have_image Phenomenon142 spectrograph13)
	(have_image Phenomenon142 spectrograph11)
	(have_image Star144 spectrograph17)
	(have_image Star144 image5)
	(have_image Star144 spectrograph3)
	(have_image Phenomenon145 infrared7)
	(have_image Phenomenon145 spectrograph1)
	(have_image Phenomenon145 spectrograph11)
	(have_image Star147 spectrograph17)
	(have_image Star147 spectrograph3)
	(have_image Star147 spectrograph11)
	(have_image Star148 infrared10)
	(have_image Star148 image4)
	(have_image Star148 thermograph9)
	(have_image Star148 spectrograph13)
	(have_image Planet149 thermograph19)
	(have_image Planet149 spectrograph2)
	(have_image Planet149 spectrograph17)
	(have_image Planet149 spectrograph1)
	(have_image Planet150 image5)
	(have_image Planet150 infrared10)
	(have_image Planet150 thermograph9)
	(have_image Planet151 spectrograph13)
	(have_image Planet151 spectrograph1)
	(have_image Planet151 image5)
	(have_image Phenomenon153 spectrograph2)
	(have_image Phenomenon153 spectrograph16)
	(have_image Star154 spectrograph1)
	(have_image Star154 spectrograph11)
	(have_image Star154 infrared7)
	(have_image Star154 spectrograph16)
	(have_image Star155 spectrograph17)
	(have_image Star155 thermograph15)
	(have_image Planet158 spectrograph3)
	(have_image Phenomenon159 infrared6)
	(have_image Phenomenon159 spectrograph2)
	(have_image Phenomenon159 spectrograph11)
	(have_image Planet160 infrared7)
	(have_image Planet160 spectrograph13)
	(have_image Planet160 thermograph14)
	(have_image Planet160 spectrograph1)
	(have_image Planet161 image4)
	(have_image Planet161 infrared6)
	(have_image Planet161 spectrograph11)
	(have_image Planet161 spectrograph13)
	(have_image Planet161 spectrograph16)
))

)
