(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	satellite2 - satellite
	instrument4 - instrument
	satellite3 - satellite
	instrument5 - instrument
	instrument6 - instrument
	satellite4 - satellite
	instrument7 - instrument
	satellite5 - satellite
	instrument8 - instrument
	instrument9 - instrument
	satellite6 - satellite
	instrument10 - instrument
	instrument11 - instrument
	satellite7 - satellite
	instrument12 - instrument
	satellite8 - satellite
	instrument13 - instrument
	satellite9 - satellite
	instrument14 - instrument
	satellite10 - satellite
	instrument15 - instrument
	instrument16 - instrument
	infrared6 - mode
	infrared15 - mode
	thermograph7 - mode
	image9 - mode
	thermograph13 - mode
	thermograph16 - mode
	spectrograph19 - mode
	spectrograph8 - mode
	infrared11 - mode
	infrared4 - mode
	infrared12 - mode
	spectrograph18 - mode
	infrared14 - mode
	image1 - mode
	infrared3 - mode
	thermograph10 - mode
	infrared2 - mode
	spectrograph17 - mode
	spectrograph0 - mode
	spectrograph5 - mode
	Star0 - direction
	Star1 - direction
	Phenomenon2 - direction
	Star3 - direction
	Phenomenon4 - direction
	Planet5 - direction
	Planet6 - direction
	Star7 - direction
	Planet8 - direction
	Star9 - direction
	Planet10 - direction
	Star11 - direction
	Phenomenon12 - direction
	Phenomenon13 - direction
	Phenomenon14 - direction
	Star15 - direction
	Planet16 - direction
	Planet17 - direction
	Phenomenon18 - direction
	Planet19 - direction
	Star20 - direction
	Phenomenon21 - direction
	Phenomenon22 - direction
	Planet23 - direction
	Planet24 - direction
	Star25 - direction
	Phenomenon26 - direction
	Phenomenon27 - direction
	Star28 - direction
	Planet29 - direction
	Planet30 - direction
	Planet31 - direction
	Star32 - direction
	Phenomenon33 - direction
	Star34 - direction
	Star35 - direction
	Phenomenon36 - direction
	Phenomenon37 - direction
	Phenomenon38 - direction
	Phenomenon39 - direction
	Phenomenon40 - direction
	Star41 - direction
	Planet42 - direction
	Star43 - direction
	Planet44 - direction
	Star45 - direction
	Planet46 - direction
	Phenomenon47 - direction
	Planet48 - direction
	Planet49 - direction
	Planet50 - direction
	Phenomenon51 - direction
	Phenomenon52 - direction
	Star53 - direction
	Star54 - direction
	Star55 - direction
	Phenomenon56 - direction
	Planet57 - direction
	Planet58 - direction
	Phenomenon59 - direction
	Planet60 - direction
	Planet61 - direction
	Planet62 - direction
	Planet63 - direction
	Star64 - direction
	Phenomenon65 - direction
	Star66 - direction
	Planet67 - direction
	Planet68 - direction
	Planet69 - direction
	Planet70 - direction
	Phenomenon71 - direction
	Planet72 - direction
	Phenomenon73 - direction
	Phenomenon74 - direction
	Star75 - direction
	Star76 - direction
	Planet77 - direction
	Planet78 - direction
	Phenomenon79 - direction
	Planet80 - direction
	Star81 - direction
	Star82 - direction
	Planet83 - direction
	Phenomenon84 - direction
	Star85 - direction
	Planet86 - direction
	Planet87 - direction
	Planet88 - direction
	Planet89 - direction
	Planet90 - direction
	Star91 - direction
	Star92 - direction
	Phenomenon93 - direction
	Phenomenon94 - direction
	Planet95 - direction
	Star96 - direction
	Star97 - direction
	Phenomenon98 - direction
	Phenomenon99 - direction
	Planet100 - direction
	Star101 - direction
	Planet102 - direction
	Phenomenon103 - direction
	Phenomenon104 - direction
	Star105 - direction
	Star106 - direction
	Planet107 - direction
	Planet108 - direction
	Phenomenon109 - direction
	Planet110 - direction
	Planet111 - direction
	Planet112 - direction
	Planet113 - direction
	Star114 - direction
	Planet115 - direction
	Star116 - direction
	Planet117 - direction
	Phenomenon118 - direction
	Planet119 - direction
	Star120 - direction
	Star121 - direction
	Star122 - direction
	Planet123 - direction
	Star124 - direction
	Phenomenon125 - direction
	Star126 - direction
	Phenomenon127 - direction
	Planet128 - direction
	Phenomenon129 - direction
	Star130 - direction
	Phenomenon131 - direction
	Star132 - direction
	Planet133 - direction
	Star134 - direction
	Phenomenon135 - direction
	Star136 - direction
	Phenomenon137 - direction
	Planet138 - direction
	Phenomenon139 - direction
	Star140 - direction
	Star141 - direction
	Star142 - direction
	Planet143 - direction
	Planet144 - direction
	Planet145 - direction
	Phenomenon146 - direction
	Phenomenon147 - direction
	Planet148 - direction
	Star149 - direction
	Planet150 - direction
	Planet151 - direction
	Planet152 - direction
	Phenomenon153 - direction
	Phenomenon154 - direction
	Planet155 - direction
	Planet156 - direction
	Planet157 - direction
	Star158 - direction
	Planet159 - direction
	Star160 - direction
	Phenomenon161 - direction
)
(:init
	(supports instrument0 spectrograph0)
	(supports instrument0 thermograph16)
	(calibration_target instrument0 Star1)
	(supports instrument1 image1)
	(calibration_target instrument1 Star0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet67)
	(supports instrument2 image1)
	(calibration_target instrument2 Star1)
	(supports instrument3 spectrograph8)
	(supports instrument3 thermograph7)
	(calibration_target instrument3 Star1)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Planet86)
	(supports instrument4 infrared14)
	(supports instrument4 spectrograph0)
	(supports instrument4 thermograph7)
	(calibration_target instrument4 Star0)
	(on_board instrument4 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star81)
	(supports instrument5 image9)
	(calibration_target instrument5 Star1)
	(supports instrument6 thermograph16)
	(supports instrument6 infrared12)
	(supports instrument6 thermograph13)
	(calibration_target instrument6 Star0)
	(on_board instrument5 satellite3)
	(on_board instrument6 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon94)
	(supports instrument7 infrared11)
	(supports instrument7 infrared3)
	(supports instrument7 spectrograph19)
	(calibration_target instrument7 Star0)
	(on_board instrument7 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet148)
	(supports instrument8 infrared11)
	(supports instrument8 spectrograph8)
	(calibration_target instrument8 Star0)
	(supports instrument9 spectrograph0)
	(supports instrument9 spectrograph18)
	(supports instrument9 infrared12)
	(calibration_target instrument9 Star0)
	(on_board instrument8 satellite5)
	(on_board instrument9 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star35)
	(supports instrument10 infrared4)
	(supports instrument10 spectrograph18)
	(calibration_target instrument10 Star1)
	(supports instrument11 image1)
	(calibration_target instrument11 Star1)
	(on_board instrument10 satellite6)
	(on_board instrument11 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star20)
	(supports instrument12 infrared14)
	(supports instrument12 spectrograph18)
	(supports instrument12 infrared12)
	(calibration_target instrument12 Star0)
	(on_board instrument12 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star114)
	(supports instrument13 infrared3)
	(supports instrument13 image1)
	(calibration_target instrument13 Star0)
	(on_board instrument13 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Planet90)
	(supports instrument14 spectrograph0)
	(calibration_target instrument14 Star1)
	(on_board instrument14 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Planet87)
	(supports instrument15 spectrograph17)
	(supports instrument15 infrared2)
	(supports instrument15 thermograph10)
	(calibration_target instrument15 Star0)
	(supports instrument16 spectrograph5)
	(supports instrument16 spectrograph0)
	(calibration_target instrument16 Star1)
	(on_board instrument15 satellite10)
	(on_board instrument16 satellite10)
	(power_avail satellite10)
	(pointing satellite10 Phenomenon52)
)
(:goal (and
	(pointing satellite3 Phenomenon47)
	(pointing satellite4 Star54)
	(pointing satellite6 Planet100)
	(pointing satellite7 Star75)
	(pointing satellite8 Planet87)
	(pointing satellite10 Phenomenon37)
	(have_image Phenomenon2 infrared3)
	(have_image Phenomenon2 thermograph16)
	(have_image Phenomenon2 spectrograph0)
	(have_image Phenomenon2 thermograph7)
	(have_image Phenomenon2 spectrograph19)
	(have_image Phenomenon2 thermograph13)
	(have_image Star3 infrared4)
	(have_image Star3 spectrograph5)
	(have_image Star3 infrared3)
	(have_image Phenomenon4 thermograph13)
	(have_image Phenomenon4 thermograph7)
	(have_image Phenomenon4 spectrograph17)
	(have_image Planet5 thermograph13)
	(have_image Planet5 infrared12)
	(have_image Planet5 image1)
	(have_image Planet6 spectrograph5)
	(have_image Planet6 spectrograph19)
	(have_image Planet6 infrared4)
	(have_image Planet6 spectrograph0)
	(have_image Star7 image9)
	(have_image Star7 thermograph16)
	(have_image Star7 spectrograph0)
	(have_image Star7 thermograph7)
	(have_image Star7 infrared4)
	(have_image Planet8 spectrograph0)
	(have_image Planet8 spectrograph18)
	(have_image Star9 spectrograph17)
	(have_image Star9 image1)
	(have_image Star9 spectrograph18)
	(have_image Planet10 spectrograph18)
	(have_image Planet10 thermograph7)
	(have_image Star11 infrared14)
	(have_image Star11 spectrograph0)
	(have_image Star11 spectrograph19)
	(have_image Star11 spectrograph8)
	(have_image Star11 infrared4)
	(have_image Star11 infrared2)
	(have_image Phenomenon12 thermograph7)
	(have_image Phenomenon12 image1)
	(have_image Phenomenon12 thermograph16)
	(have_image Phenomenon12 infrared14)
	(have_image Phenomenon13 infrared2)
	(have_image Phenomenon13 spectrograph5)
	(have_image Phenomenon13 spectrograph19)
	(have_image Phenomenon13 spectrograph0)
	(have_image Star15 image1)
	(have_image Star15 infrared2)
	(have_image Star15 infrared4)
	(have_image Star15 spectrograph17)
	(have_image Planet16 spectrograph5)
	(have_image Planet16 infrared4)
	(have_image Planet16 infrared2)
	(have_image Planet16 spectrograph17)
	(have_image Planet16 infrared3)
	(have_image Planet17 image9)
	(have_image Planet17 infrared4)
	(have_image Planet17 spectrograph17)
	(have_image Planet17 spectrograph18)
	(have_image Planet17 spectrograph5)
	(have_image Planet17 infrared12)
	(have_image Phenomenon18 spectrograph5)
	(have_image Phenomenon18 infrared3)
	(have_image Phenomenon18 image9)
	(have_image Phenomenon18 thermograph16)
	(have_image Planet19 thermograph13)
	(have_image Planet19 image1)
	(have_image Planet19 spectrograph18)
	(have_image Planet19 infrared3)
	(have_image Planet19 spectrograph0)
	(have_image Star20 thermograph10)
	(have_image Star20 spectrograph17)
	(have_image Star20 infrared2)
	(have_image Star20 image9)
	(have_image Phenomenon21 thermograph13)
	(have_image Phenomenon21 image9)
	(have_image Phenomenon21 spectrograph18)
	(have_image Phenomenon21 spectrograph5)
	(have_image Phenomenon22 infrared4)
	(have_image Phenomenon22 thermograph10)
	(have_image Phenomenon22 image9)
	(have_image Planet23 infrared14)
	(have_image Planet23 thermograph13)
	(have_image Planet23 thermograph7)
	(have_image Planet24 infrared4)
	(have_image Planet24 spectrograph0)
	(have_image Planet24 spectrograph5)
	(have_image Planet24 infrared14)
	(have_image Star25 image1)
	(have_image Star25 spectrograph8)
	(have_image Star25 spectrograph17)
	(have_image Star25 infrared4)
	(have_image Star25 infrared3)
	(have_image Star25 thermograph16)
	(have_image Phenomenon26 spectrograph17)
	(have_image Phenomenon27 spectrograph0)
	(have_image Phenomenon27 spectrograph8)
	(have_image Phenomenon27 thermograph16)
	(have_image Phenomenon27 thermograph10)
	(have_image Star28 spectrograph8)
	(have_image Star28 thermograph7)
	(have_image Star28 spectrograph0)
	(have_image Star28 infrared12)
	(have_image Star28 thermograph16)
	(have_image Star28 infrared11)
	(have_image Planet30 spectrograph18)
	(have_image Planet30 infrared3)
	(have_image Planet30 thermograph7)
	(have_image Planet30 spectrograph17)
	(have_image Planet31 infrared11)
	(have_image Star32 spectrograph17)
	(have_image Star32 thermograph13)
	(have_image Star32 spectrograph5)
	(have_image Star32 spectrograph8)
	(have_image Star32 infrared11)
	(have_image Phenomenon33 infrared12)
	(have_image Phenomenon33 thermograph13)
	(have_image Phenomenon33 image9)
	(have_image Phenomenon33 thermograph7)
	(have_image Star34 image9)
	(have_image Star34 infrared3)
	(have_image Star34 infrared14)
	(have_image Star34 spectrograph0)
	(have_image Star35 infrared2)
	(have_image Star35 infrared14)
	(have_image Star35 spectrograph5)
	(have_image Star35 infrared12)
	(have_image Star35 spectrograph17)
	(have_image Phenomenon36 infrared4)
	(have_image Phenomenon36 spectrograph18)
	(have_image Phenomenon36 thermograph16)
	(have_image Phenomenon37 spectrograph0)
	(have_image Phenomenon38 spectrograph18)
	(have_image Phenomenon38 infrared11)
	(have_image Phenomenon39 image1)
	(have_image Phenomenon39 spectrograph0)
	(have_image Phenomenon39 infrared12)
	(have_image Phenomenon39 spectrograph19)
	(have_image Phenomenon39 spectrograph8)
	(have_image Phenomenon39 spectrograph17)
	(have_image Phenomenon40 spectrograph8)
	(have_image Star41 infrared12)
	(have_image Star41 thermograph13)
	(have_image Star41 spectrograph5)
	(have_image Star41 spectrograph19)
	(have_image Star41 spectrograph17)
	(have_image Star41 infrared2)
	(have_image Planet42 spectrograph5)
	(have_image Planet42 spectrograph18)
	(have_image Planet42 thermograph10)
	(have_image Planet42 infrared14)
	(have_image Planet42 infrared3)
	(have_image Planet42 thermograph13)
	(have_image Planet44 infrared2)
	(have_image Planet44 spectrograph5)
	(have_image Planet44 thermograph10)
	(have_image Planet44 spectrograph17)
	(have_image Planet44 thermograph13)
	(have_image Star45 spectrograph8)
	(have_image Star45 infrared12)
	(have_image Planet46 spectrograph0)
	(have_image Planet46 thermograph10)
	(have_image Planet46 image1)
	(have_image Planet46 spectrograph8)
	(have_image Planet46 spectrograph18)
	(have_image Planet46 image9)
	(have_image Planet48 infrared4)
	(have_image Planet48 image9)
	(have_image Planet48 spectrograph18)
	(have_image Planet48 spectrograph0)
	(have_image Planet48 thermograph10)
	(have_image Planet49 thermograph16)
	(have_image Planet50 image1)
	(have_image Planet50 infrared14)
	(have_image Phenomenon52 thermograph16)
	(have_image Phenomenon52 spectrograph17)
	(have_image Star54 infrared3)
	(have_image Star54 thermograph13)
	(have_image Star54 thermograph10)
	(have_image Star54 spectrograph8)
	(have_image Star54 spectrograph5)
	(have_image Star55 spectrograph19)
	(have_image Star55 infrared3)
	(have_image Star55 infrared14)
	(have_image Star55 spectrograph8)
	(have_image Star55 thermograph7)
	(have_image Star55 thermograph13)
	(have_image Phenomenon56 spectrograph17)
	(have_image Phenomenon56 image9)
	(have_image Planet57 infrared14)
	(have_image Planet57 image9)
	(have_image Planet57 spectrograph8)
	(have_image Planet57 infrared11)
	(have_image Phenomenon59 spectrograph8)
	(have_image Phenomenon59 thermograph13)
	(have_image Phenomenon59 spectrograph5)
	(have_image Phenomenon59 image9)
	(have_image Phenomenon59 infrared12)
	(have_image Planet61 thermograph13)
	(have_image Planet61 thermograph10)
	(have_image Planet61 thermograph7)
	(have_image Planet62 thermograph13)
	(have_image Planet62 infrared11)
	(have_image Planet62 infrared12)
	(have_image Planet63 spectrograph19)
	(have_image Planet63 image1)
	(have_image Star64 infrared11)
	(have_image Phenomenon65 spectrograph5)
	(have_image Phenomenon65 infrared14)
	(have_image Phenomenon65 infrared2)
	(have_image Phenomenon65 infrared4)
	(have_image Star66 spectrograph19)
	(have_image Planet67 infrared4)
	(have_image Planet67 spectrograph18)
	(have_image Planet67 infrared14)
	(have_image Planet67 spectrograph0)
	(have_image Planet68 spectrograph19)
	(have_image Planet68 spectrograph17)
	(have_image Planet68 spectrograph5)
	(have_image Planet68 thermograph16)
	(have_image Planet68 infrared3)
	(have_image Planet69 infrared2)
	(have_image Planet69 thermograph16)
	(have_image Planet69 thermograph10)
	(have_image Planet69 spectrograph8)
	(have_image Planet70 image9)
	(have_image Planet70 infrared3)
	(have_image Phenomenon71 thermograph7)
	(have_image Phenomenon71 thermograph13)
	(have_image Planet72 infrared11)
	(have_image Planet72 image9)
	(have_image Planet72 spectrograph8)
	(have_image Planet72 thermograph13)
	(have_image Planet72 spectrograph17)
	(have_image Phenomenon73 thermograph10)
	(have_image Phenomenon73 spectrograph17)
	(have_image Phenomenon73 spectrograph5)
	(have_image Phenomenon74 infrared3)
	(have_image Phenomenon74 thermograph7)
	(have_image Star75 spectrograph8)
	(have_image Star75 spectrograph18)
	(have_image Star75 infrared14)
	(have_image Star75 thermograph16)
	(have_image Star75 infrared11)
	(have_image Star76 spectrograph17)
	(have_image Planet77 spectrograph5)
	(have_image Planet77 image9)
	(have_image Planet77 infrared11)
	(have_image Planet77 infrared4)
	(have_image Planet78 infrared4)
	(have_image Planet78 spectrograph8)
	(have_image Planet78 spectrograph19)
	(have_image Planet78 spectrograph18)
	(have_image Planet78 infrared11)
	(have_image Phenomenon79 thermograph13)
	(have_image Phenomenon79 infrared11)
	(have_image Phenomenon79 spectrograph19)
	(have_image Planet80 image9)
	(have_image Star81 infrared2)
	(have_image Star81 spectrograph19)
	(have_image Star81 thermograph10)
	(have_image Star81 spectrograph18)
	(have_image Star81 spectrograph8)
	(have_image Star82 spectrograph5)
	(have_image Planet83 spectrograph5)
	(have_image Planet83 infrared3)
	(have_image Planet83 image9)
	(have_image Planet83 image1)
	(have_image Phenomenon84 thermograph7)
	(have_image Phenomenon84 spectrograph17)
	(have_image Phenomenon84 thermograph16)
	(have_image Phenomenon84 infrared12)
	(have_image Phenomenon84 thermograph10)
	(have_image Star85 spectrograph5)
	(have_image Star85 spectrograph0)
	(have_image Star85 thermograph7)
	(have_image Star85 thermograph16)
	(have_image Star85 thermograph13)
	(have_image Star85 thermograph10)
	(have_image Planet86 spectrograph0)
	(have_image Planet87 spectrograph0)
	(have_image Planet87 infrared4)
	(have_image Planet87 spectrograph19)
	(have_image Planet87 image9)
	(have_image Planet88 thermograph7)
	(have_image Planet88 image9)
	(have_image Planet88 spectrograph8)
	(have_image Planet88 infrared3)
	(have_image Planet88 thermograph13)
	(have_image Planet89 thermograph10)
	(have_image Planet89 thermograph16)
	(have_image Planet89 infrared14)
	(have_image Planet89 infrared3)
	(have_image Planet89 spectrograph17)
	(have_image Planet89 infrared11)
	(have_image Planet90 infrared14)
	(have_image Star91 infrared2)
	(have_image Star91 spectrograph5)
	(have_image Star91 spectrograph17)
	(have_image Star91 thermograph16)
	(have_image Star91 infrared3)
	(have_image Star92 infrared3)
	(have_image Star92 spectrograph19)
	(have_image Star92 infrared12)
	(have_image Phenomenon93 spectrograph5)
	(have_image Phenomenon93 infrared3)
	(have_image Phenomenon93 spectrograph8)
	(have_image Phenomenon94 thermograph16)
	(have_image Phenomenon94 infrared11)
	(have_image Phenomenon94 infrared3)
	(have_image Phenomenon94 spectrograph18)
	(have_image Phenomenon94 infrared4)
	(have_image Planet95 spectrograph0)
	(have_image Planet95 spectrograph18)
	(have_image Planet95 spectrograph8)
	(have_image Planet95 infrared12)
	(have_image Planet95 spectrograph5)
	(have_image Star96 spectrograph5)
	(have_image Star96 infrared3)
	(have_image Star96 spectrograph17)
	(have_image Star96 spectrograph8)
	(have_image Star96 image1)
	(have_image Star96 spectrograph0)
	(have_image Phenomenon98 thermograph13)
	(have_image Planet100 infrared2)
	(have_image Planet100 infrared14)
	(have_image Planet100 spectrograph8)
	(have_image Planet100 spectrograph5)
	(have_image Star101 infrared4)
	(have_image Planet102 infrared12)
	(have_image Phenomenon103 infrared3)
	(have_image Phenomenon103 spectrograph5)
	(have_image Phenomenon103 spectrograph19)
	(have_image Phenomenon103 spectrograph18)
	(have_image Phenomenon103 thermograph7)
	(have_image Star105 spectrograph8)
	(have_image Star105 image1)
	(have_image Star106 thermograph10)
	(have_image Planet107 spectrograph8)
	(have_image Planet107 infrared2)
	(have_image Planet107 infrared3)
	(have_image Planet107 spectrograph18)
	(have_image Planet108 infrared3)
	(have_image Planet108 thermograph10)
	(have_image Planet108 thermograph16)
	(have_image Phenomenon109 infrared12)
	(have_image Phenomenon109 image9)
	(have_image Phenomenon109 spectrograph17)
	(have_image Phenomenon109 infrared4)
	(have_image Phenomenon109 spectrograph18)
	(have_image Planet110 image1)
	(have_image Planet110 thermograph16)
	(have_image Planet110 infrared2)
	(have_image Planet110 spectrograph8)
	(have_image Planet111 spectrograph0)
	(have_image Planet112 spectrograph17)
	(have_image Planet112 infrared14)
	(have_image Planet112 spectrograph0)
	(have_image Planet113 infrared14)
	(have_image Star114 spectrograph18)
	(have_image Star114 infrared3)
	(have_image Star114 infrared2)
	(have_image Star116 thermograph16)
	(have_image Planet117 infrared11)
	(have_image Phenomenon118 image1)
	(have_image Phenomenon118 infrared12)
	(have_image Phenomenon118 infrared4)
	(have_image Phenomenon118 infrared11)
	(have_image Phenomenon118 thermograph7)
	(have_image Phenomenon118 infrared14)
	(have_image Planet119 spectrograph18)
	(have_image Planet119 spectrograph19)
	(have_image Planet119 spectrograph17)
	(have_image Star120 spectrograph17)
	(have_image Star120 infrared4)
	(have_image Star120 spectrograph0)
	(have_image Star120 spectrograph5)
	(have_image Star121 image1)
	(have_image Star121 spectrograph8)
	(have_image Star121 infrared3)
	(have_image Star121 spectrograph17)
	(have_image Star122 thermograph7)
	(have_image Star124 spectrograph0)
	(have_image Star124 spectrograph18)
	(have_image Star124 infrared14)
	(have_image Phenomenon125 infrared12)
	(have_image Phenomenon125 thermograph7)
	(have_image Phenomenon125 spectrograph19)
	(have_image Phenomenon125 infrared4)
	(have_image Phenomenon125 spectrograph5)
	(have_image Phenomenon125 infrared2)
	(have_image Star126 infrared14)
	(have_image Star126 spectrograph5)
	(have_image Star126 infrared11)
	(have_image Star126 image9)
	(have_image Star126 infrared4)
	(have_image Phenomenon127 infrared12)
	(have_image Phenomenon127 infrared11)
	(have_image Phenomenon127 spectrograph18)
	(have_image Planet128 infrared4)
	(have_image Planet128 thermograph16)
	(have_image Phenomenon129 spectrograph18)
	(have_image Phenomenon129 thermograph10)
	(have_image Phenomenon129 thermograph13)
	(have_image Star130 thermograph7)
	(have_image Star130 spectrograph0)
	(have_image Star130 infrared14)
	(have_image Phenomenon131 spectrograph18)
	(have_image Phenomenon131 infrared2)
	(have_image Phenomenon131 spectrograph0)
	(have_image Phenomenon131 thermograph10)
	(have_image Planet133 thermograph7)
	(have_image Star134 image1)
	(have_image Star134 image9)
	(have_image Star134 spectrograph18)
	(have_image Star134 thermograph13)
	(have_image Star134 infrared2)
	(have_image Star134 spectrograph8)
	(have_image Phenomenon135 infrared4)
	(have_image Star136 infrared14)
	(have_image Star136 spectrograph0)
	(have_image Phenomenon137 image1)
	(have_image Phenomenon137 thermograph13)
	(have_image Phenomenon137 thermograph7)
	(have_image Phenomenon137 spectrograph17)
	(have_image Phenomenon137 infrared12)
	(have_image Phenomenon137 infrared2)
	(have_image Planet138 spectrograph8)
	(have_image Planet138 thermograph7)
	(have_image Phenomenon139 infrared3)
	(have_image Star140 spectrograph17)
	(have_image Star141 spectrograph0)
	(have_image Star141 infrared14)
	(have_image Star142 infrared11)
	(have_image Star142 image9)
	(have_image Star142 infrared2)
	(have_image Star142 spectrograph18)
	(have_image Planet143 spectrograph0)
	(have_image Planet143 infrared3)
	(have_image Planet143 spectrograph18)
	(have_image Planet143 infrared12)
	(have_image Planet144 thermograph13)
	(have_image Planet144 infrared14)
	(have_image Planet144 spectrograph0)
	(have_image Planet144 spectrograph17)
	(have_image Planet144 spectrograph19)
	(have_image Planet144 thermograph16)
	(have_image Planet145 spectrograph19)
	(have_image Planet145 infrared11)
	(have_image Planet145 image1)
	(have_image Planet145 infrared2)
	(have_image Phenomenon146 spectrograph8)
	(have_image Phenomenon146 infrared14)
	(have_image Phenomenon146 spectrograph17)
	(have_image Phenomenon146 spectrograph5)
	(have_image Phenomenon146 thermograph13)
	(have_image Phenomenon147 spectrograph5)
	(have_image Phenomenon147 thermograph10)
	(have_image Phenomenon147 spectrograph19)
	(have_image Phenomenon147 infrared12)
	(have_image Phenomenon147 image9)
	(have_image Phenomenon147 thermograph13)
	(have_image Planet148 infrared12)
	(have_image Planet148 thermograph10)
	(have_image Planet148 infrared11)
	(have_image Planet148 spectrograph19)
	(have_image Planet148 spectrograph8)
	(have_image Planet148 infrared4)
	(have_image Star149 spectrograph0)
	(have_image Star149 spectrograph18)
	(have_image Star149 image1)
	(have_image Star149 thermograph16)
	(have_image Planet150 thermograph16)
	(have_image Planet150 thermograph13)
	(have_image Planet151 infrared12)
	(have_image Planet151 spectrograph8)
	(have_image Planet152 thermograph10)
	(have_image Planet152 thermograph13)
	(have_image Planet152 infrared11)
	(have_image Planet152 image1)
	(have_image Phenomenon153 image9)
	(have_image Phenomenon153 infrared3)
	(have_image Phenomenon153 spectrograph5)
	(have_image Phenomenon153 thermograph7)
	(have_image Phenomenon154 spectrograph0)
	(have_image Phenomenon154 thermograph10)
	(have_image Phenomenon154 spectrograph17)
	(have_image Planet155 infrared11)
	(have_image Planet155 infrared3)
	(have_image Planet155 image1)
	(have_image Planet155 spectrograph0)
	(have_image Planet155 spectrograph5)
	(have_image Planet156 spectrograph17)
	(have_image Planet156 thermograph10)
	(have_image Planet156 infrared12)
	(have_image Planet157 infrared11)
	(have_image Planet157 thermograph7)
	(have_image Star158 infrared2)
	(have_image Star158 image1)
	(have_image Star158 thermograph10)
	(have_image Star158 spectrograph5)
	(have_image Star158 spectrograph19)
	(have_image Planet159 thermograph16)
	(have_image Planet159 thermograph10)
	(have_image Planet159 thermograph13)
	(have_image Planet159 infrared4)
	(have_image Planet159 infrared3)
	(have_image Star160 spectrograph19)
	(have_image Phenomenon161 spectrograph19)
))

)
