(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	satellite2 - satellite
	instrument3 - instrument
	satellite3 - satellite
	instrument4 - instrument
	instrument5 - instrument
	satellite4 - satellite
	instrument6 - instrument
	instrument7 - instrument
	satellite5 - satellite
	instrument8 - instrument
	satellite6 - satellite
	instrument9 - instrument
	instrument10 - instrument
	satellite7 - satellite
	instrument11 - instrument
	satellite8 - satellite
	instrument12 - instrument
	instrument13 - instrument
	satellite9 - satellite
	instrument14 - instrument
	instrument15 - instrument
	satellite10 - satellite
	instrument16 - instrument
	satellite11 - satellite
	instrument17 - instrument
	instrument18 - instrument
	spectrograph12 - mode
	spectrograph9 - mode
	spectrograph16 - mode
	infrared13 - mode
	thermograph5 - mode
	spectrograph17 - mode
	image1 - mode
	infrared6 - mode
	spectrograph10 - mode
	image18 - mode
	thermograph2 - mode
	thermograph7 - mode
	image11 - mode
	infrared14 - mode
	spectrograph8 - mode
	spectrograph4 - mode
	thermograph19 - mode
	thermograph15 - mode
	spectrograph0 - mode
	image3 - mode
	Star1 - direction
	GroundStation0 - direction
	Planet2 - direction
	Planet3 - direction
	Star4 - direction
	Phenomenon5 - direction
	Phenomenon6 - direction
	Star7 - direction
	Planet8 - direction
	Phenomenon9 - direction
	Star10 - direction
	Phenomenon11 - direction
	Phenomenon12 - direction
	Planet13 - direction
	Star14 - direction
	Planet15 - direction
	Phenomenon16 - direction
	Star17 - direction
	Star18 - direction
	Star19 - direction
	Star20 - direction
	Phenomenon21 - direction
	Phenomenon22 - direction
	Planet23 - direction
	Phenomenon24 - direction
	Phenomenon25 - direction
	Star26 - direction
	Star27 - direction
	Star28 - direction
	Star29 - direction
	Star30 - direction
	Planet31 - direction
	Phenomenon32 - direction
	Phenomenon33 - direction
	Phenomenon34 - direction
	Planet35 - direction
	Star36 - direction
	Phenomenon37 - direction
	Planet38 - direction
	Star39 - direction
	Phenomenon40 - direction
	Star41 - direction
	Phenomenon42 - direction
	Star43 - direction
	Star44 - direction
	Phenomenon45 - direction
	Star46 - direction
	Star47 - direction
	Planet48 - direction
	Planet49 - direction
	Phenomenon50 - direction
	Planet51 - direction
	Planet52 - direction
	Planet53 - direction
	Star54 - direction
	Phenomenon55 - direction
	Planet56 - direction
	Phenomenon57 - direction
	Star58 - direction
	Planet59 - direction
	Phenomenon60 - direction
	Phenomenon61 - direction
	Star62 - direction
	Phenomenon63 - direction
	Star64 - direction
	Planet65 - direction
	Planet66 - direction
	Phenomenon67 - direction
	Phenomenon68 - direction
	Phenomenon69 - direction
	Planet70 - direction
	Star71 - direction
	Planet72 - direction
	Star73 - direction
	Planet74 - direction
	Star75 - direction
	Planet76 - direction
	Planet77 - direction
	Star78 - direction
	Star79 - direction
	Star80 - direction
	Star81 - direction
	Planet82 - direction
	Phenomenon83 - direction
	Planet84 - direction
	Planet85 - direction
	Planet86 - direction
	Phenomenon87 - direction
	Phenomenon88 - direction
	Planet89 - direction
	Star90 - direction
	Star91 - direction
	Phenomenon92 - direction
	Star93 - direction
	Star94 - direction
	Phenomenon95 - direction
	Star96 - direction
	Phenomenon97 - direction
	Planet98 - direction
	Planet99 - direction
	Planet100 - direction
	Phenomenon101 - direction
	Phenomenon102 - direction
	Phenomenon103 - direction
	Planet104 - direction
	Star105 - direction
	Star106 - direction
	Planet107 - direction
	Star108 - direction
	Planet109 - direction
	Phenomenon110 - direction
	Planet111 - direction
	Star112 - direction
	Phenomenon113 - direction
	Phenomenon114 - direction
	Phenomenon115 - direction
	Phenomenon116 - direction
	Star117 - direction
	Phenomenon118 - direction
	Planet119 - direction
	Phenomenon120 - direction
	Planet121 - direction
	Phenomenon122 - direction
	Star123 - direction
	Phenomenon124 - direction
	Planet125 - direction
	Star126 - direction
	Planet127 - direction
	Star128 - direction
	Phenomenon129 - direction
	Phenomenon130 - direction
	Star131 - direction
	Planet132 - direction
	Star133 - direction
	Phenomenon134 - direction
	Star135 - direction
	Planet136 - direction
	Phenomenon137 - direction
	Star138 - direction
	Planet139 - direction
	Star140 - direction
	Phenomenon141 - direction
	Planet142 - direction
	Star143 - direction
	Planet144 - direction
	Phenomenon145 - direction
	Phenomenon146 - direction
	Star147 - direction
	Star148 - direction
	Planet149 - direction
	Star150 - direction
	Phenomenon151 - direction
	Phenomenon152 - direction
	Planet153 - direction
	Phenomenon154 - direction
	Phenomenon155 - direction
	Phenomenon156 - direction
	Star157 - direction
	Star158 - direction
	Phenomenon159 - direction
	Phenomenon160 - direction
	Planet161 - direction
	Phenomenon162 - direction
	Star163 - direction
	Planet164 - direction
	Star165 - direction
	Planet166 - direction
	Planet167 - direction
	Planet168 - direction
	Planet169 - direction
	Phenomenon170 - direction
	Star171 - direction
	Star172 - direction
	Star173 - direction
	Planet174 - direction
	Planet175 - direction
	Phenomenon176 - direction
	Star177 - direction
	Planet178 - direction
	Star179 - direction
	Star180 - direction
	Phenomenon181 - direction
)
(:init
	(supports instrument0 thermograph7)
	(calibration_target instrument0 Star1)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star18)
	(supports instrument1 infrared6)
	(supports instrument1 spectrograph10)
	(supports instrument1 spectrograph8)
	(calibration_target instrument1 Star1)
	(supports instrument2 spectrograph0)
	(calibration_target instrument2 GroundStation0)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Phenomenon181)
	(supports instrument3 spectrograph4)
	(calibration_target instrument3 GroundStation0)
	(on_board instrument3 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star46)
	(supports instrument4 thermograph7)
	(supports instrument4 image1)
	(calibration_target instrument4 GroundStation0)
	(supports instrument5 infrared6)
	(supports instrument5 spectrograph4)
	(calibration_target instrument5 GroundStation0)
	(on_board instrument4 satellite3)
	(on_board instrument5 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon162)
	(supports instrument6 infrared6)
	(calibration_target instrument6 Star1)
	(supports instrument7 infrared6)
	(supports instrument7 infrared14)
	(supports instrument7 image3)
	(calibration_target instrument7 Star1)
	(on_board instrument6 satellite4)
	(on_board instrument7 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet38)
	(supports instrument8 spectrograph10)
	(calibration_target instrument8 GroundStation0)
	(on_board instrument8 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Phenomenon130)
	(supports instrument9 spectrograph10)
	(supports instrument9 thermograph15)
	(supports instrument9 infrared14)
	(calibration_target instrument9 Star1)
	(supports instrument10 image18)
	(supports instrument10 spectrograph8)
	(supports instrument10 infrared14)
	(calibration_target instrument10 Star1)
	(on_board instrument9 satellite6)
	(on_board instrument10 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star80)
	(supports instrument11 thermograph7)
	(supports instrument11 thermograph2)
	(calibration_target instrument11 GroundStation0)
	(on_board instrument11 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Planet48)
	(supports instrument12 thermograph15)
	(calibration_target instrument12 Star1)
	(supports instrument13 infrared14)
	(supports instrument13 spectrograph0)
	(calibration_target instrument13 GroundStation0)
	(on_board instrument12 satellite8)
	(on_board instrument13 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Planet111)
	(supports instrument14 infrared14)
	(supports instrument14 image11)
	(calibration_target instrument14 GroundStation0)
	(supports instrument15 spectrograph8)
	(supports instrument15 infrared14)
	(supports instrument15 thermograph19)
	(calibration_target instrument15 GroundStation0)
	(on_board instrument14 satellite9)
	(on_board instrument15 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Planet86)
	(supports instrument16 thermograph19)
	(supports instrument16 spectrograph4)
	(calibration_target instrument16 GroundStation0)
	(on_board instrument16 satellite10)
	(power_avail satellite10)
	(pointing satellite10 Star93)
	(supports instrument17 thermograph15)
	(calibration_target instrument17 Star1)
	(supports instrument18 image3)
	(supports instrument18 spectrograph0)
	(calibration_target instrument18 GroundStation0)
	(on_board instrument17 satellite11)
	(on_board instrument18 satellite11)
	(power_avail satellite11)
	(pointing satellite11 Planet52)
)
(:goal (and
	(pointing satellite4 Phenomenon114)
	(pointing satellite9 Planet99)
	(pointing satellite10 Star90)
	(pointing satellite11 Star179)
	(have_image Planet2 spectrograph8)
	(have_image Planet2 spectrograph4)
	(have_image Planet2 thermograph19)
	(have_image Star4 thermograph2)
	(have_image Star4 image1)
	(have_image Star4 spectrograph0)
	(have_image Phenomenon5 spectrograph4)
	(have_image Phenomenon5 image1)
	(have_image Phenomenon5 image11)
	(have_image Phenomenon5 image18)
	(have_image Phenomenon6 thermograph19)
	(have_image Phenomenon6 thermograph2)
	(have_image Phenomenon6 spectrograph0)
	(have_image Phenomenon6 infrared14)
	(have_image Phenomenon6 thermograph15)
	(have_image Planet8 image1)
	(have_image Planet8 spectrograph0)
	(have_image Planet8 thermograph15)
	(have_image Phenomenon9 thermograph2)
	(have_image Phenomenon9 image3)
	(have_image Phenomenon9 thermograph15)
	(have_image Phenomenon9 thermograph19)
	(have_image Phenomenon9 infrared14)
	(have_image Phenomenon11 thermograph19)
	(have_image Phenomenon11 infrared6)
	(have_image Phenomenon11 image18)
	(have_image Phenomenon12 image3)
	(have_image Phenomenon12 image11)
	(have_image Planet13 image18)
	(have_image Planet13 thermograph2)
	(have_image Star14 image18)
	(have_image Star14 thermograph15)
	(have_image Star14 infrared14)
	(have_image Planet15 thermograph19)
	(have_image Planet15 thermograph2)
	(have_image Planet15 thermograph7)
	(have_image Phenomenon16 spectrograph8)
	(have_image Star17 infrared6)
	(have_image Star17 image18)
	(have_image Star18 thermograph19)
	(have_image Star18 infrared14)
	(have_image Star18 image18)
	(have_image Star20 infrared6)
	(have_image Star20 image11)
	(have_image Phenomenon21 spectrograph8)
	(have_image Phenomenon21 infrared6)
	(have_image Phenomenon21 image11)
	(have_image Phenomenon22 thermograph7)
	(have_image Phenomenon22 infrared14)
	(have_image Phenomenon22 image3)
	(have_image Phenomenon22 thermograph19)
	(have_image Phenomenon24 image3)
	(have_image Phenomenon24 image18)
	(have_image Star26 spectrograph4)
	(have_image Star26 image3)
	(have_image Star26 spectrograph10)
	(have_image Star27 thermograph2)
	(have_image Star27 image18)
	(have_image Star27 spectrograph8)
	(have_image Star27 image1)
	(have_image Star28 thermograph15)
	(have_image Star29 image3)
	(have_image Star29 spectrograph10)
	(have_image Star30 thermograph7)
	(have_image Planet31 thermograph19)
	(have_image Planet31 image3)
	(have_image Phenomenon32 thermograph2)
	(have_image Phenomenon32 image1)
	(have_image Phenomenon32 image3)
	(have_image Phenomenon33 infrared14)
	(have_image Phenomenon33 spectrograph8)
	(have_image Phenomenon33 thermograph19)
	(have_image Planet35 image11)
	(have_image Planet35 image3)
	(have_image Star36 spectrograph8)
	(have_image Phenomenon37 spectrograph0)
	(have_image Planet38 image11)
	(have_image Planet38 thermograph15)
	(have_image Planet38 infrared6)
	(have_image Star39 thermograph19)
	(have_image Star39 spectrograph10)
	(have_image Star39 image11)
	(have_image Phenomenon40 spectrograph10)
	(have_image Phenomenon40 infrared14)
	(have_image Star41 spectrograph8)
	(have_image Star41 image11)
	(have_image Star41 infrared14)
	(have_image Phenomenon42 infrared6)
	(have_image Phenomenon42 spectrograph10)
	(have_image Phenomenon42 image1)
	(have_image Phenomenon42 thermograph7)
	(have_image Phenomenon42 thermograph19)
	(have_image Star43 image3)
	(have_image Star43 spectrograph8)
	(have_image Star43 spectrograph0)
	(have_image Star43 thermograph15)
	(have_image Star46 image1)
	(have_image Star46 thermograph15)
	(have_image Star46 spectrograph10)
	(have_image Star46 thermograph19)
	(have_image Star46 spectrograph8)
	(have_image Star47 infrared14)
	(have_image Star47 infrared6)
	(have_image Star47 thermograph7)
	(have_image Planet49 image11)
	(have_image Planet49 spectrograph10)
	(have_image Planet49 thermograph15)
	(have_image Planet49 thermograph19)
	(have_image Phenomenon50 thermograph7)
	(have_image Phenomenon50 infrared14)
	(have_image Planet51 image1)
	(have_image Planet51 spectrograph4)
	(have_image Planet51 infrared6)
	(have_image Planet51 image3)
	(have_image Planet52 image1)
	(have_image Planet53 thermograph7)
	(have_image Planet53 spectrograph8)
	(have_image Star54 image11)
	(have_image Phenomenon55 thermograph15)
	(have_image Phenomenon55 thermograph19)
	(have_image Phenomenon55 infrared14)
	(have_image Planet56 thermograph2)
	(have_image Phenomenon57 spectrograph4)
	(have_image Phenomenon57 thermograph15)
	(have_image Star58 image3)
	(have_image Star58 thermograph7)
	(have_image Star58 thermograph15)
	(have_image Star58 image1)
	(have_image Star58 infrared6)
	(have_image Phenomenon60 image18)
	(have_image Phenomenon60 infrared14)
	(have_image Phenomenon60 thermograph7)
	(have_image Phenomenon60 spectrograph4)
	(have_image Phenomenon60 thermograph2)
	(have_image Phenomenon61 image11)
	(have_image Phenomenon61 infrared6)
	(have_image Phenomenon61 spectrograph0)
	(have_image Star62 image18)
	(have_image Phenomenon63 image11)
	(have_image Phenomenon63 image1)
	(have_image Phenomenon63 thermograph15)
	(have_image Star64 thermograph19)
	(have_image Star64 infrared6)
	(have_image Star64 infrared14)
	(have_image Star64 thermograph15)
	(have_image Star64 image1)
	(have_image Planet65 image11)
	(have_image Planet65 spectrograph10)
	(have_image Planet66 image3)
	(have_image Planet66 spectrograph10)
	(have_image Planet66 infrared14)
	(have_image Phenomenon67 thermograph19)
	(have_image Phenomenon67 thermograph15)
	(have_image Phenomenon67 infrared14)
	(have_image Phenomenon67 image3)
	(have_image Phenomenon68 spectrograph8)
	(have_image Phenomenon68 spectrograph10)
	(have_image Phenomenon68 image3)
	(have_image Phenomenon69 infrared14)
	(have_image Planet70 thermograph15)
	(have_image Planet70 spectrograph10)
	(have_image Planet70 thermograph2)
	(have_image Planet70 image11)
	(have_image Planet72 thermograph2)
	(have_image Star73 image11)
	(have_image Star73 spectrograph4)
	(have_image Star73 infrared6)
	(have_image Planet74 infrared6)
	(have_image Planet74 image11)
	(have_image Planet74 thermograph7)
	(have_image Planet74 spectrograph0)
	(have_image Star75 image11)
	(have_image Star75 spectrograph10)
	(have_image Star75 infrared6)
	(have_image Planet77 infrared6)
	(have_image Star80 image11)
	(have_image Star80 thermograph2)
	(have_image Star80 thermograph15)
	(have_image Star80 image1)
	(have_image Star80 infrared14)
	(have_image Star81 image3)
	(have_image Star81 thermograph15)
	(have_image Star81 thermograph19)
	(have_image Star81 spectrograph0)
	(have_image Star81 infrared6)
	(have_image Planet82 image11)
	(have_image Planet82 thermograph15)
	(have_image Planet82 spectrograph4)
	(have_image Planet82 image1)
	(have_image Phenomenon83 infrared14)
	(have_image Planet84 thermograph15)
	(have_image Planet85 image1)
	(have_image Phenomenon87 infrared14)
	(have_image Phenomenon87 thermograph2)
	(have_image Phenomenon87 thermograph15)
	(have_image Phenomenon87 thermograph19)
	(have_image Phenomenon88 spectrograph8)
	(have_image Phenomenon88 thermograph19)
	(have_image Planet89 thermograph19)
	(have_image Star90 spectrograph4)
	(have_image Star90 infrared14)
	(have_image Star90 thermograph15)
	(have_image Star90 image11)
	(have_image Star91 image11)
	(have_image Phenomenon92 image3)
	(have_image Phenomenon92 thermograph15)
	(have_image Phenomenon92 thermograph2)
	(have_image Phenomenon92 thermograph7)
	(have_image Star94 spectrograph8)
	(have_image Star94 thermograph19)
	(have_image Star94 thermograph2)
	(have_image Phenomenon95 spectrograph10)
	(have_image Phenomenon95 spectrograph8)
	(have_image Phenomenon95 image3)
	(have_image Phenomenon95 spectrograph4)
	(have_image Star96 image3)
	(have_image Star96 thermograph2)
	(have_image Star96 image18)
	(have_image Phenomenon97 spectrograph0)
	(have_image Phenomenon97 thermograph19)
	(have_image Planet98 thermograph2)
	(have_image Planet99 thermograph19)
	(have_image Planet99 thermograph15)
	(have_image Planet99 infrared6)
	(have_image Planet100 thermograph7)
	(have_image Phenomenon102 image1)
	(have_image Phenomenon103 spectrograph10)
	(have_image Phenomenon103 image11)
	(have_image Planet104 spectrograph10)
	(have_image Planet104 thermograph19)
	(have_image Star105 infrared14)
	(have_image Star105 spectrograph10)
	(have_image Star105 image3)
	(have_image Star105 spectrograph4)
	(have_image Star106 image11)
	(have_image Planet107 infrared14)
	(have_image Star108 thermograph7)
	(have_image Star108 image11)
	(have_image Star108 thermograph2)
	(have_image Star108 image1)
	(have_image Planet109 infrared6)
	(have_image Planet109 thermograph2)
	(have_image Planet109 image11)
	(have_image Planet109 image1)
	(have_image Planet109 thermograph7)
	(have_image Phenomenon110 spectrograph10)
	(have_image Phenomenon110 spectrograph0)
	(have_image Phenomenon110 thermograph2)
	(have_image Phenomenon110 image18)
	(have_image Planet111 thermograph19)
	(have_image Planet111 spectrograph4)
	(have_image Star112 infrared14)
	(have_image Phenomenon113 image3)
	(have_image Phenomenon114 thermograph15)
	(have_image Phenomenon114 spectrograph10)
	(have_image Phenomenon114 image1)
	(have_image Planet119 image11)
	(have_image Planet119 image1)
	(have_image Phenomenon120 image11)
	(have_image Phenomenon120 thermograph19)
	(have_image Phenomenon120 infrared6)
	(have_image Phenomenon122 thermograph15)
	(have_image Star123 spectrograph0)
	(have_image Star123 spectrograph10)
	(have_image Star123 thermograph2)
	(have_image Star123 thermograph19)
	(have_image Phenomenon124 thermograph15)
	(have_image Planet125 spectrograph8)
	(have_image Planet125 thermograph19)
	(have_image Planet125 image1)
	(have_image Planet125 image11)
	(have_image Star126 thermograph2)
	(have_image Star126 spectrograph10)
	(have_image Star126 thermograph15)
	(have_image Planet127 spectrograph0)
	(have_image Planet127 image18)
	(have_image Planet127 thermograph19)
	(have_image Planet127 spectrograph4)
	(have_image Star128 image18)
	(have_image Star128 spectrograph4)
	(have_image Star128 infrared14)
	(have_image Star128 spectrograph8)
	(have_image Phenomenon130 infrared14)
	(have_image Phenomenon130 image18)
	(have_image Phenomenon130 spectrograph10)
	(have_image Star133 image11)
	(have_image Star133 spectrograph4)
	(have_image Star133 spectrograph8)
	(have_image Phenomenon134 infrared6)
	(have_image Phenomenon134 thermograph19)
	(have_image Star135 infrared6)
	(have_image Star135 thermograph19)
	(have_image Star135 spectrograph0)
	(have_image Star135 spectrograph8)
	(have_image Star135 image11)
	(have_image Planet136 infrared14)
	(have_image Planet136 spectrograph10)
	(have_image Planet136 thermograph2)
	(have_image Phenomenon137 thermograph7)
	(have_image Star138 infrared6)
	(have_image Star138 thermograph2)
	(have_image Star138 spectrograph10)
	(have_image Star138 spectrograph4)
	(have_image Star138 thermograph19)
	(have_image Planet139 thermograph15)
	(have_image Planet139 spectrograph10)
	(have_image Star140 infrared6)
	(have_image Star140 image3)
	(have_image Star140 spectrograph0)
	(have_image Phenomenon141 spectrograph10)
	(have_image Phenomenon141 thermograph7)
	(have_image Planet142 image3)
	(have_image Star143 spectrograph4)
	(have_image Star143 infrared6)
	(have_image Star143 thermograph19)
	(have_image Star143 image1)
	(have_image Star143 thermograph7)
	(have_image Star143 thermograph15)
	(have_image Planet144 spectrograph10)
	(have_image Phenomenon146 spectrograph0)
	(have_image Phenomenon146 thermograph15)
	(have_image Phenomenon146 spectrograph10)
	(have_image Phenomenon146 thermograph7)
	(have_image Star147 thermograph15)
	(have_image Star147 thermograph7)
	(have_image Star150 thermograph7)
	(have_image Phenomenon151 image18)
	(have_image Phenomenon152 thermograph15)
	(have_image Phenomenon152 image18)
	(have_image Planet153 thermograph19)
	(have_image Phenomenon154 thermograph15)
	(have_image Phenomenon154 image11)
	(have_image Phenomenon154 spectrograph8)
	(have_image Phenomenon154 infrared6)
	(have_image Phenomenon154 spectrograph4)
	(have_image Phenomenon155 spectrograph10)
	(have_image Phenomenon155 image11)
	(have_image Phenomenon155 spectrograph8)
	(have_image Phenomenon155 thermograph7)
	(have_image Phenomenon155 image3)
	(have_image Star157 infrared6)
	(have_image Star157 image18)
	(have_image Star157 thermograph2)
	(have_image Star157 thermograph19)
	(have_image Star157 spectrograph4)
	(have_image Star158 infrared6)
	(have_image Star158 image11)
	(have_image Phenomenon159 image1)
	(have_image Phenomenon159 spectrograph4)
	(have_image Phenomenon159 thermograph2)
	(have_image Phenomenon159 thermograph7)
	(have_image Phenomenon160 thermograph2)
	(have_image Phenomenon160 spectrograph0)
	(have_image Planet161 spectrograph0)
	(have_image Planet161 infrared6)
	(have_image Planet161 thermograph15)
	(have_image Phenomenon162 spectrograph4)
	(have_image Phenomenon162 infrared6)
	(have_image Phenomenon162 image3)
	(have_image Phenomenon162 thermograph2)
	(have_image Phenomenon162 image1)
	(have_image Planet164 spectrograph4)
	(have_image Planet164 image3)
	(have_image Star165 thermograph2)
	(have_image Star165 image3)
	(have_image Star165 spectrograph4)
	(have_image Star165 thermograph15)
	(have_image Planet168 image1)
	(have_image Planet168 image3)
	(have_image Planet168 infrared6)
	(have_image Planet168 image18)
	(have_image Phenomenon170 spectrograph8)
	(have_image Phenomenon170 thermograph15)
	(have_image Phenomenon170 spectrograph10)
	(have_image Phenomenon170 thermograph7)
	(have_image Star171 image11)
	(have_image Star171 spectrograph10)
	(have_image Star172 thermograph2)
	(have_image Star172 thermograph19)
	(have_image Planet174 spectrograph8)
	(have_image Planet175 spectrograph4)
	(have_image Star177 infrared6)
	(have_image Planet178 thermograph2)
	(have_image Planet178 spectrograph10)
	(have_image Planet178 spectrograph4)
	(have_image Planet178 spectrograph0)
	(have_image Planet178 image18)
	(have_image Star180 spectrograph4)
	(have_image Star180 infrared6)
	(have_image Star180 image18)
	(have_image Phenomenon181 thermograph15)
))

)
