(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	satellite2 - satellite
	instrument3 - instrument
	satellite3 - satellite
	instrument4 - instrument
	satellite4 - satellite
	instrument5 - instrument
	instrument6 - instrument
	satellite5 - satellite
	instrument7 - instrument
	instrument8 - instrument
	satellite6 - satellite
	instrument9 - instrument
	instrument10 - instrument
	satellite7 - satellite
	instrument11 - instrument
	satellite8 - satellite
	instrument12 - instrument
	instrument13 - instrument
	satellite9 - satellite
	instrument14 - instrument
	instrument15 - instrument
	satellite10 - satellite
	instrument16 - instrument
	instrument17 - instrument
	satellite11 - satellite
	instrument18 - instrument
	instrument19 - instrument
	spectrograph0 - mode
	image14 - mode
	thermograph18 - mode
	infrared4 - mode
	thermograph2 - mode
	spectrograph8 - mode
	spectrograph15 - mode
	image12 - mode
	image11 - mode
	spectrograph19 - mode
	thermograph3 - mode
	infrared9 - mode
	thermograph5 - mode
	thermograph13 - mode
	thermograph10 - mode
	infrared1 - mode
	infrared17 - mode
	thermograph7 - mode
	infrared6 - mode
	image16 - mode
	GroundStation1 - direction
	GroundStation0 - direction
	Planet2 - direction
	Planet3 - direction
	Phenomenon4 - direction
	Star5 - direction
	Phenomenon6 - direction
	Phenomenon7 - direction
	Planet8 - direction
	Phenomenon9 - direction
	Planet10 - direction
	Star11 - direction
	Phenomenon12 - direction
	Planet13 - direction
	Star14 - direction
	Phenomenon15 - direction
	Planet16 - direction
	Star17 - direction
	Planet18 - direction
	Phenomenon19 - direction
	Star20 - direction
	Star21 - direction
	Planet22 - direction
	Planet23 - direction
	Phenomenon24 - direction
	Planet25 - direction
	Phenomenon26 - direction
	Star27 - direction
	Planet28 - direction
	Planet29 - direction
	Planet30 - direction
	Star31 - direction
	Phenomenon32 - direction
	Phenomenon33 - direction
	Star34 - direction
	Star35 - direction
	Planet36 - direction
	Planet37 - direction
	Phenomenon38 - direction
	Star39 - direction
	Star40 - direction
	Phenomenon41 - direction
	Star42 - direction
	Planet43 - direction
	Planet44 - direction
	Star45 - direction
	Phenomenon46 - direction
	Planet47 - direction
	Phenomenon48 - direction
	Star49 - direction
	Planet50 - direction
	Planet51 - direction
	Planet52 - direction
	Star53 - direction
	Phenomenon54 - direction
	Planet55 - direction
	Planet56 - direction
	Planet57 - direction
	Phenomenon58 - direction
	Phenomenon59 - direction
	Star60 - direction
	Phenomenon61 - direction
	Star62 - direction
	Star63 - direction
	Star64 - direction
	Phenomenon65 - direction
	Planet66 - direction
	Phenomenon67 - direction
	Planet68 - direction
	Planet69 - direction
	Planet70 - direction
	Star71 - direction
	Star72 - direction
	Phenomenon73 - direction
	Planet74 - direction
	Phenomenon75 - direction
	Star76 - direction
	Planet77 - direction
	Star78 - direction
	Phenomenon79 - direction
	Phenomenon80 - direction
	Planet81 - direction
	Star82 - direction
	Phenomenon83 - direction
	Planet84 - direction
	Planet85 - direction
	Phenomenon86 - direction
	Planet87 - direction
	Star88 - direction
	Phenomenon89 - direction
	Phenomenon90 - direction
	Phenomenon91 - direction
	Phenomenon92 - direction
	Phenomenon93 - direction
	Phenomenon94 - direction
	Planet95 - direction
	Star96 - direction
	Phenomenon97 - direction
	Phenomenon98 - direction
	Phenomenon99 - direction
	Phenomenon100 - direction
	Phenomenon101 - direction
	Phenomenon102 - direction
	Star103 - direction
	Phenomenon104 - direction
	Star105 - direction
	Phenomenon106 - direction
	Phenomenon107 - direction
	Planet108 - direction
	Planet109 - direction
	Phenomenon110 - direction
	Star111 - direction
	Planet112 - direction
	Phenomenon113 - direction
	Star114 - direction
	Phenomenon115 - direction
	Star116 - direction
	Star117 - direction
	Phenomenon118 - direction
	Planet119 - direction
	Star120 - direction
	Planet121 - direction
	Phenomenon122 - direction
	Phenomenon123 - direction
	Planet124 - direction
	Star125 - direction
	Phenomenon126 - direction
	Planet127 - direction
	Star128 - direction
	Planet129 - direction
	Star130 - direction
	Phenomenon131 - direction
	Star132 - direction
	Planet133 - direction
	Planet134 - direction
	Phenomenon135 - direction
	Star136 - direction
	Planet137 - direction
	Planet138 - direction
	Planet139 - direction
	Phenomenon140 - direction
	Planet141 - direction
	Planet142 - direction
	Phenomenon143 - direction
	Planet144 - direction
	Phenomenon145 - direction
	Star146 - direction
	Planet147 - direction
	Phenomenon148 - direction
	Phenomenon149 - direction
	Star150 - direction
	Star151 - direction
	Phenomenon152 - direction
	Planet153 - direction
	Star154 - direction
	Phenomenon155 - direction
	Planet156 - direction
	Phenomenon157 - direction
	Phenomenon158 - direction
	Star159 - direction
	Planet160 - direction
	Star161 - direction
	Planet162 - direction
	Phenomenon163 - direction
	Star164 - direction
	Star165 - direction
	Phenomenon166 - direction
	Phenomenon167 - direction
	Phenomenon168 - direction
	Planet169 - direction
	Star170 - direction
	Planet171 - direction
	Phenomenon172 - direction
	Planet173 - direction
	Phenomenon174 - direction
	Planet175 - direction
	Phenomenon176 - direction
	Star177 - direction
	Phenomenon178 - direction
	Planet179 - direction
	Planet180 - direction
	Phenomenon181 - direction
)
(:init
	(supports instrument0 infrared4)
	(calibration_target instrument0 GroundStation1)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon172)
	(supports instrument1 image12)
	(supports instrument1 image11)
	(supports instrument1 thermograph10)
	(calibration_target instrument1 GroundStation0)
	(supports instrument2 infrared9)
	(calibration_target instrument2 GroundStation1)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star164)
	(supports instrument3 image16)
	(calibration_target instrument3 GroundStation1)
	(on_board instrument3 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon6)
	(supports instrument4 thermograph13)
	(supports instrument4 thermograph2)
	(calibration_target instrument4 GroundStation1)
	(on_board instrument4 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet129)
	(supports instrument5 image12)
	(calibration_target instrument5 GroundStation0)
	(supports instrument6 thermograph5)
	(supports instrument6 thermograph7)
	(calibration_target instrument6 GroundStation1)
	(on_board instrument5 satellite4)
	(on_board instrument6 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet18)
	(supports instrument7 spectrograph15)
	(calibration_target instrument7 GroundStation0)
	(supports instrument8 spectrograph8)
	(supports instrument8 spectrograph19)
	(supports instrument8 thermograph10)
	(calibration_target instrument8 GroundStation0)
	(on_board instrument7 satellite5)
	(on_board instrument8 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Planet134)
	(supports instrument9 infrared17)
	(calibration_target instrument9 GroundStation1)
	(supports instrument10 spectrograph15)
	(supports instrument10 infrared9)
	(calibration_target instrument10 GroundStation0)
	(on_board instrument9 satellite6)
	(on_board instrument10 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet129)
	(supports instrument11 thermograph13)
	(calibration_target instrument11 GroundStation1)
	(on_board instrument11 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Phenomenon113)
	(supports instrument12 image12)
	(supports instrument12 thermograph13)
	(calibration_target instrument12 GroundStation1)
	(supports instrument13 image11)
	(calibration_target instrument13 GroundStation0)
	(on_board instrument12 satellite8)
	(on_board instrument13 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star35)
	(supports instrument14 thermograph7)
	(supports instrument14 infrared1)
	(supports instrument14 spectrograph19)
	(calibration_target instrument14 GroundStation1)
	(supports instrument15 infrared1)
	(supports instrument15 thermograph3)
	(supports instrument15 thermograph5)
	(calibration_target instrument15 GroundStation0)
	(on_board instrument14 satellite9)
	(on_board instrument15 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star63)
	(supports instrument16 thermograph5)
	(supports instrument16 thermograph13)
	(supports instrument16 infrared9)
	(calibration_target instrument16 GroundStation1)
	(supports instrument17 thermograph10)
	(supports instrument17 thermograph7)
	(supports instrument17 thermograph13)
	(calibration_target instrument17 GroundStation1)
	(on_board instrument16 satellite10)
	(on_board instrument17 satellite10)
	(power_avail satellite10)
	(pointing satellite10 Planet13)
	(supports instrument18 infrared17)
	(supports instrument18 infrared1)
	(calibration_target instrument18 GroundStation0)
	(supports instrument19 image16)
	(supports instrument19 infrared6)
	(supports instrument19 thermograph7)
	(calibration_target instrument19 GroundStation0)
	(on_board instrument18 satellite11)
	(on_board instrument19 satellite11)
	(power_avail satellite11)
	(pointing satellite11 Phenomenon4)
)
(:goal (and
	(pointing satellite1 Star132)
	(pointing satellite4 Phenomenon26)
	(pointing satellite7 Phenomenon75)
	(have_image Planet2 image12)
	(have_image Planet2 infrared6)
	(have_image Planet2 thermograph7)
	(have_image Phenomenon4 infrared1)
	(have_image Phenomenon4 thermograph2)
	(have_image Star5 spectrograph15)
	(have_image Phenomenon7 infrared1)
	(have_image Phenomenon7 spectrograph8)
	(have_image Planet8 spectrograph8)
	(have_image Planet8 infrared1)
	(have_image Planet8 spectrograph15)
	(have_image Planet8 infrared6)
	(have_image Planet8 infrared9)
	(have_image Planet8 thermograph10)
	(have_image Star11 infrared4)
	(have_image Star11 infrared17)
	(have_image Star11 image16)
	(have_image Star11 infrared6)
	(have_image Star11 spectrograph19)
	(have_image Phenomenon12 thermograph2)
	(have_image Phenomenon12 infrared9)
	(have_image Phenomenon12 image16)
	(have_image Phenomenon12 infrared4)
	(have_image Planet13 infrared4)
	(have_image Planet13 thermograph7)
	(have_image Planet13 spectrograph15)
	(have_image Star14 thermograph10)
	(have_image Star14 thermograph3)
	(have_image Star14 image12)
	(have_image Star14 thermograph5)
	(have_image Phenomenon15 spectrograph8)
	(have_image Phenomenon15 thermograph10)
	(have_image Phenomenon15 thermograph3)
	(have_image Planet16 thermograph3)
	(have_image Planet16 spectrograph19)
	(have_image Planet16 spectrograph15)
	(have_image Star17 thermograph2)
	(have_image Phenomenon19 spectrograph19)
	(have_image Star20 infrared1)
	(have_image Star20 thermograph5)
	(have_image Star20 spectrograph15)
	(have_image Star21 infrared17)
	(have_image Star21 spectrograph15)
	(have_image Star21 infrared6)
	(have_image Phenomenon24 infrared6)
	(have_image Phenomenon24 spectrograph19)
	(have_image Phenomenon24 infrared9)
	(have_image Phenomenon24 image11)
	(have_image Phenomenon24 infrared1)
	(have_image Phenomenon24 thermograph13)
	(have_image Planet25 infrared9)
	(have_image Planet25 thermograph2)
	(have_image Planet25 spectrograph19)
	(have_image Phenomenon26 image16)
	(have_image Star27 spectrograph15)
	(have_image Star27 thermograph7)
	(have_image Star27 infrared4)
	(have_image Star27 spectrograph8)
	(have_image Star27 thermograph2)
	(have_image Star27 thermograph10)
	(have_image Planet28 image11)
	(have_image Planet28 infrared6)
	(have_image Planet29 thermograph13)
	(have_image Planet29 spectrograph19)
	(have_image Planet30 thermograph7)
	(have_image Planet30 spectrograph19)
	(have_image Planet30 spectrograph15)
	(have_image Planet30 image11)
	(have_image Star31 spectrograph8)
	(have_image Star31 spectrograph15)
	(have_image Star31 infrared9)
	(have_image Phenomenon32 infrared4)
	(have_image Phenomenon32 thermograph3)
	(have_image Phenomenon32 infrared17)
	(have_image Phenomenon32 thermograph13)
	(have_image Phenomenon32 spectrograph15)
	(have_image Phenomenon33 infrared1)
	(have_image Star34 infrared17)
	(have_image Star34 image16)
	(have_image Star34 thermograph10)
	(have_image Star34 spectrograph19)
	(have_image Star34 spectrograph8)
	(have_image Star34 thermograph2)
	(have_image Star35 thermograph13)
	(have_image Star35 infrared9)
	(have_image Star35 spectrograph19)
	(have_image Star35 thermograph10)
	(have_image Planet36 thermograph13)
	(have_image Planet36 infrared4)
	(have_image Planet36 infrared6)
	(have_image Planet36 spectrograph8)
	(have_image Planet36 infrared9)
	(have_image Planet37 infrared9)
	(have_image Planet37 image12)
	(have_image Planet37 thermograph3)
	(have_image Planet37 infrared6)
	(have_image Planet37 image16)
	(have_image Planet37 spectrograph8)
	(have_image Star39 infrared17)
	(have_image Star39 thermograph13)
	(have_image Star39 thermograph2)
	(have_image Star40 infrared1)
	(have_image Phenomenon41 spectrograph15)
	(have_image Phenomenon41 image16)
	(have_image Phenomenon41 spectrograph19)
	(have_image Phenomenon41 thermograph7)
	(have_image Star42 spectrograph15)
	(have_image Star42 image12)
	(have_image Star42 infrared4)
	(have_image Star42 infrared9)
	(have_image Star42 thermograph3)
	(have_image Planet43 thermograph10)
	(have_image Planet44 thermograph2)
	(have_image Planet44 thermograph13)
	(have_image Star45 image16)
	(have_image Star45 thermograph10)
	(have_image Star45 image12)
	(have_image Phenomenon46 infrared9)
	(have_image Phenomenon46 thermograph10)
	(have_image Phenomenon46 thermograph7)
	(have_image Planet47 image11)
	(have_image Phenomenon48 spectrograph8)
	(have_image Phenomenon48 thermograph5)
	(have_image Star49 thermograph3)
	(have_image Star49 thermograph13)
	(have_image Planet50 spectrograph15)
	(have_image Planet50 infrared6)
	(have_image Planet50 thermograph10)
	(have_image Planet50 spectrograph8)
	(have_image Planet51 infrared6)
	(have_image Planet51 image12)
	(have_image Planet51 infrared1)
	(have_image Planet51 spectrograph19)
	(have_image Planet51 thermograph5)
	(have_image Planet51 infrared4)
	(have_image Planet52 thermograph5)
	(have_image Planet52 image12)
	(have_image Planet52 spectrograph8)
	(have_image Star53 thermograph5)
	(have_image Star53 image11)
	(have_image Star53 infrared4)
	(have_image Planet55 thermograph2)
	(have_image Planet55 thermograph3)
	(have_image Planet55 infrared4)
	(have_image Planet56 image11)
	(have_image Planet56 thermograph3)
	(have_image Planet57 infrared6)
	(have_image Planet57 image16)
	(have_image Planet57 infrared4)
	(have_image Phenomenon59 spectrograph8)
	(have_image Phenomenon59 thermograph3)
	(have_image Phenomenon59 thermograph13)
	(have_image Phenomenon59 image16)
	(have_image Star60 infrared6)
	(have_image Star60 thermograph2)
	(have_image Star60 infrared4)
	(have_image Star60 thermograph7)
	(have_image Phenomenon61 thermograph3)
	(have_image Star62 image12)
	(have_image Star62 spectrograph15)
	(have_image Star62 thermograph2)
	(have_image Star62 infrared6)
	(have_image Star63 thermograph5)
	(have_image Star63 infrared4)
	(have_image Star64 thermograph3)
	(have_image Star64 thermograph7)
	(have_image Star64 image12)
	(have_image Phenomenon65 infrared9)
	(have_image Phenomenon65 thermograph2)
	(have_image Phenomenon65 infrared6)
	(have_image Phenomenon65 infrared17)
	(have_image Phenomenon65 spectrograph15)
	(have_image Phenomenon65 image16)
	(have_image Planet66 infrared9)
	(have_image Planet66 thermograph3)
	(have_image Planet66 image12)
	(have_image Planet66 image11)
	(have_image Planet66 thermograph7)
	(have_image Planet66 thermograph10)
	(have_image Phenomenon67 thermograph13)
	(have_image Phenomenon67 image11)
	(have_image Planet68 image11)
	(have_image Planet68 infrared9)
	(have_image Planet68 infrared1)
	(have_image Planet68 image16)
	(have_image Planet69 spectrograph15)
	(have_image Planet69 image12)
	(have_image Star71 thermograph5)
	(have_image Star71 spectrograph8)
	(have_image Star71 image11)
	(have_image Star71 spectrograph19)
	(have_image Star72 spectrograph19)
	(have_image Star72 infrared6)
	(have_image Star72 image16)
	(have_image Star72 infrared9)
	(have_image Star72 thermograph10)
	(have_image Phenomenon73 thermograph5)
	(have_image Phenomenon73 infrared1)
	(have_image Planet74 spectrograph19)
	(have_image Phenomenon75 thermograph10)
	(have_image Phenomenon75 thermograph13)
	(have_image Phenomenon75 infrared1)
	(have_image Phenomenon75 image16)
	(have_image Star76 thermograph3)
	(have_image Star76 infrared4)
	(have_image Star76 image11)
	(have_image Planet77 thermograph13)
	(have_image Star78 thermograph2)
	(have_image Star78 thermograph7)
	(have_image Star78 infrared17)
	(have_image Star78 thermograph5)
	(have_image Star78 thermograph13)
	(have_image Phenomenon79 spectrograph19)
	(have_image Phenomenon79 thermograph7)
	(have_image Phenomenon80 thermograph3)
	(have_image Phenomenon80 infrared9)
	(have_image Phenomenon80 thermograph7)
	(have_image Planet81 infrared4)
	(have_image Planet81 thermograph3)
	(have_image Star82 spectrograph8)
	(have_image Star82 infrared1)
	(have_image Star82 image16)
	(have_image Star82 thermograph5)
	(have_image Phenomenon83 image16)
	(have_image Phenomenon83 thermograph13)
	(have_image Phenomenon83 infrared17)
	(have_image Phenomenon83 thermograph5)
	(have_image Phenomenon83 infrared6)
	(have_image Planet84 image12)
	(have_image Planet84 thermograph10)
	(have_image Planet85 thermograph5)
	(have_image Planet85 thermograph3)
	(have_image Planet85 image11)
	(have_image Planet85 thermograph7)
	(have_image Planet85 thermograph2)
	(have_image Phenomenon86 thermograph5)
	(have_image Phenomenon86 image12)
	(have_image Phenomenon86 thermograph2)
	(have_image Planet87 thermograph13)
	(have_image Planet87 thermograph3)
	(have_image Planet87 thermograph2)
	(have_image Phenomenon89 spectrograph8)
	(have_image Phenomenon89 image16)
	(have_image Phenomenon89 infrared1)
	(have_image Phenomenon89 thermograph13)
	(have_image Phenomenon91 thermograph7)
	(have_image Phenomenon91 spectrograph19)
	(have_image Phenomenon91 infrared9)
	(have_image Phenomenon91 spectrograph15)
	(have_image Phenomenon92 spectrograph19)
	(have_image Phenomenon93 thermograph5)
	(have_image Phenomenon94 spectrograph8)
	(have_image Phenomenon94 infrared9)
	(have_image Phenomenon94 thermograph10)
	(have_image Planet95 thermograph13)
	(have_image Planet95 thermograph10)
	(have_image Planet95 infrared9)
	(have_image Planet95 infrared1)
	(have_image Planet95 thermograph5)
	(have_image Star96 image12)
	(have_image Phenomenon97 image12)
	(have_image Phenomenon97 thermograph2)
	(have_image Phenomenon97 image16)
	(have_image Phenomenon97 thermograph7)
	(have_image Phenomenon97 infrared4)
	(have_image Phenomenon98 infrared1)
	(have_image Phenomenon98 thermograph13)
	(have_image Phenomenon99 spectrograph8)
	(have_image Phenomenon99 infrared1)
	(have_image Phenomenon99 thermograph13)
	(have_image Phenomenon99 infrared4)
	(have_image Phenomenon99 spectrograph15)
	(have_image Phenomenon100 infrared6)
	(have_image Phenomenon100 spectrograph8)
	(have_image Phenomenon100 spectrograph15)
	(have_image Phenomenon100 thermograph5)
	(have_image Phenomenon101 image11)
	(have_image Phenomenon101 spectrograph8)
	(have_image Phenomenon101 thermograph3)
	(have_image Phenomenon101 thermograph5)
	(have_image Phenomenon101 thermograph7)
	(have_image Phenomenon102 image12)
	(have_image Phenomenon102 image11)
	(have_image Phenomenon102 infrared4)
	(have_image Phenomenon102 thermograph13)
	(have_image Star103 infrared1)
	(have_image Star103 spectrograph19)
	(have_image Star103 infrared9)
	(have_image Phenomenon104 thermograph13)
	(have_image Phenomenon104 spectrograph19)
	(have_image Phenomenon104 thermograph7)
	(have_image Phenomenon104 infrared6)
	(have_image Phenomenon104 image12)
	(have_image Star105 infrared17)
	(have_image Star105 spectrograph19)
	(have_image Star105 thermograph3)
	(have_image Phenomenon106 infrared9)
	(have_image Phenomenon106 thermograph2)
	(have_image Phenomenon106 image16)
	(have_image Phenomenon107 spectrograph19)
	(have_image Phenomenon107 infrared1)
	(have_image Phenomenon107 thermograph10)
	(have_image Phenomenon107 image11)
	(have_image Phenomenon107 thermograph13)
	(have_image Planet108 spectrograph19)
	(have_image Planet108 infrared6)
	(have_image Planet108 thermograph2)
	(have_image Planet108 infrared1)
	(have_image Planet108 infrared9)
	(have_image Planet109 spectrograph15)
	(have_image Phenomenon110 image11)
	(have_image Star111 image11)
	(have_image Star111 spectrograph8)
	(have_image Planet112 image16)
	(have_image Planet112 thermograph3)
	(have_image Phenomenon113 spectrograph8)
	(have_image Phenomenon113 infrared6)
	(have_image Phenomenon113 infrared1)
	(have_image Star114 thermograph2)
	(have_image Star114 thermograph5)
	(have_image Star114 infrared6)
	(have_image Phenomenon115 infrared17)
	(have_image Phenomenon115 infrared6)
	(have_image Star116 infrared4)
	(have_image Star116 infrared1)
	(have_image Star116 thermograph7)
	(have_image Star116 image12)
	(have_image Star117 thermograph3)
	(have_image Star117 spectrograph15)
	(have_image Star117 infrared17)
	(have_image Star117 thermograph13)
	(have_image Star117 thermograph2)
	(have_image Phenomenon118 infrared6)
	(have_image Phenomenon118 image11)
	(have_image Phenomenon118 infrared4)
	(have_image Phenomenon118 thermograph7)
	(have_image Planet119 thermograph5)
	(have_image Planet119 infrared17)
	(have_image Planet119 image16)
	(have_image Planet119 infrared4)
	(have_image Planet119 thermograph7)
	(have_image Star120 infrared4)
	(have_image Star120 infrared17)
	(have_image Star120 spectrograph8)
	(have_image Planet121 thermograph5)
	(have_image Phenomenon122 infrared17)
	(have_image Phenomenon122 image12)
	(have_image Phenomenon122 thermograph3)
	(have_image Phenomenon123 infrared4)
	(have_image Phenomenon123 thermograph7)
	(have_image Phenomenon123 image16)
	(have_image Phenomenon123 infrared6)
	(have_image Phenomenon123 image11)
	(have_image Planet124 infrared1)
	(have_image Planet124 spectrograph15)
	(have_image Planet124 thermograph5)
	(have_image Planet124 infrared6)
	(have_image Planet124 infrared9)
	(have_image Planet124 thermograph10)
	(have_image Star125 image12)
	(have_image Star125 thermograph2)
	(have_image Star125 image11)
	(have_image Star125 thermograph5)
	(have_image Star125 infrared9)
	(have_image Planet127 image11)
	(have_image Planet127 thermograph3)
	(have_image Planet127 infrared9)
	(have_image Star128 image11)
	(have_image Star128 spectrograph15)
	(have_image Planet129 spectrograph15)
	(have_image Planet129 thermograph2)
	(have_image Star130 image11)
	(have_image Star130 infrared17)
	(have_image Star130 thermograph5)
	(have_image Star132 image16)
	(have_image Star132 infrared17)
	(have_image Star132 thermograph3)
	(have_image Star132 infrared6)
	(have_image Star132 infrared9)
	(have_image Planet133 image12)
	(have_image Planet133 image11)
	(have_image Planet133 infrared9)
	(have_image Planet133 spectrograph8)
	(have_image Planet133 thermograph13)
	(have_image Phenomenon135 thermograph5)
	(have_image Phenomenon135 spectrograph19)
	(have_image Star136 infrared6)
	(have_image Star136 infrared9)
	(have_image Star136 spectrograph15)
	(have_image Planet137 thermograph7)
	(have_image Planet138 infrared17)
	(have_image Planet139 spectrograph8)
	(have_image Planet139 image16)
	(have_image Planet139 infrared9)
	(have_image Planet139 spectrograph15)
	(have_image Planet139 image12)
	(have_image Phenomenon140 spectrograph19)
	(have_image Phenomenon140 image12)
	(have_image Phenomenon140 spectrograph15)
	(have_image Phenomenon140 image16)
	(have_image Phenomenon140 thermograph7)
	(have_image Phenomenon140 infrared4)
	(have_image Planet141 image16)
	(have_image Planet141 infrared17)
	(have_image Planet141 thermograph13)
	(have_image Planet142 image16)
	(have_image Planet142 thermograph10)
	(have_image Planet142 infrared1)
	(have_image Planet142 infrared4)
	(have_image Phenomenon143 image11)
	(have_image Phenomenon143 spectrograph15)
	(have_image Planet144 infrared6)
	(have_image Planet144 thermograph13)
	(have_image Phenomenon145 image11)
	(have_image Planet147 spectrograph15)
	(have_image Planet147 infrared6)
	(have_image Phenomenon148 spectrograph8)
	(have_image Phenomenon148 image12)
	(have_image Phenomenon148 thermograph7)
	(have_image Phenomenon148 infrared17)
	(have_image Phenomenon148 infrared4)
	(have_image Phenomenon149 thermograph7)
	(have_image Star150 spectrograph19)
	(have_image Star150 thermograph3)
	(have_image Star150 thermograph7)
	(have_image Phenomenon152 thermograph13)
	(have_image Planet153 thermograph5)
	(have_image Planet153 thermograph2)
	(have_image Planet153 spectrograph15)
	(have_image Star154 thermograph3)
	(have_image Star154 infrared6)
	(have_image Phenomenon155 spectrograph8)
	(have_image Phenomenon155 image12)
	(have_image Phenomenon155 spectrograph15)
	(have_image Planet156 spectrograph19)
	(have_image Planet156 infrared4)
	(have_image Planet156 infrared17)
	(have_image Planet156 infrared1)
	(have_image Phenomenon157 image12)
	(have_image Phenomenon157 infrared17)
	(have_image Phenomenon157 thermograph10)
	(have_image Phenomenon158 thermograph10)
	(have_image Phenomenon158 infrared9)
	(have_image Phenomenon158 infrared4)
	(have_image Star159 spectrograph8)
	(have_image Star159 infrared4)
	(have_image Star159 infrared6)
	(have_image Planet160 thermograph2)
	(have_image Star161 image16)
	(have_image Planet162 spectrograph19)
	(have_image Planet162 thermograph7)
	(have_image Phenomenon163 infrared17)
	(have_image Phenomenon163 image12)
	(have_image Star164 image16)
	(have_image Star164 thermograph10)
	(have_image Star164 spectrograph8)
	(have_image Star164 thermograph13)
	(have_image Star165 infrared17)
	(have_image Phenomenon166 spectrograph8)
	(have_image Phenomenon166 thermograph10)
	(have_image Phenomenon166 thermograph5)
	(have_image Phenomenon166 image11)
	(have_image Phenomenon166 infrared4)
	(have_image Phenomenon167 spectrograph8)
	(have_image Phenomenon167 infrared17)
	(have_image Phenomenon167 thermograph5)
	(have_image Phenomenon167 image16)
	(have_image Phenomenon168 infrared4)
	(have_image Phenomenon168 thermograph5)
	(have_image Phenomenon168 spectrograph19)
	(have_image Phenomenon168 infrared17)
	(have_image Phenomenon168 spectrograph8)
	(have_image Planet169 image11)
	(have_image Planet169 thermograph5)
	(have_image Planet169 spectrograph8)
	(have_image Planet169 thermograph2)
	(have_image Star170 infrared4)
	(have_image Star170 infrared1)
	(have_image Star170 spectrograph8)
	(have_image Phenomenon172 infrared17)
	(have_image Planet173 thermograph2)
	(have_image Planet173 spectrograph15)
	(have_image Planet175 infrared4)
	(have_image Phenomenon176 thermograph2)
	(have_image Phenomenon176 infrared1)
	(have_image Phenomenon176 spectrograph19)
	(have_image Phenomenon176 thermograph5)
	(have_image Phenomenon176 thermograph13)
	(have_image Star177 infrared4)
	(have_image Phenomenon178 image16)
	(have_image Planet179 thermograph10)
	(have_image Planet179 infrared4)
	(have_image Planet179 thermograph3)
	(have_image Planet180 infrared4)
	(have_image Planet180 thermograph2)
	(have_image Planet180 thermograph13)
	(have_image Planet180 spectrograph19)
	(have_image Phenomenon181 thermograph7)
	(have_image Phenomenon181 spectrograph15)
))

)
