domains = [
{'description': 'Traveling and buying goods at selected markets minimizing costs (from OR with variants, NP-hard).',
 'ipc': '2011',
 'name': 'tpp',
 'problems': [('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p01.pddl'),
('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p02.pddl'),
('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p03.pddl'),
('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p04.pddl'),
('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p05.pddl'),
('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p06.pddl'),
('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p07.pddl'),
('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p08.pddl'),
('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p09.pddl'),
('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p10.pddl'),
('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p11.pddl'),
('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p12.pddl'),
('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p13.pddl'),
('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p14.pddl'),
('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p15.pddl'),
('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p16.pddl'),
('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p17.pddl'),
('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p18.pddl'),
('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p19.pddl'),
('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p20.pddl'),
('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p21.pddl'),
('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p22.pddl'),
('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p23.pddl'),
('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p24.pddl'),
('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p25.pddl'),
('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p26.pddl'),
('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p27.pddl'),
('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p28.pddl'),
('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p29.pddl'),
('tpp-ipc11-learning-target/domain.pddl', 'tpp-ipc11-learning-target/p30.pddl')]}
]
