domains = [
{'description': 'The GED problem is to find a min-cost sequence of operations that transforms one genome (signed permutation of genes) into another. The purpose of this is to use this cost as a measure of the distance between the two genomes, which is used to construct hypotheses about the evolutionary relationship between the organisms.',
 'ipc': '2014',
 'name': 'ged',
 'problems': [('ged-opt14-strips/domain.pddl', 'ged-opt14-strips/d-1-2.pddl'),
              ('ged-opt14-strips/domain.pddl', 'ged-opt14-strips/d-1-3.pddl'),
              ('ged-opt14-strips/domain.pddl', 'ged-opt14-strips/d-1-4.pddl'),
              ('ged-opt14-strips/domain.pddl', 'ged-opt14-strips/d-1-8.pddl'),
              ('ged-opt14-strips/domain.pddl', 'ged-opt14-strips/d-2-1.pddl'),
              ('ged-opt14-strips/domain.pddl', 'ged-opt14-strips/d-2-3.pddl'),
              ('ged-opt14-strips/domain.pddl', 'ged-opt14-strips/d-2-4.pddl'),
              ('ged-opt14-strips/domain.pddl', 'ged-opt14-strips/d-2-8.pddl'),
              ('ged-opt14-strips/domain.pddl', 'ged-opt14-strips/d-3-1.pddl'),
              ('ged-opt14-strips/domain.pddl', 'ged-opt14-strips/d-3-2.pddl'),
              ('ged-opt14-strips/domain.pddl', 'ged-opt14-strips/d-3-4.pddl'),
              ('ged-opt14-strips/domain.pddl', 'ged-opt14-strips/d-4-2.pddl'),
              ('ged-opt14-strips/domain.pddl', 'ged-opt14-strips/d-4-3.pddl'),
              ('ged-opt14-strips/domain.pddl', 'ged-opt14-strips/d-4-8.pddl'),
              ('ged-opt14-strips/domain.pddl', 'ged-opt14-strips/d-7-5.pddl'),
              ('ged-opt14-strips/domain.pddl', 'ged-opt14-strips/d-7-6.pddl'),
              ('ged-opt14-strips/domain.pddl', 'ged-opt14-strips/d-8-1.pddl'),
              ('ged-opt14-strips/domain.pddl', 'ged-opt14-strips/d-8-2.pddl'),
              ('ged-opt14-strips/domain.pddl', 'ged-opt14-strips/d-8-4.pddl'),
              ('ged-opt14-strips/domain.pddl', 'ged-opt14-strips/d-8-9.pddl')]}
]