domains = [
{'description': 'The first of the domains inspired by space-applications is a first step towards the "Ambitious Spacecraft" described by David Smith at AIPS-2000. It involves planning and scheduling a collection of observation tasks between multiple satellites, each equipped in slightly different ways.',
 'ipc': '2011',
 'name': 'satellite',
 'problems': [('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p01.pddl'),
('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p02.pddl'),
('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p03.pddl'),
('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p04.pddl'),
('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p05.pddl'),
('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p06.pddl'),
('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p07.pddl'),
('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p08.pddl'),
('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p09.pddl'),
('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p10.pddl'),
('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p11.pddl'),
('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p12.pddl'),
('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p13.pddl'),
('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p14.pddl'),
('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p15.pddl'),
('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p16.pddl'),
('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p17.pddl'),
('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p18.pddl'),
('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p19.pddl'),
('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p20.pddl'),
('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p21.pddl'),
('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p22.pddl'),
('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p23.pddl'),
('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p24.pddl'),
('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p25.pddl'),
('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p26.pddl'),
('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p27.pddl'),
('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p28.pddl'),
('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p29.pddl'),
('satellite-ipc11-learning-test/domain.pddl', 'satellite-ipc11-learning-test/p30.pddl')]}
]
