(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	satellite2 - satellite
	instrument3 - instrument
	satellite3 - satellite
	instrument4 - instrument
	instrument5 - instrument
	satellite4 - satellite
	instrument6 - instrument
	satellite5 - satellite
	instrument7 - instrument
	satellite6 - satellite
	instrument8 - instrument
	satellite7 - satellite
	instrument9 - instrument
	instrument10 - instrument
	satellite8 - satellite
	instrument11 - instrument
	satellite9 - satellite
	instrument12 - instrument
	thermograph13 - mode
	infrared10 - mode
	thermograph14 - mode
	thermograph6 - mode
	infrared11 - mode
	infrared1 - mode
	image12 - mode
	image4 - mode
	spectrograph5 - mode
	spectrograph2 - mode
	infrared8 - mode
	image9 - mode
	infrared7 - mode
	infrared0 - mode
	spectrograph3 - mode
	GroundStation1 - direction
	GroundStation0 - direction
	Star2 - direction
	Phenomenon3 - direction
	Star4 - direction
	Planet5 - direction
	Star6 - direction
	Planet7 - direction
	Planet8 - direction
	Planet9 - direction
	Star10 - direction
	Planet11 - direction
	Planet12 - direction
	Planet13 - direction
	Planet14 - direction
	Phenomenon15 - direction
	Star16 - direction
	Phenomenon17 - direction
	Planet18 - direction
	Phenomenon19 - direction
	Star20 - direction
	Planet21 - direction
	Phenomenon22 - direction
	Planet23 - direction
	Phenomenon24 - direction
	Phenomenon25 - direction
	Phenomenon26 - direction
	Planet27 - direction
	Phenomenon28 - direction
	Planet29 - direction
	Phenomenon30 - direction
	Star31 - direction
	Planet32 - direction
	Star33 - direction
	Star34 - direction
	Phenomenon35 - direction
	Phenomenon36 - direction
	Planet37 - direction
	Phenomenon38 - direction
	Star39 - direction
	Phenomenon40 - direction
	Phenomenon41 - direction
	Phenomenon42 - direction
	Phenomenon43 - direction
	Phenomenon44 - direction
	Phenomenon45 - direction
	Phenomenon46 - direction
	Phenomenon47 - direction
	Planet48 - direction
	Planet49 - direction
	Planet50 - direction
	Planet51 - direction
	Planet52 - direction
	Phenomenon53 - direction
	Planet54 - direction
	Star55 - direction
	Planet56 - direction
	Star57 - direction
	Planet58 - direction
	Star59 - direction
	Phenomenon60 - direction
	Phenomenon61 - direction
	Star62 - direction
	Phenomenon63 - direction
	Planet64 - direction
	Planet65 - direction
	Phenomenon66 - direction
	Planet67 - direction
	Planet68 - direction
	Planet69 - direction
	Planet70 - direction
	Phenomenon71 - direction
	Star72 - direction
	Planet73 - direction
	Star74 - direction
	Star75 - direction
	Phenomenon76 - direction
	Star77 - direction
	Phenomenon78 - direction
	Phenomenon79 - direction
	Planet80 - direction
	Phenomenon81 - direction
	Planet82 - direction
	Phenomenon83 - direction
	Phenomenon84 - direction
	Phenomenon85 - direction
	Star86 - direction
	Phenomenon87 - direction
	Star88 - direction
	Star89 - direction
	Phenomenon90 - direction
	Phenomenon91 - direction
	Phenomenon92 - direction
	Star93 - direction
	Planet94 - direction
	Planet95 - direction
	Phenomenon96 - direction
	Phenomenon97 - direction
	Star98 - direction
	Phenomenon99 - direction
	Star100 - direction
	Planet101 - direction
	Star102 - direction
	Planet103 - direction
	Planet104 - direction
	Star105 - direction
	Star106 - direction
	Planet107 - direction
	Star108 - direction
	Star109 - direction
	Planet110 - direction
	Planet111 - direction
	Planet112 - direction
	Star113 - direction
	Star114 - direction
	Planet115 - direction
	Planet116 - direction
	Phenomenon117 - direction
	Star118 - direction
	Star119 - direction
	Planet120 - direction
	Phenomenon121 - direction
	Phenomenon122 - direction
	Phenomenon123 - direction
	Phenomenon124 - direction
	Phenomenon125 - direction
	Planet126 - direction
	Star127 - direction
	Phenomenon128 - direction
	Planet129 - direction
	Star130 - direction
	Star131 - direction
	Star132 - direction
	Star133 - direction
	Planet134 - direction
	Star135 - direction
	Phenomenon136 - direction
	Star137 - direction
	Planet138 - direction
	Star139 - direction
	Planet140 - direction
	Planet141 - direction
	Planet142 - direction
	Phenomenon143 - direction
	Phenomenon144 - direction
	Phenomenon145 - direction
	Planet146 - direction
	Phenomenon147 - direction
	Star148 - direction
	Phenomenon149 - direction
	Planet150 - direction
	Planet151 - direction
)
(:init
	(supports instrument0 image12)
	(calibration_target instrument0 GroundStation1)
	(supports instrument1 thermograph6)
	(calibration_target instrument1 GroundStation1)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star118)
	(supports instrument2 image4)
	(calibration_target instrument2 GroundStation0)
	(on_board instrument2 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star89)
	(supports instrument3 infrared8)
	(supports instrument3 infrared11)
	(calibration_target instrument3 GroundStation1)
	(on_board instrument3 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon36)
	(supports instrument4 spectrograph5)
	(supports instrument4 image12)
	(calibration_target instrument4 GroundStation1)
	(supports instrument5 image4)
	(calibration_target instrument5 GroundStation0)
	(on_board instrument4 satellite3)
	(on_board instrument5 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet21)
	(supports instrument6 infrared1)
	(supports instrument6 infrared0)
	(calibration_target instrument6 GroundStation1)
	(on_board instrument6 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star98)
	(supports instrument7 spectrograph2)
	(supports instrument7 spectrograph5)
	(supports instrument7 image12)
	(calibration_target instrument7 GroundStation1)
	(on_board instrument7 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Planet51)
	(supports instrument8 spectrograph2)
	(supports instrument8 image4)
	(calibration_target instrument8 GroundStation1)
	(on_board instrument8 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet51)
	(supports instrument9 infrared8)
	(supports instrument9 spectrograph2)
	(supports instrument9 spectrograph5)
	(calibration_target instrument9 GroundStation0)
	(supports instrument10 image9)
	(calibration_target instrument10 GroundStation0)
	(on_board instrument9 satellite7)
	(on_board instrument10 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Planet32)
	(supports instrument11 infrared0)
	(supports instrument11 infrared7)
	(calibration_target instrument11 GroundStation1)
	(on_board instrument11 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Phenomenon53)
	(supports instrument12 spectrograph3)
	(calibration_target instrument12 GroundStation0)
	(on_board instrument12 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Phenomenon40)
)
(:goal (and
	(pointing satellite2 Star100)
	(pointing satellite5 Phenomenon85)
	(pointing satellite7 Phenomenon25)
	(pointing satellite8 Star77)
	(have_image Star2 spectrograph5)
	(have_image Star2 image9)
	(have_image Star2 infrared8)
	(have_image Star2 thermograph6)
	(have_image Star2 infrared0)
	(have_image Phenomenon3 image9)
	(have_image Phenomenon3 spectrograph3)
	(have_image Star4 infrared8)
	(have_image Planet5 infrared1)
	(have_image Planet5 spectrograph3)
	(have_image Planet7 infrared7)
	(have_image Planet8 infrared11)
	(have_image Planet8 image4)
	(have_image Planet8 image12)
	(have_image Planet9 spectrograph2)
	(have_image Planet9 infrared7)
	(have_image Planet9 image9)
	(have_image Planet9 image4)
	(have_image Planet9 infrared1)
	(have_image Star10 infrared8)
	(have_image Star10 image4)
	(have_image Star10 spectrograph5)
	(have_image Star10 image12)
	(have_image Planet11 infrared0)
	(have_image Planet11 spectrograph5)
	(have_image Planet11 spectrograph2)
	(have_image Planet11 infrared8)
	(have_image Planet11 image4)
	(have_image Planet12 spectrograph5)
	(have_image Planet12 image4)
	(have_image Planet12 image9)
	(have_image Planet13 infrared0)
	(have_image Planet13 image9)
	(have_image Planet13 infrared8)
	(have_image Planet13 image12)
	(have_image Planet13 infrared1)
	(have_image Planet14 image12)
	(have_image Planet14 infrared8)
	(have_image Planet14 infrared0)
	(have_image Phenomenon15 infrared11)
	(have_image Phenomenon15 spectrograph2)
	(have_image Phenomenon15 image9)
	(have_image Star16 infrared8)
	(have_image Star16 infrared1)
	(have_image Star16 image4)
	(have_image Phenomenon17 image12)
	(have_image Phenomenon17 spectrograph3)
	(have_image Phenomenon17 image9)
	(have_image Planet18 spectrograph3)
	(have_image Planet18 infrared1)
	(have_image Phenomenon19 infrared11)
	(have_image Phenomenon19 spectrograph2)
	(have_image Phenomenon19 spectrograph3)
	(have_image Phenomenon19 infrared8)
	(have_image Star20 infrared11)
	(have_image Star20 infrared7)
	(have_image Planet21 spectrograph5)
	(have_image Planet21 image12)
	(have_image Planet21 infrared0)
	(have_image Planet21 infrared11)
	(have_image Phenomenon22 image12)
	(have_image Phenomenon22 image4)
	(have_image Phenomenon22 infrared8)
	(have_image Planet23 image12)
	(have_image Planet23 spectrograph2)
	(have_image Phenomenon24 infrared0)
	(have_image Phenomenon24 image9)
	(have_image Phenomenon25 infrared8)
	(have_image Phenomenon25 image4)
	(have_image Phenomenon25 image9)
	(have_image Phenomenon26 image9)
	(have_image Phenomenon26 spectrograph3)
	(have_image Phenomenon26 infrared8)
	(have_image Phenomenon26 image12)
	(have_image Planet27 infrared8)
	(have_image Planet27 image12)
	(have_image Phenomenon28 image9)
	(have_image Phenomenon28 spectrograph2)
	(have_image Phenomenon28 infrared8)
	(have_image Phenomenon28 image12)
	(have_image Phenomenon28 thermograph6)
	(have_image Planet29 infrared8)
	(have_image Planet29 infrared11)
	(have_image Planet29 thermograph6)
	(have_image Planet29 image12)
	(have_image Star31 infrared11)
	(have_image Planet32 image9)
	(have_image Star33 thermograph6)
	(have_image Star33 infrared1)
	(have_image Star34 spectrograph3)
	(have_image Star34 infrared0)
	(have_image Star34 spectrograph5)
	(have_image Phenomenon36 infrared7)
	(have_image Planet37 spectrograph5)
	(have_image Planet37 infrared1)
	(have_image Planet37 image9)
	(have_image Planet37 infrared7)
	(have_image Phenomenon38 infrared11)
	(have_image Phenomenon38 spectrograph2)
	(have_image Phenomenon38 spectrograph5)
	(have_image Phenomenon38 infrared1)
	(have_image Phenomenon38 infrared0)
	(have_image Star39 image12)
	(have_image Star39 spectrograph5)
	(have_image Star39 infrared11)
	(have_image Star39 infrared8)
	(have_image Star39 infrared0)
	(have_image Phenomenon40 infrared1)
	(have_image Phenomenon40 infrared7)
	(have_image Phenomenon41 infrared8)
	(have_image Phenomenon41 spectrograph2)
	(have_image Phenomenon42 spectrograph5)
	(have_image Phenomenon42 spectrograph2)
	(have_image Phenomenon43 infrared1)
	(have_image Phenomenon43 spectrograph5)
	(have_image Phenomenon43 spectrograph2)
	(have_image Phenomenon44 infrared8)
	(have_image Phenomenon44 image9)
	(have_image Phenomenon44 spectrograph5)
	(have_image Phenomenon45 thermograph6)
	(have_image Phenomenon45 infrared0)
	(have_image Phenomenon46 infrared0)
	(have_image Phenomenon46 image12)
	(have_image Phenomenon46 infrared1)
	(have_image Phenomenon47 spectrograph2)
	(have_image Phenomenon47 spectrograph5)
	(have_image Phenomenon47 spectrograph3)
	(have_image Phenomenon47 image4)
	(have_image Phenomenon47 image9)
	(have_image Planet48 image9)
	(have_image Planet48 image4)
	(have_image Planet49 infrared11)
	(have_image Planet49 spectrograph3)
	(have_image Planet49 spectrograph2)
	(have_image Planet50 infrared7)
	(have_image Planet50 infrared1)
	(have_image Planet51 infrared7)
	(have_image Phenomenon53 image4)
	(have_image Planet56 infrared8)
	(have_image Planet56 image12)
	(have_image Planet56 image4)
	(have_image Star57 infrared8)
	(have_image Star57 infrared7)
	(have_image Planet58 spectrograph3)
	(have_image Planet58 infrared7)
	(have_image Planet58 image4)
	(have_image Star59 spectrograph5)
	(have_image Phenomenon60 infrared8)
	(have_image Phenomenon60 infrared0)
	(have_image Phenomenon60 image4)
	(have_image Phenomenon61 infrared0)
	(have_image Phenomenon61 spectrograph5)
	(have_image Phenomenon61 infrared7)
	(have_image Phenomenon61 image4)
	(have_image Phenomenon61 infrared8)
	(have_image Star62 infrared0)
	(have_image Star62 spectrograph3)
	(have_image Phenomenon63 infrared11)
	(have_image Phenomenon63 image4)
	(have_image Planet65 spectrograph2)
	(have_image Planet65 infrared11)
	(have_image Planet65 image9)
	(have_image Phenomenon66 infrared11)
	(have_image Planet67 image12)
	(have_image Planet68 image9)
	(have_image Planet68 spectrograph3)
	(have_image Planet68 image4)
	(have_image Planet69 image12)
	(have_image Planet69 infrared1)
	(have_image Planet70 image12)
	(have_image Planet70 infrared7)
	(have_image Planet70 infrared0)
	(have_image Planet70 image4)
	(have_image Phenomenon71 infrared7)
	(have_image Phenomenon71 spectrograph5)
	(have_image Star72 spectrograph3)
	(have_image Star72 image9)
	(have_image Planet73 thermograph6)
	(have_image Planet73 image9)
	(have_image Star74 thermograph6)
	(have_image Star74 image12)
	(have_image Star74 spectrograph3)
	(have_image Star75 infrared8)
	(have_image Star75 infrared7)
	(have_image Phenomenon76 image4)
	(have_image Phenomenon76 infrared0)
	(have_image Star77 image4)
	(have_image Star77 infrared11)
	(have_image Star77 image12)
	(have_image Phenomenon78 image12)
	(have_image Phenomenon78 spectrograph2)
	(have_image Phenomenon79 infrared7)
	(have_image Phenomenon79 infrared1)
	(have_image Planet80 thermograph6)
	(have_image Phenomenon81 infrared7)
	(have_image Phenomenon81 infrared1)
	(have_image Phenomenon83 infrared8)
	(have_image Phenomenon83 spectrograph2)
	(have_image Phenomenon84 infrared1)
	(have_image Phenomenon84 thermograph6)
	(have_image Phenomenon85 image12)
	(have_image Phenomenon85 infrared11)
	(have_image Phenomenon85 thermograph6)
	(have_image Star86 spectrograph5)
	(have_image Star86 infrared0)
	(have_image Star86 spectrograph2)
	(have_image Star86 infrared1)
	(have_image Star88 spectrograph2)
	(have_image Star88 infrared7)
	(have_image Star89 thermograph6)
	(have_image Star89 infrared0)
	(have_image Star89 infrared7)
	(have_image Star89 spectrograph2)
	(have_image Star89 image12)
	(have_image Phenomenon90 infrared0)
	(have_image Phenomenon91 image9)
	(have_image Phenomenon92 image9)
	(have_image Phenomenon92 infrared8)
	(have_image Phenomenon92 infrared0)
	(have_image Star93 thermograph6)
	(have_image Planet94 image4)
	(have_image Planet94 spectrograph5)
	(have_image Planet94 infrared7)
	(have_image Planet94 infrared1)
	(have_image Planet95 infrared7)
	(have_image Planet95 infrared11)
	(have_image Planet95 infrared0)
	(have_image Planet95 spectrograph5)
	(have_image Phenomenon96 infrared7)
	(have_image Phenomenon97 infrared11)
	(have_image Star98 infrared1)
	(have_image Star98 spectrograph3)
	(have_image Star98 thermograph6)
	(have_image Phenomenon99 infrared0)
	(have_image Phenomenon99 spectrograph3)
	(have_image Star100 image4)
	(have_image Star100 spectrograph2)
	(have_image Planet101 image9)
	(have_image Planet101 thermograph6)
	(have_image Star102 infrared0)
	(have_image Star102 thermograph6)
	(have_image Star102 image4)
	(have_image Star102 image12)
	(have_image Star105 spectrograph5)
	(have_image Star105 infrared0)
	(have_image Star106 thermograph6)
	(have_image Star106 spectrograph2)
	(have_image Planet107 image12)
	(have_image Planet107 image9)
	(have_image Planet107 spectrograph5)
	(have_image Planet107 spectrograph3)
	(have_image Planet107 infrared0)
	(have_image Star108 spectrograph3)
	(have_image Star108 infrared7)
	(have_image Star108 image12)
	(have_image Star109 infrared1)
	(have_image Planet110 infrared8)
	(have_image Planet110 image9)
	(have_image Planet112 thermograph6)
	(have_image Planet112 infrared7)
	(have_image Planet112 spectrograph2)
	(have_image Star113 infrared8)
	(have_image Star113 thermograph6)
	(have_image Star114 infrared1)
	(have_image Star114 image12)
	(have_image Planet115 thermograph6)
	(have_image Planet115 spectrograph3)
	(have_image Planet115 infrared8)
	(have_image Planet115 infrared11)
	(have_image Planet116 spectrograph2)
	(have_image Planet116 thermograph6)
	(have_image Planet116 spectrograph5)
	(have_image Planet116 image9)
	(have_image Phenomenon117 infrared1)
	(have_image Phenomenon117 infrared8)
	(have_image Phenomenon117 thermograph6)
	(have_image Phenomenon117 infrared0)
	(have_image Star118 image4)
	(have_image Star118 infrared8)
	(have_image Star118 infrared1)
	(have_image Star118 thermograph6)
	(have_image Star118 image12)
	(have_image Star119 spectrograph2)
	(have_image Star119 infrared7)
	(have_image Star119 image9)
	(have_image Phenomenon121 infrared7)
	(have_image Phenomenon122 spectrograph5)
	(have_image Phenomenon122 thermograph6)
	(have_image Phenomenon125 infrared11)
	(have_image Phenomenon125 infrared0)
	(have_image Phenomenon125 spectrograph5)
	(have_image Phenomenon125 image4)
	(have_image Planet126 image9)
	(have_image Planet126 image4)
	(have_image Planet126 thermograph6)
	(have_image Star127 image12)
	(have_image Star127 spectrograph3)
	(have_image Star127 infrared8)
	(have_image Phenomenon128 image4)
	(have_image Phenomenon128 spectrograph3)
	(have_image Phenomenon128 image9)
	(have_image Planet129 infrared8)
	(have_image Star130 infrared8)
	(have_image Star130 spectrograph3)
	(have_image Star131 image9)
	(have_image Star131 infrared0)
	(have_image Star133 infrared8)
	(have_image Star133 infrared11)
	(have_image Star133 image4)
	(have_image Star133 spectrograph3)
	(have_image Star133 spectrograph5)
	(have_image Planet134 infrared7)
	(have_image Planet134 infrared8)
	(have_image Planet134 thermograph6)
	(have_image Planet134 spectrograph2)
	(have_image Star135 spectrograph3)
	(have_image Star135 image9)
	(have_image Phenomenon136 thermograph6)
	(have_image Star137 image9)
	(have_image Star137 spectrograph5)
	(have_image Star137 infrared7)
	(have_image Planet138 infrared0)
	(have_image Planet140 infrared8)
	(have_image Planet140 spectrograph3)
	(have_image Planet141 infrared7)
	(have_image Planet141 infrared8)
	(have_image Planet142 thermograph6)
	(have_image Planet142 image9)
	(have_image Planet142 spectrograph5)
	(have_image Planet142 image4)
	(have_image Phenomenon143 infrared7)
	(have_image Phenomenon143 infrared1)
	(have_image Phenomenon143 spectrograph2)
	(have_image Planet146 infrared11)
	(have_image Phenomenon147 infrared11)
	(have_image Phenomenon147 infrared8)
	(have_image Phenomenon147 thermograph6)
	(have_image Phenomenon147 image9)
	(have_image Star148 infrared7)
	(have_image Star148 spectrograph3)
	(have_image Star148 image12)
	(have_image Star148 infrared11)
))

)
