(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	satellite2 - satellite
	instrument2 - instrument
	instrument3 - instrument
	satellite3 - satellite
	instrument4 - instrument
	satellite4 - satellite
	instrument5 - instrument
	satellite5 - satellite
	instrument6 - instrument
	satellite6 - satellite
	instrument7 - instrument
	satellite7 - satellite
	instrument8 - instrument
	satellite8 - satellite
	instrument9 - instrument
	instrument10 - instrument
	satellite9 - satellite
	instrument11 - instrument
	instrument12 - instrument
	infrared11 - mode
	infrared4 - mode
	infrared14 - mode
	thermograph13 - mode
	spectrograph8 - mode
	infrared2 - mode
	thermograph10 - mode
	image1 - mode
	thermograph7 - mode
	infrared3 - mode
	infrared12 - mode
	spectrograph5 - mode
	spectrograph0 - mode
	image9 - mode
	infrared6 - mode
	GroundStation1 - direction
	Star0 - direction
	Phenomenon2 - direction
	Planet3 - direction
	Planet4 - direction
	Phenomenon5 - direction
	Star6 - direction
	Phenomenon7 - direction
	Planet8 - direction
	Planet9 - direction
	Phenomenon10 - direction
	Star11 - direction
	Planet12 - direction
	Star13 - direction
	Star14 - direction
	Planet15 - direction
	Planet16 - direction
	Phenomenon17 - direction
	Planet18 - direction
	Star19 - direction
	Phenomenon20 - direction
	Star21 - direction
	Phenomenon22 - direction
	Phenomenon23 - direction
	Planet24 - direction
	Planet25 - direction
	Planet26 - direction
	Phenomenon27 - direction
	Phenomenon28 - direction
	Star29 - direction
	Phenomenon30 - direction
	Planet31 - direction
	Phenomenon32 - direction
	Planet33 - direction
	Planet34 - direction
	Phenomenon35 - direction
	Planet36 - direction
	Planet37 - direction
	Star38 - direction
	Planet39 - direction
	Planet40 - direction
	Star41 - direction
	Star42 - direction
	Star43 - direction
	Phenomenon44 - direction
	Phenomenon45 - direction
	Planet46 - direction
	Star47 - direction
	Star48 - direction
	Phenomenon49 - direction
	Phenomenon50 - direction
	Star51 - direction
	Planet52 - direction
	Planet53 - direction
	Star54 - direction
	Planet55 - direction
	Phenomenon56 - direction
	Planet57 - direction
	Planet58 - direction
	Phenomenon59 - direction
	Phenomenon60 - direction
	Star61 - direction
	Planet62 - direction
	Phenomenon63 - direction
	Phenomenon64 - direction
	Star65 - direction
	Phenomenon66 - direction
	Phenomenon67 - direction
	Star68 - direction
	Phenomenon69 - direction
	Planet70 - direction
	Planet71 - direction
	Phenomenon72 - direction
	Phenomenon73 - direction
	Phenomenon74 - direction
	Star75 - direction
	Star76 - direction
	Star77 - direction
	Phenomenon78 - direction
	Planet79 - direction
	Planet80 - direction
	Planet81 - direction
	Phenomenon82 - direction
	Phenomenon83 - direction
	Planet84 - direction
	Phenomenon85 - direction
	Planet86 - direction
	Planet87 - direction
	Phenomenon88 - direction
	Planet89 - direction
	Phenomenon90 - direction
	Planet91 - direction
	Star92 - direction
	Phenomenon93 - direction
	Star94 - direction
	Star95 - direction
	Phenomenon96 - direction
	Planet97 - direction
	Star98 - direction
	Planet99 - direction
	Star100 - direction
	Planet101 - direction
	Phenomenon102 - direction
	Phenomenon103 - direction
	Star104 - direction
	Star105 - direction
	Phenomenon106 - direction
	Star107 - direction
	Star108 - direction
	Star109 - direction
	Star110 - direction
	Phenomenon111 - direction
	Phenomenon112 - direction
	Phenomenon113 - direction
	Star114 - direction
	Planet115 - direction
	Phenomenon116 - direction
	Phenomenon117 - direction
	Phenomenon118 - direction
	Planet119 - direction
	Phenomenon120 - direction
	Star121 - direction
	Star122 - direction
	Planet123 - direction
	Star124 - direction
	Star125 - direction
	Phenomenon126 - direction
	Star127 - direction
	Phenomenon128 - direction
	Star129 - direction
	Phenomenon130 - direction
	Star131 - direction
	Planet132 - direction
	Phenomenon133 - direction
	Phenomenon134 - direction
	Phenomenon135 - direction
	Planet136 - direction
	Planet137 - direction
	Planet138 - direction
	Phenomenon139 - direction
	Phenomenon140 - direction
	Phenomenon141 - direction
	Phenomenon142 - direction
	Planet143 - direction
	Star144 - direction
	Star145 - direction
	Phenomenon146 - direction
	Star147 - direction
	Phenomenon148 - direction
	Phenomenon149 - direction
	Phenomenon150 - direction
	Star151 - direction
)
(:init
	(supports instrument0 infrared3)
	(supports instrument0 spectrograph8)
	(supports instrument0 thermograph13)
	(calibration_target instrument0 Star0)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon22)
	(supports instrument1 infrared14)
	(supports instrument1 image1)
	(calibration_target instrument1 GroundStation1)
	(on_board instrument1 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Phenomenon141)
	(supports instrument2 thermograph7)
	(supports instrument2 infrared2)
	(calibration_target instrument2 Star0)
	(supports instrument3 infrared14)
	(calibration_target instrument3 GroundStation1)
	(on_board instrument2 satellite2)
	(on_board instrument3 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon148)
	(supports instrument4 infrared12)
	(supports instrument4 thermograph13)
	(calibration_target instrument4 Star0)
	(on_board instrument4 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon50)
	(supports instrument5 infrared12)
	(supports instrument5 spectrograph0)
	(calibration_target instrument5 GroundStation1)
	(on_board instrument5 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet71)
	(supports instrument6 thermograph10)
	(supports instrument6 infrared2)
	(supports instrument6 spectrograph8)
	(calibration_target instrument6 Star0)
	(on_board instrument6 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Phenomenon150)
	(supports instrument7 thermograph7)
	(supports instrument7 image1)
	(supports instrument7 infrared3)
	(calibration_target instrument7 GroundStation1)
	(on_board instrument7 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star65)
	(supports instrument8 infrared6)
	(calibration_target instrument8 Star0)
	(on_board instrument8 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Planet97)
	(supports instrument9 infrared12)
	(supports instrument9 infrared3)
	(calibration_target instrument9 Star0)
	(supports instrument10 spectrograph5)
	(supports instrument10 image9)
	(calibration_target instrument10 GroundStation1)
	(on_board instrument9 satellite8)
	(on_board instrument10 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Planet79)
	(supports instrument11 spectrograph0)
	(calibration_target instrument11 Star0)
	(supports instrument12 infrared6)
	(supports instrument12 image9)
	(calibration_target instrument12 Star0)
	(on_board instrument11 satellite9)
	(on_board instrument12 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Phenomenon17)
)
(:goal (and
	(pointing satellite3 Planet15)
	(pointing satellite6 Planet86)
	(pointing satellite8 Planet40)
	(have_image Phenomenon2 thermograph10)
	(have_image Phenomenon2 spectrograph8)
	(have_image Planet3 infrared3)
	(have_image Planet3 infrared14)
	(have_image Planet3 image9)
	(have_image Planet3 spectrograph0)
	(have_image Planet3 thermograph7)
	(have_image Planet4 infrared6)
	(have_image Planet4 spectrograph8)
	(have_image Planet4 spectrograph5)
	(have_image Planet4 infrared12)
	(have_image Phenomenon5 image1)
	(have_image Phenomenon5 infrared12)
	(have_image Star6 infrared6)
	(have_image Star6 spectrograph8)
	(have_image Star6 infrared3)
	(have_image Star6 thermograph13)
	(have_image Star6 image1)
	(have_image Phenomenon7 spectrograph8)
	(have_image Phenomenon7 infrared2)
	(have_image Phenomenon7 spectrograph5)
	(have_image Phenomenon7 infrared12)
	(have_image Phenomenon7 thermograph13)
	(have_image Planet8 image9)
	(have_image Planet8 image1)
	(have_image Planet9 infrared6)
	(have_image Planet9 spectrograph8)
	(have_image Planet9 thermograph7)
	(have_image Planet9 infrared3)
	(have_image Planet9 thermograph10)
	(have_image Phenomenon10 spectrograph8)
	(have_image Phenomenon10 infrared14)
	(have_image Phenomenon10 image9)
	(have_image Planet12 image9)
	(have_image Star14 image9)
	(have_image Planet15 infrared14)
	(have_image Planet16 image9)
	(have_image Planet16 spectrograph8)
	(have_image Planet16 image1)
	(have_image Phenomenon17 infrared6)
	(have_image Planet18 infrared2)
	(have_image Planet18 spectrograph5)
	(have_image Planet18 infrared6)
	(have_image Star19 spectrograph8)
	(have_image Star19 spectrograph0)
	(have_image Star19 spectrograph5)
	(have_image Star19 image1)
	(have_image Phenomenon20 infrared14)
	(have_image Planet24 image1)
	(have_image Planet24 thermograph7)
	(have_image Planet24 spectrograph0)
	(have_image Planet24 infrared6)
	(have_image Planet25 infrared12)
	(have_image Planet25 infrared3)
	(have_image Planet25 infrared14)
	(have_image Planet25 infrared6)
	(have_image Planet25 image9)
	(have_image Phenomenon28 thermograph7)
	(have_image Phenomenon28 spectrograph0)
	(have_image Star29 thermograph13)
	(have_image Star29 infrared3)
	(have_image Phenomenon30 thermograph7)
	(have_image Phenomenon30 infrared3)
	(have_image Planet31 spectrograph5)
	(have_image Planet31 infrared12)
	(have_image Phenomenon32 infrared14)
	(have_image Phenomenon32 infrared3)
	(have_image Phenomenon32 spectrograph5)
	(have_image Planet33 infrared3)
	(have_image Planet33 spectrograph0)
	(have_image Planet34 thermograph13)
	(have_image Planet34 spectrograph5)
	(have_image Planet34 spectrograph8)
	(have_image Planet34 infrared2)
	(have_image Phenomenon35 image9)
	(have_image Phenomenon35 thermograph7)
	(have_image Planet36 thermograph10)
	(have_image Planet36 spectrograph0)
	(have_image Planet37 infrared2)
	(have_image Planet37 spectrograph8)
	(have_image Planet37 thermograph13)
	(have_image Planet37 infrared3)
	(have_image Star38 spectrograph5)
	(have_image Star38 infrared12)
	(have_image Star38 infrared14)
	(have_image Star38 image9)
	(have_image Star38 thermograph13)
	(have_image Planet39 infrared14)
	(have_image Planet39 thermograph13)
	(have_image Planet40 image9)
	(have_image Planet40 thermograph10)
	(have_image Star41 image9)
	(have_image Star41 infrared3)
	(have_image Star41 infrared14)
	(have_image Star42 infrared14)
	(have_image Star42 thermograph13)
	(have_image Star42 infrared12)
	(have_image Star43 thermograph10)
	(have_image Star43 spectrograph8)
	(have_image Star43 infrared6)
	(have_image Phenomenon44 infrared3)
	(have_image Phenomenon44 infrared12)
	(have_image Phenomenon44 spectrograph0)
	(have_image Phenomenon44 thermograph7)
	(have_image Phenomenon45 infrared14)
	(have_image Phenomenon45 spectrograph0)
	(have_image Planet46 infrared12)
	(have_image Planet46 infrared6)
	(have_image Planet46 thermograph7)
	(have_image Star47 infrared3)
	(have_image Star47 infrared6)
	(have_image Star48 image9)
	(have_image Star48 thermograph10)
	(have_image Phenomenon49 image1)
	(have_image Phenomenon50 thermograph7)
	(have_image Phenomenon50 spectrograph8)
	(have_image Phenomenon50 spectrograph0)
	(have_image Star51 infrared2)
	(have_image Star51 spectrograph5)
	(have_image Star51 infrared12)
	(have_image Star51 infrared3)
	(have_image Star51 spectrograph0)
	(have_image Planet53 infrared6)
	(have_image Planet53 infrared14)
	(have_image Planet53 thermograph13)
	(have_image Planet53 spectrograph8)
	(have_image Star54 infrared12)
	(have_image Star54 infrared3)
	(have_image Star54 infrared6)
	(have_image Planet55 infrared12)
	(have_image Planet55 infrared2)
	(have_image Planet55 thermograph13)
	(have_image Planet55 infrared6)
	(have_image Planet57 image1)
	(have_image Planet57 infrared2)
	(have_image Phenomenon59 spectrograph5)
	(have_image Phenomenon59 thermograph10)
	(have_image Phenomenon60 infrared2)
	(have_image Phenomenon60 infrared12)
	(have_image Planet62 spectrograph0)
	(have_image Planet62 thermograph7)
	(have_image Planet62 infrared3)
	(have_image Phenomenon64 thermograph10)
	(have_image Phenomenon64 thermograph7)
	(have_image Phenomenon64 infrared12)
	(have_image Phenomenon64 infrared3)
	(have_image Phenomenon64 spectrograph0)
	(have_image Star65 spectrograph8)
	(have_image Star65 infrared6)
	(have_image Star65 thermograph7)
	(have_image Phenomenon67 thermograph10)
	(have_image Phenomenon67 spectrograph5)
	(have_image Phenomenon67 thermograph13)
	(have_image Star68 thermograph10)
	(have_image Star68 thermograph7)
	(have_image Star68 spectrograph8)
	(have_image Star68 infrared12)
	(have_image Phenomenon69 infrared12)
	(have_image Phenomenon69 image1)
	(have_image Planet70 infrared12)
	(have_image Planet70 image9)
	(have_image Planet71 image9)
	(have_image Planet71 spectrograph8)
	(have_image Planet71 infrared14)
	(have_image Phenomenon72 spectrograph5)
	(have_image Phenomenon72 infrared6)
	(have_image Phenomenon72 infrared14)
	(have_image Phenomenon72 spectrograph8)
	(have_image Phenomenon73 infrared12)
	(have_image Phenomenon73 infrared2)
	(have_image Phenomenon73 thermograph13)
	(have_image Phenomenon74 thermograph10)
	(have_image Phenomenon74 infrared14)
	(have_image Phenomenon74 image9)
	(have_image Star75 infrared14)
	(have_image Star75 infrared3)
	(have_image Star76 spectrograph8)
	(have_image Star76 spectrograph0)
	(have_image Star76 infrared12)
	(have_image Star76 infrared6)
	(have_image Star77 image9)
	(have_image Star77 thermograph13)
	(have_image Star77 image1)
	(have_image Star77 thermograph10)
	(have_image Star77 infrared2)
	(have_image Phenomenon78 infrared2)
	(have_image Planet79 infrared3)
	(have_image Planet79 infrared2)
	(have_image Planet79 infrared14)
	(have_image Planet80 image9)
	(have_image Planet80 image1)
	(have_image Planet80 infrared14)
	(have_image Planet81 image1)
	(have_image Planet81 image9)
	(have_image Planet81 infrared6)
	(have_image Phenomenon82 infrared12)
	(have_image Phenomenon82 infrared2)
	(have_image Phenomenon82 thermograph7)
	(have_image Planet84 infrared3)
	(have_image Planet84 spectrograph8)
	(have_image Planet84 thermograph13)
	(have_image Planet84 thermograph7)
	(have_image Phenomenon85 spectrograph0)
	(have_image Phenomenon85 infrared6)
	(have_image Phenomenon85 infrared3)
	(have_image Planet86 infrared6)
	(have_image Planet86 infrared3)
	(have_image Planet86 image9)
	(have_image Planet86 spectrograph0)
	(have_image Planet86 infrared2)
	(have_image Planet87 thermograph13)
	(have_image Planet87 image1)
	(have_image Phenomenon88 thermograph13)
	(have_image Phenomenon88 image9)
	(have_image Phenomenon88 infrared2)
	(have_image Planet89 infrared3)
	(have_image Phenomenon90 thermograph10)
	(have_image Phenomenon90 infrared3)
	(have_image Planet91 infrared6)
	(have_image Planet91 spectrograph5)
	(have_image Planet91 image9)
	(have_image Star92 image9)
	(have_image Star92 spectrograph0)
	(have_image Star94 infrared2)
	(have_image Star94 image1)
	(have_image Star94 thermograph7)
	(have_image Star95 image1)
	(have_image Star95 spectrograph0)
	(have_image Phenomenon96 thermograph10)
	(have_image Planet97 thermograph13)
	(have_image Planet97 spectrograph8)
	(have_image Planet97 image1)
	(have_image Planet97 spectrograph0)
	(have_image Star98 thermograph13)
	(have_image Star98 spectrograph0)
	(have_image Planet99 infrared14)
	(have_image Star100 thermograph10)
	(have_image Star100 thermograph13)
	(have_image Star100 thermograph7)
	(have_image Star100 infrared12)
	(have_image Star100 spectrograph0)
	(have_image Planet101 infrared2)
	(have_image Planet101 thermograph10)
	(have_image Planet101 infrared12)
	(have_image Phenomenon102 infrared12)
	(have_image Phenomenon102 thermograph10)
	(have_image Phenomenon102 spectrograph5)
	(have_image Phenomenon103 infrared2)
	(have_image Phenomenon103 infrared6)
	(have_image Star104 image9)
	(have_image Star104 spectrograph5)
	(have_image Star105 image9)
	(have_image Star105 infrared3)
	(have_image Star105 spectrograph8)
	(have_image Star105 thermograph13)
	(have_image Phenomenon106 spectrograph0)
	(have_image Phenomenon106 spectrograph8)
	(have_image Phenomenon106 infrared14)
	(have_image Phenomenon106 thermograph7)
	(have_image Star107 infrared6)
	(have_image Star108 infrared12)
	(have_image Star108 infrared3)
	(have_image Star108 infrared2)
	(have_image Star109 spectrograph0)
	(have_image Star110 infrared6)
	(have_image Star110 spectrograph8)
	(have_image Phenomenon111 thermograph10)
	(have_image Phenomenon112 infrared6)
	(have_image Phenomenon112 spectrograph8)
	(have_image Phenomenon112 thermograph13)
	(have_image Phenomenon112 spectrograph5)
	(have_image Phenomenon113 thermograph10)
	(have_image Phenomenon113 infrared6)
	(have_image Phenomenon113 infrared12)
	(have_image Phenomenon113 infrared3)
	(have_image Star114 infrared6)
	(have_image Star114 infrared14)
	(have_image Star114 thermograph7)
	(have_image Planet115 image1)
	(have_image Planet115 infrared2)
	(have_image Phenomenon116 spectrograph0)
	(have_image Phenomenon116 image9)
	(have_image Phenomenon116 thermograph13)
	(have_image Phenomenon116 infrared14)
	(have_image Phenomenon117 image9)
	(have_image Phenomenon118 infrared6)
	(have_image Phenomenon118 image1)
	(have_image Phenomenon118 spectrograph0)
	(have_image Phenomenon118 spectrograph8)
	(have_image Planet119 image9)
	(have_image Phenomenon120 thermograph10)
	(have_image Star121 infrared6)
	(have_image Star121 infrared14)
	(have_image Star122 thermograph7)
	(have_image Star122 image9)
	(have_image Star122 infrared14)
	(have_image Planet123 infrared12)
	(have_image Planet123 spectrograph8)
	(have_image Planet123 infrared2)
	(have_image Planet123 thermograph10)
	(have_image Star124 infrared12)
	(have_image Star124 image9)
	(have_image Star124 spectrograph8)
	(have_image Star124 thermograph10)
	(have_image Star125 spectrograph0)
	(have_image Phenomenon126 infrared2)
	(have_image Phenomenon126 thermograph10)
	(have_image Star127 spectrograph0)
	(have_image Star127 infrared3)
	(have_image Star127 infrared12)
	(have_image Phenomenon128 thermograph7)
	(have_image Phenomenon128 image9)
	(have_image Star129 thermograph13)
	(have_image Star131 spectrograph5)
	(have_image Star131 thermograph13)
	(have_image Planet132 image9)
	(have_image Phenomenon133 spectrograph0)
	(have_image Phenomenon134 thermograph10)
	(have_image Phenomenon135 infrared12)
	(have_image Phenomenon135 infrared14)
	(have_image Planet136 infrared6)
	(have_image Planet137 infrared14)
	(have_image Planet137 thermograph13)
	(have_image Planet137 thermograph10)
	(have_image Planet137 spectrograph8)
	(have_image Planet138 infrared14)
	(have_image Planet138 thermograph10)
	(have_image Phenomenon139 infrared12)
	(have_image Phenomenon139 image1)
	(have_image Phenomenon139 infrared2)
	(have_image Phenomenon139 spectrograph8)
	(have_image Phenomenon140 thermograph13)
	(have_image Phenomenon140 spectrograph5)
	(have_image Phenomenon140 image9)
	(have_image Phenomenon141 image1)
	(have_image Phenomenon142 thermograph10)
	(have_image Planet143 spectrograph8)
	(have_image Planet143 image9)
	(have_image Planet143 infrared2)
	(have_image Planet143 image1)
	(have_image Star144 infrared2)
	(have_image Star145 infrared12)
	(have_image Star145 infrared2)
	(have_image Star145 infrared14)
	(have_image Phenomenon146 thermograph13)
	(have_image Star147 infrared2)
	(have_image Star147 spectrograph8)
	(have_image Star147 infrared6)
	(have_image Phenomenon148 thermograph7)
	(have_image Phenomenon148 infrared6)
	(have_image Phenomenon149 thermograph13)
	(have_image Phenomenon149 infrared2)
	(have_image Phenomenon149 image1)
	(have_image Phenomenon150 infrared14)
	(have_image Phenomenon150 infrared2)
	(have_image Phenomenon150 thermograph7)
	(have_image Phenomenon150 infrared3)
	(have_image Star151 thermograph10)
	(have_image Star151 infrared2)
))

)
