(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	satellite2 - satellite
	instrument4 - instrument
	instrument5 - instrument
	satellite3 - satellite
	instrument6 - instrument
	satellite4 - satellite
	instrument7 - instrument
	satellite5 - satellite
	instrument8 - instrument
	instrument9 - instrument
	satellite6 - satellite
	instrument10 - instrument
	satellite7 - satellite
	instrument11 - instrument
	instrument12 - instrument
	satellite8 - satellite
	instrument13 - instrument
	satellite9 - satellite
	instrument14 - instrument
	instrument15 - instrument
	satellite10 - satellite
	instrument16 - instrument
	satellite11 - satellite
	instrument17 - instrument
	spectrograph4 - mode
	spectrograph19 - mode
	thermograph13 - mode
	infrared11 - mode
	infrared3 - mode
	thermograph7 - mode
	spectrograph14 - mode
	infrared12 - mode
	infrared10 - mode
	image0 - mode
	spectrograph6 - mode
	image9 - mode
	infrared2 - mode
	infrared18 - mode
	spectrograph16 - mode
	spectrograph1 - mode
	infrared5 - mode
	infrared8 - mode
	infrared17 - mode
	infrared15 - mode
	GroundStation1 - direction
	GroundStation0 - direction
	Planet2 - direction
	Planet3 - direction
	Phenomenon4 - direction
	Phenomenon5 - direction
	Star6 - direction
	Phenomenon7 - direction
	Phenomenon8 - direction
	Planet9 - direction
	Star10 - direction
	Phenomenon11 - direction
	Star12 - direction
	Phenomenon13 - direction
	Planet14 - direction
	Planet15 - direction
	Phenomenon16 - direction
	Phenomenon17 - direction
	Phenomenon18 - direction
	Star19 - direction
	Phenomenon20 - direction
	Star21 - direction
	Phenomenon22 - direction
	Star23 - direction
	Planet24 - direction
	Phenomenon25 - direction
	Phenomenon26 - direction
	Planet27 - direction
	Phenomenon28 - direction
	Star29 - direction
	Planet30 - direction
	Phenomenon31 - direction
	Planet32 - direction
	Phenomenon33 - direction
	Star34 - direction
	Planet35 - direction
	Phenomenon36 - direction
	Phenomenon37 - direction
	Star38 - direction
	Phenomenon39 - direction
	Phenomenon40 - direction
	Star41 - direction
	Phenomenon42 - direction
	Star43 - direction
	Star44 - direction
	Planet45 - direction
	Planet46 - direction
	Phenomenon47 - direction
	Phenomenon48 - direction
	Phenomenon49 - direction
	Phenomenon50 - direction
	Phenomenon51 - direction
	Star52 - direction
	Star53 - direction
	Star54 - direction
	Phenomenon55 - direction
	Planet56 - direction
	Phenomenon57 - direction
	Phenomenon58 - direction
	Phenomenon59 - direction
	Planet60 - direction
	Star61 - direction
	Star62 - direction
	Planet63 - direction
	Phenomenon64 - direction
	Star65 - direction
	Planet66 - direction
	Phenomenon67 - direction
	Phenomenon68 - direction
	Planet69 - direction
	Planet70 - direction
	Star71 - direction
	Phenomenon72 - direction
	Star73 - direction
	Star74 - direction
	Phenomenon75 - direction
	Star76 - direction
	Planet77 - direction
	Planet78 - direction
	Phenomenon79 - direction
	Phenomenon80 - direction
	Star81 - direction
	Planet82 - direction
	Phenomenon83 - direction
	Phenomenon84 - direction
	Planet85 - direction
	Star86 - direction
	Phenomenon87 - direction
	Phenomenon88 - direction
	Star89 - direction
	Planet90 - direction
	Phenomenon91 - direction
	Phenomenon92 - direction
	Planet93 - direction
	Phenomenon94 - direction
	Star95 - direction
	Star96 - direction
	Phenomenon97 - direction
	Planet98 - direction
	Star99 - direction
	Star100 - direction
	Planet101 - direction
	Phenomenon102 - direction
	Planet103 - direction
	Phenomenon104 - direction
	Planet105 - direction
	Planet106 - direction
	Star107 - direction
	Planet108 - direction
	Star109 - direction
	Phenomenon110 - direction
	Star111 - direction
	Star112 - direction
	Star113 - direction
	Star114 - direction
	Star115 - direction
	Phenomenon116 - direction
	Star117 - direction
	Phenomenon118 - direction
	Star119 - direction
	Phenomenon120 - direction
	Phenomenon121 - direction
	Star122 - direction
	Star123 - direction
	Star124 - direction
	Planet125 - direction
	Star126 - direction
	Star127 - direction
	Phenomenon128 - direction
	Star129 - direction
	Planet130 - direction
	Phenomenon131 - direction
	Phenomenon132 - direction
	Planet133 - direction
	Star134 - direction
	Planet135 - direction
	Star136 - direction
	Planet137 - direction
	Star138 - direction
	Planet139 - direction
	Star140 - direction
	Phenomenon141 - direction
	Planet142 - direction
	Star143 - direction
	Star144 - direction
	Phenomenon145 - direction
	Planet146 - direction
	Star147 - direction
	Phenomenon148 - direction
	Phenomenon149 - direction
	Phenomenon150 - direction
	Phenomenon151 - direction
	Planet152 - direction
	Phenomenon153 - direction
	Phenomenon154 - direction
	Phenomenon155 - direction
	Star156 - direction
	Star157 - direction
	Planet158 - direction
	Phenomenon159 - direction
	Star160 - direction
	Planet161 - direction
	Planet162 - direction
	Planet163 - direction
	Star164 - direction
	Phenomenon165 - direction
	Planet166 - direction
	Phenomenon167 - direction
	Phenomenon168 - direction
	Star169 - direction
	Star170 - direction
	Planet171 - direction
	Star172 - direction
	Star173 - direction
	Phenomenon174 - direction
	Phenomenon175 - direction
	Star176 - direction
	Planet177 - direction
	Phenomenon178 - direction
	Planet179 - direction
	Planet180 - direction
	Planet181 - direction
)
(:init
	(supports instrument0 spectrograph16)
	(supports instrument0 spectrograph14)
	(calibration_target instrument0 GroundStation0)
	(supports instrument1 infrared12)
	(supports instrument1 image0)
	(supports instrument1 thermograph7)
	(calibration_target instrument1 GroundStation0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon49)
	(supports instrument2 infrared3)
	(supports instrument2 spectrograph6)
	(calibration_target instrument2 GroundStation0)
	(supports instrument3 infrared8)
	(calibration_target instrument3 GroundStation1)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star74)
	(supports instrument4 spectrograph16)
	(supports instrument4 infrared15)
	(calibration_target instrument4 GroundStation0)
	(supports instrument5 thermograph7)
	(calibration_target instrument5 GroundStation1)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Planet60)
	(supports instrument6 infrared12)
	(supports instrument6 spectrograph14)
	(calibration_target instrument6 GroundStation0)
	(on_board instrument6 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet60)
	(supports instrument7 infrared8)
	(supports instrument7 infrared17)
	(calibration_target instrument7 GroundStation0)
	(on_board instrument7 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet78)
	(supports instrument8 infrared10)
	(calibration_target instrument8 GroundStation0)
	(supports instrument9 image0)
	(calibration_target instrument9 GroundStation0)
	(on_board instrument8 satellite5)
	(on_board instrument9 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star111)
	(supports instrument10 infrared2)
	(calibration_target instrument10 GroundStation1)
	(on_board instrument10 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star173)
	(supports instrument11 spectrograph1)
	(calibration_target instrument11 GroundStation0)
	(supports instrument12 spectrograph1)
	(supports instrument12 spectrograph6)
	(supports instrument12 infrared5)
	(calibration_target instrument12 GroundStation1)
	(on_board instrument11 satellite7)
	(on_board instrument12 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star53)
	(supports instrument13 infrared2)
	(supports instrument13 image9)
	(calibration_target instrument13 GroundStation0)
	(on_board instrument13 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Phenomenon40)
	(supports instrument14 spectrograph1)
	(supports instrument14 spectrograph16)
	(supports instrument14 infrared18)
	(calibration_target instrument14 GroundStation1)
	(supports instrument15 infrared8)
	(supports instrument15 infrared5)
	(supports instrument15 infrared17)
	(calibration_target instrument15 GroundStation1)
	(on_board instrument14 satellite9)
	(on_board instrument15 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star12)
	(supports instrument16 infrared17)
	(calibration_target instrument16 GroundStation1)
	(on_board instrument16 satellite10)
	(power_avail satellite10)
	(pointing satellite10 Planet27)
	(supports instrument17 infrared15)
	(calibration_target instrument17 GroundStation0)
	(on_board instrument17 satellite11)
	(power_avail satellite11)
	(pointing satellite11 Planet137)
)
(:goal (and
	(pointing satellite0 Phenomenon102)
	(pointing satellite1 Planet56)
	(pointing satellite5 Star117)
	(pointing satellite6 Planet2)
	(pointing satellite7 Planet77)
	(pointing satellite8 Phenomenon26)
	(have_image Planet2 image0)
	(have_image Planet3 spectrograph16)
	(have_image Planet3 spectrograph14)
	(have_image Planet3 infrared10)
	(have_image Planet3 image0)
	(have_image Planet3 infrared5)
	(have_image Phenomenon4 infrared15)
	(have_image Phenomenon4 infrared10)
	(have_image Phenomenon5 spectrograph16)
	(have_image Phenomenon5 infrared3)
	(have_image Star6 infrared8)
	(have_image Star6 thermograph7)
	(have_image Star6 infrared10)
	(have_image Star6 infrared17)
	(have_image Star6 infrared12)
	(have_image Phenomenon7 infrared17)
	(have_image Phenomenon7 spectrograph16)
	(have_image Phenomenon7 infrared3)
	(have_image Phenomenon7 image0)
	(have_image Phenomenon7 thermograph7)
	(have_image Phenomenon7 spectrograph6)
	(have_image Planet9 spectrograph6)
	(have_image Planet9 infrared10)
	(have_image Star10 spectrograph1)
	(have_image Star10 infrared5)
	(have_image Phenomenon11 spectrograph14)
	(have_image Phenomenon11 infrared18)
	(have_image Phenomenon11 infrared17)
	(have_image Phenomenon11 spectrograph16)
	(have_image Phenomenon11 spectrograph1)
	(have_image Phenomenon11 infrared8)
	(have_image Star12 infrared3)
	(have_image Star12 infrared8)
	(have_image Star12 infrared5)
	(have_image Planet14 infrared12)
	(have_image Planet14 image0)
	(have_image Planet14 infrared5)
	(have_image Planet14 infrared17)
	(have_image Planet15 infrared10)
	(have_image Planet15 spectrograph1)
	(have_image Planet15 infrared3)
	(have_image Phenomenon17 spectrograph1)
	(have_image Phenomenon17 image0)
	(have_image Phenomenon17 infrared2)
	(have_image Phenomenon18 infrared10)
	(have_image Phenomenon18 thermograph7)
	(have_image Phenomenon18 spectrograph6)
	(have_image Phenomenon18 infrared18)
	(have_image Phenomenon18 spectrograph14)
	(have_image Phenomenon18 image0)
	(have_image Star19 infrared3)
	(have_image Star19 spectrograph16)
	(have_image Star19 spectrograph6)
	(have_image Star19 infrared15)
	(have_image Phenomenon20 infrared17)
	(have_image Star21 infrared12)
	(have_image Star21 infrared18)
	(have_image Star21 infrared3)
	(have_image Star23 infrared10)
	(have_image Planet24 spectrograph16)
	(have_image Phenomenon26 thermograph7)
	(have_image Phenomenon26 spectrograph14)
	(have_image Phenomenon26 infrared17)
	(have_image Phenomenon28 infrared8)
	(have_image Phenomenon28 thermograph7)
	(have_image Phenomenon28 image0)
	(have_image Planet30 infrared15)
	(have_image Planet30 thermograph7)
	(have_image Planet30 infrared12)
	(have_image Planet30 infrared3)
	(have_image Planet30 image9)
	(have_image Planet32 infrared17)
	(have_image Phenomenon33 infrared2)
	(have_image Phenomenon33 spectrograph14)
	(have_image Star34 spectrograph1)
	(have_image Star34 infrared15)
	(have_image Star34 infrared17)
	(have_image Phenomenon36 infrared3)
	(have_image Phenomenon36 infrared15)
	(have_image Phenomenon36 spectrograph14)
	(have_image Phenomenon36 spectrograph1)
	(have_image Phenomenon37 infrared2)
	(have_image Phenomenon37 infrared18)
	(have_image Phenomenon37 infrared3)
	(have_image Phenomenon37 infrared12)
	(have_image Star38 image0)
	(have_image Star38 thermograph7)
	(have_image Star38 spectrograph1)
	(have_image Star38 infrared17)
	(have_image Star38 infrared3)
	(have_image Phenomenon39 infrared12)
	(have_image Phenomenon40 spectrograph6)
	(have_image Phenomenon40 infrared15)
	(have_image Phenomenon40 image9)
	(have_image Phenomenon40 infrared3)
	(have_image Phenomenon40 infrared8)
	(have_image Phenomenon40 spectrograph16)
	(have_image Star41 infrared10)
	(have_image Star41 image0)
	(have_image Star41 infrared12)
	(have_image Star41 infrared2)
	(have_image Star41 thermograph7)
	(have_image Phenomenon42 infrared12)
	(have_image Phenomenon42 infrared18)
	(have_image Phenomenon42 image9)
	(have_image Phenomenon42 infrared15)
	(have_image Star44 infrared17)
	(have_image Planet45 infrared17)
	(have_image Planet45 infrared15)
	(have_image Planet46 image9)
	(have_image Planet46 infrared5)
	(have_image Planet46 spectrograph6)
	(have_image Phenomenon47 spectrograph16)
	(have_image Phenomenon47 spectrograph6)
	(have_image Phenomenon47 infrared2)
	(have_image Phenomenon47 infrared5)
	(have_image Phenomenon47 infrared10)
	(have_image Phenomenon48 infrared5)
	(have_image Phenomenon48 infrared12)
	(have_image Phenomenon49 image9)
	(have_image Phenomenon50 infrared12)
	(have_image Phenomenon50 image0)
	(have_image Phenomenon50 thermograph7)
	(have_image Phenomenon50 image9)
	(have_image Phenomenon51 spectrograph1)
	(have_image Star53 image0)
	(have_image Star53 infrared10)
	(have_image Star54 infrared8)
	(have_image Star54 infrared17)
	(have_image Star54 infrared2)
	(have_image Star54 spectrograph16)
	(have_image Star54 infrared12)
	(have_image Phenomenon55 infrared15)
	(have_image Phenomenon55 thermograph7)
	(have_image Phenomenon55 spectrograph14)
	(have_image Phenomenon57 infrared3)
	(have_image Phenomenon57 thermograph7)
	(have_image Phenomenon57 spectrograph1)
	(have_image Phenomenon57 spectrograph14)
	(have_image Phenomenon58 spectrograph6)
	(have_image Phenomenon58 infrared8)
	(have_image Phenomenon58 spectrograph16)
	(have_image Phenomenon58 thermograph7)
	(have_image Phenomenon58 infrared5)
	(have_image Phenomenon58 image9)
	(have_image Phenomenon59 image0)
	(have_image Phenomenon59 infrared2)
	(have_image Phenomenon59 infrared12)
	(have_image Phenomenon59 infrared3)
	(have_image Planet60 spectrograph6)
	(have_image Planet60 spectrograph1)
	(have_image Planet60 infrared5)
	(have_image Planet60 image9)
	(have_image Star61 image9)
	(have_image Star61 infrared3)
	(have_image Planet63 spectrograph1)
	(have_image Planet63 spectrograph14)
	(have_image Planet63 thermograph7)
	(have_image Phenomenon64 image0)
	(have_image Phenomenon64 infrared10)
	(have_image Phenomenon64 infrared8)
	(have_image Star65 spectrograph16)
	(have_image Star65 spectrograph1)
	(have_image Star65 infrared12)
	(have_image Star65 infrared8)
	(have_image Star65 image0)
	(have_image Planet66 infrared8)
	(have_image Planet66 thermograph7)
	(have_image Phenomenon67 spectrograph1)
	(have_image Phenomenon67 infrared10)
	(have_image Phenomenon68 infrared10)
	(have_image Phenomenon68 spectrograph6)
	(have_image Phenomenon68 infrared18)
	(have_image Phenomenon68 infrared15)
	(have_image Phenomenon68 thermograph7)
	(have_image Planet69 image9)
	(have_image Planet69 thermograph7)
	(have_image Planet69 infrared5)
	(have_image Planet70 infrared5)
	(have_image Planet70 image0)
	(have_image Planet70 infrared12)
	(have_image Planet70 infrared8)
	(have_image Star71 infrared12)
	(have_image Star71 infrared3)
	(have_image Star71 infrared5)
	(have_image Phenomenon72 infrared10)
	(have_image Phenomenon72 spectrograph16)
	(have_image Phenomenon72 spectrograph6)
	(have_image Phenomenon72 spectrograph14)
	(have_image Phenomenon72 infrared18)
	(have_image Star73 image0)
	(have_image Star73 spectrograph14)
	(have_image Star74 spectrograph16)
	(have_image Phenomenon75 infrared18)
	(have_image Star76 infrared15)
	(have_image Star76 image0)
	(have_image Planet78 spectrograph16)
	(have_image Planet78 infrared10)
	(have_image Planet78 image0)
	(have_image Phenomenon79 infrared8)
	(have_image Phenomenon79 infrared12)
	(have_image Phenomenon79 infrared17)
	(have_image Phenomenon80 spectrograph6)
	(have_image Phenomenon80 infrared17)
	(have_image Phenomenon80 image9)
	(have_image Phenomenon80 infrared12)
	(have_image Phenomenon80 spectrograph16)
	(have_image Planet82 infrared12)
	(have_image Planet82 infrared10)
	(have_image Planet82 infrared2)
	(have_image Planet82 image9)
	(have_image Phenomenon83 infrared5)
	(have_image Phenomenon83 infrared2)
	(have_image Phenomenon83 image9)
	(have_image Phenomenon84 infrared12)
	(have_image Phenomenon84 image0)
	(have_image Phenomenon84 infrared2)
	(have_image Phenomenon84 image9)
	(have_image Phenomenon84 infrared5)
	(have_image Planet85 infrared12)
	(have_image Planet85 infrared8)
	(have_image Planet85 infrared15)
	(have_image Planet85 image9)
	(have_image Planet85 spectrograph1)
	(have_image Star86 infrared10)
	(have_image Phenomenon88 infrared18)
	(have_image Phenomenon88 infrared5)
	(have_image Phenomenon88 infrared10)
	(have_image Star89 image9)
	(have_image Star89 infrared18)
	(have_image Star89 spectrograph14)
	(have_image Planet90 infrared18)
	(have_image Planet90 infrared12)
	(have_image Planet90 spectrograph14)
	(have_image Planet90 spectrograph6)
	(have_image Planet90 infrared3)
	(have_image Planet90 thermograph7)
	(have_image Phenomenon91 infrared18)
	(have_image Phenomenon92 infrared5)
	(have_image Phenomenon92 spectrograph14)
	(have_image Planet93 infrared5)
	(have_image Planet93 spectrograph6)
	(have_image Planet93 infrared17)
	(have_image Planet93 infrared8)
	(have_image Phenomenon94 infrared3)
	(have_image Phenomenon94 spectrograph6)
	(have_image Star95 image9)
	(have_image Star95 infrared8)
	(have_image Star95 spectrograph6)
	(have_image Star96 infrared17)
	(have_image Star96 infrared2)
	(have_image Star96 infrared10)
	(have_image Phenomenon97 infrared3)
	(have_image Phenomenon97 infrared2)
	(have_image Planet98 infrared10)
	(have_image Star100 spectrograph16)
	(have_image Star100 infrared10)
	(have_image Star100 spectrograph14)
	(have_image Planet101 image9)
	(have_image Planet101 infrared18)
	(have_image Planet101 infrared12)
	(have_image Planet101 infrared5)
	(have_image Planet101 infrared8)
	(have_image Phenomenon102 spectrograph6)
	(have_image Phenomenon104 infrared17)
	(have_image Planet105 infrared3)
	(have_image Planet105 spectrograph16)
	(have_image Planet105 spectrograph6)
	(have_image Planet106 infrared12)
	(have_image Planet106 infrared3)
	(have_image Planet106 infrared10)
	(have_image Planet106 spectrograph6)
	(have_image Star107 image9)
	(have_image Star107 infrared15)
	(have_image Star107 infrared12)
	(have_image Star107 infrared3)
	(have_image Planet108 infrared18)
	(have_image Planet108 thermograph7)
	(have_image Star109 image9)
	(have_image Star109 infrared8)
	(have_image Star109 thermograph7)
	(have_image Phenomenon110 spectrograph16)
	(have_image Phenomenon110 infrared5)
	(have_image Star111 image0)
	(have_image Star111 spectrograph6)
	(have_image Star111 infrared17)
	(have_image Star111 spectrograph14)
	(have_image Star111 spectrograph1)
	(have_image Star112 spectrograph6)
	(have_image Star112 thermograph7)
	(have_image Star113 infrared3)
	(have_image Star114 infrared5)
	(have_image Star114 spectrograph6)
	(have_image Star114 infrared18)
	(have_image Star114 thermograph7)
	(have_image Phenomenon116 infrared3)
	(have_image Phenomenon116 spectrograph16)
	(have_image Phenomenon116 spectrograph6)
	(have_image Star117 spectrograph16)
	(have_image Phenomenon118 infrared10)
	(have_image Phenomenon118 image9)
	(have_image Phenomenon118 infrared2)
	(have_image Phenomenon118 infrared17)
	(have_image Phenomenon118 infrared18)
	(have_image Phenomenon118 spectrograph1)
	(have_image Star119 infrared5)
	(have_image Star119 spectrograph14)
	(have_image Star119 thermograph7)
	(have_image Star119 infrared18)
	(have_image Phenomenon120 spectrograph6)
	(have_image Phenomenon121 infrared12)
	(have_image Phenomenon121 infrared8)
	(have_image Phenomenon121 spectrograph16)
	(have_image Star124 image0)
	(have_image Star124 infrared12)
	(have_image Star124 infrared5)
	(have_image Planet125 infrared17)
	(have_image Star126 spectrograph14)
	(have_image Star126 thermograph7)
	(have_image Star126 image9)
	(have_image Star126 infrared18)
	(have_image Star127 infrared18)
	(have_image Star127 spectrograph1)
	(have_image Star127 spectrograph6)
	(have_image Star127 infrared10)
	(have_image Star127 infrared17)
	(have_image Star127 image0)
	(have_image Phenomenon128 infrared10)
	(have_image Star129 infrared17)
	(have_image Planet130 spectrograph1)
	(have_image Planet130 infrared5)
	(have_image Phenomenon131 thermograph7)
	(have_image Phenomenon131 image9)
	(have_image Phenomenon131 infrared15)
	(have_image Phenomenon131 spectrograph14)
	(have_image Phenomenon132 spectrograph14)
	(have_image Phenomenon132 infrared17)
	(have_image Phenomenon132 infrared12)
	(have_image Planet133 spectrograph6)
	(have_image Planet133 spectrograph16)
	(have_image Planet133 image9)
	(have_image Star134 infrared17)
	(have_image Star134 spectrograph16)
	(have_image Planet135 image0)
	(have_image Planet135 spectrograph6)
	(have_image Planet135 spectrograph14)
	(have_image Star136 spectrograph1)
	(have_image Planet137 infrared2)
	(have_image Star138 image9)
	(have_image Planet139 spectrograph6)
	(have_image Planet139 infrared3)
	(have_image Planet139 infrared10)
	(have_image Planet139 spectrograph1)
	(have_image Planet139 infrared8)
	(have_image Star140 infrared18)
	(have_image Star140 thermograph7)
	(have_image Star140 infrared2)
	(have_image Star140 spectrograph1)
	(have_image Phenomenon141 spectrograph1)
	(have_image Phenomenon141 thermograph7)
	(have_image Phenomenon141 infrared17)
	(have_image Planet142 spectrograph6)
	(have_image Star143 infrared17)
	(have_image Star143 infrared8)
	(have_image Star143 infrared5)
	(have_image Star143 spectrograph14)
	(have_image Star143 infrared3)
	(have_image Star143 infrared18)
	(have_image Star144 infrared17)
	(have_image Planet146 spectrograph1)
	(have_image Planet146 image0)
	(have_image Planet146 infrared5)
	(have_image Planet146 infrared2)
	(have_image Star147 spectrograph1)
	(have_image Star147 infrared18)
	(have_image Star147 image9)
	(have_image Phenomenon149 infrared17)
	(have_image Phenomenon149 image0)
	(have_image Phenomenon150 spectrograph14)
	(have_image Phenomenon150 infrared3)
	(have_image Phenomenon151 image0)
	(have_image Planet152 infrared18)
	(have_image Planet152 infrared12)
	(have_image Planet152 spectrograph14)
	(have_image Planet152 image9)
	(have_image Planet152 thermograph7)
	(have_image Phenomenon153 infrared10)
	(have_image Phenomenon153 infrared3)
	(have_image Phenomenon153 image9)
	(have_image Phenomenon154 infrared18)
	(have_image Phenomenon154 spectrograph16)
	(have_image Star156 infrared3)
	(have_image Star156 infrared18)
	(have_image Star157 spectrograph1)
	(have_image Star157 infrared8)
	(have_image Star157 image0)
	(have_image Planet158 spectrograph6)
	(have_image Planet158 spectrograph16)
	(have_image Planet158 image9)
	(have_image Phenomenon159 infrared2)
	(have_image Phenomenon159 thermograph7)
	(have_image Star160 infrared18)
	(have_image Star160 image9)
	(have_image Star160 spectrograph14)
	(have_image Star160 infrared8)
	(have_image Planet161 thermograph7)
	(have_image Planet161 infrared18)
	(have_image Planet161 infrared3)
	(have_image Planet161 spectrograph14)
	(have_image Planet162 infrared8)
	(have_image Planet163 infrared12)
	(have_image Planet163 spectrograph6)
	(have_image Star164 infrared12)
	(have_image Star164 spectrograph6)
	(have_image Star164 infrared3)
	(have_image Star164 infrared17)
	(have_image Phenomenon165 spectrograph6)
	(have_image Planet166 image9)
	(have_image Planet166 infrared3)
	(have_image Phenomenon167 infrared8)
	(have_image Phenomenon167 infrared15)
	(have_image Phenomenon167 infrared3)
	(have_image Phenomenon167 thermograph7)
	(have_image Phenomenon167 infrared18)
	(have_image Phenomenon168 infrared10)
	(have_image Phenomenon168 image0)
	(have_image Phenomenon168 thermograph7)
	(have_image Star169 infrared3)
	(have_image Star169 infrared10)
	(have_image Star169 thermograph7)
	(have_image Star169 infrared5)
	(have_image Star170 spectrograph14)
	(have_image Star170 image9)
	(have_image Star170 infrared10)
	(have_image Star170 infrared8)
	(have_image Planet171 infrared3)
	(have_image Planet171 infrared12)
	(have_image Star172 infrared12)
	(have_image Star172 spectrograph16)
	(have_image Star172 infrared8)
	(have_image Star172 spectrograph1)
	(have_image Star172 infrared2)
	(have_image Star173 image0)
	(have_image Phenomenon174 image0)
	(have_image Phenomenon174 spectrograph16)
	(have_image Phenomenon174 infrared8)
	(have_image Phenomenon174 image9)
	(have_image Phenomenon174 infrared17)
	(have_image Phenomenon174 infrared3)
	(have_image Star176 infrared17)
	(have_image Star176 infrared10)
	(have_image Star176 infrared8)
	(have_image Star176 infrared12)
	(have_image Planet177 infrared3)
	(have_image Planet177 infrared18)
	(have_image Phenomenon178 spectrograph6)
	(have_image Planet179 infrared8)
	(have_image Planet179 infrared2)
	(have_image Planet179 image0)
	(have_image Planet179 infrared5)
	(have_image Planet179 spectrograph16)
	(have_image Planet180 image0)
	(have_image Planet180 spectrograph6)
	(have_image Planet181 spectrograph1)
	(have_image Planet181 spectrograph16)
	(have_image Planet181 infrared10)
))

)
