(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	satellite2 - satellite
	instrument3 - instrument
	satellite3 - satellite
	instrument4 - instrument
	satellite4 - satellite
	instrument5 - instrument
	instrument6 - instrument
	satellite5 - satellite
	instrument7 - instrument
	instrument8 - instrument
	satellite6 - satellite
	instrument9 - instrument
	satellite7 - satellite
	instrument10 - instrument
	satellite8 - satellite
	instrument11 - instrument
	satellite9 - satellite
	instrument12 - instrument
	instrument13 - instrument
	satellite10 - satellite
	instrument14 - instrument
	satellite11 - satellite
	instrument15 - instrument
	instrument16 - instrument
	thermograph3 - mode
	spectrograph16 - mode
	spectrograph11 - mode
	image14 - mode
	spectrograph19 - mode
	image12 - mode
	infrared4 - mode
	thermograph0 - mode
	image1 - mode
	image8 - mode
	image7 - mode
	infrared13 - mode
	thermograph9 - mode
	spectrograph2 - mode
	thermograph5 - mode
	thermograph15 - mode
	spectrograph18 - mode
	spectrograph6 - mode
	thermograph10 - mode
	infrared17 - mode
	Star0 - direction
	Star1 - direction
	Planet2 - direction
	Planet3 - direction
	Star4 - direction
	Planet5 - direction
	Phenomenon6 - direction
	Phenomenon7 - direction
	Phenomenon8 - direction
	Phenomenon9 - direction
	Star10 - direction
	Star11 - direction
	Phenomenon12 - direction
	Phenomenon13 - direction
	Phenomenon14 - direction
	Planet15 - direction
	Planet16 - direction
	Phenomenon17 - direction
	Star18 - direction
	Planet19 - direction
	Star20 - direction
	Star21 - direction
	Star22 - direction
	Planet23 - direction
	Planet24 - direction
	Planet25 - direction
	Phenomenon26 - direction
	Planet27 - direction
	Phenomenon28 - direction
	Phenomenon29 - direction
	Star30 - direction
	Planet31 - direction
	Planet32 - direction
	Star33 - direction
	Star34 - direction
	Planet35 - direction
	Star36 - direction
	Phenomenon37 - direction
	Star38 - direction
	Phenomenon39 - direction
	Star40 - direction
	Star41 - direction
	Star42 - direction
	Planet43 - direction
	Planet44 - direction
	Planet45 - direction
	Phenomenon46 - direction
	Planet47 - direction
	Star48 - direction
	Star49 - direction
	Planet50 - direction
	Phenomenon51 - direction
	Planet52 - direction
	Star53 - direction
	Planet54 - direction
	Planet55 - direction
	Planet56 - direction
	Phenomenon57 - direction
	Star58 - direction
	Phenomenon59 - direction
	Planet60 - direction
	Planet61 - direction
	Star62 - direction
	Phenomenon63 - direction
	Planet64 - direction
	Planet65 - direction
	Phenomenon66 - direction
	Planet67 - direction
	Planet68 - direction
	Star69 - direction
	Planet70 - direction
	Phenomenon71 - direction
	Planet72 - direction
	Phenomenon73 - direction
	Star74 - direction
	Phenomenon75 - direction
	Planet76 - direction
	Star77 - direction
	Star78 - direction
	Planet79 - direction
	Star80 - direction
	Planet81 - direction
	Phenomenon82 - direction
	Phenomenon83 - direction
	Planet84 - direction
	Star85 - direction
	Star86 - direction
	Planet87 - direction
	Phenomenon88 - direction
	Planet89 - direction
	Phenomenon90 - direction
	Phenomenon91 - direction
	Phenomenon92 - direction
	Planet93 - direction
	Phenomenon94 - direction
	Phenomenon95 - direction
	Phenomenon96 - direction
	Phenomenon97 - direction
	Planet98 - direction
	Planet99 - direction
	Planet100 - direction
	Star101 - direction
	Planet102 - direction
	Planet103 - direction
	Star104 - direction
	Planet105 - direction
	Star106 - direction
	Planet107 - direction
	Phenomenon108 - direction
	Phenomenon109 - direction
	Star110 - direction
	Star111 - direction
	Planet112 - direction
	Planet113 - direction
	Star114 - direction
	Phenomenon115 - direction
	Planet116 - direction
	Star117 - direction
	Star118 - direction
	Phenomenon119 - direction
	Star120 - direction
	Phenomenon121 - direction
	Star122 - direction
	Phenomenon123 - direction
	Star124 - direction
	Phenomenon125 - direction
	Planet126 - direction
	Phenomenon127 - direction
	Phenomenon128 - direction
	Phenomenon129 - direction
	Planet130 - direction
	Phenomenon131 - direction
	Star132 - direction
	Star133 - direction
	Phenomenon134 - direction
	Star135 - direction
	Phenomenon136 - direction
	Phenomenon137 - direction
	Planet138 - direction
	Phenomenon139 - direction
	Planet140 - direction
	Star141 - direction
	Planet142 - direction
	Phenomenon143 - direction
	Planet144 - direction
	Planet145 - direction
	Planet146 - direction
	Planet147 - direction
	Phenomenon148 - direction
	Phenomenon149 - direction
	Phenomenon150 - direction
	Star151 - direction
	Phenomenon152 - direction
	Phenomenon153 - direction
	Star154 - direction
	Planet155 - direction
	Star156 - direction
	Planet157 - direction
	Phenomenon158 - direction
	Star159 - direction
	Phenomenon160 - direction
	Planet161 - direction
	Planet162 - direction
	Phenomenon163 - direction
	Phenomenon164 - direction
	Planet165 - direction
	Star166 - direction
	Planet167 - direction
	Phenomenon168 - direction
	Star169 - direction
	Star170 - direction
	Planet171 - direction
	Star172 - direction
	Planet173 - direction
	Phenomenon174 - direction
	Phenomenon175 - direction
	Star176 - direction
	Phenomenon177 - direction
	Star178 - direction
	Phenomenon179 - direction
	Planet180 - direction
	Star181 - direction
)
(:init
	(supports instrument0 image8)
	(supports instrument0 thermograph10)
	(calibration_target instrument0 Star0)
	(supports instrument1 thermograph10)
	(supports instrument1 infrared4)
	(supports instrument1 image12)
	(calibration_target instrument1 Star0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star18)
	(supports instrument2 thermograph9)
	(calibration_target instrument2 Star0)
	(on_board instrument2 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Planet116)
	(supports instrument3 image7)
	(calibration_target instrument3 Star0)
	(on_board instrument3 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star11)
	(supports instrument4 thermograph9)
	(supports instrument4 image1)
	(supports instrument4 thermograph15)
	(calibration_target instrument4 Star0)
	(on_board instrument4 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon95)
	(supports instrument5 image7)
	(calibration_target instrument5 Star1)
	(supports instrument6 spectrograph19)
	(supports instrument6 image1)
	(calibration_target instrument6 Star0)
	(on_board instrument5 satellite4)
	(on_board instrument6 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star38)
	(supports instrument7 image7)
	(supports instrument7 thermograph15)
	(supports instrument7 infrared4)
	(calibration_target instrument7 Star1)
	(supports instrument8 spectrograph2)
	(supports instrument8 image12)
	(supports instrument8 thermograph9)
	(calibration_target instrument8 Star1)
	(on_board instrument7 satellite5)
	(on_board instrument8 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star106)
	(supports instrument9 infrared4)
	(calibration_target instrument9 Star1)
	(on_board instrument9 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star151)
	(supports instrument10 image1)
	(supports instrument10 thermograph5)
	(supports instrument10 thermograph0)
	(calibration_target instrument10 Star1)
	(on_board instrument10 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star101)
	(supports instrument11 infrared13)
	(supports instrument11 image7)
	(supports instrument11 image8)
	(calibration_target instrument11 Star1)
	(on_board instrument11 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Phenomenon115)
	(supports instrument12 thermograph9)
	(calibration_target instrument12 Star0)
	(supports instrument13 spectrograph2)
	(supports instrument13 thermograph15)
	(calibration_target instrument13 Star1)
	(on_board instrument12 satellite9)
	(on_board instrument13 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Phenomenon109)
	(supports instrument14 thermograph15)
	(supports instrument14 thermograph5)
	(calibration_target instrument14 Star1)
	(on_board instrument14 satellite10)
	(power_avail satellite10)
	(pointing satellite10 Phenomenon129)
	(supports instrument15 thermograph10)
	(supports instrument15 spectrograph6)
	(supports instrument15 spectrograph18)
	(calibration_target instrument15 Star1)
	(supports instrument16 infrared17)
	(calibration_target instrument16 Star1)
	(on_board instrument15 satellite11)
	(on_board instrument16 satellite11)
	(power_avail satellite11)
	(pointing satellite11 Star69)
)
(:goal (and
	(pointing satellite1 Star78)
	(pointing satellite2 Planet146)
	(pointing satellite3 Star178)
	(pointing satellite6 Planet99)
	(pointing satellite7 Planet103)
	(pointing satellite9 Planet64)
	(pointing satellite10 Planet98)
	(have_image Planet2 infrared13)
	(have_image Planet2 spectrograph19)
	(have_image Planet3 image12)
	(have_image Planet3 image1)
	(have_image Planet3 thermograph10)
	(have_image Star4 thermograph9)
	(have_image Star4 image1)
	(have_image Star4 thermograph0)
	(have_image Planet5 infrared13)
	(have_image Planet5 infrared4)
	(have_image Planet5 image7)
	(have_image Planet5 thermograph15)
	(have_image Phenomenon6 image8)
	(have_image Phenomenon6 image12)
	(have_image Phenomenon6 infrared4)
	(have_image Phenomenon7 image12)
	(have_image Phenomenon7 infrared17)
	(have_image Phenomenon7 thermograph15)
	(have_image Phenomenon7 infrared13)
	(have_image Phenomenon8 thermograph5)
	(have_image Phenomenon8 infrared13)
	(have_image Phenomenon8 thermograph9)
	(have_image Phenomenon8 infrared17)
	(have_image Phenomenon9 infrared13)
	(have_image Phenomenon9 image12)
	(have_image Star10 spectrograph2)
	(have_image Star11 thermograph15)
	(have_image Star11 thermograph5)
	(have_image Star11 thermograph0)
	(have_image Star11 thermograph9)
	(have_image Phenomenon12 spectrograph18)
	(have_image Phenomenon12 thermograph9)
	(have_image Phenomenon12 spectrograph6)
	(have_image Phenomenon12 thermograph5)
	(have_image Phenomenon13 spectrograph19)
	(have_image Phenomenon13 image1)
	(have_image Phenomenon14 image8)
	(have_image Phenomenon14 thermograph9)
	(have_image Phenomenon14 thermograph10)
	(have_image Phenomenon14 spectrograph2)
	(have_image Planet15 thermograph10)
	(have_image Planet15 thermograph5)
	(have_image Planet16 image8)
	(have_image Planet16 infrared4)
	(have_image Planet16 infrared17)
	(have_image Phenomenon17 infrared17)
	(have_image Star18 spectrograph6)
	(have_image Planet19 infrared17)
	(have_image Planet19 infrared4)
	(have_image Planet19 image7)
	(have_image Planet19 image8)
	(have_image Star20 infrared4)
	(have_image Star20 thermograph5)
	(have_image Star20 thermograph0)
	(have_image Star20 spectrograph19)
	(have_image Star21 spectrograph19)
	(have_image Star21 thermograph9)
	(have_image Star22 image1)
	(have_image Star22 thermograph15)
	(have_image Planet23 image7)
	(have_image Planet23 thermograph5)
	(have_image Planet23 image12)
	(have_image Planet23 image8)
	(have_image Phenomenon26 thermograph0)
	(have_image Phenomenon26 infrared4)
	(have_image Phenomenon26 image12)
	(have_image Planet27 infrared17)
	(have_image Planet27 spectrograph2)
	(have_image Planet27 spectrograph19)
	(have_image Phenomenon28 image7)
	(have_image Phenomenon28 spectrograph6)
	(have_image Phenomenon28 infrared17)
	(have_image Phenomenon28 spectrograph2)
	(have_image Phenomenon28 thermograph15)
	(have_image Phenomenon29 spectrograph2)
	(have_image Phenomenon29 thermograph0)
	(have_image Phenomenon29 image7)
	(have_image Planet31 image8)
	(have_image Planet32 image12)
	(have_image Planet32 spectrograph2)
	(have_image Planet32 thermograph15)
	(have_image Star33 image12)
	(have_image Star33 thermograph9)
	(have_image Star34 spectrograph6)
	(have_image Star34 thermograph0)
	(have_image Planet35 thermograph0)
	(have_image Planet35 spectrograph6)
	(have_image Planet35 thermograph15)
	(have_image Planet35 infrared13)
	(have_image Planet35 image1)
	(have_image Phenomenon37 thermograph15)
	(have_image Phenomenon37 infrared17)
	(have_image Phenomenon37 image7)
	(have_image Star38 thermograph5)
	(have_image Star38 spectrograph18)
	(have_image Star38 image8)
	(have_image Star38 infrared13)
	(have_image Star38 image12)
	(have_image Star38 spectrograph6)
	(have_image Phenomenon39 infrared17)
	(have_image Phenomenon39 spectrograph6)
	(have_image Star40 spectrograph19)
	(have_image Star40 image8)
	(have_image Star40 infrared17)
	(have_image Star40 spectrograph6)
	(have_image Star40 thermograph15)
	(have_image Star41 thermograph10)
	(have_image Star41 infrared13)
	(have_image Star41 thermograph9)
	(have_image Star41 thermograph5)
	(have_image Star42 infrared4)
	(have_image Star42 spectrograph18)
	(have_image Star42 thermograph5)
	(have_image Star42 infrared13)
	(have_image Planet43 thermograph9)
	(have_image Planet43 spectrograph19)
	(have_image Planet43 infrared17)
	(have_image Planet43 image8)
	(have_image Planet44 infrared4)
	(have_image Planet44 spectrograph19)
	(have_image Planet44 image12)
	(have_image Planet44 infrared17)
	(have_image Planet44 image8)
	(have_image Planet44 thermograph0)
	(have_image Planet45 infrared4)
	(have_image Planet45 thermograph10)
	(have_image Planet45 spectrograph6)
	(have_image Planet45 thermograph0)
	(have_image Planet45 thermograph5)
	(have_image Phenomenon46 image12)
	(have_image Phenomenon46 spectrograph6)
	(have_image Phenomenon46 thermograph10)
	(have_image Planet47 thermograph15)
	(have_image Planet47 image8)
	(have_image Star48 image8)
	(have_image Star48 infrared17)
	(have_image Star49 thermograph10)
	(have_image Star49 infrared13)
	(have_image Star49 thermograph0)
	(have_image Star49 image8)
	(have_image Planet50 thermograph15)
	(have_image Planet50 thermograph9)
	(have_image Phenomenon51 thermograph9)
	(have_image Planet52 thermograph5)
	(have_image Planet52 thermograph10)
	(have_image Star53 infrared13)
	(have_image Star53 image1)
	(have_image Star53 thermograph15)
	(have_image Star53 thermograph10)
	(have_image Star53 spectrograph19)
	(have_image Planet54 spectrograph6)
	(have_image Planet54 infrared13)
	(have_image Planet54 spectrograph18)
	(have_image Planet54 image12)
	(have_image Planet56 infrared17)
	(have_image Phenomenon57 image12)
	(have_image Phenomenon57 infrared4)
	(have_image Phenomenon57 image8)
	(have_image Phenomenon57 spectrograph6)
	(have_image Phenomenon57 infrared13)
	(have_image Star58 image7)
	(have_image Star58 thermograph9)
	(have_image Star58 infrared13)
	(have_image Star58 image8)
	(have_image Star58 spectrograph18)
	(have_image Star58 thermograph15)
	(have_image Phenomenon59 thermograph10)
	(have_image Phenomenon59 infrared13)
	(have_image Phenomenon59 spectrograph19)
	(have_image Phenomenon59 spectrograph2)
	(have_image Phenomenon59 spectrograph6)
	(have_image Phenomenon59 thermograph9)
	(have_image Planet60 infrared13)
	(have_image Planet60 thermograph5)
	(have_image Planet60 thermograph10)
	(have_image Planet60 spectrograph2)
	(have_image Planet61 infrared17)
	(have_image Planet61 infrared13)
	(have_image Planet61 spectrograph19)
	(have_image Star62 image8)
	(have_image Star62 spectrograph6)
	(have_image Star62 infrared13)
	(have_image Phenomenon63 image7)
	(have_image Phenomenon63 infrared4)
	(have_image Planet64 infrared13)
	(have_image Planet64 image7)
	(have_image Planet65 image8)
	(have_image Planet65 image7)
	(have_image Planet65 thermograph5)
	(have_image Planet65 spectrograph19)
	(have_image Phenomenon66 spectrograph19)
	(have_image Planet67 image1)
	(have_image Planet67 thermograph15)
	(have_image Planet67 infrared13)
	(have_image Planet67 image12)
	(have_image Planet68 infrared4)
	(have_image Planet68 image8)
	(have_image Star69 thermograph0)
	(have_image Star69 thermograph10)
	(have_image Star69 image8)
	(have_image Star69 image12)
	(have_image Star69 spectrograph2)
	(have_image Planet70 thermograph15)
	(have_image Planet70 infrared4)
	(have_image Planet70 spectrograph2)
	(have_image Planet72 image8)
	(have_image Star74 image8)
	(have_image Phenomenon75 thermograph0)
	(have_image Planet76 thermograph0)
	(have_image Planet76 image1)
	(have_image Planet76 spectrograph19)
	(have_image Planet76 thermograph10)
	(have_image Star77 image8)
	(have_image Star77 image1)
	(have_image Star77 spectrograph18)
	(have_image Star78 spectrograph18)
	(have_image Star78 thermograph5)
	(have_image Star78 thermograph0)
	(have_image Planet79 infrared17)
	(have_image Star80 image7)
	(have_image Star80 image8)
	(have_image Star80 infrared17)
	(have_image Star80 spectrograph19)
	(have_image Planet81 thermograph15)
	(have_image Planet81 infrared4)
	(have_image Planet81 infrared17)
	(have_image Phenomenon82 thermograph9)
	(have_image Phenomenon83 image8)
	(have_image Planet84 infrared4)
	(have_image Planet84 infrared17)
	(have_image Planet84 image7)
	(have_image Planet84 spectrograph6)
	(have_image Star85 infrared4)
	(have_image Star85 spectrograph18)
	(have_image Star85 spectrograph19)
	(have_image Star86 image1)
	(have_image Planet87 image7)
	(have_image Planet87 spectrograph2)
	(have_image Planet87 thermograph15)
	(have_image Phenomenon88 infrared17)
	(have_image Phenomenon88 thermograph9)
	(have_image Planet89 spectrograph19)
	(have_image Planet89 image1)
	(have_image Planet89 infrared4)
	(have_image Planet89 spectrograph2)
	(have_image Planet89 infrared13)
	(have_image Phenomenon90 infrared17)
	(have_image Phenomenon91 spectrograph18)
	(have_image Phenomenon92 spectrograph2)
	(have_image Phenomenon92 spectrograph18)
	(have_image Phenomenon92 spectrograph19)
	(have_image Planet93 thermograph9)
	(have_image Planet93 infrared13)
	(have_image Phenomenon94 infrared13)
	(have_image Phenomenon95 infrared17)
	(have_image Phenomenon95 spectrograph18)
	(have_image Phenomenon95 image1)
	(have_image Phenomenon95 thermograph5)
	(have_image Phenomenon97 infrared13)
	(have_image Phenomenon97 spectrograph19)
	(have_image Phenomenon97 spectrograph6)
	(have_image Phenomenon97 thermograph5)
	(have_image Phenomenon97 spectrograph2)
	(have_image Planet98 infrared4)
	(have_image Planet98 image7)
	(have_image Planet98 thermograph15)
	(have_image Planet99 infrared13)
	(have_image Planet99 infrared4)
	(have_image Planet99 image12)
	(have_image Planet99 spectrograph2)
	(have_image Planet100 thermograph5)
	(have_image Star101 thermograph5)
	(have_image Star101 thermograph9)
	(have_image Star101 spectrograph6)
	(have_image Planet102 spectrograph6)
	(have_image Planet103 spectrograph2)
	(have_image Planet103 thermograph9)
	(have_image Star104 image7)
	(have_image Star104 spectrograph18)
	(have_image Star104 image8)
	(have_image Planet105 spectrograph18)
	(have_image Planet105 thermograph5)
	(have_image Planet105 spectrograph19)
	(have_image Star106 spectrograph18)
	(have_image Star106 image12)
	(have_image Star106 infrared17)
	(have_image Star106 thermograph0)
	(have_image Star106 infrared4)
	(have_image Phenomenon109 spectrograph6)
	(have_image Star110 infrared4)
	(have_image Star110 image12)
	(have_image Star110 spectrograph19)
	(have_image Star110 spectrograph6)
	(have_image Star111 infrared17)
	(have_image Planet112 infrared4)
	(have_image Planet112 spectrograph18)
	(have_image Star114 infrared17)
	(have_image Star114 spectrograph6)
	(have_image Star114 image12)
	(have_image Star114 image1)
	(have_image Star114 thermograph0)
	(have_image Phenomenon115 thermograph9)
	(have_image Phenomenon115 spectrograph19)
	(have_image Planet116 thermograph9)
	(have_image Planet116 infrared13)
	(have_image Star117 image1)
	(have_image Star118 infrared4)
	(have_image Star118 spectrograph6)
	(have_image Star118 image8)
	(have_image Star118 infrared13)
	(have_image Phenomenon119 thermograph0)
	(have_image Star120 thermograph0)
	(have_image Phenomenon121 infrared4)
	(have_image Phenomenon121 thermograph9)
	(have_image Phenomenon121 spectrograph6)
	(have_image Phenomenon123 thermograph15)
	(have_image Phenomenon123 image7)
	(have_image Star124 infrared13)
	(have_image Phenomenon125 infrared4)
	(have_image Planet126 infrared17)
	(have_image Planet126 infrared13)
	(have_image Planet126 image12)
	(have_image Planet126 thermograph0)
	(have_image Phenomenon127 infrared17)
	(have_image Phenomenon127 spectrograph19)
	(have_image Phenomenon128 image12)
	(have_image Phenomenon128 image7)
	(have_image Phenomenon128 thermograph0)
	(have_image Phenomenon128 infrared17)
	(have_image Phenomenon128 spectrograph2)
	(have_image Phenomenon129 infrared13)
	(have_image Phenomenon129 thermograph10)
	(have_image Phenomenon129 spectrograph19)
	(have_image Planet130 thermograph0)
	(have_image Planet130 image1)
	(have_image Phenomenon131 thermograph10)
	(have_image Star132 spectrograph18)
	(have_image Star133 infrared4)
	(have_image Star133 spectrograph18)
	(have_image Phenomenon134 thermograph0)
	(have_image Phenomenon134 spectrograph19)
	(have_image Phenomenon134 image12)
	(have_image Star135 infrared4)
	(have_image Phenomenon136 spectrograph19)
	(have_image Phenomenon136 image8)
	(have_image Phenomenon137 infrared13)
	(have_image Planet138 spectrograph18)
	(have_image Planet138 image12)
	(have_image Planet138 spectrograph19)
	(have_image Phenomenon139 spectrograph19)
	(have_image Phenomenon139 thermograph15)
	(have_image Planet140 image8)
	(have_image Planet140 thermograph10)
	(have_image Planet140 image1)
	(have_image Planet140 infrared4)
	(have_image Planet140 spectrograph19)
	(have_image Star141 thermograph15)
	(have_image Star141 infrared4)
	(have_image Star141 thermograph10)
	(have_image Phenomenon143 image12)
	(have_image Phenomenon143 image8)
	(have_image Phenomenon143 image7)
	(have_image Phenomenon143 spectrograph19)
	(have_image Phenomenon143 spectrograph18)
	(have_image Planet144 thermograph9)
	(have_image Planet144 image7)
	(have_image Planet145 thermograph5)
	(have_image Planet145 spectrograph2)
	(have_image Planet145 thermograph0)
	(have_image Planet146 thermograph15)
	(have_image Planet146 image1)
	(have_image Planet146 image7)
	(have_image Planet147 thermograph5)
	(have_image Planet147 thermograph9)
	(have_image Phenomenon148 spectrograph18)
	(have_image Phenomenon148 thermograph10)
	(have_image Phenomenon148 thermograph9)
	(have_image Phenomenon148 thermograph0)
	(have_image Phenomenon148 thermograph15)
	(have_image Phenomenon148 infrared13)
	(have_image Phenomenon149 infrared17)
	(have_image Phenomenon149 spectrograph18)
	(have_image Phenomenon149 image7)
	(have_image Phenomenon149 infrared4)
	(have_image Phenomenon150 image7)
	(have_image Phenomenon150 image12)
	(have_image Phenomenon150 image8)
	(have_image Phenomenon150 spectrograph6)
	(have_image Phenomenon150 thermograph0)
	(have_image Star151 image12)
	(have_image Phenomenon152 image7)
	(have_image Phenomenon152 thermograph9)
	(have_image Phenomenon152 spectrograph2)
	(have_image Phenomenon152 infrared13)
	(have_image Phenomenon152 thermograph5)
	(have_image Phenomenon152 image12)
	(have_image Phenomenon153 infrared17)
	(have_image Star154 infrared17)
	(have_image Star154 spectrograph2)
	(have_image Star154 spectrograph18)
	(have_image Star154 spectrograph19)
	(have_image Star154 spectrograph6)
	(have_image Planet155 thermograph5)
	(have_image Star156 spectrograph2)
	(have_image Star156 image7)
	(have_image Planet157 image1)
	(have_image Planet157 thermograph15)
	(have_image Planet157 thermograph9)
	(have_image Planet157 spectrograph19)
	(have_image Planet157 spectrograph6)
	(have_image Planet157 spectrograph2)
	(have_image Star159 spectrograph6)
	(have_image Phenomenon160 thermograph9)
	(have_image Phenomenon160 thermograph10)
	(have_image Phenomenon160 thermograph5)
	(have_image Phenomenon160 spectrograph18)
	(have_image Phenomenon160 image7)
	(have_image Planet162 spectrograph6)
	(have_image Planet162 thermograph10)
	(have_image Phenomenon163 thermograph10)
	(have_image Phenomenon163 infrared13)
	(have_image Phenomenon164 thermograph5)
	(have_image Planet165 thermograph10)
	(have_image Planet165 image7)
	(have_image Planet165 infrared17)
	(have_image Planet165 spectrograph6)
	(have_image Phenomenon168 spectrograph19)
	(have_image Phenomenon168 image7)
	(have_image Phenomenon168 image8)
	(have_image Star169 infrared17)
	(have_image Star169 thermograph9)
	(have_image Star170 image12)
	(have_image Star170 spectrograph18)
	(have_image Star172 thermograph9)
	(have_image Planet173 infrared4)
	(have_image Phenomenon174 infrared4)
	(have_image Phenomenon174 image12)
	(have_image Phenomenon175 image12)
	(have_image Phenomenon175 image8)
	(have_image Phenomenon175 infrared17)
	(have_image Phenomenon175 thermograph5)
	(have_image Phenomenon175 thermograph15)
	(have_image Phenomenon175 infrared4)
	(have_image Star176 thermograph15)
	(have_image Star176 spectrograph6)
	(have_image Star176 spectrograph2)
	(have_image Star176 image8)
	(have_image Star176 spectrograph18)
	(have_image Star176 image7)
	(have_image Phenomenon177 image1)
	(have_image Phenomenon177 thermograph9)
	(have_image Phenomenon177 image12)
	(have_image Phenomenon177 spectrograph6)
	(have_image Phenomenon177 spectrograph2)
	(have_image Star178 infrared13)
	(have_image Phenomenon179 thermograph9)
	(have_image Phenomenon179 image12)
	(have_image Planet180 thermograph0)
	(have_image Planet180 image12)
	(have_image Planet180 thermograph9)
	(have_image Star181 spectrograph19)
	(have_image Star181 spectrograph2)
	(have_image Star181 image8)
))

)
