domains = [
{'description': 'This domain is original from the learning part of IPC2008. The domain involves parking cars on a street with N curb locations, and where cars can be double-parked but not triple-parked. The goal is to find a plan to move from one configuration of parked cars to another configuration, by driving cars from one curb location to another. The problems in the competition contain 2*(N-1) cars, which allows one free curb space and guarantees solvability.',
 'ipc': '2011',
 'name': 'parking',
 'problems': [('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p01.pddl'),
('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p02.pddl'),
('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p03.pddl'),
('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p04.pddl'),
('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p05.pddl'),
('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p06.pddl'),
('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p07.pddl'),
('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p08.pddl'),
('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p09.pddl'),
('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p10.pddl'),
('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p11.pddl'),
('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p12.pddl'),
('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p13.pddl'),
('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p14.pddl'),
('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p15.pddl'),
('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p16.pddl'),
('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p17.pddl'),
('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p18.pddl'),
('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p19.pddl'),
('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p20.pddl'),
('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p21.pddl'),
('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p22.pddl'),
('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p23.pddl'),
('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p24.pddl'),
('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p25.pddl'),
('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p26.pddl'),
('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p27.pddl'),
('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p28.pddl'),
('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p29.pddl'),
('parking-ipc11-learning-test/domain.pddl', 'parking-ipc11-learning-test/p30.pddl')]}
]
