domains = [
{'description': 'This domain models the Sokoban game. (http://en.wikipedia.org/wiki/Sokoban)',
 'ipc': '2011',
 'name': 'sokoban',
 'problems': [('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p01.pddl'),
('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p02.pddl'),
('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p03.pddl'),
('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p04.pddl'),
('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p05.pddl'),
('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p06.pddl'),
('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p07.pddl'),
('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p08.pddl'),
('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p09.pddl'),
('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p10.pddl'),
('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p11.pddl'),
('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p12.pddl'),
('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p13.pddl'),
('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p14.pddl'),
('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p15.pddl'),
('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p16.pddl'),
('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p17.pddl'),
('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p18.pddl'),
('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p19.pddl'),
('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p20.pddl'),
('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p21.pddl'),
('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p22.pddl'),
('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p23.pddl'),
('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p24.pddl'),
('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p25.pddl'),
('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p26.pddl'),
('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p27.pddl'),
('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p28.pddl'),
('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p29.pddl'),
('sokoban-ipc11-learning-target/domain.pddl', 'sokoban-ipc11-learning-target/p30.pddl')]}
]
