domains = [
{'description': 'The first of the domains inspired by space-applications is a first step towards the "Ambitious Spacecraft" described by David Smith at AIPS-2000. It involves planning and scheduling a collection of observation tasks between multiple satellites, each equipped in slightly different ways.',
 'ipc': '2004',
 'name': 'satellite',
 'problems': [('satellite/domain.pddl', 'satellite/p01-pfile1.pddl'),
              ('satellite/domain.pddl', 'satellite/p02-pfile2.pddl'),
              ('satellite/domain.pddl', 'satellite/p03-pfile3.pddl'),
              ('satellite/domain.pddl', 'satellite/p04-pfile4.pddl'),
              ('satellite/domain.pddl', 'satellite/p05-pfile5.pddl'),
              ('satellite/domain.pddl', 'satellite/p06-pfile6.pddl'),
              ('satellite/domain.pddl', 'satellite/p07-pfile7.pddl'),
              ('satellite/domain.pddl', 'satellite/p08-pfile8.pddl'),
              ('satellite/domain.pddl', 'satellite/p09-pfile9.pddl'),
              ('satellite/domain.pddl', 'satellite/p10-pfile10.pddl'),
              ('satellite/domain.pddl', 'satellite/p11-pfile11.pddl'),
              ('satellite/domain.pddl', 'satellite/p12-pfile12.pddl'),
              ('satellite/domain.pddl', 'satellite/p13-pfile13.pddl'),
              ('satellite/domain.pddl', 'satellite/p14-pfile14.pddl'),
              ('satellite/domain.pddl', 'satellite/p15-pfile15.pddl'),
              ('satellite/domain.pddl', 'satellite/p16-pfile16.pddl'),
              ('satellite/domain.pddl', 'satellite/p17-pfile17.pddl'),
              ('satellite/domain.pddl', 'satellite/p18-pfile18.pddl'),
              ('satellite/domain.pddl', 'satellite/p19-pfile19.pddl'),
              ('satellite/domain.pddl', 'satellite/p20-pfile20.pddl'),
              ('satellite/domain.pddl', 'satellite/p21-HC-pfile1.pddl'),
              ('satellite/domain.pddl', 'satellite/p22-HC-pfile2.pddl'),
              ('satellite/domain.pddl', 'satellite/p23-HC-pfile3.pddl'),
              ('satellite/domain.pddl', 'satellite/p24-HC-pfile4.pddl'),
              ('satellite/domain.pddl', 'satellite/p25-HC-pfile5.pddl'),
              ('satellite/domain.pddl', 'satellite/p26-HC-pfile6.pddl'),
              ('satellite/domain.pddl', 'satellite/p27-HC-pfile7.pddl'),
              ('satellite/domain.pddl', 'satellite/p28-HC-pfile8.pddl'),
              ('satellite/domain.pddl', 'satellite/p29-HC-pfile9.pddl'),
              ('satellite/domain.pddl', 'satellite/p30-HC-pfile10.pddl'),
              ('satellite/domain.pddl', 'satellite/p31-HC-pfile11.pddl'),
              ('satellite/domain.pddl', 'satellite/p32-HC-pfile12.pddl'),
              ('satellite/domain.pddl', 'satellite/p33-HC-pfile13.pddl'),
              ('satellite/domain.pddl', 'satellite/p34-HC-pfile14.pddl'),
              ('satellite/domain.pddl', 'satellite/p35-HC-pfile15.pddl'),
              ('satellite/domain.pddl', 'satellite/p36-HC-pfile16.pddl')]},
{'description': 'The first of the domains inspired by space-applications is a first step towards the "Ambitious Spacecraft" described by David Smith at AIPS-2000. It involves planning and scheduling a collection of observation tasks between multiple satellites, each equipped in slightly different ways.',
 'ipc': '2002',
 'name': 'satellite',
 'problems': [('satellite/domain.pddl', 'satellite/p01-pfile1.pddl'),
              ('satellite/domain.pddl', 'satellite/p02-pfile2.pddl'),
              ('satellite/domain.pddl', 'satellite/p03-pfile3.pddl'),
              ('satellite/domain.pddl', 'satellite/p04-pfile4.pddl'),
              ('satellite/domain.pddl', 'satellite/p05-pfile5.pddl'),
              ('satellite/domain.pddl', 'satellite/p06-pfile6.pddl'),
              ('satellite/domain.pddl', 'satellite/p07-pfile7.pddl'),
              ('satellite/domain.pddl', 'satellite/p08-pfile8.pddl'),
              ('satellite/domain.pddl', 'satellite/p09-pfile9.pddl'),
              ('satellite/domain.pddl', 'satellite/p10-pfile10.pddl'),
              ('satellite/domain.pddl', 'satellite/p11-pfile11.pddl'),
              ('satellite/domain.pddl', 'satellite/p12-pfile12.pddl'),
              ('satellite/domain.pddl', 'satellite/p13-pfile13.pddl'),
              ('satellite/domain.pddl', 'satellite/p14-pfile14.pddl'),
              ('satellite/domain.pddl', 'satellite/p15-pfile15.pddl'),
              ('satellite/domain.pddl', 'satellite/p16-pfile16.pddl'),
              ('satellite/domain.pddl', 'satellite/p17-pfile17.pddl'),
              ('satellite/domain.pddl', 'satellite/p18-pfile18.pddl'),
              ('satellite/domain.pddl', 'satellite/p19-pfile19.pddl'),
              ('satellite/domain.pddl', 'satellite/p20-pfile20.pddl')]}
]