domains = [
{'description': 'Finding a sequence of biochemical (pathways) reactions in an organism producing certain substances.',
 'ipc': None,
 'name': 'pathways-noneg',
 'problems': [('pathways-noneg/domain_p01.pddl', 'pathways-noneg/p01.pddl'),
              ('pathways-noneg/domain_p02.pddl', 'pathways-noneg/p02.pddl'),
              ('pathways-noneg/domain_p03.pddl', 'pathways-noneg/p03.pddl'),
              ('pathways-noneg/domain_p04.pddl', 'pathways-noneg/p04.pddl'),
              ('pathways-noneg/domain_p05.pddl', 'pathways-noneg/p05.pddl'),
              ('pathways-noneg/domain_p06.pddl', 'pathways-noneg/p06.pddl'),
              ('pathways-noneg/domain_p07.pddl', 'pathways-noneg/p07.pddl'),
              ('pathways-noneg/domain_p08.pddl', 'pathways-noneg/p08.pddl'),
              ('pathways-noneg/domain_p09.pddl', 'pathways-noneg/p09.pddl'),
              ('pathways-noneg/domain_p10.pddl', 'pathways-noneg/p10.pddl'),
              ('pathways-noneg/domain_p11.pddl', 'pathways-noneg/p11.pddl'),
              ('pathways-noneg/domain_p12.pddl', 'pathways-noneg/p12.pddl'),
              ('pathways-noneg/domain_p13.pddl', 'pathways-noneg/p13.pddl'),
              ('pathways-noneg/domain_p14.pddl', 'pathways-noneg/p14.pddl'),
              ('pathways-noneg/domain_p15.pddl', 'pathways-noneg/p15.pddl'),
              ('pathways-noneg/domain_p16.pddl', 'pathways-noneg/p16.pddl'),
              ('pathways-noneg/domain_p17.pddl', 'pathways-noneg/p17.pddl'),
              ('pathways-noneg/domain_p18.pddl', 'pathways-noneg/p18.pddl'),
              ('pathways-noneg/domain_p19.pddl', 'pathways-noneg/p19.pddl'),
              ('pathways-noneg/domain_p20.pddl', 'pathways-noneg/p20.pddl'),
              ('pathways-noneg/domain_p21.pddl', 'pathways-noneg/p21.pddl'),
              ('pathways-noneg/domain_p22.pddl', 'pathways-noneg/p22.pddl'),
              ('pathways-noneg/domain_p23.pddl', 'pathways-noneg/p23.pddl'),
              ('pathways-noneg/domain_p24.pddl', 'pathways-noneg/p24.pddl'),
              ('pathways-noneg/domain_p25.pddl', 'pathways-noneg/p25.pddl'),
              ('pathways-noneg/domain_p26.pddl', 'pathways-noneg/p26.pddl'),
              ('pathways-noneg/domain_p27.pddl', 'pathways-noneg/p27.pddl'),
              ('pathways-noneg/domain_p28.pddl', 'pathways-noneg/p28.pddl'),
              ('pathways-noneg/domain_p29.pddl', 'pathways-noneg/p29.pddl'),
              ('pathways-noneg/domain_p30.pddl', 'pathways-noneg/p30.pddl')]}
]