domains = [
{'description': 'This domain is to plan how to make and serve sandwiches for a group of children in which some are allergic to gluten. There are two actions for making sandwiches from their ingredients. The first one makes a sandwich and the second one makes a sandwich taking into account that all ingredients are gluten-free. There are also actions to put a sandwich on a tray and to serve sandwiches. Problems in this domain define the ingredients to make sandwiches at the initial state. Goals consist of having all kids served with a sandwich to which they are not allergic.',
 'ipc': '2014',
 'name': 'childsnack',
 'problems': [('childsnack-opt14-strips/domain.pddl',
               'childsnack-opt14-strips/child-snack_pfile01-2.pddl'),
              ('childsnack-opt14-strips/domain.pddl',
               'childsnack-opt14-strips/child-snack_pfile01.pddl'),
              ('childsnack-opt14-strips/domain.pddl',
               'childsnack-opt14-strips/child-snack_pfile02-2.pddl'),
              ('childsnack-opt14-strips/domain.pddl',
               'childsnack-opt14-strips/child-snack_pfile02.pddl'),
              ('childsnack-opt14-strips/domain.pddl',
               'childsnack-opt14-strips/child-snack_pfile03-2.pddl'),
              ('childsnack-opt14-strips/domain.pddl',
               'childsnack-opt14-strips/child-snack_pfile03.pddl'),
              ('childsnack-opt14-strips/domain.pddl',
               'childsnack-opt14-strips/child-snack_pfile04-2.pddl'),
              ('childsnack-opt14-strips/domain.pddl',
               'childsnack-opt14-strips/child-snack_pfile04.pddl'),
              ('childsnack-opt14-strips/domain.pddl',
               'childsnack-opt14-strips/child-snack_pfile05-2.pddl'),
              ('childsnack-opt14-strips/domain.pddl',
               'childsnack-opt14-strips/child-snack_pfile05.pddl'),
              ('childsnack-opt14-strips/domain.pddl',
               'childsnack-opt14-strips/child-snack_pfile06-2.pddl'),
              ('childsnack-opt14-strips/domain.pddl',
               'childsnack-opt14-strips/child-snack_pfile06.pddl'),
              ('childsnack-opt14-strips/domain.pddl',
               'childsnack-opt14-strips/child-snack_pfile07-2.pddl'),
              ('childsnack-opt14-strips/domain.pddl',
               'childsnack-opt14-strips/child-snack_pfile07.pddl'),
              ('childsnack-opt14-strips/domain.pddl',
               'childsnack-opt14-strips/child-snack_pfile08-2.pddl'),
              ('childsnack-opt14-strips/domain.pddl',
               'childsnack-opt14-strips/child-snack_pfile08.pddl'),
              ('childsnack-opt14-strips/domain.pddl',
               'childsnack-opt14-strips/child-snack_pfile09-2.pddl'),
              ('childsnack-opt14-strips/domain.pddl',
               'childsnack-opt14-strips/child-snack_pfile09.pddl'),
              ('childsnack-opt14-strips/domain.pddl',
               'childsnack-opt14-strips/child-snack_pfile10-2.pddl'),
              ('childsnack-opt14-strips/domain.pddl',
               'childsnack-opt14-strips/child-snack_pfile10.pddl')]}
]