domains = [
{'description': 'The Tidybot domain models a household cleaning task, in which one or more robots must pick up a set of objects and put them into goal locations. The world is structured as a 2d grid, divided into navigable locations and surfaces on which objects may lie. Robots have a gripper, which moves relative to the robot, up to some maximum radius. Existing objects block the gripper, so that it may be necessary to move one object out of the way to put another one down. Robots can carry one object at a time in the gripper, but may also make use of a cart, that can hold multiple objects. The instance generator creates worlds that contain rectangular surfaces ("tables"), as well as U-shaped enclosures ("cupboards"), which are the goal locations of objects.',
 'ipc': '2014',
 'name': 'tidybot',
 'problems': [('tidybot-opt14-strips/domain.pddl',
               'tidybot-opt14-strips/p01.pddl'),
              ('tidybot-opt14-strips/domain.pddl',
               'tidybot-opt14-strips/p02.pddl'),
              ('tidybot-opt14-strips/domain.pddl',
               'tidybot-opt14-strips/p03.pddl'),
              ('tidybot-opt14-strips/domain.pddl',
               'tidybot-opt14-strips/p04.pddl'),
              ('tidybot-opt14-strips/domain.pddl',
               'tidybot-opt14-strips/p05.pddl'),
              ('tidybot-opt14-strips/domain.pddl',
               'tidybot-opt14-strips/p06.pddl'),
              ('tidybot-opt14-strips/domain.pddl',
               'tidybot-opt14-strips/p07.pddl'),
              ('tidybot-opt14-strips/domain.pddl',
               'tidybot-opt14-strips/p08.pddl'),
              ('tidybot-opt14-strips/domain.pddl',
               'tidybot-opt14-strips/p09.pddl'),
              ('tidybot-opt14-strips/domain.pddl',
               'tidybot-opt14-strips/p10.pddl'),
              ('tidybot-opt14-strips/domain.pddl',
               'tidybot-opt14-strips/p11.pddl'),
              ('tidybot-opt14-strips/domain.pddl',
               'tidybot-opt14-strips/p12.pddl'),
              ('tidybot-opt14-strips/domain.pddl',
               'tidybot-opt14-strips/p13.pddl'),
              ('tidybot-opt14-strips/domain.pddl',
               'tidybot-opt14-strips/p14.pddl'),
              ('tidybot-opt14-strips/domain.pddl',
               'tidybot-opt14-strips/p15.pddl'),
              ('tidybot-opt14-strips/domain.pddl',
               'tidybot-opt14-strips/p16.pddl'),
              ('tidybot-opt14-strips/domain.pddl',
               'tidybot-opt14-strips/p17.pddl'),
              ('tidybot-opt14-strips/domain.pddl',
               'tidybot-opt14-strips/p18.pddl'),
              ('tidybot-opt14-strips/domain.pddl',
               'tidybot-opt14-strips/p19.pddl'),
              ('tidybot-opt14-strips/domain.pddl',
               'tidybot-opt14-strips/p20.pddl')]}
]