domains = [{'description': '(opt18) Name: Caldera\nSubmitted by: Andy Applebaum, Doug Miller, and Blake Strom from MITRE.\n\nDescription: Cybersecurity domain based on the CALDERA project with certain\nsimplifications like assuming that the network is fully known. Actions are taken from the\nMITRE ATT&CK framework which is a taxonomy of attacker behaviors observed in the real\nworld. The basic paradigm of the included actions is to steal credentials from hosts we\nhave access to and use them to laterally move across the network, which is representative\nof real adversary behavior: many adversaries tend to leverage existing, benign\ncapabilities for malicious ends, which is in contrast with some threat models that assume\nthat attackers are exploiting box-to-box. The instances were generated dynamically based\non a simulator that uses a few parameters to emulate a real network. These parameters\ncontrol the number of hosts, the number of users, the number of domains, and the\nprobability of credential overlap among others.\n\nInteresting properties: quantified conditional effects, hard to ground (some action schemas\nhave 10 parameters or more). To alleviate grounding issues we have two versions of the\ndomain, one that applies action splitting and one that does not.',
 'ipc': '2018',
 'name': 'caldera-split',
 'problems': [('caldera-split-opt18/domain.pddl',
               'caldera-split-opt18/p11.pddl'),
              ('caldera-split-opt18/domain.pddl',
               'caldera-split-opt18/p07.pddl'),
              ('caldera-split-opt18/domain.pddl',
               'caldera-split-opt18/p06.pddl'),
              ('caldera-split-opt18/domain.pddl',
               'caldera-split-opt18/p10.pddl'),
              ('caldera-split-opt18/domain.pddl',
               'caldera-split-opt18/p17.pddl'),
              ('caldera-split-opt18/domain.pddl',
               'caldera-split-opt18/p01.pddl'),
              ('caldera-split-opt18/domain.pddl',
               'caldera-split-opt18/p16.pddl'),
              ('caldera-split-opt18/domain.pddl',
               'caldera-split-opt18/p20.pddl'),
              ('caldera-split-opt18/domain.pddl',
               'caldera-split-opt18/p19.pddl'),
              ('caldera-split-opt18/domain.pddl',
               'caldera-split-opt18/p03.pddl'),
              ('caldera-split-opt18/domain.pddl',
               'caldera-split-opt18/p15.pddl'),
              ('caldera-split-opt18/domain.pddl',
               'caldera-split-opt18/p14.pddl'),
              ('caldera-split-opt18/domain.pddl',
               'caldera-split-opt18/p02.pddl'),
              ('caldera-split-opt18/domain.pddl',
               'caldera-split-opt18/p18.pddl'),
              ('caldera-split-opt18/domain.pddl',
               'caldera-split-opt18/p05.pddl'),
              ('caldera-split-opt18/domain.pddl',
               'caldera-split-opt18/p13.pddl'),
              ('caldera-split-opt18/domain.pddl',
               'caldera-split-opt18/p09.pddl'),
              ('caldera-split-opt18/domain.pddl',
               'caldera-split-opt18/p08.pddl'),
              ('caldera-split-opt18/domain.pddl',
               'caldera-split-opt18/p12.pddl'),
              ('caldera-split-opt18/domain.pddl',
               'caldera-split-opt18/p04.pddl')]}]
