domains = [
{'description': 'This is the mystery domain with one extra action, the ability to squirt a unit of fuel from any node to a neighboring node, provided the originating node has at least two units. Created by Drew McDermott',
 'ipc': '2011',
 'name': 'mprime',
 'problems': [('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p01.pddl'),
('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p02.pddl'),
('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p03.pddl'),
('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p04.pddl'),
('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p05.pddl'),
('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p06.pddl'),
('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p07.pddl'),
('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p08.pddl'),
('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p09.pddl'),
('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p10.pddl'),
('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p11.pddl'),
('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p12.pddl'),
('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p13.pddl'),
('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p14.pddl'),
('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p15.pddl'),
('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p16.pddl'),
('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p17.pddl'),
('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p18.pddl'),
('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p19.pddl'),
('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p20.pddl'),
('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p21.pddl'),
('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p22.pddl'),
('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p23.pddl'),
('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p24.pddl'),
('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p25.pddl'),
('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p26.pddl'),
('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p27.pddl'),
('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p28.pddl'),
('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p29.pddl'),
('mprime-ipc11-learning-target/domain.pddl', 'mprime-ipc11-learning-target/p30.pddl')
]}
]
