domains = [
{'description': 'The scenario is the following: There is a building with N+1 floors, numbered from 0 to N. The building can be separated in blocks of size M+1, where M divides N. Adjacent blocks have a common floor. For example, suppose N=12 and M=4, then we have 13 floors in total (ranging from 0 to 12), which form 3 blocks of 5 floors each, being 0 to 4, 4 to 8 and 8 to 12. The building has K fast (accelarating) elevators that stop only in floors that are multiple of M/2 (so M has to be an even number). Each fast elevator has a capacity of X persons. Furthermore, within each block, there are L slow elevators, that stop at every floor of the block. Each slow elevator has a capacity of Y persons (usually Y<X). There are costs associated with each elavator starting/stoping and moving. In particular, fast (accelarating) elevators have negligible cost of starting/stoping but have significant cost while moving. On the other hand, slow (constant speed) elevators have significant cost when starting/stoping and negligible cost while moving. Travelling times between floors are given for any type of elevator, taking into account the constant speed of the slow elevators and the constant acceleration of the fast elevators. There are several passengers, for which their current location (i.e. the floor they are) and their destination are given. The planning problem is to find a plan that moves the passengers to their destinations while minimizing the total cost of moving the passengers to their destinations . The total cost is increased each time an elevator starts/stops or moves.',
 'ipc': '2011',
 'name': 'elevators',
 'problems': [('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p01.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p02.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p03.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p04.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p05.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p06.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p07.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p08.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p09.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p10.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p11.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p12.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p13.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p14.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p15.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p16.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p17.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p18.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p19.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p20.pddl')]}
]