domains = [
{'description': '',
 'ipc': '2011',
 'name': 'elevators',
 'problems': [('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p01.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p02.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p03.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p04.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p05.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p06.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p07.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p08.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p09.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p10.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p11.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p12.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p13.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p14.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p15.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p16.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p17.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p18.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p19.pddl'),
              ('elevators-sat11-strips/domain.pddl',
               'elevators-sat11-strips/p20.pddl')]}
]