domains = [
{'description': 'Untyped STRIPS domain. Extremely simple version of TSP. The locations are connected by a complete graph, i.e. each location is accessible from each other location. The edges all have equal cost---one moving operation---and the goal is simply to have all locations visited. An optimal solution simply visits all locations once in an arbitrary ordering.',
 'ipc': None,
 'name': 'tsp',
 'problems': [('tsp/domain.pddl', 'tsp/pfile1.pddl'),
              ('tsp/domain.pddl', 'tsp/pfile10.pddl'),
              ('tsp/domain.pddl', 'tsp/pfile11.pddl'),
              ('tsp/domain.pddl', 'tsp/pfile12.pddl'),
              ('tsp/domain.pddl', 'tsp/pfile13.pddl'),
              ('tsp/domain.pddl', 'tsp/pfile14.pddl'),
              ('tsp/domain.pddl', 'tsp/pfile15.pddl'),
              ('tsp/domain.pddl', 'tsp/pfile16.pddl'),
              ('tsp/domain.pddl', 'tsp/pfile17.pddl'),
              ('tsp/domain.pddl', 'tsp/pfile18.pddl'),
              ('tsp/domain.pddl', 'tsp/pfile19.pddl'),
              ('tsp/domain.pddl', 'tsp/pfile2.pddl'),
              ('tsp/domain.pddl', 'tsp/pfile20.pddl'),
              ('tsp/domain.pddl', 'tsp/pfile21.pddl'),
              ('tsp/domain.pddl', 'tsp/pfile22.pddl'),
              ('tsp/domain.pddl', 'tsp/pfile23.pddl'),
              ('tsp/domain.pddl', 'tsp/pfile24.pddl'),
              ('tsp/domain.pddl', 'tsp/pfile25.pddl'),
              ('tsp/domain.pddl', 'tsp/pfile26.pddl'),
              ('tsp/domain.pddl', 'tsp/pfile27.pddl'),
              ('tsp/domain.pddl', 'tsp/pfile28.pddl'),
              ('tsp/domain.pddl', 'tsp/pfile29.pddl'),
              ('tsp/domain.pddl', 'tsp/pfile3.pddl'),
              ('tsp/domain.pddl', 'tsp/pfile30.pddl'),
              ('tsp/domain.pddl', 'tsp/pfile4.pddl'),
              ('tsp/domain.pddl', 'tsp/pfile5.pddl'),
              ('tsp/domain.pddl', 'tsp/pfile6.pddl'),
              ('tsp/domain.pddl', 'tsp/pfile7.pddl'),
              ('tsp/domain.pddl', 'tsp/pfile8.pddl'),
              ('tsp/domain.pddl', 'tsp/pfile9.pddl')]}
]