domains = [
{'description': '',
 'ipc': '2014',
 'name': 'barman',
 'problems': [('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p1-11-4-15.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p1-11-5-15.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p1-11-5-16.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p2-10-4-13.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p2-11-4-15.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p2-11-5-15.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p2-11-5-16.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p2-11-5-17.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p3-10-4-13.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p3-11-4-15.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p3-11-5-15.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p3-11-5-16.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p3-11-5-17.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p4-11-4-14.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p4-11-4-15.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p4-11-5-15.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p5-10-4-13.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p5-11-4-15.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p5-11-5-15.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p5-11-5-16.pddl')]}
]