domains = [
{'description': "In this domain there is a robot barman that manipulates drink dispensers, glasses and a shaker. The goal is to find a plan of the robot's actions that serves a desired set of drinks. In this domain deletes of actions encode relevant knowledge given that robot hands can only grasp one object at a time and given that glasses need to be empty and clean to be filled.",
 'ipc': '2014',
 'name': 'barman',
 'problems': [('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p1-11-4-15.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p1-11-5-15.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p1-11-5-16.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p2-10-4-13.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p2-11-4-15.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p2-11-5-15.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p2-11-5-16.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p2-11-5-17.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p3-10-4-13.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p3-11-4-15.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p3-11-5-15.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p3-11-5-16.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p3-11-5-17.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p4-11-4-14.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p4-11-4-15.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p4-11-5-15.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p5-10-4-13.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p5-11-4-15.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p5-11-5-15.pddl'),
              ('barman-sat14-strips/domain.pddl',
               'barman-sat14-strips/p5-11-5-16.pddl')]}
]