(define (problem BLOCKS-60-1)
(:domain BLOCKS)
(:objects M1 B1 E D1 H1 Q I E1 N1 F2 M Y1 J O1 K1 C2
          L T1 N T F1 R D2 R1 H2 V1 E2 C W1 A V Z1 U1 
          A2 Q1 D A1 G J1 K I1 Z B2 X1 L1 Y O F P1 G2 U W C1 S1 G1 H B S P X)

(:INIT (CLEAR M1) (CLEAR B1) (CLEAR E) (CLEAR D1) (CLEAR H1)
                    (CLEAR Q) (ONTABLE I) (ONTABLE E1) (ONTABLE N1)
                    (ONTABLE F2) (ONTABLE H1) (ONTABLE Q) (ON M1 M) (ON M Y1)
                    (ON Y1 J) (ON J O1) (ON O1 K1) (ON K1 C2) (ON C2 L)
                    (ON L T1) (ON T1 I) (ON B1 N) (ON N T) (ON T F1) (ON F1 R)
                    (ON R D2) (ON D2 R1) (ON R1 H2) (ON H2 V1) (ON V1 E2)
                    (ON E2 C) (ON C W1) (ON W1 A) (ON A V) (ON V Z1)
                    (ON Z1 E1) (ON E U1) (ON U1 A2) (ON A2 Q1) (ON Q1 D)
                    (ON D A1) (ON A1 G) (ON G J1) (ON J1 K) (ON K I1)
                    (ON I1 Z) (ON Z B2) (ON B2 X1) (ON X1 L1) (ON L1 Y)
                    (ON Y O) (ON O F) (ON F P1) (ON P1 G2) (ON G2 U) (ON U W)
                    (ON W C1) (ON C1 S1) (ON S1 G1) (ON G1 H) (ON H B)
                    (ON B S) (ON S P) (ON P X) (ON X N1) (ON D1 F2)
                    (HANDEMPTY))
(:GOAL (AND (ON G B2) (ON B2 X) (ON X R1) (ON R1 D2) (ON D2 Z) (ON Z N)
           (ON N I) (ON I W) (ON W F2) (ON F2 B) (ON B M1) (ON M1 O1)
           (ON O1 T1) (ON T1 P1) (ON P1 N1) (ON N1 F1) (ON F1 C) (ON C C1)
           (ON C1 K1) (ON K1 A2) (ON A2 J) (ON J J1) (ON J1 P) (ON P G1)
           (ON G1 S) (ON S A) (ON A E1) (ON E1 H) (ON H H1) (ON H1 V) (ON V F)
           (ON F G2) (ON G2 L1) (ON L1 Y1) (ON Y1 X1) (ON X1 I1) (ON I1 T)
           (ON T L) (ON L E) (ON E W1) (ON W1 B1) (ON B1 R) (ON R U1)
           (ON U1 U) (ON U Q) (ON Q M) (ON M C2) (ON C2 H2) (ON H2 Q1)
           (ON Q1 A1) (ON A1 S1) (ON S1 Z1) (ON Z1 D1) (ON D1 K) (ON K Y)
           (ON Y V1) (ON V1 D) (ON D O) (ON O E2)))
)