(define (problem BLOCKS-60-0)
(:domain BLOCKS)
(:objects A2 T C2 H2 G1 V B1 Y C I C1 B G2 N1 E1 J Z 
          J1 N L1 M R A E2 W1 O G R1 D2 D1 A1 S1 B2 
          H1 V1 W U K1 X Z1 Q1 D P Q Y1 M1 S H P1 T1 F U1 K I1 O1 F2 E F1 L X1)
(:INIT (CLEAR A2) (CLEAR T) (CLEAR C2) (CLEAR H2) (CLEAR G1)
                    (CLEAR V) (ONTABLE B1) (ONTABLE Y) (ONTABLE C) (ONTABLE I)
                    (ONTABLE C1) (ONTABLE V) (ON A2 B) (ON B G2) (ON G2 N1)
                    (ON N1 E1) (ON E1 J) (ON J Z) (ON Z J1) (ON J1 N)
                    (ON N L1) (ON L1 M) (ON M R) (ON R A) (ON A E2) (ON E2 W1)
                    (ON W1 O) (ON O G) (ON G R1) (ON R1 D2) (ON D2 D1)
                    (ON D1 A1) (ON A1 S1) (ON S1 B2) (ON B2 H1) (ON H1 V1)
                    (ON V1 W) (ON W U) (ON U K1) (ON K1 B1) (ON T X) (ON X Z1)
                    (ON Z1 Q1) (ON Q1 D) (ON D P) (ON P Q) (ON Q Y1)
                    (ON Y1 M1) (ON M1 S) (ON S H) (ON H P1) (ON P1 T1)
                    (ON T1 F) (ON F U1) (ON U1 K) (ON K I1) (ON I1 O1)
                    (ON O1 Y) (ON C2 C) (ON H2 F2) (ON F2 E) (ON E F1)
                    (ON F1 L) (ON L X1) (ON X1 I) (ON G1 C1) (HANDEMPTY))
(:GOAL (AND (ON S L1) (ON L1 I) (ON I I1) (ON I1 H2) (ON H2 J) (ON J G1)
           (ON G1 W1) (ON W1 R) (ON R B) (ON B Q) (ON Q V) (ON V U1) (ON U1 G)
           (ON G N1) (ON N1 E2) (ON E2 D1) (ON D1 Z1) (ON Z1 A) (ON A N)
           (ON N H1) (ON H1 E1) (ON E1 R1) (ON R1 A1) (ON A1 A2) (ON A2 K)
           (ON K O1) (ON O1 C) (ON C B2) (ON B2 S1) (ON S1 O) (ON O C1)
           (ON C1 E) (ON E T) (ON T Y) (ON Y P1) (ON P1 X1) (ON X1 F)
           (ON F F2) (ON F2 M1) (ON M1 B1) (ON B1 M) (ON M F1) (ON F1 W)
           (ON W U) (ON U Z) (ON Z T1) (ON T1 L) (ON L J1) (ON J1 X) (ON X Y1)
           (ON Y1 D2) (ON D2 C2) (ON C2 D) (ON D V1) (ON V1 Q1) (ON Q1 K1)
           (ON K1 H) (ON H G2) (ON G2 P)))
)