domains = [
{'description': 'Simulates the works in a woodworking workshop where there is some quantity of wood that has to be polished, coloured, etc. using different tools with different costs. Parameters of each problem are the parts to be done and the quantity (in % of necessary) of available wood (boards). The higher the number of parts and the boards the more difficult the problem is.',
 'ipc': '2011',
 'name': 'woodworking',
 'problems': [('woodworking-opt11-strips/domain.pddl',
               'woodworking-opt11-strips/p01.pddl'),
              ('woodworking-opt11-strips/domain.pddl',
               'woodworking-opt11-strips/p02.pddl'),
              ('woodworking-opt11-strips/domain.pddl',
               'woodworking-opt11-strips/p03.pddl'),
              ('woodworking-opt11-strips/domain.pddl',
               'woodworking-opt11-strips/p04.pddl'),
              ('woodworking-opt11-strips/domain.pddl',
               'woodworking-opt11-strips/p05.pddl'),
              ('woodworking-opt11-strips/domain.pddl',
               'woodworking-opt11-strips/p06.pddl'),
              ('woodworking-opt11-strips/domain.pddl',
               'woodworking-opt11-strips/p07.pddl'),
              ('woodworking-opt11-strips/domain.pddl',
               'woodworking-opt11-strips/p08.pddl'),
              ('woodworking-opt11-strips/domain.pddl',
               'woodworking-opt11-strips/p09.pddl'),
              ('woodworking-opt11-strips/domain.pddl',
               'woodworking-opt11-strips/p10.pddl'),
              ('woodworking-opt11-strips/domain.pddl',
               'woodworking-opt11-strips/p11.pddl'),
              ('woodworking-opt11-strips/domain.pddl',
               'woodworking-opt11-strips/p12.pddl'),
              ('woodworking-opt11-strips/domain.pddl',
               'woodworking-opt11-strips/p13.pddl'),
              ('woodworking-opt11-strips/domain.pddl',
               'woodworking-opt11-strips/p14.pddl'),
              ('woodworking-opt11-strips/domain.pddl',
               'woodworking-opt11-strips/p15.pddl'),
              ('woodworking-opt11-strips/domain.pddl',
               'woodworking-opt11-strips/p16.pddl'),
              ('woodworking-opt11-strips/domain.pddl',
               'woodworking-opt11-strips/p17.pddl'),
              ('woodworking-opt11-strips/domain.pddl',
               'woodworking-opt11-strips/p18.pddl'),
              ('woodworking-opt11-strips/domain.pddl',
               'woodworking-opt11-strips/p19.pddl'),
              ('woodworking-opt11-strips/domain.pddl',
               'woodworking-opt11-strips/p20.pddl')]}
]