domains = [
{'description': 'Untyped STRIPS domain. Transport a number of cars from their start- to their goal-locations, using a ferry. Each location is accessible from each other location, cars can be debarked or boarded, the ferry can always carry only one car at a time.',
 'ipc': '2011',
 'name': 'ferry',
 'problems': 
 [('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p01.pddl'),
  ('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p02.pddl'),
  ('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p03.pddl'),
  ('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p04.pddl'),
  ('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p05.pddl'),
  ('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p06.pddl'),
  ('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p07.pddl'),
  ('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p08.pddl'),
  ('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p09.pddl'),
  ('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p10.pddl'),
  ('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p11.pddl'),
  ('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p12.pddl'),
  ('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p13.pddl'),
  ('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p14.pddl'),
  ('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p15.pddl'),
  ('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p16.pddl'),
  ('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p17.pddl'),
  ('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p18.pddl'),
  ('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p19.pddl'),
  ('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p20.pddl'),
  ('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p21.pddl'),
  ('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p22.pddl'),
  ('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p23.pddl'),
  ('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p24.pddl'),
  ('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p25.pddl'),
  ('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p26.pddl'),
  ('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p27.pddl'),
  ('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p28.pddl'),
  ('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p29.pddl'),
  ('ferry-ipc11-learning-target/domain.pddl', 'ferry-ipc11-learning-target/p30.pddl')]}
]
