domains = [
{'description': 'The 4-operator version of the classic Blocksworld. This domain consists of a set of blocks, a table and a robot hand. The blocks can be on top of other blocks or on the table; a block that has nothing on it is clear; and the robot hand can hold one block or be empty. The goal is to find a plan to move from one configuration of blocks to another.',
 'ipc': '2011',
 'name': 'blocks',
 'problems': [('blocksworld-ipc11-learning-test/domain.pddl', 'blocksworld-ipc11-learning-test/p01.pddl'),
              ('blocksworld-ipc11-learning-test/domain.pddl', 'blocksworld-ipc11-learning-test/p02.pddl'),
              ('blocksworld-ipc11-learning-test/domain.pddl', 'blocksworld-ipc11-learning-test/p03.pddl'),
              ('blocksworld-ipc11-learning-test/domain.pddl', 'blocksworld-ipc11-learning-test/p04.pddl'),
              ('blocksworld-ipc11-learning-test/domain.pddl', 'blocksworld-ipc11-learning-test/p05.pddl'),
              ('blocksworld-ipc11-learning-test/domain.pddl', 'blocksworld-ipc11-learning-test/p06.pddl'),
              ('blocksworld-ipc11-learning-test/domain.pddl', 'blocksworld-ipc11-learning-test/p07.pddl'),
              ('blocksworld-ipc11-learning-test/domain.pddl', 'blocksworld-ipc11-learning-test/p08.pddl'),
              ('blocksworld-ipc11-learning-test/domain.pddl', 'blocksworld-ipc11-learning-test/p09.pddl'),
              ('blocksworld-ipc11-learning-test/domain.pddl', 'blocksworld-ipc11-learning-test/p10.pddl'),
              ('blocksworld-ipc11-learning-test/domain.pddl', 'blocksworld-ipc11-learning-test/p11.pddl'),
              ('blocksworld-ipc11-learning-test/domain.pddl', 'blocksworld-ipc11-learning-test/p12.pddl'),
              ('blocksworld-ipc11-learning-test/domain.pddl', 'blocksworld-ipc11-learning-test/p13.pddl'),
              ('blocksworld-ipc11-learning-test/domain.pddl', 'blocksworld-ipc11-learning-test/p14.pddl'),
              ('blocksworld-ipc11-learning-test/domain.pddl', 'blocksworld-ipc11-learning-test/p15.pddl'),
              ('blocksworld-ipc11-learning-test/domain.pddl', 'blocksworld-ipc11-learning-test/p16.pddl'),
              ('blocksworld-ipc11-learning-test/domain.pddl', 'blocksworld-ipc11-learning-test/p17.pddl'),
              ('blocksworld-ipc11-learning-test/domain.pddl', 'blocksworld-ipc11-learning-test/p18.pddl'),
              ('blocksworld-ipc11-learning-test/domain.pddl', 'blocksworld-ipc11-learning-test/p19.pddl'),
              ('blocksworld-ipc11-learning-test/domain.pddl', 'blocksworld-ipc11-learning-test/p10.pddl')]}
]
