domains = [
{'description': 'Inspired by planetary rovers problems, this domain requires that a collection of rovers navigate a planet surface, finding samples and communicating them back to a lander.',
 'ipc': '2011',
 'name': 'rovers',
 'problems': [('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p01.pddl'),
('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p02.pddl'),
('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p03.pddl'),
('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p04.pddl'),
('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p05.pddl'),
('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p06.pddl'),
('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p07.pddl'),
('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p08.pddl'),
('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p09.pddl'),
('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p10.pddl'),
('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p11.pddl'),
('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p12.pddl'),
('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p13.pddl'),
('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p14.pddl'),
('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p15.pddl'),
('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p16.pddl'),
('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p17.pddl'),
('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p18.pddl'),
('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p19.pddl'),
('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p20.pddl'),
('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p21.pddl'),
('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p22.pddl'),
('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p23.pddl'),
('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p24.pddl'),
('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p25.pddl'),
('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p26.pddl'),
('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p27.pddl'),
('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p28.pddl'),
('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p29.pddl'),
('rover-ipc11-learning-test/domain.pddl', 'rover-ipc11-learning-test/p30.pddl')]}
]
