domains = [{'description': '(opt18) Agricola:\n\nsubmitted by Tomas de la Rosa.\n\nDescription: This domain is loosely based on the board game Agricola. The game models a farm with some\nworkers. The game has a number of rounds and stages, in which the player must select\nactions for every worker. Some of this actions will obtain resources, and others will\nincrease the number of workers. This allows the player to perform more actions per turn\nbut also increases the amount of food consumed at the end of the turn, potentially leading\ninto dead ends.',
 'ipc': '2018',
 'name': 'agricola',
 'problems': [('agricola-opt18/domain.pddl', 'agricola-opt18/p11.pddl'),
              ('agricola-opt18/domain.pddl', 'agricola-opt18/p07.pddl'),
              ('agricola-opt18/domain.pddl', 'agricola-opt18/p06.pddl'),
              ('agricola-opt18/domain.pddl', 'agricola-opt18/p10.pddl'),
              ('agricola-opt18/domain.pddl', 'agricola-opt18/p17.pddl'),
              ('agricola-opt18/domain.pddl', 'agricola-opt18/p01.pddl'),
              ('agricola-opt18/domain.pddl', 'agricola-opt18/p16.pddl'),
              ('agricola-opt18/domain.pddl', 'agricola-opt18/p20.pddl'),
              ('agricola-opt18/domain.pddl', 'agricola-opt18/p19.pddl'),
              ('agricola-opt18/domain.pddl', 'agricola-opt18/p03.pddl'),
              ('agricola-opt18/domain.pddl', 'agricola-opt18/p15.pddl'),
              ('agricola-opt18/domain.pddl', 'agricola-opt18/p14.pddl'),
              ('agricola-opt18/domain.pddl', 'agricola-opt18/p02.pddl'),
              ('agricola-opt18/domain.pddl', 'agricola-opt18/p18.pddl'),
              ('agricola-opt18/domain.pddl', 'agricola-opt18/p05.pddl'),
              ('agricola-opt18/domain.pddl', 'agricola-opt18/p13.pddl'),
              ('agricola-opt18/domain.pddl', 'agricola-opt18/p09.pddl'),
              ('agricola-opt18/domain.pddl', 'agricola-opt18/p08.pddl'),
              ('agricola-opt18/domain.pddl', 'agricola-opt18/p12.pddl'),
              ('agricola-opt18/domain.pddl', 'agricola-opt18/p04.pddl')]}]
