domains = [
{'description': 'Moving packages between locations by trucks under certain spatial constraints and delivering deadlines.',
 'ipc': '2006',
 'name': 'trucks',
 'problems': [('trucks/domain.pddl', 'trucks/p01.pddl'),
              ('trucks/domain.pddl', 'trucks/p02.pddl'),
              ('trucks/domain.pddl', 'trucks/p03.pddl'),
              ('trucks/domain.pddl', 'trucks/p04.pddl'),
              ('trucks/domain.pddl', 'trucks/p05.pddl'),
              ('trucks/domain.pddl', 'trucks/p06.pddl'),
              ('trucks/domain.pddl', 'trucks/p07.pddl'),
              ('trucks/domain.pddl', 'trucks/p08.pddl'),
              ('trucks/domain.pddl', 'trucks/p09.pddl'),
              ('trucks/domain.pddl', 'trucks/p10.pddl'),
              ('trucks/domain.pddl', 'trucks/p11.pddl'),
              ('trucks/domain.pddl', 'trucks/p12.pddl'),
              ('trucks/domain.pddl', 'trucks/p13.pddl'),
              ('trucks/domain.pddl', 'trucks/p14.pddl'),
              ('trucks/domain.pddl', 'trucks/p15.pddl'),
              ('trucks/domain.pddl', 'trucks/p16.pddl'),
              ('trucks/domain.pddl', 'trucks/p17.pddl'),
              ('trucks/domain.pddl', 'trucks/p18.pddl'),
              ('trucks/domain.pddl', 'trucks/p19.pddl'),
              ('trucks/domain.pddl', 'trucks/p20.pddl'),
              ('trucks/domain.pddl', 'trucks/p21.pddl'),
              ('trucks/domain.pddl', 'trucks/p22.pddl'),
              ('trucks/domain.pddl', 'trucks/p23.pddl'),
              ('trucks/domain.pddl', 'trucks/p24.pddl'),
              ('trucks/domain.pddl', 'trucks/p25.pddl'),
              ('trucks/domain.pddl', 'trucks/p26.pddl'),
              ('trucks/domain.pddl', 'trucks/p27.pddl'),
              ('trucks/domain.pddl', 'trucks/p28.pddl'),
              ('trucks/domain.pddl', 'trucks/p29.pddl'),
              ('trucks/domain.pddl', 'trucks/p30.pddl')]}
]