domains = [
{'description': '',
 'ipc': '2011',
 'name': 'openstacks',
 'problems': [('openstacks-sat11-strips/p01-domain.pddl',
               'openstacks-sat11-strips/p01.pddl'),
              ('openstacks-sat11-strips/p02-domain.pddl',
               'openstacks-sat11-strips/p02.pddl'),
              ('openstacks-sat11-strips/p03-domain.pddl',
               'openstacks-sat11-strips/p03.pddl'),
              ('openstacks-sat11-strips/p04-domain.pddl',
               'openstacks-sat11-strips/p04.pddl'),
              ('openstacks-sat11-strips/p05-domain.pddl',
               'openstacks-sat11-strips/p05.pddl'),
              ('openstacks-sat11-strips/p06-domain.pddl',
               'openstacks-sat11-strips/p06.pddl'),
              ('openstacks-sat11-strips/p07-domain.pddl',
               'openstacks-sat11-strips/p07.pddl'),
              ('openstacks-sat11-strips/p08-domain.pddl',
               'openstacks-sat11-strips/p08.pddl'),
              ('openstacks-sat11-strips/p09-domain.pddl',
               'openstacks-sat11-strips/p09.pddl'),
              ('openstacks-sat11-strips/p10-domain.pddl',
               'openstacks-sat11-strips/p10.pddl'),
              ('openstacks-sat11-strips/p11-domain.pddl',
               'openstacks-sat11-strips/p11.pddl'),
              ('openstacks-sat11-strips/p12-domain.pddl',
               'openstacks-sat11-strips/p12.pddl'),
              ('openstacks-sat11-strips/p13-domain.pddl',
               'openstacks-sat11-strips/p13.pddl'),
              ('openstacks-sat11-strips/p14-domain.pddl',
               'openstacks-sat11-strips/p14.pddl'),
              ('openstacks-sat11-strips/p15-domain.pddl',
               'openstacks-sat11-strips/p15.pddl'),
              ('openstacks-sat11-strips/p16-domain.pddl',
               'openstacks-sat11-strips/p16.pddl'),
              ('openstacks-sat11-strips/p17-domain.pddl',
               'openstacks-sat11-strips/p17.pddl'),
              ('openstacks-sat11-strips/p18-domain.pddl',
               'openstacks-sat11-strips/p18.pddl'),
              ('openstacks-sat11-strips/p19-domain.pddl',
               'openstacks-sat11-strips/p19.pddl'),
              ('openstacks-sat11-strips/p20-domain.pddl',
               'openstacks-sat11-strips/p20.pddl')]}
]