domains = [
{'description': 'This domain models the Peg Solitaire game. (http://en.wikipedia.org/wiki/Peg_solitaire)',
 'ipc': '2011',
 'name': 'pegsol',
 'problems': [('pegsol-opt11-strips/domain.pddl',
               'pegsol-opt11-strips/p01.pddl'),
              ('pegsol-opt11-strips/domain.pddl',
               'pegsol-opt11-strips/p02.pddl'),
              ('pegsol-opt11-strips/domain.pddl',
               'pegsol-opt11-strips/p03.pddl'),
              ('pegsol-opt11-strips/domain.pddl',
               'pegsol-opt11-strips/p04.pddl'),
              ('pegsol-opt11-strips/domain.pddl',
               'pegsol-opt11-strips/p05.pddl'),
              ('pegsol-opt11-strips/domain.pddl',
               'pegsol-opt11-strips/p06.pddl'),
              ('pegsol-opt11-strips/domain.pddl',
               'pegsol-opt11-strips/p07.pddl'),
              ('pegsol-opt11-strips/domain.pddl',
               'pegsol-opt11-strips/p08.pddl'),
              ('pegsol-opt11-strips/domain.pddl',
               'pegsol-opt11-strips/p09.pddl'),
              ('pegsol-opt11-strips/domain.pddl',
               'pegsol-opt11-strips/p10.pddl'),
              ('pegsol-opt11-strips/domain.pddl',
               'pegsol-opt11-strips/p11.pddl'),
              ('pegsol-opt11-strips/domain.pddl',
               'pegsol-opt11-strips/p12.pddl'),
              ('pegsol-opt11-strips/domain.pddl',
               'pegsol-opt11-strips/p13.pddl'),
              ('pegsol-opt11-strips/domain.pddl',
               'pegsol-opt11-strips/p14.pddl'),
              ('pegsol-opt11-strips/domain.pddl',
               'pegsol-opt11-strips/p15.pddl'),
              ('pegsol-opt11-strips/domain.pddl',
               'pegsol-opt11-strips/p16.pddl'),
              ('pegsol-opt11-strips/domain.pddl',
               'pegsol-opt11-strips/p17.pddl'),
              ('pegsol-opt11-strips/domain.pddl',
               'pegsol-opt11-strips/p18.pddl'),
              ('pegsol-opt11-strips/domain.pddl',
               'pegsol-opt11-strips/p19.pddl'),
              ('pegsol-opt11-strips/domain.pddl',
               'pegsol-opt11-strips/p20.pddl')]}
]