domains = [
{'description': 'Finding a sequence of biochemical (pathways) reactions in an organism producing certain substances.',
 'ipc': '2006',
 'name': 'pathways',
 'problems': [('pathways/domain_p01.pddl', 'pathways/p01.pddl'),
              ('pathways/domain_p02.pddl', 'pathways/p02.pddl'),
              ('pathways/domain_p03.pddl', 'pathways/p03.pddl'),
              ('pathways/domain_p04.pddl', 'pathways/p04.pddl'),
              ('pathways/domain_p05.pddl', 'pathways/p05.pddl'),
              ('pathways/domain_p06.pddl', 'pathways/p06.pddl'),
              ('pathways/domain_p07.pddl', 'pathways/p07.pddl'),
              ('pathways/domain_p08.pddl', 'pathways/p08.pddl'),
              ('pathways/domain_p09.pddl', 'pathways/p09.pddl'),
              ('pathways/domain_p10.pddl', 'pathways/p10.pddl'),
              ('pathways/domain_p11.pddl', 'pathways/p11.pddl'),
              ('pathways/domain_p12.pddl', 'pathways/p12.pddl'),
              ('pathways/domain_p13.pddl', 'pathways/p13.pddl'),
              ('pathways/domain_p14.pddl', 'pathways/p14.pddl'),
              ('pathways/domain_p15.pddl', 'pathways/p15.pddl'),
              ('pathways/domain_p16.pddl', 'pathways/p16.pddl'),
              ('pathways/domain_p17.pddl', 'pathways/p17.pddl'),
              ('pathways/domain_p18.pddl', 'pathways/p18.pddl'),
              ('pathways/domain_p19.pddl', 'pathways/p19.pddl'),
              ('pathways/domain_p20.pddl', 'pathways/p20.pddl'),
              ('pathways/domain_p21.pddl', 'pathways/p21.pddl'),
              ('pathways/domain_p22.pddl', 'pathways/p22.pddl'),
              ('pathways/domain_p23.pddl', 'pathways/p23.pddl'),
              ('pathways/domain_p24.pddl', 'pathways/p24.pddl'),
              ('pathways/domain_p25.pddl', 'pathways/p25.pddl'),
              ('pathways/domain_p26.pddl', 'pathways/p26.pddl'),
              ('pathways/domain_p27.pddl', 'pathways/p27.pddl'),
              ('pathways/domain_p28.pddl', 'pathways/p28.pddl'),
              ('pathways/domain_p29.pddl', 'pathways/p29.pddl'),
              ('pathways/domain_p30.pddl', 'pathways/p30.pddl')]}
]