domains = [
{'description': 'Inspired by planetary rovers problems, this domain requires that a collection of rovers navigate a planet surface, finding samples and communicating them back to a lander.',
 'ipc': '2006',
 'name': 'rovers',
 'problems': [('rovers/domain.pddl', 'rovers/p01.pddl'),
              ('rovers/domain.pddl', 'rovers/p02.pddl'),
              ('rovers/domain.pddl', 'rovers/p03.pddl'),
              ('rovers/domain.pddl', 'rovers/p04.pddl'),
              ('rovers/domain.pddl', 'rovers/p05.pddl'),
              ('rovers/domain.pddl', 'rovers/p06.pddl'),
              ('rovers/domain.pddl', 'rovers/p07.pddl'),
              ('rovers/domain.pddl', 'rovers/p08.pddl'),
              ('rovers/domain.pddl', 'rovers/p09.pddl'),
              ('rovers/domain.pddl', 'rovers/p10.pddl'),
              ('rovers/domain.pddl', 'rovers/p11.pddl'),
              ('rovers/domain.pddl', 'rovers/p12.pddl'),
              ('rovers/domain.pddl', 'rovers/p13.pddl'),
              ('rovers/domain.pddl', 'rovers/p14.pddl'),
              ('rovers/domain.pddl', 'rovers/p15.pddl'),
              ('rovers/domain.pddl', 'rovers/p16.pddl'),
              ('rovers/domain.pddl', 'rovers/p17.pddl'),
              ('rovers/domain.pddl', 'rovers/p18.pddl'),
              ('rovers/domain.pddl', 'rovers/p19.pddl'),
              ('rovers/domain.pddl', 'rovers/p20.pddl'),
              ('rovers/domain.pddl', 'rovers/p21.pddl'),
              ('rovers/domain.pddl', 'rovers/p22.pddl'),
              ('rovers/domain.pddl', 'rovers/p23.pddl'),
              ('rovers/domain.pddl', 'rovers/p24.pddl'),
              ('rovers/domain.pddl', 'rovers/p25.pddl'),
              ('rovers/domain.pddl', 'rovers/p26.pddl'),
              ('rovers/domain.pddl', 'rovers/p27.pddl'),
              ('rovers/domain.pddl', 'rovers/p28.pddl'),
              ('rovers/domain.pddl', 'rovers/p29.pddl'),
              ('rovers/domain.pddl', 'rovers/p30.pddl'),
              ('rovers/domain.pddl', 'rovers/p31.pddl'),
              ('rovers/domain.pddl', 'rovers/p32.pddl'),
              ('rovers/domain.pddl', 'rovers/p33.pddl'),
              ('rovers/domain.pddl', 'rovers/p34.pddl'),
              ('rovers/domain.pddl', 'rovers/p35.pddl'),
              ('rovers/domain.pddl', 'rovers/p36.pddl'),
              ('rovers/domain.pddl', 'rovers/p37.pddl'),
              ('rovers/domain.pddl', 'rovers/p38.pddl'),
              ('rovers/domain.pddl', 'rovers/p39.pddl'),
              ('rovers/domain.pddl', 'rovers/p40.pddl')]}
]