domains = [
{'description': 'There is a robot with two grippers. It can carry a ball in each. The goal is to take N balls from one room to another; N rises with problem number. Some planners treat the two grippers asymmetrically, giving rise to an unnecessary combinatorial explosion. This domain was created by Jana Koehler.',
 'ipc': '2011',
 'name': 'gripper',
 'problems': [('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p01.pddl'),
('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p02.pddl'),
('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p03.pddl'),
('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p04.pddl'),
('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p05.pddl'),
('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p06.pddl'),
('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p07.pddl'),
('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p08.pddl'),
('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p09.pddl'),
('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p10.pddl'),
('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p11.pddl'),
('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p12.pddl'),
('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p13.pddl'),
('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p14.pddl'),
('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p15.pddl'),
('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p16.pddl'),
('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p17.pddl'),
('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p18.pddl'),
('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p19.pddl'),
('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p20.pddl'),
('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p21.pddl'),
('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p22.pddl'),
('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p23.pddl'),
('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p24.pddl'),
('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p25.pddl'),
('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p26.pddl'),
('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p27.pddl'),
('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p28.pddl'),
('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p29.pddl'),
('gripper-ipc11-learning-test/domain.pddl', 'gripper-ipc11-learning-test/p30.pddl'),
]}
]
