domains = [
{'description': 'This domain models the Sokoban game. (http://en.wikipedia.org/wiki/Sokoban)',
 'ipc': '2011',
 'name': 'sokoban',
 'problems': [('sokoban-opt11-strips/domain.pddl',
               'sokoban-opt11-strips/p01.pddl'),
              ('sokoban-opt11-strips/domain.pddl',
               'sokoban-opt11-strips/p02.pddl'),
              ('sokoban-opt11-strips/domain.pddl',
               'sokoban-opt11-strips/p03.pddl'),
              ('sokoban-opt11-strips/domain.pddl',
               'sokoban-opt11-strips/p04.pddl'),
              ('sokoban-opt11-strips/domain.pddl',
               'sokoban-opt11-strips/p05.pddl'),
              ('sokoban-opt11-strips/domain.pddl',
               'sokoban-opt11-strips/p06.pddl'),
              ('sokoban-opt11-strips/domain.pddl',
               'sokoban-opt11-strips/p07.pddl'),
              ('sokoban-opt11-strips/domain.pddl',
               'sokoban-opt11-strips/p08.pddl'),
              ('sokoban-opt11-strips/domain.pddl',
               'sokoban-opt11-strips/p09.pddl'),
              ('sokoban-opt11-strips/domain.pddl',
               'sokoban-opt11-strips/p10.pddl'),
              ('sokoban-opt11-strips/domain.pddl',
               'sokoban-opt11-strips/p11.pddl'),
              ('sokoban-opt11-strips/domain.pddl',
               'sokoban-opt11-strips/p12.pddl'),
              ('sokoban-opt11-strips/domain.pddl',
               'sokoban-opt11-strips/p13.pddl'),
              ('sokoban-opt11-strips/domain.pddl',
               'sokoban-opt11-strips/p14.pddl'),
              ('sokoban-opt11-strips/domain.pddl',
               'sokoban-opt11-strips/p15.pddl'),
              ('sokoban-opt11-strips/domain.pddl',
               'sokoban-opt11-strips/p16.pddl'),
              ('sokoban-opt11-strips/domain.pddl',
               'sokoban-opt11-strips/p17.pddl'),
              ('sokoban-opt11-strips/domain.pddl',
               'sokoban-opt11-strips/p18.pddl'),
              ('sokoban-opt11-strips/domain.pddl',
               'sokoban-opt11-strips/p19.pddl'),
              ('sokoban-opt11-strips/domain.pddl',
               'sokoban-opt11-strips/p20.pddl')]}
]