domains = [{'description': '(sat18) Flashfill:\nsubmitted by: Javier Segovia, Universitat Pompeu Fabra\n\nFlashfill models the flashfill feature included in Excel that synthesize programs based on\nuser actions. The inputs are strings that must be transformed into other strings\n(e.g. extract the capital letters of the name and surname) and the output is a computer\nprogram that works on all instances. This can be encoded as a classical planning problem\nusing the planning programs compilation by Segovia et al.\n\nPublications: Javier Segovia Aguas, Sergio Jimenez Celorrio, Anders Jonsson: Generalized\nPlanning with Procedural Domain Control Knowledge. ICAPS 2016',
 'ipc': '2018',
 'name': 'flashfill',
 'problems': [('flashfill-sat18/domain-p11.pddl', 'flashfill-sat18/p11.pddl'),
              ('flashfill-sat18/domain-p07.pddl', 'flashfill-sat18/p07.pddl'),
              ('flashfill-sat18/domain-p06.pddl', 'flashfill-sat18/p06.pddl'),
              ('flashfill-sat18/domain-p10.pddl', 'flashfill-sat18/p10.pddl'),
              ('flashfill-sat18/domain-p17.pddl', 'flashfill-sat18/p17.pddl'),
              ('flashfill-sat18/domain-p01.pddl', 'flashfill-sat18/p01.pddl'),
              ('flashfill-sat18/domain-p16.pddl', 'flashfill-sat18/p16.pddl'),
              ('flashfill-sat18/domain-p20.pddl', 'flashfill-sat18/p20.pddl'),
              ('flashfill-sat18/domain-p19.pddl', 'flashfill-sat18/p19.pddl'),
              ('flashfill-sat18/domain-p03.pddl', 'flashfill-sat18/p03.pddl'),
              ('flashfill-sat18/domain-p15.pddl', 'flashfill-sat18/p15.pddl'),
              ('flashfill-sat18/domain-p14.pddl', 'flashfill-sat18/p14.pddl'),
              ('flashfill-sat18/domain-p02.pddl', 'flashfill-sat18/p02.pddl'),
              ('flashfill-sat18/domain-p18.pddl', 'flashfill-sat18/p18.pddl'),
              ('flashfill-sat18/domain-p05.pddl', 'flashfill-sat18/p05.pddl'),
              ('flashfill-sat18/domain-p13.pddl', 'flashfill-sat18/p13.pddl'),
              ('flashfill-sat18/domain-p09.pddl', 'flashfill-sat18/p09.pddl'),
              ('flashfill-sat18/domain-p08.pddl', 'flashfill-sat18/p08.pddl'),
              ('flashfill-sat18/domain-p12.pddl', 'flashfill-sat18/p12.pddl'),
              ('flashfill-sat18/domain-p04.pddl', 'flashfill-sat18/p04.pddl')]}]
