domains = [
{'description': 'There is a robot with two grippers. It can carry a ball in each. The goal is to take N balls from one room to another; N rises with problem number. Some planners treat the two grippers asymmetrically, giving rise to an unnecessary combinatorial explosion. This domain was created by Jana Koehler.',
 'ipc': '1998',
 'name': 'gripper',
 'problems': [('gripper/domain.pddl', 'gripper/prob01.pddl'),
              ('gripper/domain.pddl', 'gripper/prob02.pddl'),
              ('gripper/domain.pddl', 'gripper/prob03.pddl'),
              ('gripper/domain.pddl', 'gripper/prob04.pddl'),
              ('gripper/domain.pddl', 'gripper/prob05.pddl'),
              ('gripper/domain.pddl', 'gripper/prob06.pddl'),
              ('gripper/domain.pddl', 'gripper/prob07.pddl'),
              ('gripper/domain.pddl', 'gripper/prob08.pddl'),
              ('gripper/domain.pddl', 'gripper/prob09.pddl'),
              ('gripper/domain.pddl', 'gripper/prob10.pddl'),
              ('gripper/domain.pddl', 'gripper/prob11.pddl'),
              ('gripper/domain.pddl', 'gripper/prob12.pddl'),
              ('gripper/domain.pddl', 'gripper/prob13.pddl'),
              ('gripper/domain.pddl', 'gripper/prob14.pddl'),
              ('gripper/domain.pddl', 'gripper/prob15.pddl'),
              ('gripper/domain.pddl', 'gripper/prob16.pddl'),
              ('gripper/domain.pddl', 'gripper/prob17.pddl'),
              ('gripper/domain.pddl', 'gripper/prob18.pddl'),
              ('gripper/domain.pddl', 'gripper/prob19.pddl'),
              ('gripper/domain.pddl', 'gripper/prob20.pddl')]}
]