domains = [
{'description': '',
 'ipc': '2014',
 'name': 'tetris',
 'problems': [('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p01-10.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p01-6.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p01-8.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p02-10.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p02-4.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p02-6.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p02-8.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p03-10.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p03-4.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p03-6.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p03-8.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p04-10.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p04-6.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p04-8.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p05-10.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p05-6.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p05-8.pddl')]}
]