domains = [
{'description': 'This is a simplified version of the well-known Tetris. All the pieces (1x1, 2x1, L) are randomly distributed on a NxN grid. The goal is to move them in order to free the upper half of the grid. The pieces can be rotated or translated. Each movement action has a different cost, accordingly to the size of the piece.',
 'ipc': '2014',
 'name': 'tetris',
 'problems': [('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p01-10.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p01-6.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p01-8.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p02-10.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p02-4.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p02-6.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p02-8.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p03-10.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p03-4.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p03-6.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p03-8.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p04-10.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p04-6.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p04-8.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p05-10.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p05-6.pddl'),
              ('tetris-opt14-strips/domain.pddl',
               'tetris-opt14-strips/p05-8.pddl')]}
]