domains = [
{'description': 'A worker is in a shed, containing a number of spanners, and at a gate some distance away there are a number of nuts that must be tightened. Crucially, once the worker has left the shed they cannot return. Also, the spanners are fragile, so once used to tighten a nut they break, and then cannot be used to tighten another. The goal is planning to pick-up the spanners and tighten the nuts. This is an interesting domain for learning, as it has a directed search space, and is challenging for planners employing an ignore delete lists relaxation.',
 'ipc': '2011',
 'name': 'spanner',
 'problems': [('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p01.pddl'),
('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p02.pddl'),
('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p03.pddl'),
('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p04.pddl'),
('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p05.pddl'),
('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p06.pddl'),
('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p07.pddl'),
('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p08.pddl'),
('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p09.pddl'),
('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p10.pddl'),
('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p11.pddl'),
('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p12.pddl'),
('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p13.pddl'),
('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p14.pddl'),
('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p15.pddl'),
('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p16.pddl'),
('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p17.pddl'),
('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p18.pddl'),
('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p19.pddl'),
('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p20.pddl'),
('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p21.pddl'),
('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p22.pddl'),
('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p23.pddl'),
('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p24.pddl'),
('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p25.pddl'),
('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p26.pddl'),
('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p27.pddl'),
('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p28.pddl'),
('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p29.pddl'),
('spanner-ipc11-learning-target/domain.pddl', 'spanner-ipc11-learning-target/p30.pddl')]}
]
