domains = [
{'description': '',
 'ipc': '2011',
 'name': 'barman',
 'problems': [('barman-opt11-strips/domain.pddl',
               'barman-opt11-strips/pfile01-001.pddl'),
              ('barman-opt11-strips/domain.pddl',
               'barman-opt11-strips/pfile01-002.pddl'),
              ('barman-opt11-strips/domain.pddl',
               'barman-opt11-strips/pfile01-003.pddl'),
              ('barman-opt11-strips/domain.pddl',
               'barman-opt11-strips/pfile01-004.pddl'),
              ('barman-opt11-strips/domain.pddl',
               'barman-opt11-strips/pfile02-005.pddl'),
              ('barman-opt11-strips/domain.pddl',
               'barman-opt11-strips/pfile02-006.pddl'),
              ('barman-opt11-strips/domain.pddl',
               'barman-opt11-strips/pfile02-007.pddl'),
              ('barman-opt11-strips/domain.pddl',
               'barman-opt11-strips/pfile02-008.pddl'),
              ('barman-opt11-strips/domain.pddl',
               'barman-opt11-strips/pfile03-009.pddl'),
              ('barman-opt11-strips/domain.pddl',
               'barman-opt11-strips/pfile03-010.pddl'),
              ('barman-opt11-strips/domain.pddl',
               'barman-opt11-strips/pfile03-011.pddl'),
              ('barman-opt11-strips/domain.pddl',
               'barman-opt11-strips/pfile03-012.pddl'),
              ('barman-opt11-strips/domain.pddl',
               'barman-opt11-strips/pfile04-013.pddl'),
              ('barman-opt11-strips/domain.pddl',
               'barman-opt11-strips/pfile04-014.pddl'),
              ('barman-opt11-strips/domain.pddl',
               'barman-opt11-strips/pfile04-015.pddl'),
              ('barman-opt11-strips/domain.pddl',
               'barman-opt11-strips/pfile04-016.pddl'),
              ('barman-opt11-strips/domain.pddl',
               'barman-opt11-strips/pfile05-017.pddl'),
              ('barman-opt11-strips/domain.pddl',
               'barman-opt11-strips/pfile05-018.pddl'),
              ('barman-opt11-strips/domain.pddl',
               'barman-opt11-strips/pfile05-019.pddl'),
              ('barman-opt11-strips/domain.pddl',
               'barman-opt11-strips/pfile05-020.pddl')]}
]