domains = [
{'description': 'Untyped STRIPS encoding of the well-known Towers of Hanoi problem.',
 'ipc': None,
 'name': 'hanoi',
 'problems': [('hanoi/domain.pddl', 'hanoi/pfile1.pddl'),
              ('hanoi/domain.pddl', 'hanoi/pfile10.pddl'),
              ('hanoi/domain.pddl', 'hanoi/pfile11.pddl'),
              ('hanoi/domain.pddl', 'hanoi/pfile12.pddl'),
              ('hanoi/domain.pddl', 'hanoi/pfile13.pddl'),
              ('hanoi/domain.pddl', 'hanoi/pfile14.pddl'),
              ('hanoi/domain.pddl', 'hanoi/pfile15.pddl'),
              ('hanoi/domain.pddl', 'hanoi/pfile16.pddl'),
              ('hanoi/domain.pddl', 'hanoi/pfile17.pddl'),
              ('hanoi/domain.pddl', 'hanoi/pfile18.pddl'),
              ('hanoi/domain.pddl', 'hanoi/pfile19.pddl'),
              ('hanoi/domain.pddl', 'hanoi/pfile2.pddl'),
              ('hanoi/domain.pddl', 'hanoi/pfile20.pddl'),
              ('hanoi/domain.pddl', 'hanoi/pfile21.pddl'),
              ('hanoi/domain.pddl', 'hanoi/pfile22.pddl'),
              ('hanoi/domain.pddl', 'hanoi/pfile23.pddl'),
              ('hanoi/domain.pddl', 'hanoi/pfile24.pddl'),
              ('hanoi/domain.pddl', 'hanoi/pfile25.pddl'),
              ('hanoi/domain.pddl', 'hanoi/pfile26.pddl'),
              ('hanoi/domain.pddl', 'hanoi/pfile27.pddl'),
              ('hanoi/domain.pddl', 'hanoi/pfile28.pddl'),
              ('hanoi/domain.pddl', 'hanoi/pfile29.pddl'),
              ('hanoi/domain.pddl', 'hanoi/pfile3.pddl'),
              ('hanoi/domain.pddl', 'hanoi/pfile30.pddl'),
              ('hanoi/domain.pddl', 'hanoi/pfile4.pddl'),
              ('hanoi/domain.pddl', 'hanoi/pfile5.pddl'),
              ('hanoi/domain.pddl', 'hanoi/pfile6.pddl'),
              ('hanoi/domain.pddl', 'hanoi/pfile7.pddl'),
              ('hanoi/domain.pddl', 'hanoi/pfile8.pddl'),
              ('hanoi/domain.pddl', 'hanoi/pfile9.pddl')]}
]