domains = [
{'description': 'This domain is to plan how to make and serve sandwiches for a group of children in which some are allergic to gluten. There are two actions for making sandwiches from their ingredients. The first one makes a sandwich and the second one makes a sandwich taking into account that all ingredients are gluten-free. There are also actions to put a sandwich on a tray and to serve sandwiches. Problems in this domain define the ingredients to make sandwiches at the initial state. Goals consist of having all kids served with a sandwich to which they are not allergic.',
 'ipc': '2014',
 'name': 'childsnack',
 'problems': [('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile05-2.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile05.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile06-2.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile07-2.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile08-2.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile08.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile09-2.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile09.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile10-2.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile10.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile11-2.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile11.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile12.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile13-2.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile13.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile14.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile15-2.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile16-2.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile19-2.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile19.pddl')]}
]