domains = [
{'description': '',
 'ipc': '2014',
 'name': 'childsnack',
 'problems': [('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile05-2.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile05.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile06-2.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile07-2.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile08-2.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile08.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile09-2.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile09.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile10-2.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile10.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile11-2.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile11.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile12.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile13-2.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile13.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile14.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile15-2.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile16-2.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile19-2.pddl'),
              ('childsnack-sat14-strips/domain.pddl',
               'childsnack-sat14-strips/child-snack_pfile19.pddl')]}
]