domains = [
{'description': "In this domain there is a robot barman that manipulates drink dispensers, glasses and a shaker. The goal is to find a plan of the robot's actions that serves a desired set of drinks. In this domain deletes of actions encode relevant knowledge given that robot hands can only grasp one object at a time and given that glasses need to be empty and clean to be filled.",
 'ipc': '2011',
 'name': 'barman',
 'problems': [('barman-ipc11-learning-test/domain.pddl',
               'barman-ipc11-learning-test/p01.pddl'),
              ('barman-ipc11-learning-test/domain.pddl',
               'barman-ipc11-learning-test/p02.pddl'),
              ('barman-ipc11-learning-test/domain.pddl',
               'barman-ipc11-learning-test/p03.pddl'),
              ('barman-ipc11-learning-test/domain.pddl',
               'barman-ipc11-learning-test/p04.pddl'),
              ('barman-ipc11-learning-test/domain.pddl',
               'barman-ipc11-learning-test/p05.pddl'),
              ('barman-ipc11-learning-test/domain.pddl',
               'barman-ipc11-learning-test/p06.pddl'),
              ('barman-ipc11-learning-test/domain.pddl',
               'barman-ipc11-learning-test/p07.pddl'),
              ('barman-ipc11-learning-test/domain.pddl',
               'barman-ipc11-learning-test/p08.pddl'),
              ('barman-ipc11-learning-test/domain.pddl',
               'barman-ipc11-learning-test/p09.pddl'),
              ('barman-ipc11-learning-test/domain.pddl',
               'barman-ipc11-learning-test/p10.pddl'),
              ('barman-ipc11-learning-test/domain.pddl',
               'barman-ipc11-learning-test/p11.pddl'),
              ('barman-ipc11-learning-test/domain.pddl',
               'barman-ipc11-learning-test/p12.pddl'),
              ('barman-ipc11-learning-test/domain.pddl',
               'barman-ipc11-learning-test/p13.pddl'),
              ('barman-ipc11-learning-test/domain.pddl',
               'barman-ipc11-learning-test/p14.pddl'),
              ('barman-ipc11-learning-test/domain.pddl',
               'barman-ipc11-learning-test/p15.pddl'),
              ('barman-ipc11-learning-test/domain.pddl',
               'barman-ipc11-learning-test/p16.pddl'),
              ('barman-ipc11-learning-test/domain.pddl',
               'barman-ipc11-learning-test/p17.pddl'),
              ('barman-ipc11-learning-test/domain.pddl',
               'barman-ipc11-learning-test/p18.pddl'),
              ('barman-ipc11-learning-test/domain.pddl',
               'barman-ipc11-learning-test/p19.pddl'),
              ('barman-ipc11-learning-test/domain.pddl',
               'barman-ipc11-learning-test/p20.pddl')]}
]
