domains = [
{'description': 'The zenotravel domain involves transporting people around in planes, using different modes of movement: fast and slow. The key to this domain is that, where the expressive power of the numeric tracks is used, the fast movement consumes fuel faster than slow movement, making the search for a good quality plan (one using less fuel) much harder.',
 'ipc': '2002',
 'name': 'zenotravel',
 'problems': [('zenotravel/domain.pddl', 'zenotravel/pfile1.pddl'),
              ('zenotravel/domain.pddl', 'zenotravel/pfile10.pddl'),
              ('zenotravel/domain.pddl', 'zenotravel/pfile11.pddl'),
              ('zenotravel/domain.pddl', 'zenotravel/pfile12.pddl'),
              ('zenotravel/domain.pddl', 'zenotravel/pfile13.pddl'),
              ('zenotravel/domain.pddl', 'zenotravel/pfile14.pddl'),
              ('zenotravel/domain.pddl', 'zenotravel/pfile15.pddl'),
              ('zenotravel/domain.pddl', 'zenotravel/pfile16.pddl'),
              ('zenotravel/domain.pddl', 'zenotravel/pfile17.pddl'),
              ('zenotravel/domain.pddl', 'zenotravel/pfile18.pddl'),
              ('zenotravel/domain.pddl', 'zenotravel/pfile19.pddl'),
              ('zenotravel/domain.pddl', 'zenotravel/pfile2.pddl'),
              ('zenotravel/domain.pddl', 'zenotravel/pfile20.pddl'),
              ('zenotravel/domain.pddl', 'zenotravel/pfile3.pddl'),
              ('zenotravel/domain.pddl', 'zenotravel/pfile4.pddl'),
              ('zenotravel/domain.pddl', 'zenotravel/pfile5.pddl'),
              ('zenotravel/domain.pddl', 'zenotravel/pfile6.pddl'),
              ('zenotravel/domain.pddl', 'zenotravel/pfile7.pddl'),
              ('zenotravel/domain.pddl', 'zenotravel/pfile8.pddl'),
              ('zenotravel/domain.pddl', 'zenotravel/pfile9.pddl')]}
]