domains = [
{'description': 'In this domain, the goal is always the same (to have lots of snacks in order to watch a movie), but the number of constants increases with problem number. Some planners have combinatorial problems in such cases. This domain was created by Corin Anderson.',
 'ipc': '1998',
 'name': 'movie',
 'problems': [('movie/domain.pddl', 'movie/prob01.pddl'),
              ('movie/domain.pddl', 'movie/prob02.pddl'),
              ('movie/domain.pddl', 'movie/prob03.pddl'),
              ('movie/domain.pddl', 'movie/prob04.pddl'),
              ('movie/domain.pddl', 'movie/prob05.pddl'),
              ('movie/domain.pddl', 'movie/prob06.pddl'),
              ('movie/domain.pddl', 'movie/prob07.pddl'),
              ('movie/domain.pddl', 'movie/prob08.pddl'),
              ('movie/domain.pddl', 'movie/prob09.pddl'),
              ('movie/domain.pddl', 'movie/prob10.pddl'),
              ('movie/domain.pddl', 'movie/prob11.pddl'),
              ('movie/domain.pddl', 'movie/prob12.pddl'),
              ('movie/domain.pddl', 'movie/prob13.pddl'),
              ('movie/domain.pddl', 'movie/prob14.pddl'),
              ('movie/domain.pddl', 'movie/prob15.pddl'),
              ('movie/domain.pddl', 'movie/prob16.pddl'),
              ('movie/domain.pddl', 'movie/prob17.pddl'),
              ('movie/domain.pddl', 'movie/prob18.pddl'),
              ('movie/domain.pddl', 'movie/prob19.pddl'),
              ('movie/domain.pddl', 'movie/prob20.pddl'),
              ('movie/domain.pddl', 'movie/prob21.pddl'),
              ('movie/domain.pddl', 'movie/prob22.pddl'),
              ('movie/domain.pddl', 'movie/prob23.pddl'),
              ('movie/domain.pddl', 'movie/prob24.pddl'),
              ('movie/domain.pddl', 'movie/prob25.pddl'),
              ('movie/domain.pddl', 'movie/prob26.pddl'),
              ('movie/domain.pddl', 'movie/prob27.pddl'),
              ('movie/domain.pddl', 'movie/prob28.pddl'),
              ('movie/domain.pddl', 'movie/prob29.pddl'),
              ('movie/domain.pddl', 'movie/prob30.pddl')]}
]