domains = [
{'description': 'Untyped STRIPS domain. Transport a number of cars from their start- to their goal-locations, using a ferry. Each location is accessible from each other location, cars can be debarked or boarded, the ferry can always carry only one car at a time.',
 'ipc': None,
 'name': 'ferry',
 'problems': [('ferry/domain.pddl', 'ferry/p-10locs-5cars.pddl'),
              ('ferry/domain.pddl', 'ferry/p-10locs-6cars.pddl'),
              ('ferry/domain.pddl', 'ferry/p-10locs-7cars.pddl'),
              ('ferry/domain.pddl', 'ferry/p-10locs-8cars.pddl'),
              ('ferry/domain.pddl', 'ferry/p-10locs-9cars.pddl'),
              ('ferry/domain.pddl', 'ferry/p-11locs-5cars.pddl'),
              ('ferry/domain.pddl', 'ferry/p-11locs-6cars.pddl'),
              ('ferry/domain.pddl', 'ferry/p-11locs-7cars.pddl'),
              ('ferry/domain.pddl', 'ferry/p-11locs-8cars.pddl'),
              ('ferry/domain.pddl', 'ferry/p-11locs-9cars.pddl'),
              ('ferry/domain.pddl', 'ferry/p-12locs-5cars.pddl'),
              ('ferry/domain.pddl', 'ferry/p-12locs-6cars.pddl'),
              ('ferry/domain.pddl', 'ferry/p-12locs-7cars.pddl'),
              ('ferry/domain.pddl', 'ferry/p-12locs-8cars.pddl'),
              ('ferry/domain.pddl', 'ferry/p-12locs-9cars.pddl'),
              ('ferry/domain.pddl', 'ferry/p-13locs-5cars.pddl'),
              ('ferry/domain.pddl', 'ferry/p-13locs-6cars.pddl'),
              ('ferry/domain.pddl', 'ferry/p-13locs-7cars.pddl'),
              ('ferry/domain.pddl', 'ferry/p-13locs-8cars.pddl'),
              ('ferry/domain.pddl', 'ferry/p-13locs-9cars.pddl'),
              ('ferry/domain.pddl', 'ferry/p-14locs-5cars.pddl'),
              ('ferry/domain.pddl', 'ferry/p-14locs-6cars.pddl'),
              ('ferry/domain.pddl', 'ferry/p-14locs-7cars.pddl'),
              ('ferry/domain.pddl', 'ferry/p-14locs-8cars.pddl'),
              ('ferry/domain.pddl', 'ferry/p-14locs-9cars.pddl'),
              ('ferry/domain.pddl', 'ferry/p-15locs-5cars.pddl'),
              ('ferry/domain.pddl', 'ferry/p-15locs-6cars.pddl'),
              ('ferry/domain.pddl', 'ferry/p-15locs-7cars.pddl'),
              ('ferry/domain.pddl', 'ferry/p-15locs-8cars.pddl'),
              ('ferry/domain.pddl', 'ferry/p-15locs-9cars.pddl')]}
]