domains = [
{'description': 'This domain is original from the learning part of IPC2008. The domain involves parking cars on a street with N curb locations, and where cars can be double-parked but not triple-parked. The goal is to find a plan to move from one configuration of parked cars to another configuration, by driving cars from one curb location to another. The problems in the competition contain 2*(N-1) cars, which allows one free curb space and guarantees solvability.',
 'ipc': '2014',
 'name': 'parking',
 'problems': [('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_12_7-01.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_12_7-02.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_12_7-03.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_12_7-04.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_14_8-01.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_14_8-02.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_14_8-03.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_14_8-04.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_16_9-01.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_16_9-02.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_16_9-03.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_16_9-04.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_18_10-01.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_18_10-02.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_18_10-03.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_18_10-04.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_20_11-01.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_20_11-02.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_20_11-03.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_20_11-04.pddl')]}
]