domains = [
{'description': '',
 'ipc': '2014',
 'name': 'parking',
 'problems': [('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_12_7-01.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_12_7-02.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_12_7-03.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_12_7-04.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_14_8-01.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_14_8-02.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_14_8-03.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_14_8-04.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_16_9-01.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_16_9-02.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_16_9-03.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_16_9-04.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_18_10-01.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_18_10-02.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_18_10-03.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_18_10-04.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_20_11-01.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_20_11-02.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_20_11-03.pddl'),
              ('parking-opt14-strips/domain.pddl',
               'parking-opt14-strips/p_20_11-04.pddl')]}
]