domains = [
{'description': '',
 'ipc': '2014',
 'name': 'citycar',
 'problems': [('citycar-sat14-adl/domain.pddl',
               'citycar-sat14-adl/p3-2-2-0-1.pddl'),
              ('citycar-sat14-adl/domain.pddl',
               'citycar-sat14-adl/p3-3-2-0-1.pddl'),
              ('citycar-sat14-adl/domain.pddl',
               'citycar-sat14-adl/p3-4-2-0-1.pddl'),
              ('citycar-sat14-adl/domain.pddl',
               'citycar-sat14-adl/p3-5-2-0-1.pddl'),
              ('citycar-sat14-adl/domain.pddl',
               'citycar-sat14-adl/p3-5-2-0-2.pddl'),
              ('citycar-sat14-adl/domain.pddl',
               'citycar-sat14-adl/p4-2-2-0-1.pddl'),
              ('citycar-sat14-adl/domain.pddl',
               'citycar-sat14-adl/p4-2-3-0-1.pddl'),
              ('citycar-sat14-adl/domain.pddl',
               'citycar-sat14-adl/p4-2-3-0-2.pddl'),
              ('citycar-sat14-adl/domain.pddl',
               'citycar-sat14-adl/p4-3-2-0-1.pddl'),
              ('citycar-sat14-adl/domain.pddl',
               'citycar-sat14-adl/p4-3-2-0-2.pddl'),
              ('citycar-sat14-adl/domain.pddl',
               'citycar-sat14-adl/p4-3-3-0-1.pddl'),
              ('citycar-sat14-adl/domain.pddl',
               'citycar-sat14-adl/p4-3-3-0-2.pddl'),
              ('citycar-sat14-adl/domain.pddl',
               'citycar-sat14-adl/p4-4-2-0-1.pddl'),
              ('citycar-sat14-adl/domain.pddl',
               'citycar-sat14-adl/p4-4-2-0-2.pddl'),
              ('citycar-sat14-adl/domain.pddl',
               'citycar-sat14-adl/p4-4-3-0-1.pddl'),
              ('citycar-sat14-adl/domain.pddl',
               'citycar-sat14-adl/p4-4-3-0-2.pddl'),
              ('citycar-sat14-adl/domain.pddl',
               'citycar-sat14-adl/p4-5-2-0-1.pddl'),
              ('citycar-sat14-adl/domain.pddl',
               'citycar-sat14-adl/p4-5-2-0-2.pddl'),
              ('citycar-sat14-adl/domain.pddl',
               'citycar-sat14-adl/p4-5-3-0-1.pddl'),
              ('citycar-sat14-adl/domain.pddl',
               'citycar-sat14-adl/p4-5-3-0-2.pddl')]}
]