domains = [{'description': '(opt18) Spider:\n\nIn the solitaire game "Spider solitaire" stacks of cards of the same suit can be moved\nfrom a pile to another and cards can be placed on a card with a value that is higher by\none (of any suit). In contrast to the real game, all cards are face-up from the start, to\nremove uncertainty. Movement of stacks of cards could be easily modeled with derived\npredicates but here we use auxiliary 0-cost actions that update the state.',
 'ipc': '2018',
 'name': 'spider',
 'problems': [('spider-opt18/domain.pddl', 'spider-opt18/p11.pddl'),
              ('spider-opt18/domain.pddl', 'spider-opt18/p07.pddl'),
              ('spider-opt18/domain.pddl', 'spider-opt18/p06.pddl'),
              ('spider-opt18/domain.pddl', 'spider-opt18/p10.pddl'),
              ('spider-opt18/domain.pddl', 'spider-opt18/p17.pddl'),
              ('spider-opt18/domain.pddl', 'spider-opt18/p01.pddl'),
              ('spider-opt18/domain.pddl', 'spider-opt18/p16.pddl'),
              ('spider-opt18/domain.pddl', 'spider-opt18/p20.pddl'),
              ('spider-opt18/domain.pddl', 'spider-opt18/p19.pddl'),
              ('spider-opt18/domain.pddl', 'spider-opt18/p03.pddl'),
              ('spider-opt18/domain.pddl', 'spider-opt18/p15.pddl'),
              ('spider-opt18/domain.pddl', 'spider-opt18/p14.pddl'),
              ('spider-opt18/domain.pddl', 'spider-opt18/p02.pddl'),
              ('spider-opt18/domain.pddl', 'spider-opt18/p18.pddl'),
              ('spider-opt18/domain.pddl', 'spider-opt18/p05.pddl'),
              ('spider-opt18/domain.pddl', 'spider-opt18/p13.pddl'),
              ('spider-opt18/domain.pddl', 'spider-opt18/p09.pddl'),
              ('spider-opt18/domain.pddl', 'spider-opt18/p08.pddl'),
              ('spider-opt18/domain.pddl', 'spider-opt18/p12.pddl'),
              ('spider-opt18/domain.pddl', 'spider-opt18/p04.pddl')]}]
