domains = [
{'description': '',
 'ipc': '2011',
 'name': 'parking',
 'problems': [('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile08-031.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile08-032.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile09-033.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile09-034.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile09-035.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile09-036.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile10-037.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile10-038.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile10-039.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile10-040.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile11-041.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile11-042.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile11-043.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile11-044.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile12-045.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile12-046.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile12-047.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile12-048.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile13-049.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile13-050.pddl')]}
]