domains = [
{'description': 'This domain is original from the learning part of IPC2008. The domain involves parking cars on a street with N curb locations, and where cars can be double-parked but not triple-parked. The goal is to find a plan to move from one configuration of parked cars to another configuration, by driving cars from one curb location to another. The problems in the competition contain 2*(N-1) cars, which allows one free curb space and guarantees solvability.',
 'ipc': '2011',
 'name': 'parking',
 'problems': [('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile08-031.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile08-032.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile09-033.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile09-034.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile09-035.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile09-036.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile10-037.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile10-038.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile10-039.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile10-040.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile11-041.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile11-042.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile11-043.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile11-044.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile12-045.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile12-046.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile12-047.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile12-048.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile13-049.pddl'),
              ('parking-sat11-strips/domain.pddl',
               'parking-sat11-strips/pfile13-050.pddl')]}
]