domains = [
{'description': '',
 'ipc': '2014',
 'name': 'citycar',
 'problems': [('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p2-2-2-1-2.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p2-2-2-2-1.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p2-2-3-1-2.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p2-2-3-2-1.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p2-2-3-2-2.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p2-2-4-1-2.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p2-2-4-2-1.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p2-2-5-2-2.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p2-2-6-1-1.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p2-2-6-2-2.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p2-3-2-3-1.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p2-3-3-3-1.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p2-3-4-3-1.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p2-3-6-3-2.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p3-3-2-2-1.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p3-3-2-2-2.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p3-3-2-3-1.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p3-3-2-3-2.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p3-3-3-3-1.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p3-3-3-3-2.pddl')]}
]