domains = [
{'description': 'This model aims to simulate the impact of road building / demolition on traffic flows. A city is represented as an acyclic graph, in which each node is a junction and edges are "potential" roads. Some cars start from different positions and have to reach their final destination as soon as possible. The agent has a finite number of roads available, which can be built for connecting two junctions and allowing a car to move between them. Roads can also be removed, and placed somewhere else, if needed. In order to place roads or to move cars, the destination junction must be clear, i.e., no cars should be in there.',
 'ipc': '2014',
 'name': 'citycar',
 'problems': [('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p2-2-2-1-2.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p2-2-2-2-1.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p2-2-3-1-2.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p2-2-3-2-1.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p2-2-3-2-2.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p2-2-4-1-2.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p2-2-4-2-1.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p2-2-5-2-2.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p2-2-6-1-1.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p2-2-6-2-2.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p2-3-2-3-1.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p2-3-3-3-1.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p2-3-4-3-1.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p2-3-6-3-2.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p3-3-2-2-1.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p3-3-2-2-2.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p3-3-2-3-1.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p3-3-2-3-2.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p3-3-3-3-1.pddl'),
              ('citycar-opt14-adl/domain.pddl',
               'citycar-opt14-adl/p3-3-3-3-2.pddl')]}
]