domains = [
{'description': 'A set of robots use different colors to paint patterns in floor tiles. The robots can move around the floor tiles in four directions (up, down, left and right). Robots paint with one color at a time, but can change their spray guns to any available color. However, robots can only paint the tile that is in front (up) and behind (down) them, and once a tile has been painted no robot can stand on it. For the IPC set, robots need to paint a grid with black and white, where the cell color is alternated always. This particular configuration makes the domain hard because robots should only paint tiles in front of them, since painting tiles behind make the search to reach a dead-end.',
 'ipc': '2011',
 'name': 'floortile',
 'problems': [('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p01-001.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p01-002.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p02-003.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p02-004.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p03-005.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p03-006.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p04-007.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p04-008.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p05-009.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p05-010.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p06-011.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p06-012.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p07-013.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p07-014.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p08-015.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p08-016.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p09-017.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p09-018.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p10-019.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p10-020.pddl')]}
]