domains = [
{'description': '',
 'ipc': '2011',
 'name': 'floortile',
 'problems': [('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p01-001.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p01-002.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p02-003.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p02-004.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p03-005.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p03-006.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p04-007.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p04-008.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p05-009.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p05-010.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p06-011.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p06-012.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p07-013.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p07-014.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p08-015.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p08-016.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p09-017.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p09-018.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p10-019.pddl'),
              ('floortile-sat11-strips/domain.pddl',
               'floortile-sat11-strips/seq-p10-020.pddl')]}
]