domains = [
{'description': 'This domain models the operation of the multi-engine printer, for which one prototype is developed at the Palo Alto Research Center (PARC). This type of printer can handle multiple print jobs simultaneously. Multiple sheets, belonging to the same job or different jobs, can be printed simultaneously using multiple Image Marking Engines (IME). Each IME can either be color, which can print both color and black&white images, or mono, which can only print black&white image. Each sheet needs to go through multiple printer components such as feeder, transporter, IME, inverter, finisher and need to arrive at the finisher in order. Thus, sheet (n+1) needs to be stacked in the same finisher with sheet n of the same job, but needs to arrive at the finisher right after sheet n (no other sheet stacked in between those two consecutive sheets). Given that the IMEs are heterogeneous (mixture of color and mono) and can run at different speeds, optimizing the operation of this printer for a mixture of print jobs, each of them is an arbitrary mixture of color/b&w pages that are either simplex (one-sided print) or duplex (two-sided print) is a hard problem.',
 'ipc': '2011',
 'name': 'parcprinter',
 'problems': [('parcprinter-sat11-strips/p01-domain.pddl',
               'parcprinter-sat11-strips/p01.pddl'),
              ('parcprinter-sat11-strips/p02-domain.pddl',
               'parcprinter-sat11-strips/p02.pddl'),
              ('parcprinter-sat11-strips/p03-domain.pddl',
               'parcprinter-sat11-strips/p03.pddl'),
              ('parcprinter-sat11-strips/p04-domain.pddl',
               'parcprinter-sat11-strips/p04.pddl'),
              ('parcprinter-sat11-strips/p05-domain.pddl',
               'parcprinter-sat11-strips/p05.pddl'),
              ('parcprinter-sat11-strips/p06-domain.pddl',
               'parcprinter-sat11-strips/p06.pddl'),
              ('parcprinter-sat11-strips/p07-domain.pddl',
               'parcprinter-sat11-strips/p07.pddl'),
              ('parcprinter-sat11-strips/p08-domain.pddl',
               'parcprinter-sat11-strips/p08.pddl'),
              ('parcprinter-sat11-strips/p09-domain.pddl',
               'parcprinter-sat11-strips/p09.pddl'),
              ('parcprinter-sat11-strips/p10-domain.pddl',
               'parcprinter-sat11-strips/p10.pddl'),
              ('parcprinter-sat11-strips/p11-domain.pddl',
               'parcprinter-sat11-strips/p11.pddl'),
              ('parcprinter-sat11-strips/p12-domain.pddl',
               'parcprinter-sat11-strips/p12.pddl'),
              ('parcprinter-sat11-strips/p13-domain.pddl',
               'parcprinter-sat11-strips/p13.pddl'),
              ('parcprinter-sat11-strips/p14-domain.pddl',
               'parcprinter-sat11-strips/p14.pddl'),
              ('parcprinter-sat11-strips/p15-domain.pddl',
               'parcprinter-sat11-strips/p15.pddl'),
              ('parcprinter-sat11-strips/p16-domain.pddl',
               'parcprinter-sat11-strips/p16.pddl'),
              ('parcprinter-sat11-strips/p17-domain.pddl',
               'parcprinter-sat11-strips/p17.pddl'),
              ('parcprinter-sat11-strips/p18-domain.pddl',
               'parcprinter-sat11-strips/p18.pddl'),
              ('parcprinter-sat11-strips/p19-domain.pddl',
               'parcprinter-sat11-strips/p19.pddl'),
              ('parcprinter-sat11-strips/p20-domain.pddl',
               'parcprinter-sat11-strips/p20.pddl')]}
]