domains = [{'description': '(opt18) Name: Petri-net Alignment\nsubmitted by: Massimiliano de Leoni and Andrea Marrella\n\nDescription: This domain models the problem of conformance checking on Petri Nets. Given\nan input Petri Net and an event log, it determines whether the petri net models the event.\nIn the original work, the authors introduced noise by permuting actions in the Petri\nNet. For the IPC we also introduced noise by mixing several traces together.\n\nPublication: Aligning Real Process Executions and Prescriptive Process Models through\nAutomated Planning. Massimiliano de Leoni and Andrea Marrella.  Expert Systems with\nApplications, 2017.\n\n\nInteresting properties: 0-cost actions, pre-grounded in PDDL',
 'ipc': '2018',
 'name': 'petri-net-alignment',
 'problems': [('petri-net-alignment-opt18/domain-p11.pddl',
               'petri-net-alignment-opt18/p11.pddl'),
              ('petri-net-alignment-opt18/domain-p07.pddl',
               'petri-net-alignment-opt18/p07.pddl'),
              ('petri-net-alignment-opt18/domain-p06.pddl',
               'petri-net-alignment-opt18/p06.pddl'),
              ('petri-net-alignment-opt18/domain-p10.pddl',
               'petri-net-alignment-opt18/p10.pddl'),
              ('petri-net-alignment-opt18/domain-p17.pddl',
               'petri-net-alignment-opt18/p17.pddl'),
              ('petri-net-alignment-opt18/domain-p01.pddl',
               'petri-net-alignment-opt18/p01.pddl'),
              ('petri-net-alignment-opt18/domain-p16.pddl',
               'petri-net-alignment-opt18/p16.pddl'),
              ('petri-net-alignment-opt18/domain-p20.pddl',
               'petri-net-alignment-opt18/p20.pddl'),
              ('petri-net-alignment-opt18/domain-p19.pddl',
               'petri-net-alignment-opt18/p19.pddl'),
              ('petri-net-alignment-opt18/domain-p03.pddl',
               'petri-net-alignment-opt18/p03.pddl'),
              ('petri-net-alignment-opt18/domain-p15.pddl',
               'petri-net-alignment-opt18/p15.pddl'),
              ('petri-net-alignment-opt18/domain-p14.pddl',
               'petri-net-alignment-opt18/p14.pddl'),
              ('petri-net-alignment-opt18/domain-p02.pddl',
               'petri-net-alignment-opt18/p02.pddl'),
              ('petri-net-alignment-opt18/domain-p18.pddl',
               'petri-net-alignment-opt18/p18.pddl'),
              ('petri-net-alignment-opt18/domain-p05.pddl',
               'petri-net-alignment-opt18/p05.pddl'),
              ('petri-net-alignment-opt18/domain-p13.pddl',
               'petri-net-alignment-opt18/p13.pddl'),
              ('petri-net-alignment-opt18/domain-p09.pddl',
               'petri-net-alignment-opt18/p09.pddl'),
              ('petri-net-alignment-opt18/domain-p08.pddl',
               'petri-net-alignment-opt18/p08.pddl'),
              ('petri-net-alignment-opt18/domain-p12.pddl',
               'petri-net-alignment-opt18/p12.pddl'),
              ('petri-net-alignment-opt18/domain-p04.pddl',
               'petri-net-alignment-opt18/p04.pddl')]}]
