domains = [
{'description': 'The openstacks domain is based on the "minimum maximum simultaneous open stacks" combinatorial optimization problem, which can be stated as follows: A manufacturer has a number of orders, each for a combination of different products, and can only make one product at a time. The total required quantity of each product is made at the same time (because changing from making one product to making another requires a production stop). From the time that the first product included in an order is made to the time that all products included in the order have been made, the order is said to be "open" and during this time it requires a "stack" (a temporary storage space). The problem is to order the making of the different products so that the maximum number of stacks that are in use simultaneously, or equivalently the number of orders that are in simultaneous production, is minimized (because each stack takes up space in the production area).',
 'ipc': '2011',
 'name': 'openstacks',
 'problems': [('openstacks-opt11-strips/p01-domain.pddl',
               'openstacks-opt11-strips/p01.pddl'),
              ('openstacks-opt11-strips/p02-domain.pddl',
               'openstacks-opt11-strips/p02.pddl'),
              ('openstacks-opt11-strips/p03-domain.pddl',
               'openstacks-opt11-strips/p03.pddl'),
              ('openstacks-opt11-strips/p04-domain.pddl',
               'openstacks-opt11-strips/p04.pddl'),
              ('openstacks-opt11-strips/p05-domain.pddl',
               'openstacks-opt11-strips/p05.pddl'),
              ('openstacks-opt11-strips/p06-domain.pddl',
               'openstacks-opt11-strips/p06.pddl'),
              ('openstacks-opt11-strips/p07-domain.pddl',
               'openstacks-opt11-strips/p07.pddl'),
              ('openstacks-opt11-strips/p08-domain.pddl',
               'openstacks-opt11-strips/p08.pddl'),
              ('openstacks-opt11-strips/p09-domain.pddl',
               'openstacks-opt11-strips/p09.pddl'),
              ('openstacks-opt11-strips/p10-domain.pddl',
               'openstacks-opt11-strips/p10.pddl'),
              ('openstacks-opt11-strips/p11-domain.pddl',
               'openstacks-opt11-strips/p11.pddl'),
              ('openstacks-opt11-strips/p12-domain.pddl',
               'openstacks-opt11-strips/p12.pddl'),
              ('openstacks-opt11-strips/p13-domain.pddl',
               'openstacks-opt11-strips/p13.pddl'),
              ('openstacks-opt11-strips/p14-domain.pddl',
               'openstacks-opt11-strips/p14.pddl'),
              ('openstacks-opt11-strips/p15-domain.pddl',
               'openstacks-opt11-strips/p15.pddl'),
              ('openstacks-opt11-strips/p16-domain.pddl',
               'openstacks-opt11-strips/p16.pddl'),
              ('openstacks-opt11-strips/p17-domain.pddl',
               'openstacks-opt11-strips/p17.pddl'),
              ('openstacks-opt11-strips/p18-domain.pddl',
               'openstacks-opt11-strips/p18.pddl'),
              ('openstacks-opt11-strips/p19-domain.pddl',
               'openstacks-opt11-strips/p19.pddl'),
              ('openstacks-opt11-strips/p20-domain.pddl',
               'openstacks-opt11-strips/p20.pddl')]}
]