domains = [{'description': '(sat18) Snake:\n\nIn the game Snake, a snake moves around a grid. There is a number of apples in some grid\ncells and when the snake moves into one of these locations, it eats the apple, extends its\nlength by one, and a new apple may spawn. In this version uncertainty has been removed by\ndeciding the location where apples will spawn in advance. Except for the end of the game,\nthere will be more than one apple on the board at the same time.\n\nInteresting properties: dead-end states',
 'ipc': '2018',
 'name': 'snake',
 'problems': [('snake-sat18/domain.pddl', 'snake-sat18/p11.pddl'),
              ('snake-sat18/domain.pddl', 'snake-sat18/p07.pddl'),
              ('snake-sat18/domain.pddl', 'snake-sat18/p06.pddl'),
              ('snake-sat18/domain.pddl', 'snake-sat18/p10.pddl'),
              ('snake-sat18/domain.pddl', 'snake-sat18/p17.pddl'),
              ('snake-sat18/domain.pddl', 'snake-sat18/p01.pddl'),
              ('snake-sat18/domain.pddl', 'snake-sat18/p16.pddl'),
              ('snake-sat18/domain.pddl', 'snake-sat18/p20.pddl'),
              ('snake-sat18/domain.pddl', 'snake-sat18/p19.pddl'),
              ('snake-sat18/domain.pddl', 'snake-sat18/p03.pddl'),
              ('snake-sat18/domain.pddl', 'snake-sat18/p15.pddl'),
              ('snake-sat18/domain.pddl', 'snake-sat18/p14.pddl'),
              ('snake-sat18/domain.pddl', 'snake-sat18/p02.pddl'),
              ('snake-sat18/domain.pddl', 'snake-sat18/p18.pddl'),
              ('snake-sat18/domain.pddl', 'snake-sat18/p05.pddl'),
              ('snake-sat18/domain.pddl', 'snake-sat18/p13.pddl'),
              ('snake-sat18/domain.pddl', 'snake-sat18/p09.pddl'),
              ('snake-sat18/domain.pddl', 'snake-sat18/p08.pddl'),
              ('snake-sat18/domain.pddl', 'snake-sat18/p12.pddl'),
              ('snake-sat18/domain.pddl', 'snake-sat18/p04.pddl')]}]
