domains = [
{'description': 'An agent in the middle of a square grid nxn must visit all the cells in the grid. Solving optimally the delete relaxation h+ gives the exact goal distance as long as there exists a hamiltonian path visiting every cell. Recall that in a 1xn grid, no hamiltonian path exists.',
 'ipc': '2011',
 'name': 'visitall',
 'problems': [('visitall-sat11-strips/domain.pddl',
               'visitall-sat11-strips/problem12.pddl'),
              ('visitall-sat11-strips/domain.pddl',
               'visitall-sat11-strips/problem14.pddl'),
              ('visitall-sat11-strips/domain.pddl',
               'visitall-sat11-strips/problem16.pddl'),
              ('visitall-sat11-strips/domain.pddl',
               'visitall-sat11-strips/problem18.pddl'),
              ('visitall-sat11-strips/domain.pddl',
               'visitall-sat11-strips/problem20.pddl'),
              ('visitall-sat11-strips/domain.pddl',
               'visitall-sat11-strips/problem22.pddl'),
              ('visitall-sat11-strips/domain.pddl',
               'visitall-sat11-strips/problem24.pddl'),
              ('visitall-sat11-strips/domain.pddl',
               'visitall-sat11-strips/problem26.pddl'),
              ('visitall-sat11-strips/domain.pddl',
               'visitall-sat11-strips/problem28.pddl'),
              ('visitall-sat11-strips/domain.pddl',
               'visitall-sat11-strips/problem30.pddl'),
              ('visitall-sat11-strips/domain.pddl',
               'visitall-sat11-strips/problem32.pddl'),
              ('visitall-sat11-strips/domain.pddl',
               'visitall-sat11-strips/problem34.pddl'),
              ('visitall-sat11-strips/domain.pddl',
               'visitall-sat11-strips/problem36.pddl'),
              ('visitall-sat11-strips/domain.pddl',
               'visitall-sat11-strips/problem38.pddl'),
              ('visitall-sat11-strips/domain.pddl',
               'visitall-sat11-strips/problem40.pddl'),
              ('visitall-sat11-strips/domain.pddl',
               'visitall-sat11-strips/problem42.pddl'),
              ('visitall-sat11-strips/domain.pddl',
               'visitall-sat11-strips/problem44.pddl'),
              ('visitall-sat11-strips/domain.pddl',
               'visitall-sat11-strips/problem46.pddl'),
              ('visitall-sat11-strips/domain.pddl',
               'visitall-sat11-strips/problem48.pddl'),
              ('visitall-sat11-strips/domain.pddl',
               'visitall-sat11-strips/problem50.pddl')]}
]