domains = [
{'description': '',
 'ipc': '2014',
 'name': 'hiking',
 'problems': [('hiking-opt14-strips/domain.pddl',
               'hiking-opt14-strips/ptesting-1-2-3.pddl'),
              ('hiking-opt14-strips/domain.pddl',
               'hiking-opt14-strips/ptesting-1-2-4.pddl'),
              ('hiking-opt14-strips/domain.pddl',
               'hiking-opt14-strips/ptesting-1-2-5.pddl'),
              ('hiking-opt14-strips/domain.pddl',
               'hiking-opt14-strips/ptesting-1-2-7.pddl'),
              ('hiking-opt14-strips/domain.pddl',
               'hiking-opt14-strips/ptesting-1-2-8.pddl'),
              ('hiking-opt14-strips/domain.pddl',
               'hiking-opt14-strips/ptesting-2-2-3.pddl'),
              ('hiking-opt14-strips/domain.pddl',
               'hiking-opt14-strips/ptesting-2-2-4.pddl'),
              ('hiking-opt14-strips/domain.pddl',
               'hiking-opt14-strips/ptesting-2-2-5.pddl'),
              ('hiking-opt14-strips/domain.pddl',
               'hiking-opt14-strips/ptesting-2-2-6.pddl'),
              ('hiking-opt14-strips/domain.pddl',
               'hiking-opt14-strips/ptesting-2-2-7.pddl'),
              ('hiking-opt14-strips/domain.pddl',
               'hiking-opt14-strips/ptesting-2-2-8.pddl'),
              ('hiking-opt14-strips/domain.pddl',
               'hiking-opt14-strips/ptesting-2-3-4.pddl'),
              ('hiking-opt14-strips/domain.pddl',
               'hiking-opt14-strips/ptesting-2-3-5.pddl'),
              ('hiking-opt14-strips/domain.pddl',
               'hiking-opt14-strips/ptesting-2-3-6.pddl'),
              ('hiking-opt14-strips/domain.pddl',
               'hiking-opt14-strips/ptesting-2-3-7.pddl'),
              ('hiking-opt14-strips/domain.pddl',
               'hiking-opt14-strips/ptesting-2-4-3.pddl'),
              ('hiking-opt14-strips/domain.pddl',
               'hiking-opt14-strips/ptesting-2-4-4.pddl'),
              ('hiking-opt14-strips/domain.pddl',
               'hiking-opt14-strips/ptesting-2-4-5.pddl'),
              ('hiking-opt14-strips/domain.pddl',
               'hiking-opt14-strips/ptesting-2-4-6.pddl'),
              ('hiking-opt14-strips/domain.pddl',
               'hiking-opt14-strips/ptesting-2-4-7.pddl')]}
]