domains = [{'description': '(opt18) Organic Synthesis:\nsubmitted by Hadi Qovaizi, Arman Masoumi, Anne Johnson, Russell Viirre, Andrew McWilliams, and Mikhail Soutchanski, Ryerson University\n\nDescription: Computer Assisted Organic Synthesis Planning. Description taken from the\npaper: The organic synthesis problem is a common chemistry problem that requires finding a\nsequence of reactions that produces the target molecule from given initial molecules. The\ninstances are based on real chemistry exam questions that can vary in difficulty from\nrelatively simple problems that can be solved in 2 or 3 steps to more complex problems\nthat may require finding a sequence of 10-12 reactions.\n\nIf you would like to write a paper related to this research, please cite the following\npublications:\n        Arman Masoumi, Megan Antoniazzi and Mikhail Soutchanski\n        Modeling Organic Chemistry and Planning Organic Synthesis.\n        Proceedings of the 1st Global Conference on Artificial Intelligence\n        (GCAI 2015): Tbilisi, Georgia, October 16-19, 2015. This paper was\n        published in the EasyChair Proceedings in Computing:\n        Volume 36, pages 176-195, 2015 (issn 2040-557X).\n\n        Rami Matloob and Mikhail Soutchanski\n        Exploring Organic Synthesis With State-of-the-Art Planners.\n        Proceedings of Scheduling and Planning Applications woRKshop (SPARK),\n        pages 52-61, held on June 13, 2016 in conjunction with the 26th\n        Intern. Conference on Automated Planning and Scheduling, London, UK.',
 'ipc': '2018',
 'name': 'organic-synthesis-split',
 'problems': [('organic-synthesis-split-opt18/domain-p11.pddl',
               'organic-synthesis-split-opt18/p11.pddl'),
              ('organic-synthesis-split-opt18/domain-p07.pddl',
               'organic-synthesis-split-opt18/p07.pddl'),
              ('organic-synthesis-split-opt18/domain-p06.pddl',
               'organic-synthesis-split-opt18/p06.pddl'),
              ('organic-synthesis-split-opt18/domain-p10.pddl',
               'organic-synthesis-split-opt18/p10.pddl'),
              ('organic-synthesis-split-opt18/domain-p17.pddl',
               'organic-synthesis-split-opt18/p17.pddl'),
              ('organic-synthesis-split-opt18/domain-p01.pddl',
               'organic-synthesis-split-opt18/p01.pddl'),
              ('organic-synthesis-split-opt18/domain-p16.pddl',
               'organic-synthesis-split-opt18/p16.pddl'),
              ('organic-synthesis-split-opt18/domain-p20.pddl',
               'organic-synthesis-split-opt18/p20.pddl'),
              ('organic-synthesis-split-opt18/domain-p19.pddl',
               'organic-synthesis-split-opt18/p19.pddl'),
              ('organic-synthesis-split-opt18/domain-p03.pddl',
               'organic-synthesis-split-opt18/p03.pddl'),
              ('organic-synthesis-split-opt18/domain-p15.pddl',
               'organic-synthesis-split-opt18/p15.pddl'),
              ('organic-synthesis-split-opt18/domain-p14.pddl',
               'organic-synthesis-split-opt18/p14.pddl'),
              ('organic-synthesis-split-opt18/domain-p02.pddl',
               'organic-synthesis-split-opt18/p02.pddl'),
              ('organic-synthesis-split-opt18/domain-p18.pddl',
               'organic-synthesis-split-opt18/p18.pddl'),
              ('organic-synthesis-split-opt18/domain-p05.pddl',
               'organic-synthesis-split-opt18/p05.pddl'),
              ('organic-synthesis-split-opt18/domain-p13.pddl',
               'organic-synthesis-split-opt18/p13.pddl'),
              ('organic-synthesis-split-opt18/domain-p09.pddl',
               'organic-synthesis-split-opt18/p09.pddl'),
              ('organic-synthesis-split-opt18/domain-p08.pddl',
               'organic-synthesis-split-opt18/p08.pddl'),
              ('organic-synthesis-split-opt18/domain-p12.pddl',
               'organic-synthesis-split-opt18/p12.pddl'),
              ('organic-synthesis-split-opt18/domain-p04.pddl',
               'organic-synthesis-split-opt18/p04.pddl')]}]
