domains = [
{'description': 'This domain is original from the learning part of IPC2008. The domain represents a well-known solitaire card game.',
 'ipc': '2014',
 'name': 'thoughtful',
 'problems': [('thoughtful-sat14-strips/domain.pddl',
               'thoughtful-sat14-strips/bootstrap-typed-01.pddl'),
              ('thoughtful-sat14-strips/domain.pddl',
               'thoughtful-sat14-strips/bootstrap-typed-02.pddl'),
              ('thoughtful-sat14-strips/domain.pddl',
               'thoughtful-sat14-strips/bootstrap-typed-03.pddl'),
              ('thoughtful-sat14-strips/domain.pddl',
               'thoughtful-sat14-strips/bootstrap-typed-04.pddl'),
              ('thoughtful-sat14-strips/domain.pddl',
               'thoughtful-sat14-strips/bootstrap-typed-05.pddl'),
              ('thoughtful-sat14-strips/domain.pddl',
               'thoughtful-sat14-strips/p11_6_53-typed.pddl'),
              ('thoughtful-sat14-strips/domain.pddl',
               'thoughtful-sat14-strips/p11_6_59-typed.pddl'),
              ('thoughtful-sat14-strips/domain.pddl',
               'thoughtful-sat14-strips/p11_6_62-typed.pddl'),
              ('thoughtful-sat14-strips/domain.pddl',
               'thoughtful-sat14-strips/p13_7_78-typed.pddl'),
              ('thoughtful-sat14-strips/domain.pddl',
               'thoughtful-sat14-strips/p13_7_79-typed.pddl'),
              ('thoughtful-sat14-strips/domain.pddl',
               'thoughtful-sat14-strips/p13_7_86-typed.pddl'),
              ('thoughtful-sat14-strips/domain.pddl',
               'thoughtful-sat14-strips/target-typed-20.pddl'),
              ('thoughtful-sat14-strips/domain.pddl',
               'thoughtful-sat14-strips/target-typed-21.pddl'),
              ('thoughtful-sat14-strips/domain.pddl',
               'thoughtful-sat14-strips/target-typed-22.pddl'),
              ('thoughtful-sat14-strips/domain.pddl',
               'thoughtful-sat14-strips/target-typed-23.pddl'),
              ('thoughtful-sat14-strips/domain.pddl',
               'thoughtful-sat14-strips/target-typed-24.pddl'),
              ('thoughtful-sat14-strips/domain.pddl',
               'thoughtful-sat14-strips/target-typed-25.pddl'),
              ('thoughtful-sat14-strips/domain.pddl',
               'thoughtful-sat14-strips/target-typed-26.pddl'),
              ('thoughtful-sat14-strips/domain.pddl',
               'thoughtful-sat14-strips/target-typed-27.pddl'),
              ('thoughtful-sat14-strips/domain.pddl',
               'thoughtful-sat14-strips/target-typed-28.pddl')]}
]