domains = [
{'description': 'This domain involves driving trucks around delivering packages between locations. The complication is that the trucks require drivers who must walk between trucks in order to drive them. The paths for walking and the roads for driving form different maps on the locations.',
 'ipc': '2002',
 'name': 'driverlog',
 'problems': [('driverlog/domain.pddl', 'driverlog/pfile1.pddl'),
              ('driverlog/domain.pddl', 'driverlog/pfile10.pddl'),
              ('driverlog/domain.pddl', 'driverlog/pfile11.pddl'),
              ('driverlog/domain.pddl', 'driverlog/pfile12.pddl'),
              ('driverlog/domain.pddl', 'driverlog/pfile13.pddl'),
              ('driverlog/domain.pddl', 'driverlog/pfile14.pddl'),
              ('driverlog/domain.pddl', 'driverlog/pfile15.pddl'),
              ('driverlog/domain.pddl', 'driverlog/pfile16.pddl'),
              ('driverlog/domain.pddl', 'driverlog/pfile17.pddl'),
              ('driverlog/domain.pddl', 'driverlog/pfile18.pddl'),
              ('driverlog/domain.pddl', 'driverlog/pfile19.pddl'),
              ('driverlog/domain.pddl', 'driverlog/pfile2.pddl'),
              ('driverlog/domain.pddl', 'driverlog/pfile20.pddl'),
              ('driverlog/domain.pddl', 'driverlog/pfile3.pddl'),
              ('driverlog/domain.pddl', 'driverlog/pfile4.pddl'),
              ('driverlog/domain.pddl', 'driverlog/pfile5.pddl'),
              ('driverlog/domain.pddl', 'driverlog/pfile6.pddl'),
              ('driverlog/domain.pddl', 'driverlog/pfile7.pddl'),
              ('driverlog/domain.pddl', 'driverlog/pfile8.pddl'),
              ('driverlog/domain.pddl', 'driverlog/pfile9.pddl')]}
]