domains = [
{'description': '',
 'ipc': '2011',
 'name': 'visitall',
 'problems': [('visitall-opt11-strips/domain.pddl',
               'visitall-opt11-strips/problem02-full.pddl'),
              ('visitall-opt11-strips/domain.pddl',
               'visitall-opt11-strips/problem02-half.pddl'),
              ('visitall-opt11-strips/domain.pddl',
               'visitall-opt11-strips/problem03-full.pddl'),
              ('visitall-opt11-strips/domain.pddl',
               'visitall-opt11-strips/problem03-half.pddl'),
              ('visitall-opt11-strips/domain.pddl',
               'visitall-opt11-strips/problem04-full.pddl'),
              ('visitall-opt11-strips/domain.pddl',
               'visitall-opt11-strips/problem04-half.pddl'),
              ('visitall-opt11-strips/domain.pddl',
               'visitall-opt11-strips/problem05-full.pddl'),
              ('visitall-opt11-strips/domain.pddl',
               'visitall-opt11-strips/problem05-half.pddl'),
              ('visitall-opt11-strips/domain.pddl',
               'visitall-opt11-strips/problem06-full.pddl'),
              ('visitall-opt11-strips/domain.pddl',
               'visitall-opt11-strips/problem06-half.pddl'),
              ('visitall-opt11-strips/domain.pddl',
               'visitall-opt11-strips/problem07-full.pddl'),
              ('visitall-opt11-strips/domain.pddl',
               'visitall-opt11-strips/problem07-half.pddl'),
              ('visitall-opt11-strips/domain.pddl',
               'visitall-opt11-strips/problem08-full.pddl'),
              ('visitall-opt11-strips/domain.pddl',
               'visitall-opt11-strips/problem08-half.pddl'),
              ('visitall-opt11-strips/domain.pddl',
               'visitall-opt11-strips/problem09-full.pddl'),
              ('visitall-opt11-strips/domain.pddl',
               'visitall-opt11-strips/problem09-half.pddl'),
              ('visitall-opt11-strips/domain.pddl',
               'visitall-opt11-strips/problem10-full.pddl'),
              ('visitall-opt11-strips/domain.pddl',
               'visitall-opt11-strips/problem10-half.pddl'),
              ('visitall-opt11-strips/domain.pddl',
               'visitall-opt11-strips/problem11-full.pddl'),
              ('visitall-opt11-strips/domain.pddl',
               'visitall-opt11-strips/problem11-half.pddl')]}
]