domains = [
{'description': 'The goal is to assemble a complex object made out of subassemblies. The sequence of steps must obey a given partial order. In addition, through poor engineering design, many subassemblies must be installed temporarily in one assembly, then removed and given a permanent home in another. This domain was created by Drew McDermott.',
 'ipc': '1998',
 'name': 'assembly',
 'problems': [('assembly/domain.pddl', 'assembly/prob01.pddl'),
              ('assembly/domain.pddl', 'assembly/prob02.pddl'),
              ('assembly/domain.pddl', 'assembly/prob03.pddl'),
              ('assembly/domain.pddl', 'assembly/prob04.pddl'),
              ('assembly/domain.pddl', 'assembly/prob05.pddl'),
              ('assembly/domain.pddl', 'assembly/prob06.pddl'),
              ('assembly/domain.pddl', 'assembly/prob07.pddl'),
              ('assembly/domain.pddl', 'assembly/prob08.pddl'),
              ('assembly/domain.pddl', 'assembly/prob09.pddl'),
              ('assembly/domain.pddl', 'assembly/prob10.pddl'),
              ('assembly/domain.pddl', 'assembly/prob11.pddl'),
              ('assembly/domain.pddl', 'assembly/prob12.pddl'),
              ('assembly/domain.pddl', 'assembly/prob13.pddl'),
              ('assembly/domain.pddl', 'assembly/prob14.pddl'),
              ('assembly/domain.pddl', 'assembly/prob15.pddl'),
              ('assembly/domain.pddl', 'assembly/prob16.pddl'),
              ('assembly/domain.pddl', 'assembly/prob17.pddl'),
              ('assembly/domain.pddl', 'assembly/prob18.pddl'),
              ('assembly/domain.pddl', 'assembly/prob19.pddl'),
              ('assembly/domain.pddl', 'assembly/prob20.pddl'),
              ('assembly/domain.pddl', 'assembly/prob21.pddl'),
              ('assembly/domain.pddl', 'assembly/prob22.pddl'),
              ('assembly/domain.pddl', 'assembly/prob23.pddl'),
              ('assembly/domain.pddl', 'assembly/prob24.pddl'),
              ('assembly/domain.pddl', 'assembly/prob25.pddl'),
              ('assembly/domain.pddl', 'assembly/prob26.pddl'),
              ('assembly/domain.pddl', 'assembly/prob27.pddl'),
              ('assembly/domain.pddl', 'assembly/prob28.pddl'),
              ('assembly/domain.pddl', 'assembly/prob29.pddl'),
              ('assembly/domain.pddl', 'assembly/prob30.pddl')]}
]