domains = [
{'description': "In this domain there is a robot barman that manipulates drink dispensers, glasses and a shaker. The goal is to find a plan of the robot's actions that serves a desired set of drinks. In this domain deletes of actions encode relevant knowledge given that robot hands can only grasp one object at a time and given that glasses need to be empty and clean to be filled.",
 'ipc': '2014',
 'name': 'barman',
 'problems': [('barman-opt14-strips/domain.pddl',
               'barman-opt14-strips/p435.1.pddl'),
              ('barman-opt14-strips/domain.pddl',
               'barman-opt14-strips/p435.2.pddl'),
              ('barman-opt14-strips/domain.pddl',
               'barman-opt14-strips/p435.3.pddl'),
              ('barman-opt14-strips/domain.pddl',
               'barman-opt14-strips/p536.1.pddl'),
              ('barman-opt14-strips/domain.pddl',
               'barman-opt14-strips/p536.2.pddl'),
              ('barman-opt14-strips/domain.pddl',
               'barman-opt14-strips/p536.3.pddl'),
              ('barman-opt14-strips/domain.pddl',
               'barman-opt14-strips/p638.1.pddl'),
              ('barman-opt14-strips/domain.pddl',
               'barman-opt14-strips/p638.2.pddl'),
              ('barman-opt14-strips/domain.pddl',
               'barman-opt14-strips/p638.3.pddl'),
              ('barman-opt14-strips/domain.pddl',
               'barman-opt14-strips/p739.1.pddl'),
              ('barman-opt14-strips/domain.pddl',
               'barman-opt14-strips/p739.2.pddl'),
              ('barman-opt14-strips/domain.pddl',
               'barman-opt14-strips/p739.3.pddl'),
              ('barman-opt14-strips/domain.pddl',
               'barman-opt14-strips/p839.1.pddl'),
              ('barman-opt14-strips/domain.pddl',
               'barman-opt14-strips/p839.2.pddl')]}
]