domains = [
{'description': '',
 'ipc': '2014',
 'name': 'barman',
 'problems': [('barman-opt14-strips/domain.pddl',
               'barman-opt14-strips/p435.1.pddl'),
              ('barman-opt14-strips/domain.pddl',
               'barman-opt14-strips/p435.2.pddl'),
              ('barman-opt14-strips/domain.pddl',
               'barman-opt14-strips/p435.3.pddl'),
              ('barman-opt14-strips/domain.pddl',
               'barman-opt14-strips/p536.1.pddl'),
              ('barman-opt14-strips/domain.pddl',
               'barman-opt14-strips/p536.2.pddl'),
              ('barman-opt14-strips/domain.pddl',
               'barman-opt14-strips/p536.3.pddl'),
              ('barman-opt14-strips/domain.pddl',
               'barman-opt14-strips/p638.1.pddl'),
              ('barman-opt14-strips/domain.pddl',
               'barman-opt14-strips/p638.2.pddl'),
              ('barman-opt14-strips/domain.pddl',
               'barman-opt14-strips/p638.3.pddl'),
              ('barman-opt14-strips/domain.pddl',
               'barman-opt14-strips/p739.1.pddl'),
              ('barman-opt14-strips/domain.pddl',
               'barman-opt14-strips/p739.2.pddl'),
              ('barman-opt14-strips/domain.pddl',
               'barman-opt14-strips/p739.3.pddl'),
              ('barman-opt14-strips/domain.pddl',
               'barman-opt14-strips/p839.1.pddl'),
              ('barman-opt14-strips/domain.pddl',
               'barman-opt14-strips/p839.2.pddl')]}
]